// Registered into the shared brand-data registry so multiple brand files
// can load on one page (see compare/).
window.BRAND_DATA = window.BRAND_DATA || {};
window.BRAND_DATA['sigma'] = (() => {
// ─────────────────────────────────────────────
// SIGMA BRAND CONFIG
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Sigma',
  slug:        'sigma',
  families:    ['L-Mount Mirrorless'],
  brandSections: ['sigma'],
  mount:       'L-Mount',
  heroCamera:  'bf',
  cameras: {
    heroEyebrow:  'BF & fp Series',
    heroTitle:    '<span>Sigma</span> Camera Comparison',
    heroSubtitle: 'Compare Sigma L-Mount full-frame cameras side-by-side — the BF and the fp series',
    headerTitle:  'Sigma',
    defaultSelected: ['bf', 'fp-l', 'fp'],
  },
  lenses: {
    heroEyebrow:  'SIGMA L-Mount Lenses',
    heroTitle:    '<span>Sigma</span> Lens Comparison',
    heroSubtitle: 'Compare Sigma Art, Contemporary and Sports L-Mount lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['sigma-35mm-f14-dg-ii', 'sigma-24-70mm-f28-dg-ii', 'sigma-85mm-f14-dg'],
  },
  footerLinks: [
    { label: 'SIGMA Cameras', url: 'https://www.sigma-global.com/en/cameras/' },
    { label: 'SIGMA Lenses',  url: 'https://www.sigma-global.com/en/lenses/' },
    { label: 'DPReview Sigma', url: 'https://www.dpreview.com/products/sigma' },
  ],
};

const REGISTERED_BRANDS = [
  { slug: 'fujifilm',  name: 'Fujifilm' },
  { slug: 'canon',     name: 'Canon' },
  { slug: 'sony',      name: 'Sony' },
  { slug: 'nikon',     name: 'Nikon' },
  { slug: 'panasonic', name: 'Panasonic' },
  { slug: 'sigma',     name: 'Sigma' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards)
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'BF':         { bg: '#191a24', text: '#b9bcd0' },
  'fp Series':  { bg: '#141826', text: '#8f9bd8' },
  'sd Quattro': { bg: '#101c1a', text: '#78c2b0' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE — Sigma L-Mount full-frame mirrorless.
//
// Sigma-specific fields: foveonGen (Foveon X3 generation, null on the Bayer
// bodies), shutterType (none of these has a mechanical shutter), internalStorage
// (the BF ships 230GB of internal SSD and no card slot at all), lLog.
//
// Scope note: Sigma's Foveon bodies (sd Quattro pair and the dp/DP compacts)
// are a separate follow-up change — their specs are not reliably sourceable to
// this project's two-source bar without per-body digging.
//
// Pricing: USD is the current US list price. Sigma raised US prices ~10% on
// 2 June 2025 in response to tariffs, so launch prices are NOT current for
// anything still on sale. Discontinued bodies carry their launch RRP.
// ─────────────────────────────────────────────
const CAMERAS = {
  'bf': {
    name:'BF', series:'BF', year:2025, discontinued:false,
    tagline:'Radically Simple Full-Frame',
    productUrl:'https://www.sigma-global.com/en/cameras/bf/',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Sigma_BF_11_may_2025b.jpg/500px-Sigma_BF_11_may_2025b.jpg',
    imageCredit:{author:"昼落ち", licence:"CC0", licenceUrl:"http://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Sigma_BF_11_may_2025b.jpg"},
    asin:null,
    prices:{USD:2199,AUD:3399,EUR:2499,GBP:1999,JPY:339000,CAD:2899,SGD:3199},
    sensorMP:24.6, sensorType:'Full-frame BSI CMOS', processor:'Not disclosed',
    width:130.1, height:72.8, depth:36.8, weight:446, weatherSealed:true,
    lcdSize:'3.15"', lcdDots:2100, lcdType:'Fixed Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal (people, dogs, cats)',
    ibis:false, ibisStops:null, maxBurst:8,
    maxVideoRes:'6K / 30P (6016 x 3384)',
    logVideo:true,
    foveonGen:null, shutterType:'Electronic only', internalStorage:'230GB SSD', lLog:true,
    bluetooth:false, wifi:false,
    cardSlots:'None (230GB internal SSD)', batteryLife:260, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'fp-l': {
    name:'fp L', series:'fp Series', year:2021, discontinued:true,
    tagline:'61MP Pocketable Full-Frame',
    productUrl:'https://www.sigma-global.com/en/cameras/fpl/',
    imageUrl:null,
    asin:null,
    prices:{USD:2499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:61, sensorType:'Full-frame BSI Bayer CMOS', processor:'Not disclosed',
    width:112.6, height:69.9, depth:45.3, weight:427, weatherSealed:true,
    lcdSize:'3.15"', lcdDots:2100, lcdType:'Fixed Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Face / Eye',
    ibis:false, ibisStops:null, maxBurst:10,
    maxVideoRes:'UHD 4K / 30P',
    logVideo:false,
    foveonGen:null, shutterType:'Electronic only', internalStorage:null, lLog:false,
    bluetooth:false, wifi:false,
    cardSlots:'Single SD UHS-II', batteryLife:240, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'fp': {
    name:'fp', series:'fp Series', year:2019, discontinued:true,
    tagline:"World's Smallest Full-Frame",
    productUrl:'https://www.sigma-global.com/en/cameras/fp/',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sigma_fp_26_oct_2019a.jpg/500px-Sigma_fp_26_oct_2019a.jpg',
    imageCredit:{author:"昼落ち", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Sigma_fp_26_oct_2019a.jpg"},
    asin:null,
    prices:{USD:1899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.6, sensorType:'Full-frame BSI CMOS', processor:'Not disclosed',
    width:112.6, height:69.9, depth:45.3, weight:422, weatherSealed:true,
    lcdSize:'3.15"', lcdDots:2100, lcdType:'Fixed Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Face / Eye',
    ibis:false, ibisStops:null, maxBurst:18,
    maxVideoRes:'UHD 4K / 24P',
    logVideo:false,
    foveonGen:null, shutterType:'Electronic only', internalStorage:null, lLog:false,
    bluetooth:false, wifi:false,
    cardSlots:'Single SD UHS-II', batteryLife:280, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  // The engine renders three slots from `defaultSelected`, and the picker
  // dedup test needs a camera outside that set — so a brand page needs at
  // least four bodies. Sigma's L-Mount line is only three, so the sd Quattro
  // comes forward from the deferred Foveon batch. It is fully sourced (Sigma's
  // own spec page + DPReview); the rest of the Foveon line is a follow-up.
  'sd-quattro': {
    name:'sd Quattro', series:'sd Quattro', year:2016, discontinued:true,
    tagline:'Foveon X3 Quattro APS-C',
    productUrl:'https://www.sigma-global.com/en/cameras/sd-quattro/',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Sigma_sd_Quattro_front-right_2017_CP%2B.jpg/500px-Sigma_sd_Quattro_front-right_2017_CP%2B.jpg',
    imageCredit:{author:"Morio", licence:"CC BY-SA 3.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/3.0", source:"https://commons.wikimedia.org/wiki/File:Sigma_sd_Quattro_front-right_2017_CP+.jpg"},
    asin:null,
    prices:{USD:799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:19.6, sensorType:'Foveon X3 Quattro (APS-C, 3-layer)', processor:'Dual TRUE III',
    width:147, height:95.1, depth:90.8, weight:625, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1620, lcdType:'Fixed TFT',
    evfType:'EVF', evfDots:2.36, evfMag:1.10,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:3.6,
    maxVideoRes:'None',
    logVideo:false,
    foveonGen:'X3 Quattro', shutterType:'Mechanical', internalStorage:null, lLog:false,
    bluetooth:false, wifi:false,
    cardSlots:'Single SD/SDHC/SDXC', batteryLife:null, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'sd-quattro-h': {
    name:'sd Quattro H', series:'sd Quattro', year:2017, discontinued:true,
    tagline:'APS-H Foveon Quattro',
    productUrl:'https://www.sigma-global.com/en/cameras/sd-quattro-h/',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sigma_sd_Quattro_H_front-right_2017_CP%2B.jpg/500px-Sigma_sd_Quattro_H_front-right_2017_CP%2B.jpg',
    imageCredit:{author:"Morio", licence:"CC BY-SA 3.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/3.0", source:"https://commons.wikimedia.org/wiki/File:Sigma_sd_Quattro_H_front-right_2017_CP+.jpg"},
    asin:null,
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:25.5, sensorType:'Foveon X3 Quattro (APS-H, 3-layer)', processor:'Dual TRUE III',
    width:147, height:95.1, depth:90.8, weight:635, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1620, lcdType:'Fixed TFT',
    evfType:'EVF', evfDots:2.36, evfMag:0.96,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:3.8,
    maxVideoRes:'None',
    logVideo:false,
    foveonGen:'X3 Quattro', shutterType:'Mechanical', internalStorage:null, lLog:false,
    bluetooth:false, wifi:false,
    cardSlots:'Single SD/SDHC/SDXC', batteryLife:null, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
};

const CAMERA_ORDER = ['bf', 'fp-l', 'fp', 'sd-quattro-h', 'sd-quattro'];

const DROPDOWN_GROUPS = [
  { label: '── Current (L-Mount) ──',        ids: ['bf'] },
  { label: '── fp Series (discontinued) ──', ids: ['fp-l', 'fp'] },
  { label: '── Foveon (SA-Mount) ──',        ids: ['sd-quattro-h', 'sd-quattro'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE — Sigma first-party L-Mount.
//
// L-Mount only: Sigma's RF / X / Z / E copies of these optics live in those
// brands' files, and SA-mount DSLR glass is out of scope. The 22 entries ported
// from panasonic/data.js describe the identical physical L-Mount product, so
// their specs, asin, imageUrl and productUrl carry across verbatim.
// ─────────────────────────────────────────────
const LENSES = {
  'sigma-20mm-f14-dg': {
    name:'Sigma 20mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:1.4, minAperture:16, weight:630, length:113.2, diameter:87.8,
    filterThread:82, minFocusDist:23, maxMagnification:0.16,
    elements:17, groups:15, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a022_20_14_product_img01.png',
    asin:'B0B92CBXFF',
    prices:{USD:899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a022_20_14/',
  },
  'sigma-24mm-f14-dg': {
    name:'Sigma 24mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.4, minAperture:16, weight:510, length:97.5, diameter:75.7,
    filterThread:72, minFocusDist:25, maxMagnification:0.14,
    elements:17, groups:14, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a022_24_14_product_img01.png',
    asin:'B0B9319KZ3',
    prices:{USD:799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a022_24_14/',
  },
  'sigma-35mm-f14-dg': {
    name:'Sigma 35mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:640, length:111.5, diameter:75.5,
    filterThread:67, minFocusDist:30, maxMagnification:0.19,
    elements:15, groups:11, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a021_35_14_product_img01.png',
    asin:'B093JGV2FN',
    prices:{USD:799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a021_35_14/',
  },
  'sigma-35mm-f14-dg-ii': {
    name:'Sigma 35mm f/1.4 DG II Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:530, length:94.0, diameter:73.0,
    filterThread:67, minFocusDist:28, maxMagnification:0.19,
    elements:15, groups:12, blades:11, afType:'Dual HLA',
    weatherSealed:true, ois:false, oisStops:null, year:2026, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/images/a026_35_14_product_img01.png',
    imageSource: { url:'https://www.sigma-global.com/en/lenses/a026_35_14/', tier:'T1', note:'official sigma-global.com product page; barrel reads "35mm 1:1.4 DG II" and "SIGMA" — the guessed direct image-path pattern (matching sibling entries like sigma-50mm-f14-dg) 404s for this lens; the working path uses an extra /images/ segment', date:'2026-08-17' },
    asin:'B0GQJLTML7',
    prices:{USD:1059,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a026_35_14/',
  },
  'sigma-50mm-f14-dg': {
    name:'Sigma 50mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:660, length:111.5, diameter:78.2,
    filterThread:72, minFocusDist:45, maxMagnification:0.15,
    elements:14, groups:11, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a023_50_14_product_img01.png',
    asin:'B0BV3V7D74',
    prices:{USD:849,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a023_50_14/',
  },
  'sigma-85mm-f14-dg': {
    name:'Sigma 85mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.4, minAperture:16, weight:625, length:96.1, diameter:82.8,
    filterThread:77, minFocusDist:85, maxMagnification:0.12,
    elements:15, groups:11, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a020_85_14_product_img01.png',
    asin:'B08FND4Z17',
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a020_85_14/',
  },
  'sigma-135mm-f14-dg': {
    name:'Sigma 135mm f/1.4 DG Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:135, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'135mm',
    maxAperture:1.4, minAperture:16, weight:1430, length:135.5, diameter:111.7,
    filterThread:105, minFocusDist:110, maxMagnification:0.14,
    elements:17, groups:13, blades:13, afType:'Dual HLA',
    weatherSealed:true, ois:false, oisStops:null, year:2025, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a025_135_14_product_img01.png',
    asin:'B0FQWF28RV',
    prices:{USD:1899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a025_135_14/',
  },
  'sigma-17mm-f4-dg': {
    name:'Sigma 17mm f/4 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:17, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'17mm',
    maxAperture:4.0, minAperture:22, weight:220, length:50.8, diameter:64,
    filterThread:55, minFocusDist:12, maxMagnification:0.28,
    elements:9, groups:8, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c023_17_4_product_img01.png',
    asin:null,
    prices:{USD:599,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c023_17_4/',
  },
  'sigma-20mm-f2-dg': {
    name:'Sigma 20mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:2.0, minAperture:22, weight:370, length:74.4, diameter:70,
    filterThread:62, minFocusDist:22, maxMagnification:0.15,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c022_20_2_product_img01.png',
    asin:null,
    prices:{USD:699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c022_20_2/',
  },
  'sigma-24mm-f2-dg': {
    name:'Sigma 24mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:2.0, minAperture:22, weight:360, length:74, diameter:70,
    filterThread:62, minFocusDist:24.5, maxMagnification:0.15,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c021_24_2_product_img01.png',
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c021_24_2/',
  },
  'sigma-35mm-f2-dg': {
    name:'Sigma 35mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:2.0, minAperture:22, weight:325, length:67.4, diameter:70,
    filterThread:58, minFocusDist:27, maxMagnification:0.18,
    elements:10, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c020_35_2_product_img01.png',
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c020_35_2/',
  },
  'sigma-45mm-f28-dg': {
    name:'Sigma 45mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:45, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'45mm',
    maxAperture:2.8, minAperture:22, weight:230, length:48.2, diameter:64,
    filterThread:55, minFocusDist:24, maxMagnification:0.25,
    elements:8, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2019, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c019_45_28_product_img01.png',
    asin:null,
    prices:{USD:549,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c019_45_28/',
  },
  'sigma-50mm-f2-dg': {
    name:'Sigma 50mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.0, minAperture:22, weight:345, length:70, diameter:70,
    filterThread:58, minFocusDist:45, maxMagnification:0.14,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c023_50_2_product_img01.png',
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c023_50_2/',
  },
  'sigma-65mm-f2-dg': {
    name:'Sigma 65mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:65, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'65mm',
    maxAperture:2.0, minAperture:22, weight:405, length:76.7, diameter:72,
    filterThread:62, minFocusDist:55, maxMagnification:0.15,
    elements:12, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c020_65_2_product_img01.png',
    asin:null,
    prices:{USD:699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c020_65_2/',
  },
  'sigma-90mm-f28-dg': {
    name:'Sigma 90mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:90, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:2.8, minAperture:22, weight:295, length:61.7, diameter:64,
    filterThread:55, minFocusDist:50, maxMagnification:0.2,
    elements:11, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/images/c021_90_28_product_img01.png',
    imageSource: { url:'https://www.sigma-global.com/en/lenses/c021_90_28/', tier:'T1', note:'official sigma-global.com product page; barrel reads "90mm 1:2.8 DG DN" and "SIGMA"', date:'2026-08-17' },
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c021_90_28/',
  },
  'sigma-16-28mm-f28-dg': {
    name:'Sigma 16-28mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Zoom',
    focalLength:null, focalLengthMin:16, focalLengthMax:28, focalLengthEquiv:'16-28mm',
    maxAperture:2.8, minAperture:22, weight:450, length:102.6, diameter:77.2,
    filterThread:72, minFocusDist:25, maxMagnification:0.18,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c022_16_28_28_product_img01.png',
    asin:'B0B33S8XBJ',
    prices:{USD:899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c022_16_28_28/',
  },
  'sigma-28-70mm-f28-dg': {
    name:'Sigma 28-70mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Zoom',
    focalLength:null, focalLengthMin:28, focalLengthMax:70, focalLengthEquiv:'28-70mm',
    maxAperture:2.8, minAperture:22, weight:470, length:103.5, diameter:72.2,
    filterThread:67, minFocusDist:19, maxMagnification:0.3,
    elements:16, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/images/c021_28_70_28_product_img01.png',
    imageSource: { url:'https://www.sigma-global.com/en/lenses/c021_28_70_28/', tier:'T1', note:'official sigma-global.com product page; barrel reads "28-70mm 1:2.8 DG DN" and "SIGMA"', date:'2026-08-17' },
    asin:'B08XBNL1HL',
    prices:{USD:899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c021_28_70_28/',
  },
  'sigma-24-70mm-f28-dg-ii': {
    name:'Sigma 24-70mm f/2.8 DG DN II Art', manufacturer:'Sigma', line:'Art', type:'Zoom',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:745, length:122.2, diameter:87.8,
    filterThread:82, minFocusDist:17, maxMagnification:0.34,
    elements:19, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a024_24_70_28_ii_product_img01.png',
    asin:'B0D49R8J25',
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a024_24_70_28_ii/',
  },
  'sigma-28-45mm-f18-dg': {
    name:'Sigma 28-45mm f/1.8 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Zoom',
    focalLength:null, focalLengthMin:28, focalLengthMax:45, focalLengthEquiv:'28-45mm',
    maxAperture:1.8, minAperture:16, weight:960, length:153.4, diameter:87.8,
    filterThread:82, minFocusDist:30, maxMagnification:0.25,
    elements:18, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a024_28_45_18_product_img01.png',
    asin:'B0D5YNNJP5',
    prices:{USD:1349,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a024_28_45_18/',
  },
  'sigma-70-200mm-f28-dg': {
    name:'Sigma 70-200mm f/2.8 DG DN OS Sports', manufacturer:'Sigma', line:'Sports', type:'Zoom',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1345, length:207, diameter:90.6,
    filterThread:77, minFocusDist:65, maxMagnification:0.19,
    elements:20, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:true, oisStops:7.5, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s023_70_200_28_product_img01.png',
    asin:'B0CN1NL69M',
    prices:{USD:1499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s023_70_200_28/',
  },
  'sigma-100-400mm-f5-63-dg': {
    name:'Sigma 100-400mm f/5-6.3 DG DN OS Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Zoom',
    focalLength:null, focalLengthMin:100, focalLengthMax:400, focalLengthEquiv:'100-400mm',
    maxAperture:5.0, minAperture:22, weight:1140, length:199.2, diameter:86,
    filterThread:67, minFocusDist:112, maxMagnification:0.24,
    elements:22, groups:16, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:4, year:2020, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c020_100_400_5_63_product_img01.png',
    imageSource: { url:'https://www.sigma-global.com/en/lenses/c020_100_400_5_63/', tier:'T1', note:'official sigma-global.com product page; barrel reads "100-400mm 1:5-6.3 DG DN" and "SIGMA"', date:'2026-08-17' },
    asin:'B08HRY1VFW',
    prices:{USD:949,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c020_100_400_5_63/',
  },
  'sigma-150-600mm-f5-63-dg': {
    name:'Sigma 150-600mm f/5-6.3 DG DN OS Sports', manufacturer:'Sigma', line:'Sports', type:'Zoom',
    focalLength:null, focalLengthMin:150, focalLengthMax:600, focalLengthEquiv:'150-600mm',
    maxAperture:5.0, minAperture:22, weight:2100, length:263.6, diameter:109.4,
    filterThread:95, minFocusDist:58, maxMagnification:0.34,
    elements:25, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:6.5, year:2021, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s021_150_600_5_63_product_img01.png',
    asin:'B09BW84XTV',
    prices:{USD:1499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s021_150_600_5_63/',
  },
  'sigma-14mm-f14-dg': {
    name:'Sigma 14mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:14, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'14mm',
    maxAperture:1.4, minAperture:16, weight:1170, length:149.9, diameter:101.4,
    filterThread:null, minFocusDist:30, maxMagnification:0.084,
    elements:19, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a023_14_14_product_img01.png',
    asin:null,
    prices:{USD:1839,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a023_14_14_re/',
  },
  'sigma-15mm-f14-dg-fisheye': {
    name:'Sigma 15mm f/1.4 DG DN Diagonal Fisheye Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:15, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'15mm',
    maxAperture:1.4, minAperture:16, weight:1360, length:157.9, diameter:104,
    filterThread:null, minFocusDist:38.5, maxMagnification:0.063,
    elements:21, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a024_15_14_product_img01.png',
    asin:null,
    prices:{USD:2199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a024_15_14/',
  },
  'sigma-35mm-f12-dg-ii': {
    name:'Sigma 35mm f/1.2 DG II Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.2, minAperture:16, weight:755, length:111.4, diameter:81,
    filterThread:72, minFocusDist:28, maxMagnification:0.189,
    elements:17, groups:13, blades:11, afType:'Dual HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2025, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a025_35_12_product_img02.png',
    asin:null,
    prices:{USD:1549,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a025_35_12/',
  },
  'sigma-50mm-f12-dg': {
    name:'Sigma 50mm f/1.2 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.2, minAperture:16, weight:745, length:108.8, diameter:81,
    filterThread:72, minFocusDist:40, maxMagnification:0.161,
    elements:17, groups:12, blades:13, afType:'Dual HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a024_50_12_product_img01.png',
    asin:null,
    prices:{USD:1539,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a024_50_12/',
  },
  'sigma-105mm-f28-dg-macro': {
    name:'Sigma 105mm f/2.8 DG DN Macro Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:105, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'105mm',
    maxAperture:2.8, minAperture:22, weight:715, length:133.6, diameter:74,
    filterThread:62, minFocusDist:29.5, maxMagnification:1.0,
    elements:17, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a020_105_28_product_img01.png',
    asin:null,
    prices:{USD:879,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a020_105_28/',
  },
  'sigma-24mm-f35-dg': {
    name:'Sigma 24mm f/3.5 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:3.5, minAperture:22, weight:225, length:48.8, diameter:64,
    filterThread:55, minFocusDist:10.8, maxMagnification:0.5,
    elements:10, groups:8, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c021_24_35_product_img01.png',
    asin:null,
    prices:{USD:619,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c021_24_35_re/',
  },
  'sigma-14-24mm-f28-dg': {
    name:'Sigma 14-24mm f/2.8 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Zoom',
    focalLength:null, focalLengthMin:14, focalLengthMax:24, focalLengthEquiv:'14-24mm',
    maxAperture:2.8, minAperture:22, weight:795, length:131, diameter:85,
    filterThread:null, minFocusDist:28, maxMagnification:0.137,
    elements:18, groups:13, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a019_14_24_28_product_img01.png',
    asin:null,
    prices:{USD:1539,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a019_14_24_28/',
  },
  'sigma-28-105mm-f28-dg': {
    name:'Sigma 28-105mm f/2.8 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Zoom',
    focalLength:null, focalLengthMin:28, focalLengthMax:105, focalLengthEquiv:'28-105mm',
    maxAperture:2.8, minAperture:22, weight:995, length:157.9, diameter:87.8,
    filterThread:82, minFocusDist:40, maxMagnification:0.323,
    elements:18, groups:13, blades:12, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a024_28_105_28_product_img01.png',
    asin:null,
    prices:{USD:1649,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a024_28_105_28/',
  },
  'sigma-20-200mm-f35-63-dg': {
    name:'Sigma 20-200mm f/3.5-6.3 DG Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Zoom',
    focalLength:null, focalLengthMin:20, focalLengthMax:200, focalLengthEquiv:'20-200mm',
    maxAperture:3.5, minAperture:22, weight:550, length:115.5, diameter:77.2,
    filterThread:72, minFocusDist:16.5, maxMagnification:0.5,
    elements:18, groups:14, blades:9, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2025, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c025_20_200_35_63_product_img01.png',
    asin:null,
    prices:{USD:999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c025_20_200_35_63/',
  },
  'sigma-200mm-f2-dg': {
    name:'Sigma 200mm f/2 DG OS Sports', manufacturer:'Sigma', line:'Sports', type:'Prime',
    focalLength:200, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'200mm',
    maxAperture:2.0, minAperture:22, weight:1820, length:201, diameter:118.9,
    filterThread:105, minFocusDist:170, maxMagnification:0.132,
    elements:19, groups:14, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:true, oisStops:6.5, year:2025, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s025_200_2_product_img01.png',
    asin:null,
    prices:{USD:3299,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s025_200_2/',
  },
  'sigma-500mm-f56-dg': {
    name:'Sigma 500mm f/5.6 DG DN OS Sports', manufacturer:'Sigma', line:'Sports', type:'Prime',
    focalLength:500, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'500mm',
    maxAperture:5.6, minAperture:32, weight:1370, length:234.6, diameter:107.6,
    filterThread:95, minFocusDist:320, maxMagnification:0.167,
    elements:20, groups:14, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:true, oisStops:5, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s024_500_56_product_img01.png',
    asin:null,
    prices:{USD:3299,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s024_500_56/',
  },
  'sigma-60-600mm-f45-63-dg': {
    name:'Sigma 60-600mm f/4.5-6.3 DG DN OS Sports', manufacturer:'Sigma', line:'Sports', type:'Zoom',
    focalLength:null, focalLengthMin:60, focalLengthMax:600, focalLengthEquiv:'60-600mm',
    maxAperture:4.5, minAperture:22, weight:2495, length:279.2, diameter:119.4,
    filterThread:105, minFocusDist:45, maxMagnification:0.417,
    elements:27, groups:19, blades:9, afType:'HLA Linear',
    weatherSealed:true, ois:true, oisStops:7, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s023_60_600_45_63_product_img01.png',
    asin:null,
    prices:{USD:2199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s023_60_600_45_63/',
  },
  'sigma-300-600mm-f4-dg': {
    name:'Sigma 300-600mm f/4 DG OS Sports', manufacturer:'Sigma', line:'Sports', type:'Zoom',
    focalLength:null, focalLengthMin:300, focalLengthMax:600, focalLengthEquiv:'300-600mm',
    maxAperture:4.0, minAperture:22, weight:3985, length:467.9, diameter:167,
    filterThread:null, minFocusDist:280, maxMagnification:0.167,
    elements:28, groups:21, blades:13, afType:'HLA Linear',
    weatherSealed:true, ois:true, oisStops:5.5, year:2025, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s025_300_600_4_product_img01.png',
    asin:null,
    prices:{USD:6599,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s025_300_600_4/',
  },
};

const LENS_DROPDOWN_GROUPS = [
  { label: '── Art Primes (L-Mount) ──', ids: ['sigma-14mm-f14-dg', 'sigma-15mm-f14-dg-fisheye', 'sigma-20mm-f14-dg', 'sigma-24mm-f14-dg', 'sigma-35mm-f12-dg-ii', 'sigma-35mm-f14-dg', 'sigma-35mm-f14-dg-ii', 'sigma-50mm-f12-dg', 'sigma-50mm-f14-dg', 'sigma-85mm-f14-dg', 'sigma-105mm-f28-dg-macro', 'sigma-135mm-f14-dg'] },
  { label: '── Art Zooms (L-Mount) ──', ids: ['sigma-14-24mm-f28-dg', 'sigma-24-70mm-f28-dg-ii', 'sigma-28-45mm-f18-dg', 'sigma-28-105mm-f28-dg'] },
  { label: '── Contemporary Primes (L-Mount) ──', ids: ['sigma-17mm-f4-dg', 'sigma-20mm-f2-dg', 'sigma-24mm-f2-dg', 'sigma-24mm-f35-dg', 'sigma-35mm-f2-dg', 'sigma-45mm-f28-dg', 'sigma-50mm-f2-dg', 'sigma-65mm-f2-dg', 'sigma-90mm-f28-dg'] },
  { label: '── Contemporary Zooms (L-Mount) ──', ids: ['sigma-16-28mm-f28-dg', 'sigma-20-200mm-f35-63-dg', 'sigma-28-70mm-f28-dg', 'sigma-100-400mm-f5-63-dg'] },
  { label: '── Sports (L-Mount) ──', ids: ['sigma-200mm-f2-dg', 'sigma-500mm-f56-dg', 'sigma-60-600mm-f45-63-dg', 'sigma-70-200mm-f28-dg', 'sigma-150-600mm-f5-63-dg', 'sigma-300-600mm-f4-dg'] },
];

return { BRAND_CONFIG, SERIES_COLORS, CAMERAS, CAMERA_ORDER,
         DROPDOWN_GROUPS, LENSES, LENS_DROPDOWN_GROUPS, REGISTERED_BRANDS };
})();
