// Registered into the shared brand-data registry so multiple brand files
// can load on one page (see compare/).
window.BRAND_DATA = window.BRAND_DATA || {};
window.BRAND_DATA['leica'] = (() => {
// ─────────────────────────────────────────────
// LEICA BRAND CONFIG
//
// Leica spans two mounts that don't distinguish by sensor size the way every
// other multi-mount brand here does — SL (full-frame), M (full-frame) and Q
// (full-frame, fixed lens) all share one sensor format, so mounts.test.js
// tells them apart by `series` instead of `sensorType`. See
// openspec/changes/add-leica-brand/design.md §§2–3.
//
// `mounts` only lists 'l' for now — 'm' (M-Mount) is added once the first
// M-mount camera lands (task 5.3), since a declared-but-unused mount fails
// the "every declared mount is used" guard.
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Leica',
  slug:        'leica',
  families:    ['SL (Full-Frame L-Mount)', 'TL / CL (APS-C L-Mount)', 'M (Digital Rangefinder)', 'Q (Full-Frame Compact)', 'Leica X (APS-C Compact)', 'D-Lux / V-Lux / C-Lux (Compact)'],
  brandSections: ['leica'],
  // `mount` is the landing-tile headline label; `mounts` is the machine-readable
  // list every item's `mount` id must come from, and the order the filter chips render in.
  // 'L-Mount' alone (not 'L-Mount & M-Mount') matches the site's established
  // single-headline-mount convention — see Sigma's own tile, which also says
  // just 'L-Mount' despite spanning SA-Mount too.
  mount:       'L-Mount',
  mounts:      [{ id:'l', label:'L-Mount' }],
  heroCamera:  'sl3',
  cameras: {
    heroEyebrow:  'SL, M, Q & More',
    heroTitle:    '<span>Leica</span> Camera Comparison',
    heroSubtitle: 'Compare Leica SL, M, Q and compact cameras side-by-side — price, sensor, autofocus, stabilization and video, in seven currencies',
    headerTitle:  'Leica',
    defaultSelected: ['sl3', 'sl3-s', 'sl3-p'],
  },
  lenses: {
    heroEyebrow:  'SL & M Lenses',
    heroTitle:    '<span>Leica</span> Lens Comparison',
    heroSubtitle: 'Compare Leica SL, M and TL lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['apo-summicron-sl-50mm-f2-asph', 'super-apo-summicron-sl-21mm-f2-asph', 'vario-elmarit-sl-24-70mm-f28-asph'],
  },
  footerLinks: [
    { label: 'Leica SL Cameras', url: 'https://leica-camera.com/en-US/photography/cameras/sl' },
    { label: 'Leica SL Lenses',  url: 'https://leica-camera.com/en-US/photography/lenses/sl' },
    { label: 'DPReview Leica',   url: 'https://www.dpreview.com/products/leica' },
  ],
};

const REGISTERED_BRANDS = [
  { slug: 'fujifilm',  name: 'Fujifilm' },
  { slug: 'canon',     name: 'Canon' },
  { slug: 'sony',      name: 'Sony' },
  { slug: 'nikon',     name: 'Nikon' },
  { slug: 'panasonic', name: 'Panasonic' },
  { slug: 'sigma',     name: 'Sigma' },
  { slug: 'olympus',   name: 'Olympus' },
  { slug: 'leica',     name: 'Leica' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards)
// All 10 series declared up front (openspec/changes/add-leica-brand/
// research/decisions.md §5a) even though only SL is populated so far —
// referential.test.js only flags a USED series with no color entry, never
// the reverse, so this is safe ahead of the later camera batches.
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'SL':            { bg: '#1c1c1c', text: '#d64541' },
  'TL':            { bg: '#242320', text: '#c9a876' },
  'CL':            { bg: '#1e2420', text: '#8fae8f' },
  'M':             { bg: '#141414', text: '#c0c0c8' },
  'M Monochrom':   { bg: '#0d0d0d', text: '#9a9a9a' },
  'Q':             { bg: '#1a1a1a', text: '#4fa8d8' },
  'X':             { bg: '#22201c', text: '#d9b45c' },
  'D-Lux':         { bg: '#1c1f24', text: '#6f9bd0' },
  'V-Lux':         { bg: '#241c20', text: '#c98fae' },
  'C-Lux':         { bg: '#201c24', text: '#a68fd0' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE — Leica SL, M, Q, X & compact mirrorless.
//
// SL — full-frame L-Mount, interchangeable lens.
// ─────────────────────────────────────────────
const CAMERAS = {
  'sl3-p': {
    name:'SL3-P', series:'SL', mount:'l', year:2026, discontinued:false,
    tagline:"The most comprehensive SL-System camera to date — 44MP resolution, 8K video, and Leica's fastest hybrid autofocus.",
    productUrl:'https://leica-camera.com/en-US/photography/cameras/sl/sl3-p-black',
    imageUrl:'https://leica-camera.com/sites/default/files/styles/meta_tag_product_image/public/pm-27861-10664_Leica_SL3-P_front_cap_1920px.webp?itok=17suNuRP',
    imageSource:{url:'https://leica-camera.com/en-US/photography/cameras/sl/sl3-p-black', tier:'T1', date:'2026-09-15', title:'Leica SL3-P official product page'},
    asin:null,
    prices:{USD:6690,AUD:10500,EUR:5990,GBP:5150,JPY:1100000,CAD:9435,SGD:8800},
    sensorMP:44.9, sensorType:'Full-frame BSI CMOS', processor:'Leica Maestro IV',
    width:141.2, height:108, depth:84.6, weight:852, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2332800, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:5760000, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human (eye/face/body), animal (eye/body), and car/vehicle detection with AI subject tracking', maxBurst:40,
    ibis:true, ibisStops:5,
    maxVideoRes:'8K/30p (7680x4320)', logVideo:true,
    monochrom:false, focusingSystem:'EVF', contentCredentials:true, internalStorageGB:null,
    bluetooth:'5.0', wifi:true,
    cardSlots:'CFexpress Type B + SD UHS-II', batteryLife:383, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'sl3-s': {
    name:'SL3-S', series:'SL', mount:'l', year:2025, discontinued:false,
    tagline:'The fast and flexible full-frame system camera for photography and video production.',
    productUrl:'https://leica-camera.com/en-US/photography/cameras/sl/sl3-s-black',
    imageUrl:'https://leica-camera.com/sites/default/files/styles/meta_tag_product_image/public/pm-14662-10643_Leica_SL3-S_frontal_cap_1920px.webp?itok=XN3Lq1Oo',
    imageSource:{url:'https://leica-camera.com/en-US/photography/cameras/sl/sl3-s-black', tier:'T1', date:'2026-09-15', title:'Leica SL3-S official product page'},
    asin:null,
    prices:{USD:5295,AUD:9300,EUR:5190,GBP:4500,JPY:946000,CAD:7990,SGD:7500},
    sensorMP:24.6, sensorType:'Full-frame BSI CMOS', processor:'Leica Maestro IV',
    width:141.2, height:108, depth:82.7, weight:852, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2332800, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:5760000, evfMag:0.76,
    faceDetection:true, subjectDetection:'Person and animal (beta) detection with AI-based subject tracking', maxBurst:30,
    ibis:true, ibisStops:5.5,
    maxVideoRes:'6K/30p (5952x3968)', logVideo:true,
    monochrom:false, focusingSystem:'EVF', contentCredentials:true, internalStorageGB:null,
    bluetooth:'5.0', wifi:true,
    cardSlots:'CFexpress Type B + SD UHS-II', batteryLife:315, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'sl3': {
    name:'SL3', series:'SL', mount:'l', year:2024, discontinued:false,
    tagline:'A mirrorless full-frame camera combining exceptional image quality at 60 megapixels with intuitive operation.',
    productUrl:'https://leica-camera.com/en-US/photography/cameras/sl/sl3-black',
    imageUrl:'https://leica-camera.com/sites/default/files/styles/meta_tag_product_image/public/pm-14571-10607_Leica_SL3_frontal_cap_1920px.png?itok=Vf16HuVP',
    imageSource:{url:'https://leica-camera.com/en-US/photography/cameras/sl/sl3-black', tier:'T1', date:'2026-09-15', title:'Leica SL3 official product page'},
    asin:null,
    prices:{USD:6995,AUD:12500,EUR:6990,GBP:5920,JPY:1276000,CAD:10555,SGD:10400},
    sensorMP:60.3, sensorType:'Full-frame BSI CMOS', processor:'Leica Maestro IV',
    width:141.2, height:108, depth:84.6, weight:854, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2332800, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:5760000, evfMag:0.76,
    faceDetection:true, subjectDetection:'Person and animal (beta) detection with AI-based subject tracking', maxBurst:15,
    ibis:true, ibisStops:5,
    maxVideoRes:'8K/30p (8192x4320)', logVideo:true,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:'5.0', wifi:true,
    cardSlots:'CFexpress Type B + SD UHS-II', batteryLife:260, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'sl2-s': {
    name:'SL2-S', series:'SL', mount:'l', year:2020, discontinued:true,
    tagline:"Leica's most versatile camera for photography and videography.",
    // No current official Leica page — removed from leica-camera.com post-
    // discontinuation; B&H is used as the productUrl instead (design §7).
    productUrl:'https://www.bhphotovideo.com/c/product/1609644-REG/leica_10880_sl2_s_mirrorless_digital_camera.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/f/f5/Leica_SL2-S_Typ-Nr._9584.jpg',
    imageCredit:{author:'Ferencvizi', licence:'CC BY-SA 4.0', licenceUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:'https://commons.wikimedia.org/wiki/File:Leica_SL2-S_Typ-Nr._9584.jpg'},
    asin:null,
    prices:{USD:4895,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.6, sensorType:'Full-frame BSI CMOS', processor:'Leica Maestro III',
    width:146, height:107, depth:83, weight:931, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100000, lcdType:'Fixed Touch',
    evfType:'OLED', evfDots:5760000, evfMag:0.78,
    faceDetection:true, subjectDetection:null, maxBurst:25,
    ibis:true, ibisStops:5.5,
    maxVideoRes:'4K/60p (3840x2160)', logVideo:true,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:'4.2', wifi:true,
    cardSlots:'Dual SD UHS-II', batteryLife:510, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'sl2': {
    name:'SL2', series:'SL', mount:'l', year:2019, discontinued:true,
    tagline:'A 47MP full-frame flagship with in-body stabilization, IP54 sealing, and pro-grade 5K/4K video.',
    productUrl:'https://www.bhphotovideo.com/c/product/1639034-REG/leica_10888_sl2_mirrorless_digital_camera.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/a/a4/Leica_SL2.jpg',
    imageCredit:{author:'Jack Baty', licence:'CC BY-SA 2.0', licenceUrl:'https://creativecommons.org/licenses/by-sa/2.0/', source:'https://commons.wikimedia.org/wiki/File:Leica_SL2.jpg'},
    asin:null,
    prices:{USD:5995,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:47.3, sensorType:'Full-frame CMOS (BSI)', processor:'Maestro III',
    width:146, height:107, depth:42, weight:840, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100000, lcdType:'Fixed Touch',
    evfType:'EVF', evfDots:5760000, evfMag:0.78,
    faceDetection:true, subjectDetection:null, maxBurst:20,
    ibis:true, ibisStops:5.5,
    maxVideoRes:'5K (30p) / 4K UHD (60p)', logVideo:true,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2x SD/SDHC/SDXC (UHS-II)', batteryLife:370, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'sl-typ-601': {
    name:'SL (Typ 601)', series:'SL', mount:'l', year:2015, discontinued:true,
    tagline:"Leica's first L-Mount full-frame mirrorless — a rugged, all-metal professional system camera.",
    productUrl:'https://www.bhphotovideo.com/c/product/1192093-REG/leica_10850_sl_typ_601_mirrorless.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/8/8d/Leica_SL.jpg',
    imageCredit:{author:'GodeNehler', licence:'CC BY-SA 4.0', licenceUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:'https://commons.wikimedia.org/wiki/File:Leica_SL.jpg'},
    asin:null,
    prices:{USD:7450,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24, sensorType:'Full-frame CMOS', processor:'Maestro II',
    width:147, height:104, depth:39, weight:847, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040000, lcdType:'Fixed Touch',
    evfType:'LCOS EVF', evfDots:4400000, evfMag:0.8,
    faceDetection:true, subjectDetection:null, maxBurst:11,
    ibis:false, ibisStops:null,
    maxVideoRes:'4K (4096x2160 24p) / UHD 4K 24/25/30p', logVideo:false,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:2,
    bluetooth:false, wifi:true,
    cardSlots:'2x SD/SDHC/SDXC (UHS-II slot 1, UHS-I slot 2)', batteryLife:400, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'cl': {
    name:'CL', series:'CL', mount:'l', year:2017, discontinued:true,
    tagline:'A rangefinder-styled APS-C mirrorless with a bright built-in EVF and classic Leica dial controls.',
    productUrl:'https://www.bhphotovideo.com/c/product/1376598-REG/leica_19301_cl_mirrorless_digital_camera.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/2/23/LEICA_CL_in_the_camera_tripod.jpg',
    imageCredit:{author:'Peachyeung316', licence:'CC BY-SA 4.0', licenceUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:'https://commons.wikimedia.org/wiki/File:LEICA_CL_in_the_camera_tripod.jpg'},
    asin:null,
    prices:{USD:2795,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C CMOS', processor:'Maestro II',
    width:131, height:78, depth:45, weight:403, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040000, lcdType:'Fixed Touch',
    evfType:'LCOS EVF', evfDots:2360000, evfMag:1.11,
    faceDetection:true, subjectDetection:null, maxBurst:10,
    ibis:false, ibisStops:null,
    maxVideoRes:'4K UHD (30p)', logVideo:false,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:false, wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-II)', batteryLife:220, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'tl2': {
    name:'TL2', series:'TL', mount:'l', year:2017, discontinued:true,
    tagline:'A 24MP jump for the TL line with Maestro II processing, 4K video, and up to 20fps burst shooting.',
    productUrl:'https://www.bhphotovideo.com/c/product/1348985-REG/leica_18187_tl2_mirrorless_digital_camera.html',
    imageUrl:null,
    asin:null,
    prices:{USD:1950,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C CMOS', processor:'Maestro II',
    width:134, height:69, depth:33, weight:399, weatherSealed:false,
    lcdSize:'3.7"', lcdDots:1300000, lcdType:'Fixed Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null, maxBurst:20,
    ibis:false, ibisStops:null,
    maxVideoRes:'4K UHD (30p)', logVideo:false,
    monochrom:false, focusingSystem:null, contentCredentials:false, internalStorageGB:32,
    bluetooth:false, wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-II)', batteryLife:250, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'tl': {
    name:'TL', series:'TL', mount:'l', year:2016, discontinued:true,
    tagline:'A refined successor to the T with doubled internal storage and faster autofocus, still built from a single aluminum block.',
    productUrl:'https://www.bhphotovideo.com/c/product/1296567-REG/leica_18146_tl_mirrorless_digital_camera.html',
    imageUrl:null,
    asin:null,
    prices:{USD:1695,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:16.3, sensorType:'APS-C CMOS', processor:'Not disclosed',
    width:134, height:69, depth:33, weight:384, weatherSealed:false,
    lcdSize:'3.7"', lcdDots:1300000, lcdType:'Fixed Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null, maxBurst:5,
    ibis:false, ibisStops:null,
    maxVideoRes:'1080p (30p)', logVideo:false,
    monochrom:false, focusingSystem:null, contentCredentials:false, internalStorageGB:32,
    bluetooth:false, wifi:true,
    cardSlots:'1x SD/SDHC/SDXC', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  't-typ-701': {
    name:'T (Typ 701)', series:'TL', mount:'l', year:2014, discontinued:true,
    tagline:'A unibody aluminum APS-C mirrorless controlled almost entirely by its large touchscreen — the first Leica L-Mount camera.',
    productUrl:'https://www.bhphotovideo.com/c/product/1046767-REG/leica_18180_t_digital_camera_black.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/5/51/Leica_T_%28701%29_01.jpg',
    imageCredit:{author:'vernieman', licence:'CC BY 2.0', licenceUrl:'https://creativecommons.org/licenses/by/2.0/', source:'https://commons.wikimedia.org/wiki/File:Leica_T_(701)_01.jpg'},
    asin:null,
    prices:{USD:1850,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:16.3, sensorType:'APS-C CMOS', processor:'Not disclosed',
    width:134, height:69, depth:33, weight:384, weatherSealed:false,
    lcdSize:'3.7"', lcdDots:1300000, lcdType:'Fixed Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null, maxBurst:5,
    ibis:false, ibisStops:null,
    maxVideoRes:'1080p (30p)', logVideo:false,
    monochrom:false, focusingSystem:null, contentCredentials:false, internalStorageGB:16,
    bluetooth:false, wifi:true,
    cardSlots:'1x SD/SDHC/SDXC', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'q3-monochrom': {
    name:'Q3 Monochrom', series:'Q', mount:'l', year:2025, discontinued:false,
    tagline:'A 60MP monochrome-only compact with Content Credentials support, built for black-and-white purists.',
    productUrl:'https://leica-camera.com/en-US/photography/cameras/q/q3-monochrom',
    imageUrl:'https://leica-camera.com/sites/default/files/2025-11/cameraproduct_Q3_Mono.png',
    imageSource:{url:'https://leica-camera.com/en-US/photography/cameras/q/q3-monochrom', tier:'T1', date:'2026-09-16', title:'Leica Q3 Monochrom official product page'},
    asin:null,
    prices:{USD:7950,AUD:12600,EUR:6990,GBP:5900,JPY:1287000,CAD:11210,SGD:9990},
    sensorMP:60.3, sensorType:'Full-frame BSI-CMOS monochrome (no color filter array) with Triple Resolution Technology', processor:'Leica Maestro IV',
    width:130, height:80.3, depth:92.6, weight:662, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1843200, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:5760000, evfMag:0.79,
    faceDetection:true, subjectDetection:'Eye/Face/Body + Animal Detection (AI hybrid AF)', maxBurst:15,
    ibis:false, ibisStops:null,
    maxVideoRes:'8K/C8K (8192x4320) @30p, monochrome', logVideo:true,
    monochrom:true, focusingSystem:'EVF', contentCredentials:true, internalStorageGB:null,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-II recommended)', batteryLife:350, usbCharging:true,
    lensType:'Fixed', lensSpec:'28mm f/1.7 Summilux ASPH.',
  },
  'q3-43': {
    name:'Q3 43', series:'Q', mount:'l', year:2024, discontinued:false,
    tagline:'The Q3 platform paired with a 43mm APO-Summicron lens for a natural, human-eye perspective.',
    productUrl:'https://leica-camera.com/en-US/photography/cameras/q/q3-43-black',
    imageUrl:'https://leica-camera.com/sites/default/files/2024-09/CameraProduct_Q3_43_1.png',
    imageSource:{url:'https://leica-camera.com/en-US/photography/cameras/q/q3-43-black', tier:'T1', date:'2026-09-16', title:'Leica Q3 43 official product page'},
    asin:'B0DKG5HW7T',
    prices:{USD:7950,AUD:12600,EUR:6990,GBP:5900,JPY:1287000,CAD:11210,SGD:9990},
    sensorMP:60.3, sensorType:'Full-frame BSI-CMOS with Triple Resolution Technology', processor:'Leica Maestro IV',
    width:130, height:80.3, depth:97.6, weight:688, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1843200, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:5760000, evfMag:0.79,
    faceDetection:true, subjectDetection:'Eye/Face/Body + Animal Detection (AI hybrid AF)', maxBurst:15,
    ibis:false, ibisStops:null,
    maxVideoRes:'8K/C8K (8192x4320) @30p', logVideo:true,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-II recommended)', batteryLife:350, usbCharging:true,
    lensType:'Fixed', lensSpec:'43mm f/2 APO-Summicron ASPH.',
  },
  'q3': {
    name:'Q3', series:'Q', mount:'l', year:2023, discontinued:false,
    tagline:"Leica's 60MP full-frame compact with 8K video, phase-detect AF, and a tilting screen.",
    productUrl:'https://leica-camera.com/en-US/photography/cameras/q/q3-black',
    imageUrl:'https://leica-camera.com/sites/default/files/2024-07/cameraproduct_q3.png',
    imageSource:{url:'https://leica-camera.com/en-US/photography/cameras/q/q3-black', tier:'T1', date:'2026-09-16', title:'Leica Q3 official product page'},
    asin:'B0CGZ38M6B',
    prices:{USD:7350,AUD:11700,EUR:6490,GBP:5650,JPY:1188000,CAD:10365,SGD:9600},
    sensorMP:60.3, sensorType:'Full-frame BSI-CMOS with Triple Resolution Technology', processor:'Leica Maestro IV',
    width:130, height:80.3, depth:92.6, weight:658, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1843200, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:5760000, evfMag:0.79,
    faceDetection:true, subjectDetection:'Eye/Face/Body + Animal Detection (AI hybrid AF)', maxBurst:15,
    ibis:false, ibisStops:null,
    maxVideoRes:'8K/C8K (8192x4320) @30p', logVideo:true,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-II recommended, UHS-I compatible)', batteryLife:350, usbCharging:true,
    lensType:'Fixed', lensSpec:'28mm f/1.7 Summilux ASPH.',
  },
  'q2-monochrom': {
    name:'Q2 Monochrom', series:'Q', mount:'l', year:2020, discontinued:true,
    tagline:'A dedicated black-and-white version of the Q2, built around a 47MP monochrome-only sensor.',
    productUrl:'https://www.dpreview.com/products/leica/compacts/leica_q2m',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/2/24/Leica_Q2_Monochrom.jpg',
    imageCredit:{author:'Peachyeung316', licence:'CC BY-SA 4.0', licenceUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:'https://commons.wikimedia.org/wiki/File:Leica_Q2_Monochrom.jpg'},
    asin:null,
    prices:{USD:5995,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:47.3, sensorType:'Full-frame monochrome CMOS (no color filter array, no AA filter)', processor:'Leica Maestro II',
    width:130, height:80, depth:91.9, weight:652, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040000, lcdType:'Fixed Touch',
    evfType:'OLED', evfDots:3680000, evfMag:0.76,
    faceDetection:true, subjectDetection:null, maxBurst:20,
    ibis:false, ibisStops:null,
    maxVideoRes:'4K/C4K (4096x2160) @24-30p', logVideo:false,
    monochrom:true, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-II recommended)', batteryLife:350, usbCharging:false,
    lensType:'Fixed', lensSpec:'28mm f/1.7 Summilux ASPH.',
  },
  'q2': {
    name:'Q2', series:'Q', mount:'l', year:2019, discontinued:true,
    tagline:'A 47MP full-frame compact with IP52 weather sealing and a sharper OLED viewfinder.',
    productUrl:'https://www.dpreview.com/products/leica/compacts/leica_q2',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/a/aa/Leica_Q2_%28L1000042%29.jpg',
    imageCredit:{author:'Ferencvizi', licence:'CC BY-SA 4.0', licenceUrl:'https://creativecommons.org/licenses/by-sa/4.0/', source:'https://commons.wikimedia.org/wiki/File:Leica_Q2_(L1000042).jpg'},
    asin:null,
    prices:{USD:4995,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:47.3, sensorType:'Full-frame CMOS', processor:'Leica Maestro II',
    width:130, height:80, depth:91.9, weight:652, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040000, lcdType:'Fixed Touch',
    evfType:'OLED', evfDots:3680000, evfMag:0.76,
    faceDetection:true, subjectDetection:null, maxBurst:20,
    ibis:false, ibisStops:null,
    maxVideoRes:'4K/C4K (4096x2160) @24-30p', logVideo:false,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-II recommended)', batteryLife:350, usbCharging:false,
    lensType:'Fixed', lensSpec:'28mm f/1.7 Summilux ASPH.',
  },
  'q-p': {
    name:'Q-P', series:'Q', mount:'l', year:2018, discontinued:true,
    tagline:'A quieter, more understated take on the original Q, without the red-dot logo.',
    productUrl:'https://www.bhphotovideo.com/c/product/1442706-REG/leica_19045_q_p_digital_camera.html',
    imageUrl:null,
    asin:null,
    prices:{USD:4995,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame CMOS (no AA filter)', processor:'Leica Maestro II',
    width:130, height:80, depth:93, weight:590, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040000, lcdType:'Fixed Touch',
    evfType:'LCOS EVF', evfDots:3680000, evfMag:null,
    faceDetection:true, subjectDetection:null, maxBurst:10,
    ibis:false, ibisStops:null,
    maxVideoRes:'1920x1080 (Full HD) @60p', logVideo:false,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:false, wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-I)', batteryLife:300, usbCharging:false,
    lensType:'Fixed', lensSpec:'28mm f/1.7 Summilux ASPH.',
  },
  'q-typ-116': {
    name:'Q (Typ 116)', series:'Q', mount:'l', year:2015, discontinued:true,
    tagline:'The original full-frame compact that launched the Q line, built around a fast 28mm Summilux lens.',
    productUrl:'https://www.dpreview.com/products/leica/compacts/leica_q116',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/c/cc/Leica_Q-IMG_9924.JPG',
    imageCredit:{author:'Rama', licence:'CC BY-SA 2.0 FR', licenceUrl:'https://creativecommons.org/licenses/by-sa/2.0/fr/deed.en', source:'https://commons.wikimedia.org/wiki/File:Leica_Q-IMG_9924.JPG'},
    asin:null,
    prices:{USD:4250,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame CMOS (no AA filter)', processor:'Leica Maestro II',
    width:130, height:80, depth:93, weight:590, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040000, lcdType:'Fixed Touch',
    evfType:'LCOS EVF', evfDots:3680000, evfMag:null,
    faceDetection:true, subjectDetection:null, maxBurst:10,
    ibis:false, ibisStops:null,
    maxVideoRes:'1920x1080 (Full HD) @60p', logVideo:false,
    monochrom:false, focusingSystem:'EVF', contentCredentials:false, internalStorageGB:null,
    bluetooth:false, wifi:true,
    cardSlots:'1x SD/SDHC/SDXC (UHS-I)', batteryLife:300, usbCharging:false,
    lensType:'Fixed', lensSpec:'28mm f/1.7 Summilux ASPH.',
  },
};

// Newest-first within each group (openspec/changes/add-leica-brand/
// research/decisions.md §5a). Only the SL group exists so far — TL/CL, M,
// M Monochrom, Q, Leica X, D-Lux, V-Lux and C-Lux land in later batches
// (tasks 5.2–5.7b).
const CAMERA_ORDER = [
  'sl3-p', 'sl3-s', 'sl3', 'sl2-s', 'sl2', 'sl-typ-601',
  'cl', 'tl2', 'tl', 't-typ-701',
  'q3-monochrom', 'q3-43', 'q3', 'q2-monochrom', 'q2', 'q-p', 'q-typ-116',
];

const DROPDOWN_GROUPS = [
  { label: '── SL ──', ids: ['sl3-p', 'sl3-s', 'sl3', 'sl2-s', 'sl2', 'sl-typ-601'] },
  { label: '── TL / CL ──', ids: ['cl', 'tl2', 'tl', 't-typ-701'] },
  { label: '── Q ──', ids: ['q3-monochrom', 'q3-43', 'q3', 'q2-monochrom', 'q2', 'q-p', 'q-typ-116'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE — first-party Leica SL & M lenses (+ TL, task 6.6).
// ─────────────────────────────────────────────
const LENSES = {
  'super-apo-summicron-sl-21mm-f2-asph': {
    name:'Leica Super-APO-Summicron-SL 21mm f/2 ASPH.', manufacturer:'Leica', line:'SL', type:'Prime',
    mount:'l', focalLength:21, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'21mm',
    maxAperture:2, minAperture:22, weight:789, length:102, diameter:73,
    filterThread:67, minFocusDist:21, maxMagnification:0.19,
    elements:14, groups:11, blades:null, afType:'Dual Syncro Drive (DSD)',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://leica-camera.com/sites/default/files/styles/meta_tag_product_image/public/pm-102246-11181_Super-APO-Summicron-SL_21_f2_upright.png',
    imageSource:{url:'https://leica-camera.com/en-US/photography/lenses/sl/super-apo-summicron-sl-21-f2-asph', tier:'T1', date:'2026-09-16', title:'Leica Super-APO-Summicron-SL 21mm f/2 ASPH. official product page'},
    asin:null,
    prices:{USD:5950,AUD:9800,EUR:5490,GBP:4850,JPY:1001000,CAD:8390,SGD:8150},
    productUrl:'https://leica-camera.com/en-US/photography/lenses/sl/super-apo-summicron-sl-21-f2-asph',
  },
  'apo-summicron-sl-50mm-f2-asph': {
    name:'Leica APO-Summicron-SL 50mm f/2 ASPH.', manufacturer:'Leica', line:'SL', type:'Prime',
    mount:'l', focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2, minAperture:22, weight:740, length:102, diameter:73,
    filterThread:67, minFocusDist:35, maxMagnification:0.2,
    elements:12, groups:10, blades:null, afType:'Dual Syncro Drive (DSD)',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://leica-camera.com/sites/default/files/styles/meta_tag_product_image/public/pm-27850-11185__APO-Summicron-SL_50_f2_0.png',
    imageSource:{url:'https://leica-camera.com/en-US/photography/lenses/sl/apo-summicron-sl-50mm-f2-asph-black', tier:'T1', date:'2026-09-16', title:'Leica APO-Summicron-SL 50mm f/2 ASPH. official product page'},
    asin:null,
    prices:{USD:5450,AUD:8900,EUR:4990,GBP:4390,JPY:913000,CAD:7685,SGD:7450},
    productUrl:'https://leica-camera.com/en-US/photography/lenses/sl/apo-summicron-sl-50mm-f2-asph-black',
  },
  'summilux-sl-50mm-f14-asph': {
    name:'Leica Summilux-SL 50mm f/1.4 ASPH.', manufacturer:'Leica', line:'SL', type:'Prime',
    mount:'l', focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:584, length:75.5, diameter:74,
    filterThread:67, minFocusDist:50, maxMagnification:0.13,
    elements:11, groups:6, blades:11, afType:'Precision voice-coil drive',
    weatherSealed:true, ois:false, oisStops:null, year:2026, discontinued:false,
    imageUrl:'https://leica-camera.com/sites/default/files/styles/meta_tag_product_image/public/pm-28332-11195_Leica_Summilux-SL_50_f_1_4_upright_1920px.webp',
    imageSource:{url:'https://leica-camera.com/en-US/photography/lenses/sl/summilux-sl-50mm-f1-4-asph-black-anodized-finish', tier:'T1', date:'2026-09-16', title:'Leica Summilux-SL 50mm f/1.4 ASPH. official product page'},
    asin:null,
    // JPY/SGD not yet published — the 2026 compact redesign ships "autumn
    // 2026" and neither regional store has opened pricing/ordering yet
    // (confirmed on both store.leica-camera.jp and leica-store.sg,
    // 2026-09-16). Re-check closer to ship.
    prices:{USD:4950,AUD:7900,EUR:4500,GBP:3890,JPY:null,CAD:6980,SGD:null},
    priceIncomplete:true,
    productUrl:'https://leica-camera.com/en-US/photography/lenses/sl/summilux-sl-50mm-f1-4-asph-black-anodized-finish',
  },
  'vario-elmarit-sl-24-70mm-f28-asph': {
    name:'Leica Vario-Elmarit-SL 24-70mm f/2.8 ASPH.', manufacturer:'Leica', line:'SL', type:'Zoom',
    mount:'l', focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:856, length:123, diameter:88,
    filterThread:82, minFocusDist:18, maxMagnification:0.35,
    elements:19, groups:15, blades:11, afType:'Stepping motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://leica-camera.com/sites/default/files/styles/meta_tag_product_image/public/pm-15167-11189__Vario-Elmarit-SL_24-70_f2_8.png',
    imageSource:{url:'https://leica-camera.com/en-US/photography/lenses/sl/vario-elmarit-sl-24-70-f2-8-asph-black-finish', tier:'T1', date:'2026-09-16', title:'Leica Vario-Elmarit-SL 24-70mm f/2.8 ASPH. official product page'},
    asin:null,
    prices:{USD:3205,AUD:5300,EUR:2950,GBP:2590,JPY:539000,CAD:4520,SGD:4350},
    productUrl:'https://leica-camera.com/en-US/photography/lenses/sl/vario-elmarit-sl-24-70-f2-8-asph-black-finish',
  },
};

const LENS_DROPDOWN_GROUPS = [
  { label: '── SL Primes ──', ids: ['super-apo-summicron-sl-21mm-f2-asph', 'apo-summicron-sl-50mm-f2-asph', 'summilux-sl-50mm-f14-asph'] },
  { label: '── SL Zooms ──',  ids: ['vario-elmarit-sl-24-70mm-f28-asph'] },
];

return { BRAND_CONFIG, SERIES_COLORS, CAMERAS, CAMERA_ORDER, DROPDOWN_GROUPS, LENSES, LENS_DROPDOWN_GROUPS, REGISTERED_BRANDS };
})();
