// ─────────────────────────────────────────────
// NIKON BRAND CONFIG
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Nikon',
  slug:        'nikon',
  accentColor: '#ffd200',
  heroDark:    '#1a1700',
  logoText:    'Nikon',
  logoAccent:  '',
  families:    ['Z System'],
  brandSections: ['nikon'],
  cameras: {
    heroEyebrow:  'Z System',
    heroTitle:    '<span>Nikon</span> Camera Comparison',
    heroSubtitle: 'Compare up to 3 Nikon Z cameras side-by-side across the full lineup',
    headerTitle:  'Camera Compare',
    defaultSelected: ['z8', 'z6-iii', 'z50-ii'],
  },
  lenses: {
    heroEyebrow:  'Z Mount Lenses',
    heroTitle:    '<span>Nikon</span> Lens Comparison',
    heroSubtitle: 'Compare NIKKOR Z mount lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['z-50mm-f1-8-s', 'z-24-70mm-f2-8-s', 'z-70-200mm-f2-8-vr-s'],
  },
  footerLinks: [
    { label: 'Nikon Z System', url: 'https://www.nikonusa.com/en/nikon-products/mirrorless-cameras.page' },
    { label: 'DPReview Nikon', url: 'https://www.dpreview.com/products/nikon' },
    { label: 'Nikon Rumors',   url: 'https://nikonrumors.com' },
  ],
};

const REGISTERED_BRANDS = [
  { slug: 'fujifilm', name: 'Fujifilm' },
  { slug: 'canon',    name: 'Canon' },
  { slug: 'sony',     name: 'Sony' },
  { slug: 'nikon',    name: 'Nikon' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards) — Nikon yellow on near-black
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'Z (Full-frame)': { bg: '#1a1700', text: '#ffd54a' },
  'Z (APS-C)':      { bg: '#171400', text: '#e6c64a' },
  'Z (Retro)':      { bg: '#1f1a08', text: '#f0d27a' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE — Nikon Z mirrorless.
// Nikon-specific fields: expeed (processor gen), nRaw (internal N-RAW max res),
// pixelShift (High-Res Pixel Shift max output), preCapture (Pre-Release Capture).
// Pricing: USD is the exact launch/list RRP. Non-USD figures are APPROXIMATE RRPs
// derived from USD via regional ratios (refined as real RRP surfaces). Specs
// verified against Nikon official pages + DPReview/Wikipedia (see
// openspec/changes/add-nikon-brand/research/).
// ─────────────────────────────────────────────
const CAMERAS = {

  /* ── Z Full-frame ── */
  'z9': {
    name:'Z9', series:'Z (Full-frame)', year:2021, discontinued:false,
    tagline:'Stacked-Sensor Pro Flagship',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-9.html',
    imageUrl:null,
    asin:null,
    prices:{USD:5499,AUD:8799,EUR:6399,GBP:5299,JPY:900000,CAD:7599,SGD:7799},
    sensorMP:45.7, sensorType:'Full-frame Stacked BSI CMOS', processor:'EXPEED 7',
    width:149.0, height:149.5, depth:90.5, weight:1340, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2089, lcdType:'4-axis Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:6.0, maxBurst:20,
    maxVideoRes:'8.3K / 60P RAW',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:'8.3K', pixelShift:'180MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type B', batteryLife:700, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z8': {
    name:'Z8', series:'Z (Full-frame)', year:2023, discontinued:false,
    tagline:'Z9 Power in a Smaller Body',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-8.html',
    imageUrl:null,
    asin:null,
    prices:{USD:3999,AUD:6399,EUR:4649,GBP:3799,JPY:660000,CAD:5499,SGD:5699},
    sensorMP:45.7, sensorType:'Full-frame Stacked BSI CMOS', processor:'EXPEED 7',
    width:144.0, height:118.5, depth:83.0, weight:910, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2089, lcdType:'4-axis Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:6.0, maxBurst:20,
    maxVideoRes:'8.3K / 60P RAW',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:'8.3K', pixelShift:'180MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:340, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z6-iii': {
    name:'Z6 III', series:'Z (Full-frame)', year:2024, discontinued:false,
    tagline:'World-First Partially-Stacked Sensor',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-6iii.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Nikon_Z6III_%28by_Henry_S%C3%B6derlund%29.jpg/1280px-Nikon_Z6III_%28by_Henry_S%C3%B6derlund%29.jpg',
    asin:null,
    prices:{USD:2499,AUD:3999,EUR:2899,GBP:2399,JPY:412000,CAD:3399,SGD:3549},
    sensorMP:24.5, sensorType:'Full-frame Partially-Stacked BSI CMOS', processor:'EXPEED 7',
    width:138.5, height:101.5, depth:74.0, weight:760, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:5.76, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:8.0, maxBurst:20,
    maxVideoRes:'6K / 60P RAW',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:'6K', pixelShift:'96MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z5-ii': {
    name:'Z5 II', series:'Z (Full-frame)', year:2025, discontinued:false,
    tagline:'EXPEED 7 Full-Frame Entry Point',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z5-ii.html',
    imageUrl:null,
    asin:null,
    prices:{USD:1697,AUD:2699,EUR:1999,GBP:1599,JPY:280000,CAD:2299,SGD:2399},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 7',
    width:134.0, height:100.5, depth:72.0, weight:700, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:7.5, maxBurst:14,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:null, pixelShift:'96MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:330, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Z Full-frame (discontinued) ── USD-only pricing; asin null → search link */
  'z7-ii': {
    name:'Z7 II', series:'Z (Full-frame)', year:2020, discontinued:true,
    tagline:'High-Res Dual-Processor',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-7ii.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Nikon_Z_7II_with_Nikkor_Z_24-70mm_F4_S_-_by_Henry_S%C3%B6derlund_%2850723434183%29.jpg/1280px-Nikon_Z_7II_with_Nikkor_Z_24-70mm_F4_S_-_by_Henry_S%C3%B6derlund_%2850723434183%29.jpg', asin:null,
    prices:{USD:2999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:45.7, sensorType:'Full-frame BSI CMOS', processor:'Dual EXPEED 6',
    width:134.0, height:100.5, depth:69.5, weight:705, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:420, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z7': {
    name:'Z7', series:'Z (Full-frame)', year:2018, discontinued:true,
    tagline:'First High-Res Z Body',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-7.html',
    imageUrl:null, asin:null,
    prices:{USD:3399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:45.7, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 6',
    width:134.0, height:100.5, depth:67.5, weight:675, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:9,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× CFexpress / XQD', batteryLife:330, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z6-ii': {
    name:'Z6 II', series:'Z (Full-frame)', year:2020, discontinued:true,
    tagline:'Dual-Processor All-Rounder',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-6ii.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Nikon_Z_6II_2.jpg/1280px-Nikon_Z_6II_2.jpg', asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'Dual EXPEED 6',
    width:134.0, height:100.5, depth:69.5, weight:705, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:14,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:410, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z6': {
    name:'Z6', series:'Z (Full-frame)', year:2018, discontinued:true,
    tagline:'The Original 24MP Z',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-6.html',
    imageUrl:null, asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 6',
    width:134.0, height:100.5, depth:67.5, weight:675, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:12,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× CFexpress / XQD', batteryLife:310, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z5': {
    name:'Z5', series:'Z (Full-frame)', year:2020, discontinued:true,
    tagline:'Full-Frame Entry (Original)',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-5.html',
    imageUrl:null, asin:null,
    prices:{USD:1399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'Full-frame CMOS', processor:'EXPEED 6',
    width:134.0, height:100.5, depth:69.5, weight:675, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:1040, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:4.5,
    maxVideoRes:'4K / 30P (1.7× crop)',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:470, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Z APS-C (DX) ── */
  'z50-ii': {
    name:'Z50 II', series:'Z (APS-C)', year:2024, discontinued:false,
    tagline:'EXPEED 7 Comes to DX',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z50-ii.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Nikon_Z50II_28_nov_2024a.jpg/1280px-Nikon_Z50II_28_nov_2024a.jpg',
    asin:null,
    prices:{USD:907,AUD:1449,EUR:1049,GBP:849,JPY:150000,CAD:1249,SGD:1299},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 7',
    width:127.0, height:96.8, depth:66.5, weight:550, weatherSealed:false,
    lcdSize:'3.2"', lcdDots:1040, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:2.36, evfMag:1.02,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:null, pixelShift:null, preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:230, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z50': {
    name:'Z50', series:'Z (APS-C)', year:2019, discontinued:true,
    tagline:'First DX Z Body',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-50.html',
    imageUrl:null, asin:null,
    prices:{USD:860,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 6',
    width:126.5, height:93.5, depth:60.0, weight:450, weatherSealed:false,
    lcdSize:'3.2"', lcdDots:1040, lcdType:'Tilting',
    evfType:'EVF', evfDots:2.36, evfMag:1.02,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:320, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z30': {
    name:'Z30', series:'Z (APS-C)', year:2022, discontinued:false,
    tagline:'Vlogging DX, No Viewfinder',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z30.html',
    imageUrl:null, asin:null,
    prices:{USD:710,AUD:1099,EUR:799,GBP:649,JPY:117000,CAD:949,SGD:999},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 6',
    width:128.0, height:73.5, depth:60.0, weight:405, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Vari-angle',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:330, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Z Retro ── */
  'zf': {
    name:'Zf', series:'Z (Retro)', year:2023, discontinued:false,
    tagline:'Retro Full-Frame, Modern Guts',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-f.html',
    imageUrl:null, asin:null,
    prices:{USD:1999,AUD:3199,EUR:2299,GBP:1899,JPY:330000,CAD:2749,SGD:2849},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 7',
    width:144.0, height:103.0, depth:49.0, weight:710, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:8.0, maxBurst:14,
    maxVideoRes:'4K / 60P (DX crop)',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:null, pixelShift:'96MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× SD UHS-II + 1× microSD UHS-I', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'zfc': {
    name:'Zfc', series:'Z (Retro)', year:2021, discontinued:false,
    tagline:'Retro DX Crowd-Pleaser',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-fc.html',
    imageUrl:null, asin:null,
    prices:{USD:960,AUD:1499,EUR:1099,GBP:899,JPY:158000,CAD:1299,SGD:1349},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 6',
    width:134.5, height:93.5, depth:43.5, weight:445, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:2.36, evfMag:1.02,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:300, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

};

const CAMERA_ORDER = [
  'z9', 'z8', 'z6-iii', 'z5-ii',
  'z7-ii', 'z7', 'z6-ii', 'z6', 'z5',
  'zf', 'zfc',
  'z50-ii', 'z50', 'z30',
];

const DROPDOWN_GROUPS = [
  { label: '── Z Full-Frame ──', ids: ['z9', 'z8', 'z6-iii', 'z5-ii', 'z7-ii', 'z7', 'z6-ii', 'z6', 'z5'] },
  { label: '── Z Retro ──',      ids: ['zf', 'zfc'] },
  { label: '── Z APS-C (DX) ──', ids: ['z50-ii', 'z50', 'z30'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE — NIKKOR Z mount (Nikon first-party only).
// Specs verified against Nikon official pages + Wikipedia/DPReview.
// `priceIncomplete: true` ships an item with USD (+ any confirmed regional)
// while regional RRP backfill is pending (see check-prices-and-buy-links).
// ─────────────────────────────────────────────
const LENSES = {

  /* ── S-Line Primes ── */
  'z-50mm-f1-8-s': {
    name:'NIKKOR Z 50mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.8, minAperture:16, weight:415, length:86.5, diameter:76.0,
    filterThread:62, minFocusDist:40, maxMagnification:0.15,
    elements:12, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Nikon_NIKKOR_Z_50mm_f_1.8_S_%2849288626406%29.jpg/1280px-Nikon_NIKKOR_Z_50mm_f_1.8_S_%2849288626406%29.jpg',
    prices:{USD:597,AUD:899,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-50mm-f%2f1.8-s.html',
  },

  'z-20mm-f1-8-s': {
    name:'NIKKOR Z 20mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:1.8, minAperture:16, weight:505, length:108.5, diameter:84.5,
    filterThread:77, minFocusDist:20, maxMagnification:0.19,
    elements:14, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Nikon_NIKKOR_Z_20mm_f_1.8_S_%2852044601591%29.jpg/1280px-Nikon_NIKKOR_Z_20mm_f_1.8_S_%2852044601591%29.jpg',
    prices:{USD:1047,AUD:1599,EUR:null,GBP:null,JPY:null,CAD:1399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-20mm-f%2f1.8-s.html',
  },

  'z-24mm-f1-8-s': {
    name:'NIKKOR Z 24mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.8, minAperture:16, weight:450, length:96.5, diameter:78.0,
    filterThread:72, minFocusDist:25, maxMagnification:0.15,
    elements:12, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1499,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-24mm-f%2f1.8-s.html',
  },

  'z-35mm-f1-8-s': {
    name:'NIKKOR Z 35mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.8, minAperture:16, weight:370, length:86.0, diameter:73.0,
    filterThread:62, minFocusDist:25, maxMagnification:0.19,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:847,AUD:1299,EUR:null,GBP:null,JPY:null,CAD:1149,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-35mm-f%2f1.8-s.html',
  },

  'z-85mm-f1-8-s': {
    name:'NIKKOR Z 85mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.8, minAperture:16, weight:470, length:99.0, diameter:75.0,
    filterThread:67, minFocusDist:80, maxMagnification:0.12,
    elements:12, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:797,AUD:1199,EUR:null,GBP:null,JPY:null,CAD:1099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-85mm-f%2f1.8-s.html',
  },

  'z-35mm-f1-2-s': {
    name:'NIKKOR Z 35mm f/1.2 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.2, minAperture:16, weight:1060, length:150.0, diameter:90.0,
    filterThread:82, minFocusDist:30, maxMagnification:0.17,
    elements:17, groups:15, blades:11, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2025, discontinued:false,
    imageUrl:null,
    prices:{USD:2797,AUD:4299,EUR:null,GBP:null,JPY:null,CAD:3799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-35mm-f%2f1.2-s.html',
  },

  'z-50mm-f1-2-s': {
    name:'NIKKOR Z 50mm f/1.2 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.2, minAperture:16, weight:1090, length:150.0, diameter:89.5,
    filterThread:82, minFocusDist:45, maxMagnification:0.15,
    elements:17, groups:15, blades:9, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Nikon_NIKKOR_Z_50mm_f_1.2_S_%2851602295538%29.jpg/1280px-Nikon_NIKKOR_Z_50mm_f_1.2_S_%2851602295538%29.jpg',
    prices:{USD:2097,AUD:3199,EUR:null,GBP:null,JPY:null,CAD:2849,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-50mm-f%2f1.2-s.html',
  },

  'z-85mm-f1-2-s': {
    name:'NIKKOR Z 85mm f/1.2 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.2, minAperture:16, weight:1160, length:141.5, diameter:102.5,
    filterThread:82, minFocusDist:85, maxMagnification:0.11,
    elements:15, groups:10, blades:11, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Nikon_Nikkor_Z_85mm_f_1.2_S_by_Henry_S%C3%B6derlund.jpg/1280px-Nikon_Nikkor_Z_85mm_f_1.2_S_by_Henry_S%C3%B6derlund.jpg',
    prices:{USD:2797,AUD:4299,EUR:null,GBP:null,JPY:null,CAD:3799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-85mm-f%2f1.2-s.html',
  },

  'z-135mm-f1-8-s-plena': {
    name:'NIKKOR Z 135mm f/1.8 S Plena', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:135, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'135mm',
    maxAperture:1.8, minAperture:16, weight:995, length:139.5, diameter:98.0,
    filterThread:82, minFocusDist:82, maxMagnification:0.19,
    elements:16, groups:14, blades:11, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:2497,AUD:3799,EUR:null,GBP:null,JPY:null,CAD:3399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-135mm-f%2f1.8-s-plena.html',
  },

  'z-mc-105mm-f2-8-vr-s': {
    name:'NIKKOR Z MC 105mm f/2.8 VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:105, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'105mm',
    maxAperture:2.8, minAperture:32, weight:630, length:140.0, diameter:85.0,
    filterThread:62, minFocusDist:29, maxMagnification:1.0,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1499,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-mc-105mm-f%2f2.8-vr-s.html',
  },

  'z-58mm-f0-95-s-noct': {
    name:'NIKKOR Z 58mm f/0.95 S Noct', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:58, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'58mm',
    maxAperture:0.95, minAperture:16, weight:2000, length:153.0, diameter:102.0,
    filterThread:82, minFocusDist:50, maxMagnification:0.19,
    elements:17, groups:10, blades:11, afType:'Manual Focus',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:7997,AUD:11999,EUR:null,GBP:null,JPY:null,CAD:10999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-58mm-f%2f0.95-s-noct.html',
  },

  /* ── S-Line Zooms ── */
  'z-24-70mm-f2-8-s': {
    name:'NIKKOR Z 24-70mm f/2.8 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:805, length:126.0, diameter:89.0,
    filterThread:82, minFocusDist:38, maxMagnification:0.22,
    elements:17, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Nikon_Z7ii_%2B_nikkor_z_24-70mm_f2.8_s.jpg/1280px-Nikon_Z7ii_%2B_nikkor_z_24-70mm_f2.8_s.jpg',
    prices:{USD:2297,AUD:3499,EUR:null,GBP:null,JPY:null,CAD:3099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-24-70mm-f%2f2.8-s.html',
  },

  'z-70-200mm-f2-8-vr-s': {
    name:'NIKKOR Z 70-200mm f/2.8 VR S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1440, length:220.0, diameter:89.0,
    filterThread:77, minFocusDist:50, maxMagnification:0.20,
    elements:21, groups:18, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Nikon_NIKKOR_Z_70-200mm_f_2.8_VR_S_%2850342502711%29.jpg/1280px-Nikon_NIKKOR_Z_70-200mm_f_2.8_VR_S_%2850342502711%29.jpg',
    prices:{USD:2597,AUD:3999,EUR:null,GBP:null,JPY:null,CAD:3499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-70-200mm-f%2f2.8-vr-s.html',
  },

  /* ── Standard Primes (non-S, FX) ── */
  'z-26mm-f2-8': {
    name:'NIKKOR Z 26mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:26, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'26mm',
    maxAperture:2.8, minAperture:16, weight:125, length:23.5, diameter:70.0,
    filterThread:52, minFocusDist:20, maxMagnification:0.19,
    elements:8, groups:6, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:749,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-26mm-f%2f2.8.html',
  },

  'z-28mm-f2-8': {
    name:'NIKKOR Z 28mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:28, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'28mm',
    maxAperture:2.8, minAperture:16, weight:155, length:43.0, diameter:70.0,
    filterThread:52, minFocusDist:19, maxMagnification:0.20,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:297,AUD:449,EUR:null,GBP:null,JPY:null,CAD:399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-28mm-f%2f2.8.html',
  },

  'z-28mm-f2-8-se': {
    name:'NIKKOR Z 28mm f/2.8 (SE)', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:28, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'28mm',
    maxAperture:2.8, minAperture:16, weight:160, length:43.0, diameter:71.5,
    filterThread:52, minFocusDist:19, maxMagnification:0.20,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Nikon_Z_fc_with_Nikkor_Z_28mm_F2.8_SE_-_by_Henry_S%C3%B6derlund_%2851675302954%29.jpg/1280px-Nikon_Z_fc_with_Nikkor_Z_28mm_F2.8_SE_-_by_Henry_S%C3%B6derlund_%2851675302954%29.jpg',
    prices:{USD:297,AUD:449,EUR:null,GBP:null,JPY:null,CAD:399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-28mm-f%2f2.8-se.html',
  },

  'z-35mm-f1-4': {
    name:'NIKKOR Z 35mm f/1.4', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:415, length:86.5, diameter:74.5,
    filterThread:62, minFocusDist:27, maxMagnification:0.18,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Nikon_NIKKOR_Z_35mm_f_1.4_%2853868344792%29.jpg/1280px-Nikon_NIKKOR_Z_35mm_f_1.4_%2853868344792%29.jpg',
    prices:{USD:597,AUD:899,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-35mm-f%2f1.4.html',
  },

  'z-40mm-f2': {
    name:'NIKKOR Z 40mm f/2', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.0, minAperture:16, weight:170, length:45.5, diameter:70.0,
    filterThread:52, minFocusDist:29, maxMagnification:0.17,
    elements:6, groups:4, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Nikon_Nikkor_Z_40mm_F2_%2851607832457%29.jpg/1280px-Nikon_Nikkor_Z_40mm_F2_%2851607832457%29.jpg',
    prices:{USD:297,AUD:449,EUR:null,GBP:null,JPY:null,CAD:399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-40mm-f%2f2.html',
  },

  'z-40mm-f2-se': {
    name:'NIKKOR Z 40mm f/2 (SE)', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.0, minAperture:16, weight:170, length:45.5, diameter:71.5,
    filterThread:52, minFocusDist:29, maxMagnification:0.17,
    elements:6, groups:4, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:307,AUD:469,EUR:null,GBP:null,JPY:null,CAD:419,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-40mm-f%2f2-se.html',
  },

  'z-50mm-f1-4': {
    name:'NIKKOR Z 50mm f/1.4', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:420, length:86.5, diameter:74.5,
    filterThread:62, minFocusDist:37, maxMagnification:0.18,
    elements:10, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:749,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-50mm-f%2f1.4.html',
  },

  'z-50mm-f2-8-mc': {
    name:'NIKKOR Z MC 50mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:null,
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.8, minAperture:22, weight:260, length:66.0, diameter:74.5,
    filterThread:46, minFocusDist:16, maxMagnification:1.0,
    elements:10, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Nikon_NIKKOR_Z_MC_50mm_f_2.8_%2851378200761%29.jpg/1280px-Nikon_NIKKOR_Z_MC_50mm_f_2.8_%2851378200761%29.jpg',
    prices:{USD:647,AUD:999,EUR:null,GBP:null,JPY:null,CAD:879,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-mc-50mm-f%2f2.8.html',
  },

  /* ── DX Primes ── */
  'z-dx-24mm-f1-7': {
    name:'NIKKOR Z DX 24mm f/1.7', manufacturer:'Nikon', line:'DX', type:'Prime', asin:null,
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'36mm',
    maxAperture:1.7, minAperture:16, weight:135, length:40.0, diameter:70.0,
    filterThread:46, minFocusDist:18, maxMagnification:0.20,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:277,AUD:429,EUR:null,GBP:null,JPY:null,CAD:379,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-dx-24mm-f%2f1.7.html',
  },

  /* ── S-Line Zooms (cont.) ── */
  'z-14-24mm-f2-8-s': {
    name:'NIKKOR Z 14-24mm f/2.8 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:14, focalLengthMax:24, focalLengthEquiv:'14-24mm',
    maxAperture:2.8, minAperture:22, weight:650, length:124.5, diameter:88.5,
    filterThread:112, minFocusDist:28, maxMagnification:0.13,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:2399,AUD:3699,EUR:null,GBP:null,JPY:null,CAD:3299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-14-24mm-f%2f2.8-s.html',
  },

  'z-14-30mm-f4-s': {
    name:'NIKKOR Z 14-30mm f/4 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:14, focalLengthMax:30, focalLengthEquiv:'14-30mm',
    maxAperture:4.0, minAperture:22, weight:485, length:85.0, diameter:89.0,
    filterThread:82, minFocusDist:28, maxMagnification:0.16,
    elements:14, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-14-30mm-f%2f4-s.html',
  },

  'z-24-70mm-f4-s': {
    name:'NIKKOR Z 24-70mm f/4 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:4.0, minAperture:22, weight:500, length:88.5, diameter:77.5,
    filterThread:72, minFocusDist:30, maxMagnification:0.30,
    elements:14, groups:11, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1499,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-24-70mm-f%2f4-s.html',
  },

  'z-24-120mm-f4-s': {
    name:'NIKKOR Z 24-120mm f/4 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:24, focalLengthMax:120, focalLengthEquiv:'24-120mm',
    maxAperture:4.0, minAperture:22, weight:630, length:118.0, diameter:84.0,
    filterThread:77, minFocusDist:35, maxMagnification:0.39,
    elements:16, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Nikon_NIKKOR_Z_24-120mm_f_4_S_%2851793292337%29.jpg/1280px-Nikon_NIKKOR_Z_24-120mm_f_4_S_%2851793292337%29.jpg',
    prices:{USD:1097,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-24-120mm-f%2f4-s.html',
  },

  'z-100-400mm-f4-5-5-6-vr-s': {
    name:'NIKKOR Z 100-400mm f/4.5-5.6 VR S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:100, focalLengthMax:400, focalLengthEquiv:'100-400mm',
    maxAperture:4.5, minAperture:32, weight:1435, length:222.0, diameter:98.0,
    filterThread:77, minFocusDist:75, maxMagnification:0.38,
    elements:25, groups:20, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Nikon_Nikkor_Z_100-400mm_F4.5-5.6_VR_S_-_by_Henry_S%C3%B6derlund_%2852457041193%29.jpg/1280px-Nikon_Nikkor_Z_100-400mm_F4.5-5.6_VR_S_-_by_Henry_S%C3%B6derlund_%2852457041193%29.jpg',
    prices:{USD:2697,AUD:4199,EUR:null,GBP:null,JPY:null,CAD:3699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-100-400mm-f%2f4.5-5.6-vr-s.html',
  },

  /* ── Standard / Travel Zooms (non-S, FX) ── */
  'z-17-28mm-f2-8': {
    name:'NIKKOR Z 17-28mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:17, focalLengthMax:28, focalLengthEquiv:'17-28mm',
    maxAperture:2.8, minAperture:22, weight:450, length:101.0, diameter:75.0,
    filterThread:67, minFocusDist:19, maxMagnification:0.19,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Nikon_NIKKOR_Z_17-28mm_f_2.8_%2852474327801%29.jpg/1280px-Nikon_NIKKOR_Z_17-28mm_f_2.8_%2852474327801%29.jpg',
    prices:{USD:1197,AUD:1849,EUR:null,GBP:null,JPY:null,CAD:1649,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-17-28mm-f%2f2.8.html',
  },

  'z-24-50mm-f4-6-3': {
    name:'NIKKOR Z 24-50mm f/4-6.3', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:24, focalLengthMax:50, focalLengthEquiv:'24-50mm',
    maxAperture:4.0, minAperture:22, weight:195, length:51.0, diameter:73.5,
    filterThread:52, minFocusDist:35, maxMagnification:0.17,
    elements:11, groups:10, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:397,AUD:599,EUR:null,GBP:null,JPY:null,CAD:529,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-24-50mm-f%2f4-6.3.html',
  },

  'z-24-200mm-f4-6-3-vr': {
    name:'NIKKOR Z 24-200mm f/4-6.3 VR', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:24, focalLengthMax:200, focalLengthEquiv:'24-200mm',
    maxAperture:4.0, minAperture:22, weight:570, length:114.0, diameter:76.5,
    filterThread:67, minFocusDist:50, maxMagnification:0.28,
    elements:19, groups:15, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1229,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-24-200mm-f%2f4-6.3-vr.html',
  },

  'z-28-75mm-f2-8': {
    name:'NIKKOR Z 28-75mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:28, focalLengthMax:75, focalLengthEquiv:'28-75mm',
    maxAperture:2.8, minAperture:22, weight:565, length:120.5, diameter:75.0,
    filterThread:67, minFocusDist:19, maxMagnification:0.34,
    elements:15, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nikon_NIKKOR_Z_28-75mm_f_2.8_%2851832796897%29.jpg/1280px-Nikon_NIKKOR_Z_28-75mm_f_2.8_%2851832796897%29.jpg',
    prices:{USD:1197,AUD:1849,EUR:null,GBP:null,JPY:null,CAD:1649,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-28-75mm-f%2f2.8.html',
  },

  'z-28-400mm-f4-8-vr': {
    name:'NIKKOR Z 28-400mm f/4-8 VR', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:28, focalLengthMax:400, focalLengthEquiv:'28-400mm',
    maxAperture:4.0, minAperture:32, weight:725, length:142.0, diameter:85.0,
    filterThread:77, minFocusDist:20, maxMagnification:0.35,
    elements:21, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2024, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Nikon_NIKKOR_Z_28-400mm_f_4-8_VR_by_Henry_S%C3%B6derlund.jpg/1280px-Nikon_NIKKOR_Z_28-400mm_f_4-8_VR_by_Henry_S%C3%B6derlund.jpg',
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-28-400mm-f%2f4-8-vr.html',
  },

  /* ── Telephoto / Super-Telephoto ── */
  'z-70-180mm-f2-8': {
    name:'NIKKOR Z 70-180mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:70, focalLengthMax:180, focalLengthEquiv:'70-180mm',
    maxAperture:2.8, minAperture:22, weight:795, length:151.0, diameter:83.5,
    filterThread:67, minFocusDist:27, maxMagnification:0.48,
    elements:19, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Nikon_NIKKOR_Z_70-180mm_F2.8_%2853061678724%29.jpg/1280px-Nikon_NIKKOR_Z_70-180mm_F2.8_%2853061678724%29.jpg',
    prices:{USD:1247,AUD:1899,EUR:null,GBP:null,JPY:null,CAD:1699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-70-180mm-f%2f2.8.html',
  },

  'z-180-600mm-f5-6-6-3-vr': {
    name:'NIKKOR Z 180-600mm f/5.6-6.3 VR', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:180, focalLengthMax:600, focalLengthEquiv:'180-600mm',
    maxAperture:5.6, minAperture:32, weight:2140, length:315.5, diameter:110.0,
    filterThread:95, minFocusDist:130, maxMagnification:0.25,
    elements:25, groups:17, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:1697,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-180-600mm-f%2f5.6-6.3-vr.html',
  },

  'z-400mm-f4-5-vr-s': {
    name:'NIKKOR Z 400mm f/4.5 VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:400, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm',
    maxAperture:4.5, minAperture:32, weight:1245, length:234.5, diameter:104.0,
    filterThread:95, minFocusDist:250, maxMagnification:0.16,
    elements:19, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:3247,AUD:4999,EUR:null,GBP:null,JPY:null,CAD:4399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-400mm-f%2f4.5-vr-s.html',
  },

  'z-400mm-f2-8-tc-vr-s': {
    name:'NIKKOR Z 400mm f/2.8 TC VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:400, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm (560mm w/ TC)',
    maxAperture:2.8, minAperture:22, weight:2950, length:380.0, diameter:156.0,
    filterThread:46, minFocusDist:250, maxMagnification:0.16,
    elements:25, groups:19, blades:9, afType:'Silky Swift VCM',
    weatherSealed:true, ois:true, oisStops:5.5, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:13997,AUD:21499,EUR:null,GBP:null,JPY:null,CAD:18999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-400mm-f%2f2.8-tc-vr-s.html',
  },

  'z-600mm-f6-3-vr-s-pf': {
    name:'NIKKOR Z 600mm f/6.3 VR S (PF)', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:600, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'600mm',
    maxAperture:6.3, minAperture:32, weight:1470, length:278.0, diameter:106.5,
    filterThread:95, minFocusDist:400, maxMagnification:0.16,
    elements:21, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:4797,AUD:7399,EUR:null,GBP:null,JPY:null,CAD:6499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-600mm-f%2f6.3-vr-s.html',
  },

  'z-600mm-f4-tc-vr-s': {
    name:'NIKKOR Z 600mm f/4 TC VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:600, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'600mm (840mm w/ TC)',
    maxAperture:4.0, minAperture:22, weight:3260, length:437.0, diameter:165.0,
    filterThread:46, minFocusDist:440, maxMagnification:0.14,
    elements:26, groups:20, blades:9, afType:'Silky Swift VCM',
    weatherSealed:true, ois:true, oisStops:5.5, year:2022, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Nikon_Nikkor_Z_600mm_F4_TC_VR_S_20260516113641.jpg/1280px-Nikon_Nikkor_Z_600mm_F4_TC_VR_S_20260516113641.jpg',
    prices:{USD:15497,AUD:23999,EUR:null,GBP:null,JPY:null,CAD:20999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-600mm-f%2f4-tc-vr-s.html',
  },

  'z-800mm-f6-3-vr-s-pf': {
    name:'NIKKOR Z 800mm f/6.3 VR S (PF)', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:null,
    focalLength:800, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'800mm',
    maxAperture:6.3, minAperture:32, weight:2385, length:385.0, diameter:140.0,
    filterThread:46, minFocusDist:500, maxMagnification:0.16,
    elements:22, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:6497,AUD:9999,EUR:null,GBP:null,JPY:null,CAD:8799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-800mm-f%2f6.3-vr-s.html',
  },

  /* ── DX Zooms ── */
  'z-dx-12-28mm-pz-vr': {
    name:'NIKKOR Z DX 12-28mm f/3.5-5.6 PZ VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:12, focalLengthMax:28, focalLengthEquiv:'18-42mm',
    maxAperture:3.5, minAperture:22, weight:205, length:63.5, diameter:72.0,
    filterThread:67, minFocusDist:19, maxMagnification:0.21,
    elements:12, groups:11, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:357,AUD:549,EUR:null,GBP:null,JPY:null,CAD:479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-dx-12-28mm-f%2f3.5-5.6-pz-vr.html',
  },

  'z-dx-16-50mm-vr': {
    name:'NIKKOR Z DX 16-50mm f/3.5-6.3 VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:16, focalLengthMax:50, focalLengthEquiv:'24-75mm',
    maxAperture:3.5, minAperture:22, weight:135, length:32.0, diameter:70.0,
    filterThread:46, minFocusDist:20, maxMagnification:0.20,
    elements:9, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:4.5, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:307,AUD:469,EUR:null,GBP:null,JPY:null,CAD:419,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-dx-16-50mm-f%2f3.5-6.3-vr.html',
  },

  'z-dx-18-140mm-vr': {
    name:'NIKKOR Z DX 18-140mm f/3.5-6.3 VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:18, focalLengthMax:140, focalLengthEquiv:'27-210mm',
    maxAperture:3.5, minAperture:22, weight:315, length:90.0, diameter:73.0,
    filterThread:62, minFocusDist:20, maxMagnification:0.33,
    elements:17, groups:13, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:5.0, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:397,AUD:599,EUR:null,GBP:null,JPY:null,CAD:529,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-dx-18-140mm-f%2f3.5-6.3-vr.html',
  },

  'z-dx-50-250mm-vr': {
    name:'NIKKOR Z DX 50-250mm f/4.5-6.3 VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:null,
    focalLength:null, focalLengthMin:50, focalLengthMax:250, focalLengthEquiv:'75-375mm',
    maxAperture:4.5, minAperture:22, weight:405, length:110.0, diameter:74.0,
    filterThread:62, minFocusDist:50, maxMagnification:0.23,
    elements:16, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:5.0, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:357,AUD:549,EUR:null,GBP:null,JPY:null,CAD:479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/camera-lenses/nikkor-z-dx-50-250mm-f%2f4.5-6.3-vr.html',
  },

};

const LENS_DROPDOWN_GROUPS = [
  { label: '── S-Line Primes ──', ids: ['z-20mm-f1-8-s', 'z-24mm-f1-8-s', 'z-35mm-f1-8-s', 'z-50mm-f1-8-s', 'z-85mm-f1-8-s', 'z-35mm-f1-2-s', 'z-50mm-f1-2-s', 'z-85mm-f1-2-s', 'z-135mm-f1-8-s-plena', 'z-mc-105mm-f2-8-vr-s', 'z-58mm-f0-95-s-noct'] },
  { label: '── Standard Primes ──', ids: ['z-26mm-f2-8', 'z-28mm-f2-8', 'z-28mm-f2-8-se', 'z-35mm-f1-4', 'z-40mm-f2', 'z-40mm-f2-se', 'z-50mm-f1-4', 'z-50mm-f2-8-mc'] },
  { label: '── S-Line Zooms ──',  ids: ['z-14-24mm-f2-8-s', 'z-24-70mm-f2-8-s', 'z-24-70mm-f4-s', 'z-14-30mm-f4-s', 'z-24-120mm-f4-s', 'z-70-200mm-f2-8-vr-s', 'z-100-400mm-f4-5-5-6-vr-s'] },
  { label: '── Standard / Travel Zooms ──', ids: ['z-17-28mm-f2-8', 'z-24-50mm-f4-6-3', 'z-28-75mm-f2-8', 'z-24-200mm-f4-6-3-vr', 'z-28-400mm-f4-8-vr'] },
  { label: '── Telephoto / Super-Telephoto ──', ids: ['z-70-180mm-f2-8', 'z-180-600mm-f5-6-6-3-vr', 'z-400mm-f4-5-vr-s', 'z-400mm-f2-8-tc-vr-s', 'z-600mm-f6-3-vr-s-pf', 'z-600mm-f4-tc-vr-s', 'z-800mm-f6-3-vr-s-pf'] },
  { label: '── DX Lenses ──',     ids: ['z-dx-24mm-f1-7', 'z-dx-12-28mm-pz-vr', 'z-dx-16-50mm-vr', 'z-dx-18-140mm-vr', 'z-dx-50-250mm-vr'] },
];
