// Registered into the shared brand-data registry so multiple brand files
// can load on one page (see compare/). The data below is unchanged.
window.BRAND_DATA = window.BRAND_DATA || {};
window.BRAND_DATA['nikon'] = (() => {
// ─────────────────────────────────────────────
// NIKON BRAND CONFIG
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Nikon',
  slug:        'nikon',
  accentColor: '#ffd200',
  heroDark:    '#1a1700',
  logoText:    'Nikon',
  logoAccent:  '',
  families:    ['Z System'],
  brandSections: ['nikon'],
  cameras: {
    heroEyebrow:  'Z System',
    heroTitle:    '<span>Nikon</span> Camera Comparison',
    heroSubtitle: 'Compare up to 3 Nikon Z cameras side-by-side across the full lineup',
    headerTitle:  'Camera Compare',
    defaultSelected: ['z8', 'z6-iii', 'z50-ii'],
  },
  lenses: {
    heroEyebrow:  'Z Mount Lenses',
    heroTitle:    '<span>Nikon</span> Lens Comparison',
    heroSubtitle: 'Compare NIKKOR Z mount lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['z-50mm-f1-8-s', 'z-24-70mm-f2-8-s', 'z-70-200mm-f2-8-vr-s'],
  },
  footerLinks: [
    { label: 'Nikon Z System', url: 'https://www.nikonusa.com/en/nikon-products/mirrorless-cameras.page' },
    { label: 'DPReview Nikon', url: 'https://www.dpreview.com/products/nikon' },
    { label: 'Nikon Rumors',   url: 'https://nikonrumors.com' },
  ],
};

const REGISTERED_BRANDS = [
  { slug: 'fujifilm', name: 'Fujifilm' },
  { slug: 'canon',    name: 'Canon' },
  { slug: 'sony',     name: 'Sony' },
  { slug: 'nikon',    name: 'Nikon' },
  { slug: 'panasonic', name: 'Panasonic' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards) — Nikon yellow on near-black
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'Z (Full-frame)': { bg: '#1a1700', text: '#ffd54a' },
  'Z (APS-C)':      { bg: '#171400', text: '#e6c64a' },
  'Z (Retro)':      { bg: '#1f1a08', text: '#f0d27a' },
  'Z Cinema (Full-frame)': { bg: '#160f00', text: '#ffcf4a' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE — Nikon Z mirrorless.
// Nikon-specific fields: expeed (processor gen), nRaw (internal N-RAW max res),
// pixelShift (High-Res Pixel Shift max output), preCapture (Pre-Release Capture).
// Pricing: USD is the exact launch/list RRP. Non-USD figures are APPROXIMATE RRPs
// derived from USD via regional ratios (refined as real RRP surfaces). Specs
// verified against Nikon official pages + DPReview/Wikipedia (see
// openspec/changes/add-nikon-brand/research/).
// ─────────────────────────────────────────────
const CAMERAS = {

  /* ── Z Full-frame ── */
  'z9': {
    name:'Z9', series:'Z (Full-frame)', year:2021, discontinued:false,
    tagline:'Stacked-Sensor Pro Flagship',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-9.html',
    imageUrl:null,
    asin:'B09KHC4XCT',
    prices:{USD:5900,AUD:8799,EUR:6399,GBP:5299,JPY:900000,CAD:7599,SGD:7799},
    sensorMP:45.7, sensorType:'Full-frame Stacked BSI CMOS', processor:'EXPEED 7',
    width:149.0, height:149.5, depth:90.5, weight:1340, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2089, lcdType:'4-axis Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:6.0, maxBurst:20,
    maxVideoRes:'8.3K / 60P RAW',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:'8.3K', pixelShift:'180MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type B', batteryLife:700, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z8': {
    name:'Z8', series:'Z (Full-frame)', year:2023, discontinued:false,
    tagline:'Z9 Power in a Smaller Body',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-8.html',
    imageUrl:null,
    asin:'B0C4Q71JBY',
    prices:{USD:4300,AUD:6399,EUR:4649,GBP:3799,JPY:660000,CAD:5499,SGD:5699},
    sensorMP:45.7, sensorType:'Full-frame Stacked BSI CMOS', processor:'EXPEED 7',
    width:144.0, height:118.5, depth:83.0, weight:910, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2089, lcdType:'4-axis Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:6.0, maxBurst:20,
    maxVideoRes:'8.3K / 60P RAW',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:'8.3K', pixelShift:'180MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:340, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z6-iii': {
    name:'Z6 III', series:'Z (Full-frame)', year:2024, discontinued:false,
    tagline:'World-First Partially-Stacked Sensor',
    productUrl:'https://www.nikonusa.com/p/z6iii/1890/overview',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Nikon_Z6III_%28by_Henry_S%C3%B6derlund%29.jpg/1280px-Nikon_Z6III_%28by_Henry_S%C3%B6derlund%29.jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z6III_(by_Henry_S%C3%B6derlund).jpg"},
    asin:'B0D77SL8CY',
    prices:{USD:2700,AUD:3999,EUR:2899,GBP:2399,JPY:412000,CAD:3399,SGD:3549},
    sensorMP:24.5, sensorType:'Full-frame Partially-Stacked BSI CMOS', processor:'EXPEED 7',
    width:138.5, height:101.5, depth:74.0, weight:760, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:5.76, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:8.0, maxBurst:20,
    maxVideoRes:'6K / 60P RAW',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:'6K', pixelShift:'96MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z5-ii': {
    name:'Z5 II', series:'Z (Full-frame)', year:2025, discontinued:false,
    tagline:'EXPEED 7 Full-Frame Entry Point',
    productUrl:'https://www.nikonusa.com/p/z5ii/1680/overview',
    imageUrl:null,
    asin:'B0F3HJD64Y',
    prices:{USD:1850,AUD:2699,EUR:1999,GBP:1599,JPY:280000,CAD:2299,SGD:2399},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 7',
    width:134.0, height:100.5, depth:72.0, weight:700, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:7.5, maxBurst:14,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:null, pixelShift:'96MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:330, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Z Cinema ── */
  'zr': {
    name:'ZR', series:'Z Cinema (Full-frame)', year:2025, discontinued:false,
    tagline:'RED-Powered Full-Frame Cinema',
    productUrl:'https://imaging.nikon.com/imaging/lineup/z_cinema/z_r/',
    imageUrl:null,
    asin:'B0FPXLG8X7',
    prices:{USD:2199,AUD:3499,EUR:2549,GBP:2099,JPY:363000,CAD:2999,SGD:3149},
    sensorMP:24.5, sensorType:'Full-frame Partially-Stacked BSI CMOS', processor:'EXPEED 7',
    width:134.0, height:80.5, depth:49.0, weight:630, weatherSealed:true,
    lcdSize:'4.0"', lcdDots:3070, lcdType:'Fully-Articulating Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:7.5, maxBurst:15,
    maxVideoRes:'6K / 60P R3D RAW',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:'6K', pixelShift:null, preCapture:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× microSD', batteryLife:null, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Z Full-frame (discontinued) ── USD-only pricing; asin null → search link */
  'z7-ii': {
    name:'Z7 II', series:'Z (Full-frame)', year:2020, discontinued:true,
    tagline:'High-Res Dual-Processor',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-7ii.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Nikon_Z_7II_with_Nikkor_Z_24-70mm_F4_S_-_by_Henry_S%C3%B6derlund_%2850723434183%29.jpg/1280px-Nikon_Z_7II_with_Nikkor_Z_24-70mm_F4_S_-_by_Henry_S%C3%B6derlund_%2850723434183%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z_7II_with_Nikkor_Z_24-70mm_F4_S_-_by_Henry_S%C3%B6derlund_(50723434183).jpg"}, asin:null,
    prices:{USD:2999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:45.7, sensorType:'Full-frame BSI CMOS', processor:'Dual EXPEED 6',
    width:134.0, height:100.5, depth:69.5, weight:705, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:420, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z7': {
    name:'Z7', series:'Z (Full-frame)', year:2018, discontinued:true,
    tagline:'First High-Res Z Body',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-7.html',
    imageUrl:null, asin:null,
    prices:{USD:3399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:45.7, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 6',
    width:134.0, height:100.5, depth:67.5, weight:675, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:9,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× CFexpress / XQD', batteryLife:330, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z6-ii': {
    name:'Z6 II', series:'Z (Full-frame)', year:2020, discontinued:true,
    tagline:'Dual-Processor All-Rounder',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-6ii.html',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Nikon_Z_6II_2.jpg/1280px-Nikon_Z_6II_2.jpg',
    imageCredit:{author:"Thilo Parg", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z_6II_2.jpg"}, asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'Dual EXPEED 6',
    width:134.0, height:100.5, depth:69.5, weight:705, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:14,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:410, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z6': {
    name:'Z6', series:'Z (Full-frame)', year:2018, discontinued:true,
    tagline:'The Original 24MP Z',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-6.html',
    imageUrl:null, asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 6',
    width:134.0, height:100.5, depth:67.5, weight:675, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:12,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× CFexpress / XQD', batteryLife:310, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z5': {
    name:'Z5', series:'Z (Full-frame)', year:2020, discontinued:true,
    tagline:'Full-Frame Entry (Original)',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-5.html',
    imageUrl:null, asin:null,
    prices:{USD:1399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'Full-frame CMOS', processor:'EXPEED 6',
    width:134.0, height:100.5, depth:69.5, weight:675, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:1040, lcdType:'Tilting',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:true, ibisStops:5.0, maxBurst:4.5,
    maxVideoRes:'4K / 30P (1.7× crop)',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:470, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Z APS-C (DX) ── */
  'z50-ii': {
    name:'Z50 II', series:'Z (APS-C)', year:2024, discontinued:false,
    tagline:'EXPEED 7 Comes to DX',
    productUrl:'https://www.nikonusa.com/p/z50ii/1784/overview',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Nikon_Z50II_28_nov_2024a.jpg/1280px-Nikon_Z50II_28_nov_2024a.jpg',
    imageCredit:{author:"昼落ち", licence:"CC0", licenceUrl:"http://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z50II_28_nov_2024a.jpg"},
    asin:'B0DMJBLQGP',
    prices:{USD:1007,AUD:1449,EUR:1049,GBP:849,JPY:150000,CAD:1249,SGD:1299},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 7',
    width:127.0, height:96.8, depth:66.5, weight:550, weatherSealed:false,
    lcdSize:'3.2"', lcdDots:1040, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:2.36, evfMag:1.02,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:null, pixelShift:null, preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:230, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z50': {
    name:'Z50', series:'Z (APS-C)', year:2019, discontinued:true,
    tagline:'First DX Z Body',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-50.html',
    imageUrl:null, asin:null,
    prices:{USD:860,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 6',
    width:126.5, height:93.5, depth:60.0, weight:450, weatherSealed:false,
    lcdSize:'3.2"', lcdDots:1040, lcdType:'Tilting',
    evfType:'EVF', evfDots:2.36, evfMag:1.02,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:320, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'z30': {
    name:'Z30', series:'Z (APS-C)', year:2022, discontinued:false,
    tagline:'Vlogging DX, No Viewfinder',
    productUrl:'https://www.nikonusa.com/p/z-30/1737/overview',
    imageUrl:null, asin:'B0B527JD1C',
    prices:{USD:810,AUD:1099,EUR:799,GBP:649,JPY:117000,CAD:949,SGD:999},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 6',
    width:128.0, height:73.5, depth:60.0, weight:405, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Vari-angle',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:330, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Z Retro ── */
  'zf': {
    name:'Zf', series:'Z (Retro)', year:2023, discontinued:false,
    tagline:'Retro Full-Frame, Modern Guts',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-f.html',
    imageUrl:null, asin:'B0CJDHSFTN',
    prices:{USD:2200,AUD:3199,EUR:2299,GBP:1899,JPY:330000,CAD:2749,SGD:2849},
    sensorMP:24.5, sensorType:'Full-frame BSI CMOS', processor:'EXPEED 7',
    width:144.0, height:103.0, depth:49.0, weight:710, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:3.69, evfMag:0.80,
    faceDetection:true, subjectDetection:'9 types (People / Animals / Birds / Vehicles / Aircraft)',
    ibis:true, ibisStops:8.0, maxBurst:14,
    maxVideoRes:'4K / 60P (DX crop)',
    logVideo:true,
    expeed:'EXPEED 7', nRaw:null, pixelShift:'96MP', preCapture:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× SD UHS-II + 1× microSD UHS-I', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'zfc': {
    name:'Zfc', series:'Z (Retro)', year:2021, discontinued:false,
    tagline:'Retro DX Crowd-Pleaser',
    productUrl:'https://www.nikonusa.com/en/nikon-products/product/mirrorless-cameras/z-fc.html',
    imageUrl:null, asin:'B09883MWLL',
    prices:{USD:1060,AUD:1499,EUR:1099,GBP:899,JPY:158000,CAD:1299,SGD:1349},
    sensorMP:20.9, sensorType:'APS-C (DX) CMOS', processor:'EXPEED 6',
    width:134.5, height:93.5, depth:43.5, weight:445, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Vari-angle',
    evfType:'EVF', evfDots:2.36, evfMag:1.02,
    faceDetection:true, subjectDetection:'Eye / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    expeed:'EXPEED 6', nRaw:null, pixelShift:null, preCapture:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:300, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

};

const CAMERA_ORDER = [
  'z9', 'z8', 'z6-iii', 'z5-ii',
  'z7-ii', 'z7', 'z6-ii', 'z6', 'z5',
  'zr',
  'zf', 'zfc',
  'z50-ii', 'z50', 'z30',
];

const DROPDOWN_GROUPS = [
  { label: '── Z Full-Frame ──', ids: ['z9', 'z8', 'z6-iii', 'z5-ii', 'z7-ii', 'z7', 'z6-ii', 'z6', 'z5'] },
  { label: '── Z Cinema ──',     ids: ['zr'] },
  { label: '── Z Retro ──',      ids: ['zf', 'zfc'] },
  { label: '── Z APS-C (DX) ──', ids: ['z50-ii', 'z50', 'z30'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE — NIKKOR Z mount (Nikon first-party only).
// Specs verified against Nikon official pages + Wikipedia/DPReview.
// `priceIncomplete: true` ships an item with USD (+ any confirmed regional)
// while regional RRP backfill is pending (see check-prices-and-buy-links).
// ─────────────────────────────────────────────
const LENSES = {

  /* ── S-Line Primes ── */
  'z-50mm-f1-8-s': {
    name:'NIKKOR Z 50mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B07GQ6FR5F',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.8, minAperture:16, weight:415, length:86.5, diameter:76.0,
    filterThread:62, minFocusDist:40, maxMagnification:0.15,
    elements:12, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Nikon_NIKKOR_Z_50mm_f_1.8_S_%2849288626406%29.jpg/1280px-Nikon_NIKKOR_Z_50mm_f_1.8_S_%2849288626406%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_50mm_f_1.8_S_(49288626406).jpg"},
    prices:{USD:597,AUD:899,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-50mm-f18-s/20083/overview',
  },

  'z-20mm-f1-8-s': {
    name:'NIKKOR Z 20mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B084QPDT1H',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:1.8, minAperture:16, weight:505, length:108.5, diameter:84.5,
    filterThread:77, minFocusDist:20, maxMagnification:0.19,
    elements:14, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Nikon_NIKKOR_Z_20mm_f_1.8_S_%2852044601591%29.jpg/1280px-Nikon_NIKKOR_Z_20mm_f_1.8_S_%2852044601591%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_20mm_f_1.8_S_(52044601591).jpg"},
    prices:{USD:1047,AUD:1599,EUR:null,GBP:null,JPY:null,CAD:1399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-20mm-f18-s/20093/overview',
  },

  'z-24mm-f1-8-s': {
    name:'NIKKOR Z 24mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B07W86M8FG',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.8, minAperture:16, weight:450, length:96.5, diameter:78.0,
    filterThread:72, minFocusDist:25, maxMagnification:0.15,
    elements:12, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1499,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-24mm-f18-s/20080/overview',
  },

  'z-35mm-f1-8-s': {
    name:'NIKKOR Z 35mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B07GPVJ6HG',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.8, minAperture:16, weight:370, length:86.0, diameter:73.0,
    filterThread:62, minFocusDist:25, maxMagnification:0.19,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:847,AUD:1299,EUR:null,GBP:null,JPY:null,CAD:1149,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-35mm-f18-s/20081/overview',
  },

  'z-85mm-f1-8-s': {
    name:'NIKKOR Z 85mm f/1.8 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B07VQWGNHR',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.8, minAperture:16, weight:470, length:99.0, diameter:75.0,
    filterThread:67, minFocusDist:80, maxMagnification:0.12,
    elements:12, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Nikon_NIKKOR_Z_85mm_f_1.8_S_%2848706710723%29.jpg/1280px-Nikon_NIKKOR_Z_85mm_f_1.8_S_%2848706710723%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_85mm_f_1.8_S_(48706710723).jpg"},
    prices:{USD:797,AUD:1199,EUR:null,GBP:null,JPY:null,CAD:1099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-85mm-f18-s/20090/overview',
  },

  'z-35mm-f1-2-s': {
    name:'NIKKOR Z 35mm f/1.2 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B0DVZRWJSG',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.2, minAperture:16, weight:1060, length:150.0, diameter:90.0,
    filterThread:82, minFocusDist:30, maxMagnification:0.17,
    elements:17, groups:15, blades:11, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2025, discontinued:false,
    imageUrl:null,
    prices:{USD:2797,AUD:4299,EUR:null,GBP:null,JPY:null,CAD:3799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-35mm-f12-s/20124/overview',
  },

  'z-50mm-f1-2-s': {
    name:'NIKKOR Z 50mm f/1.2 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B08J7FDF6G',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.2, minAperture:16, weight:1090, length:150.0, diameter:89.5,
    filterThread:82, minFocusDist:45, maxMagnification:0.15,
    elements:17, groups:15, blades:9, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Nikon_NIKKOR_Z_50mm_f_1.2_S_%2851602295538%29.jpg/1280px-Nikon_NIKKOR_Z_50mm_f_1.2_S_%2851602295538%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_50mm_f_1.2_S_(51602295538).jpg"},
    prices:{USD:2097,AUD:3199,EUR:null,GBP:null,JPY:null,CAD:2849,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-50mm-f12-s/20095/overview',
  },

  'z-85mm-f1-2-s': {
    name:'NIKKOR Z 85mm f/1.2 S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B0BTZZTTRH',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.2, minAperture:16, weight:1160, length:141.5, diameter:102.5,
    filterThread:82, minFocusDist:85, maxMagnification:0.11,
    elements:15, groups:10, blades:11, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Nikon_Nikkor_Z_85mm_f_1.2_S_by_Henry_S%C3%B6derlund.jpg/1280px-Nikon_Nikkor_Z_85mm_f_1.2_S_by_Henry_S%C3%B6derlund.jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Nikkor_Z_85mm_f_1.2_S_by_Henry_S%C3%B6derlund.jpg"},
    prices:{USD:2797,AUD:4299,EUR:null,GBP:null,JPY:null,CAD:3799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-85mm-f12-s/20114/overview',
  },

  'z-135mm-f1-8-s-plena': {
    name:'NIKKOR Z 135mm f/1.8 S Plena', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B0CJWJ2PMY',
    focalLength:135, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'135mm',
    maxAperture:1.8, minAperture:16, weight:995, length:139.5, diameter:98.0,
    filterThread:82, minFocusDist:82, maxMagnification:0.19,
    elements:16, groups:14, blades:11, afType:'Multi-Focus Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:2497,AUD:3799,EUR:null,GBP:null,JPY:null,CAD:3399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-135mm-f18-s-plena/20123/overview',
  },

  'z-mc-105mm-f2-8-vr-s': {
    name:'NIKKOR Z MC 105mm f/2.8 VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B096DHS1BF',
    focalLength:105, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'105mm',
    maxAperture:2.8, minAperture:32, weight:630, length:140.0, diameter:85.0,
    filterThread:62, minFocusDist:29, maxMagnification:1.0,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Nikon_NIKKOR_Z_MC_105mm_f_2.8_VR_S_%2852012537302%29.jpg/1280px-Nikon_NIKKOR_Z_MC_105mm_f_2.8_VR_S_%2852012537302%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_MC_105mm_f_2.8_VR_S_(52012537302).jpg"},
    prices:{USD:997,AUD:1499,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-mc-105mm-f28-vr-s/20100/overview',
  },

  'z-58mm-f0-95-s-noct': {
    name:'NIKKOR Z 58mm f/0.95 S Noct', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B07YXBWK3W',
    focalLength:58, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'58mm',
    maxAperture:0.95, minAperture:16, weight:2000, length:153.0, diameter:102.0,
    filterThread:82, minFocusDist:50, maxMagnification:0.19,
    elements:17, groups:10, blades:11, afType:'Manual Focus',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:7997,AUD:11999,EUR:null,GBP:null,JPY:null,CAD:10999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-58mm-f095-s-noct/20086/overview',
  },

  /* ── S-Line Zooms ── */
  'z-24-70mm-f2-8-s': {
    name:'NIKKOR Z 24-70mm f/2.8 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:'B07NLQ46M2',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:805, length:126.0, diameter:89.0,
    filterThread:82, minFocusDist:38, maxMagnification:0.22,
    elements:17, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Nikon_Z7ii_%2B_nikkor_z_24-70mm_f2.8_s.jpg/1280px-Nikon_Z7ii_%2B_nikkor_z_24-70mm_f2.8_s.jpg',
    imageCredit:{author:"Wilfredor", licence:"CC0", licenceUrl:"http://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z7ii_+_nikkor_z_24-70mm_f2.8_s.jpg"},
    prices:{USD:2297,AUD:3499,EUR:null,GBP:null,JPY:null,CAD:3099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-24-70mm-f28-s/20089/overview',
  },

  'z-70-200mm-f2-8-vr-s': {
    name:'NIKKOR Z 70-200mm f/2.8 VR S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:'B083K3C5P2',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1440, length:220.0, diameter:89.0,
    filterThread:77, minFocusDist:50, maxMagnification:0.20,
    elements:21, groups:18, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Nikon_NIKKOR_Z_70-200mm_f_2.8_VR_S_%2850342502711%29.jpg/1280px-Nikon_NIKKOR_Z_70-200mm_f_2.8_VR_S_%2850342502711%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_70-200mm_f_2.8_VR_S_(50342502711).jpg"},
    prices:{USD:2597,AUD:3999,EUR:null,GBP:null,JPY:null,CAD:3499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-70-200mm-f28-vr-s/20091/overview',
  },

  /* ── Standard Primes (non-S, FX) ── */
  'z-26mm-f2-8': {
    name:'NIKKOR Z 26mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B0BV11Z35L',
    focalLength:26, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'26mm',
    maxAperture:2.8, minAperture:16, weight:125, length:23.5, diameter:70.0,
    filterThread:52, minFocusDist:20, maxMagnification:0.19,
    elements:8, groups:6, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:749,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-26mm-f28/20116/overview',
  },

  'z-28mm-f2-8': {
    name:'NIKKOR Z 28mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B09M62RJK2',
    focalLength:28, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'28mm',
    maxAperture:2.8, minAperture:16, weight:155, length:43.0, diameter:70.0,
    filterThread:52, minFocusDist:19, maxMagnification:0.20,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Nikon_NIKKOR_Z_28mm_f_2.8_%2851770949640%29.jpg/1280px-Nikon_NIKKOR_Z_28mm_f_2.8_%2851770949640%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_28mm_f_2.8_(51770949640).jpg"},
    prices:{USD:297,AUD:449,EUR:null,GBP:null,JPY:null,CAD:399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-28mm-f28/20101/overview',
  },

  'z-28mm-f2-8-se': {
    name:'NIKKOR Z 28mm f/2.8 (SE)', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B0982T5T68',
    focalLength:28, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'28mm',
    maxAperture:2.8, minAperture:16, weight:160, length:43.0, diameter:71.5,
    filterThread:52, minFocusDist:19, maxMagnification:0.20,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Nikon_Z_fc_with_Nikkor_Z_28mm_F2.8_SE_-_by_Henry_S%C3%B6derlund_%2851675302954%29.jpg/1280px-Nikon_Z_fc_with_Nikkor_Z_28mm_F2.8_SE_-_by_Henry_S%C3%B6derlund_%2851675302954%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z_fc_with_Nikkor_Z_28mm_F2.8_SE_-_by_Henry_S%C3%B6derlund_(51675302954).jpg"},
    prices:{USD:297,AUD:449,EUR:null,GBP:null,JPY:null,CAD:399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-28mm-f28-se/20110/overview',
  },

  'z-35mm-f1-4': {
    name:'NIKKOR Z 35mm f/1.4', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B0D83PR5SQ',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:415, length:86.5, diameter:74.5,
    filterThread:62, minFocusDist:27, maxMagnification:0.18,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Nikon_NIKKOR_Z_35mm_f_1.4_%2853868344792%29.jpg/1280px-Nikon_NIKKOR_Z_35mm_f_1.4_%2853868344792%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_35mm_f_1.4_(53868344792).jpg"},
    prices:{USD:597,AUD:899,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-35mm-f14/20126/overview',
  },

  'z-40mm-f2': {
    name:'NIKKOR Z 40mm f/2', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B09G57BXZ4',
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.0, minAperture:16, weight:170, length:45.5, diameter:70.0,
    filterThread:52, minFocusDist:29, maxMagnification:0.17,
    elements:6, groups:4, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Nikon_Nikkor_Z_40mm_F2_%2851607832457%29.jpg/1280px-Nikon_Nikkor_Z_40mm_F2_%2851607832457%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Nikkor_Z_40mm_F2_(51607832457).jpg"},
    prices:{USD:297,AUD:449,EUR:null,GBP:null,JPY:null,CAD:399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-40mm-f2/20102/overview',
  },

  'z-40mm-f2-se': {
    name:'NIKKOR Z 40mm f/2 (SE)', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B0BLTDSVM2',
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.0, minAperture:16, weight:170, length:45.5, diameter:71.5,
    filterThread:52, minFocusDist:29, maxMagnification:0.17,
    elements:6, groups:4, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:307,AUD:469,EUR:null,GBP:null,JPY:null,CAD:419,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-40mm-f2-se/20121/overview',
  },

  'z-50mm-f1-4': {
    name:'NIKKOR Z 50mm f/1.4', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B0DGHTDNY7',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:420, length:86.5, diameter:74.5,
    filterThread:62, minFocusDist:37, maxMagnification:0.18,
    elements:10, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:749,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-50mm-f14/20128/overview',
  },

  'z-50mm-f2-8-mc': {
    name:'NIKKOR Z MC 50mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Prime', asin:'B096DVRX22',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.8, minAperture:22, weight:260, length:66.0, diameter:74.5,
    filterThread:46, minFocusDist:16, maxMagnification:1.0,
    elements:10, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Nikon_NIKKOR_Z_MC_50mm_f_2.8_%2851378200761%29.jpg/1280px-Nikon_NIKKOR_Z_MC_50mm_f_2.8_%2851378200761%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_MC_50mm_f_2.8_(51378200761).jpg"},
    prices:{USD:647,AUD:999,EUR:null,GBP:null,JPY:null,CAD:879,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-mc-50mm-f28/20103/overview',
  },

  /* ── DX Primes ── */
  'z-dx-24mm-f1-7': {
    name:'NIKKOR Z DX 24mm f/1.7', manufacturer:'Nikon', line:'DX', type:'Prime', asin:'B0C6P4CTTT',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'36mm',
    maxAperture:1.7, minAperture:16, weight:135, length:40.0, diameter:70.0,
    filterThread:46, minFocusDist:18, maxMagnification:0.20,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:277,AUD:429,EUR:null,GBP:null,JPY:null,CAD:379,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-dx-24mm-f17/20119/overview',
  },

  /* ── S-Line Zooms (cont.) ── */
  'z-14-24mm-f2-8-s': {
    name:'NIKKOR Z 14-24mm f/2.8 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:'B08J7FHHWX',
    focalLength:null, focalLengthMin:14, focalLengthMax:24, focalLengthEquiv:'14-24mm',
    maxAperture:2.8, minAperture:22, weight:650, length:124.5, diameter:88.5,
    filterThread:112, minFocusDist:28, maxMagnification:0.13,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:2399,AUD:3699,EUR:null,GBP:null,JPY:null,CAD:3299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-14-24mm-f28-s/20097/overview',
  },

  'z-14-30mm-f4-s': {
    name:'NIKKOR Z 14-30mm f/4 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:'B07MS6299X',
    focalLength:null, focalLengthMin:14, focalLengthMax:30, focalLengthEquiv:'14-30mm',
    maxAperture:4.0, minAperture:22, weight:485, length:85.0, diameter:89.0,
    filterThread:82, minFocusDist:28, maxMagnification:0.16,
    elements:14, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-14-30mm-f4-s/20070/overview',
  },

  'z-24-70mm-f4-s': {
    name:'NIKKOR Z 24-70mm f/4 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:'B07GPX4HK5',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:4.0, minAperture:22, weight:500, length:88.5, diameter:77.5,
    filterThread:72, minFocusDist:30, maxMagnification:0.30,
    elements:14, groups:11, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Nikon_Z_6_with_Nikkor_Z_24-70mm_f-4_S_%28DSCF8451%29.jpg/1280px-Nikon_Z_6_with_Nikkor_Z_24-70mm_f-4_S_%28DSCF8451%29.jpg',
    imageCredit:{author:"Trougnouf (Benoit Brummer)", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z_6_with_Nikkor_Z_24-70mm_f-4_S_(DSCF8451).jpg"},
    prices:{USD:997,AUD:1499,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-24-70mm-f4-s/20072/overview',
  },

  'z-24-120mm-f4-s': {
    name:'NIKKOR Z 24-120mm f/4 S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:'B09KHB76TP',
    focalLength:null, focalLengthMin:24, focalLengthMax:120, focalLengthEquiv:'24-120mm',
    maxAperture:4.0, minAperture:22, weight:630, length:118.0, diameter:84.0,
    filterThread:77, minFocusDist:35, maxMagnification:0.39,
    elements:16, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Nikon_NIKKOR_Z_24-120mm_f_4_S_%2851793292337%29.jpg/1280px-Nikon_NIKKOR_Z_24-120mm_f_4_S_%2851793292337%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_24-120mm_f_4_S_(51793292337).jpg"},
    prices:{USD:1097,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-24-120mm-f4-s/20105/overview',
  },

  'z-100-400mm-f4-5-5-6-vr-s': {
    name:'NIKKOR Z 100-400mm f/4.5-5.6 VR S', manufacturer:'Nikon', line:'S-Line', type:'Zoom', asin:'B09KH9X5DL',
    focalLength:null, focalLengthMin:100, focalLengthMax:400, focalLengthEquiv:'100-400mm',
    maxAperture:4.5, minAperture:32, weight:1435, length:222.0, diameter:98.0,
    filterThread:77, minFocusDist:75, maxMagnification:0.38,
    elements:25, groups:20, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Nikon_Nikkor_Z_100-400mm_F4.5-5.6_VR_S_-_by_Henry_S%C3%B6derlund_%2852457041193%29.jpg/1280px-Nikon_Nikkor_Z_100-400mm_F4.5-5.6_VR_S_-_by_Henry_S%C3%B6derlund_%2852457041193%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Nikkor_Z_100-400mm_F4.5-5.6_VR_S_-_by_Henry_S%C3%B6derlund_(52457041193).jpg"},
    prices:{USD:2697,AUD:4199,EUR:null,GBP:null,JPY:null,CAD:3699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-100-400mm-f45-56-vr-s/20106/overview',
  },

  /* ── Standard / Travel Zooms (non-S, FX) ── */
  'z-17-28mm-f2-8': {
    name:'NIKKOR Z 17-28mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:'B0BFTX4DS7',
    focalLength:null, focalLengthMin:17, focalLengthMax:28, focalLengthEquiv:'17-28mm',
    maxAperture:2.8, minAperture:22, weight:450, length:101.0, diameter:75.0,
    filterThread:67, minFocusDist:19, maxMagnification:0.19,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Nikon_NIKKOR_Z_17-28mm_f_2.8_%2852474327801%29.jpg/1280px-Nikon_NIKKOR_Z_17-28mm_f_2.8_%2852474327801%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_17-28mm_f_2.8_(52474327801).jpg"},
    prices:{USD:1197,AUD:1849,EUR:null,GBP:null,JPY:null,CAD:1649,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-17-28mm-f28/20115/overview',
  },

  'z-24-50mm-f4-6-3': {
    name:'NIKKOR Z 24-50mm f/4-6.3', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:'B08D8QK5LP',
    focalLength:null, focalLengthMin:24, focalLengthMax:50, focalLengthEquiv:'24-50mm',
    maxAperture:4.0, minAperture:22, weight:195, length:51.0, diameter:73.5,
    filterThread:52, minFocusDist:35, maxMagnification:0.17,
    elements:11, groups:10, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Nikon_Z_5_with_Nikkor_Z_24-50mm_F4-6.3_-_by_Henry_S%C3%B6derlund_%2850328069222%29.jpg/1280px-Nikon_Z_5_with_Nikkor_Z_24-50mm_F4-6.3_-_by_Henry_S%C3%B6derlund_%2850328069222%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z_5_with_Nikkor_Z_24-50mm_F4-6.3_-_by_Henry_S%C3%B6derlund_(50328069222).jpg"},
    prices:{USD:397,AUD:599,EUR:null,GBP:null,JPY:null,CAD:529,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-24-50mm-f4-63/20096/overview',
  },

  'z-24-200mm-f4-6-3-vr': {
    name:'NIKKOR Z 24-200mm f/4-6.3 VR', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:'B084QP747Q',
    focalLength:null, focalLengthMin:24, focalLengthMax:200, focalLengthEquiv:'24-200mm',
    maxAperture:4.0, minAperture:22, weight:570, length:114.0, diameter:76.5,
    filterThread:67, minFocusDist:50, maxMagnification:0.28,
    elements:19, groups:15, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2020, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Nikon_Z_7II_with_Nikkor_Z_24-200mm_f_4-6.3_VR_01_-_by_ato.jpg/1280px-Nikon_Z_7II_with_Nikkor_Z_24-200mm_f_4-6.3_VR_01_-_by_ato.jpg',
    imageCredit:{author:"Ato 01", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Z_7II_with_Nikkor_Z_24-200mm_f_4-6.3_VR_01_-_by_ato.jpg"},
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1229,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-24-200mm-f4-63-vr/20092/overview',
  },

  'z-28-75mm-f2-8': {
    name:'NIKKOR Z 28-75mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:'B09NLBL2F1',
    focalLength:null, focalLengthMin:28, focalLengthMax:75, focalLengthEquiv:'28-75mm',
    maxAperture:2.8, minAperture:22, weight:565, length:120.5, diameter:75.0,
    filterThread:67, minFocusDist:19, maxMagnification:0.34,
    elements:15, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nikon_NIKKOR_Z_28-75mm_f_2.8_%2851832796897%29.jpg/1280px-Nikon_NIKKOR_Z_28-75mm_f_2.8_%2851832796897%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_28-75mm_f_2.8_(51832796897).jpg"},
    prices:{USD:1197,AUD:1849,EUR:null,GBP:null,JPY:null,CAD:1649,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-28-75mm-f28/20107/overview',
  },

  'z-28-400mm-f4-8-vr': {
    name:'NIKKOR Z 28-400mm f/4-8 VR', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:'B0CZ4JX9JW',
    focalLength:null, focalLengthMin:28, focalLengthMax:400, focalLengthEquiv:'28-400mm',
    maxAperture:4.0, minAperture:32, weight:725, length:142.0, diameter:85.0,
    filterThread:77, minFocusDist:20, maxMagnification:0.35,
    elements:21, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2024, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Nikon_NIKKOR_Z_28-400mm_f_4-8_VR_by_Henry_S%C3%B6derlund.jpg/1280px-Nikon_NIKKOR_Z_28-400mm_f_4-8_VR_by_Henry_S%C3%B6derlund.jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_28-400mm_f_4-8_VR_by_Henry_S%C3%B6derlund.jpg"},
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-28-400mm-f4-8-vr/20125/overview',
  },

  /* ── Telephoto / Super-Telephoto ── */
  'z-70-180mm-f2-8': {
    name:'NIKKOR Z 70-180mm f/2.8', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:'B0C8QL89L5',
    focalLength:null, focalLengthMin:70, focalLengthMax:180, focalLengthEquiv:'70-180mm',
    maxAperture:2.8, minAperture:22, weight:795, length:151.0, diameter:83.5,
    filterThread:67, minFocusDist:27, maxMagnification:0.48,
    elements:19, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Nikon_NIKKOR_Z_70-180mm_F2.8_%2853061678724%29.jpg/1280px-Nikon_NIKKOR_Z_70-180mm_F2.8_%2853061678724%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_NIKKOR_Z_70-180mm_F2.8_(53061678724).jpg"},
    prices:{USD:1247,AUD:1899,EUR:null,GBP:null,JPY:null,CAD:1699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-70-180mm-f28/20120/overview',
  },

  'z-180-600mm-f5-6-6-3-vr': {
    name:'NIKKOR Z 180-600mm f/5.6-6.3 VR', manufacturer:'Nikon', line:'NIKKOR Z', type:'Zoom', asin:'B0C8QFSPFQ',
    focalLength:null, focalLengthMin:180, focalLengthMax:600, focalLengthEquiv:'180-600mm',
    maxAperture:5.6, minAperture:32, weight:2140, length:315.5, diameter:110.0,
    filterThread:95, minFocusDist:130, maxMagnification:0.25,
    elements:25, groups:17, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:1697,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-180-600mm-f56-63-vr/20117/overview',
  },

  'z-400mm-f4-5-vr-s': {
    name:'NIKKOR Z 400mm f/4.5 VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B0B52C7Z7D',
    focalLength:400, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm',
    maxAperture:4.5, minAperture:32, weight:1245, length:234.5, diameter:104.0,
    filterThread:95, minFocusDist:250, maxMagnification:0.16,
    elements:19, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2022, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Nikon_Nikkor_Z_400mm_F4.5_VR_S_-_by_Henry_S%C3%B6derlund_%2852456525351%29.jpg/1280px-Nikon_Nikkor_Z_400mm_F4.5_VR_S_-_by_Henry_S%C3%B6derlund_%2852456525351%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Nikkor_Z_400mm_F4.5_VR_S_-_by_Henry_S%C3%B6derlund_(52456525351).jpg"},
    prices:{USD:3247,AUD:4999,EUR:null,GBP:null,JPY:null,CAD:4399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-400mm-f45-vr-s/20112/overview',
  },

  'z-400mm-f2-8-tc-vr-s': {
    name:'NIKKOR Z 400mm f/2.8 TC VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B09QP4SSYW',
    focalLength:400, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm (560mm w/ TC)',
    maxAperture:2.8, minAperture:22, weight:2950, length:380.0, diameter:156.0,
    filterThread:46, minFocusDist:250, maxMagnification:0.16,
    elements:25, groups:19, blades:9, afType:'Silky Swift VCM',
    weatherSealed:true, ois:true, oisStops:5.5, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:13997,AUD:21499,EUR:null,GBP:null,JPY:null,CAD:18999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-400mm-f28-tc-vr-s/20111/overview',
  },

  'z-600mm-f6-3-vr-s-pf': {
    name:'NIKKOR Z 600mm f/6.3 VR S (PF)', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B0CKTYF2ZZ',
    focalLength:600, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'600mm',
    maxAperture:6.3, minAperture:32, weight:1470, length:278.0, diameter:106.5,
    filterThread:95, minFocusDist:400, maxMagnification:0.16,
    elements:21, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.5, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:4797,AUD:7399,EUR:null,GBP:null,JPY:null,CAD:6499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-600mm-f63-vr-s/20122/overview',
  },

  'z-600mm-f4-tc-vr-s': {
    name:'NIKKOR Z 600mm f/4 TC VR S', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B0BL5FKJF7',
    focalLength:600, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'600mm (840mm w/ TC)',
    maxAperture:4.0, minAperture:22, weight:3260, length:437.0, diameter:165.0,
    filterThread:46, minFocusDist:440, maxMagnification:0.14,
    elements:26, groups:20, blades:9, afType:'Silky Swift VCM',
    weatherSealed:true, ois:true, oisStops:5.5, year:2022, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Nikon_Nikkor_Z_600mm_F4_TC_VR_S_20260516113641.jpg/1280px-Nikon_Nikkor_Z_600mm_F4_TC_VR_S_20260516113641.jpg',
    imageCredit:{author:"TurnOnTheNight", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Nikon_Nikkor_Z_600mm_F4_TC_VR_S_20260516113641.jpg"},
    prices:{USD:15497,AUD:23999,EUR:null,GBP:null,JPY:null,CAD:20999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-600mm-f4-tc-vr-s/20113/overview',
  },

  'z-800mm-f6-3-vr-s-pf': {
    name:'NIKKOR Z 800mm f/6.3 VR S (PF)', manufacturer:'Nikon', line:'S-Line', type:'Prime', asin:'B09X8TBSFZ',
    focalLength:800, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'800mm',
    maxAperture:6.3, minAperture:32, weight:2385, length:385.0, diameter:140.0,
    filterThread:46, minFocusDist:500, maxMagnification:0.16,
    elements:22, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:5.0, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:6497,AUD:9999,EUR:null,GBP:null,JPY:null,CAD:8799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-800mm-f63-vr-s/20108/overview',
  },

  /* ── DX Zooms ── */
  'z-dx-12-28mm-pz-vr': {
    name:'NIKKOR Z DX 12-28mm f/3.5-5.6 PZ VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:'B0C2RHKLDK',
    focalLength:null, focalLengthMin:12, focalLengthMax:28, focalLengthEquiv:'18-42mm',
    maxAperture:3.5, minAperture:22, weight:205, length:63.5, diameter:72.0,
    filterThread:67, minFocusDist:19, maxMagnification:0.21,
    elements:12, groups:11, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:357,AUD:549,EUR:null,GBP:null,JPY:null,CAD:479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-dx-12-28mm-f35-56-pz-vr/20118/overview',
  },

  'z-dx-16-50mm-vr': {
    name:'NIKKOR Z DX 16-50mm f/3.5-6.3 VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:'B07YX95XJL',
    focalLength:null, focalLengthMin:16, focalLengthMax:50, focalLengthEquiv:'24-75mm',
    maxAperture:3.5, minAperture:22, weight:135, length:32.0, diameter:70.0,
    filterThread:46, minFocusDist:20, maxMagnification:0.20,
    elements:9, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:4.5, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:307,AUD:469,EUR:null,GBP:null,JPY:null,CAD:419,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-dx-16-50mm-f35-63-vr/20084/overview',
  },

  'z-dx-18-140mm-vr': {
    name:'NIKKOR Z DX 18-140mm f/3.5-6.3 VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:'B09JBJKRBZ',
    focalLength:null, focalLengthMin:18, focalLengthMax:140, focalLengthEquiv:'27-210mm',
    maxAperture:3.5, minAperture:22, weight:315, length:90.0, diameter:73.0,
    filterThread:62, minFocusDist:20, maxMagnification:0.33,
    elements:17, groups:13, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:5.0, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:397,AUD:599,EUR:null,GBP:null,JPY:null,CAD:529,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-dx-18-140mm-f35-63-vr/20104/overview',
  },

  'z-dx-50-250mm-vr': {
    name:'NIKKOR Z DX 50-250mm f/4.5-6.3 VR', manufacturer:'Nikon', line:'DX', type:'Zoom', asin:'B07YX9KYQZ',
    focalLength:null, focalLengthMin:50, focalLengthMax:250, focalLengthEquiv:'75-375mm',
    maxAperture:4.5, minAperture:22, weight:405, length:110.0, diameter:74.0,
    filterThread:62, minFocusDist:50, maxMagnification:0.23,
    elements:16, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:5.0, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:357,AUD:549,EUR:null,GBP:null,JPY:null,CAD:479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.nikonusa.com/p/nikkor-z-dx-50-250mm-f45-63-vr/20085/overview',
  },

  /* ── Sigma (Z DX, APS-C DC DN) ── */
  /* Nikon Z APS-C crop = 1.5×. Sigma's official Z lineup is only these 3 DC DN
     primes (Nikon licenses no full-frame Sigma). Z-mount weights from Sigma. */
  'sigma-16mm-f14': {
    name:'Sigma 16mm f/1.4 DC DN', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:16, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.4, minAperture:16, weight:420, length:94.3, diameter:72.2,
    filterThread:67, minFocusDist:25, maxMagnification:0.1,
    elements:16, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c017_16_14_product_img01.png',
    asin:null,
    prices:{USD:459,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c017_16_14/',
  },

  'sigma-30mm-f14': {
    name:'Sigma 30mm f/1.4 DC DN', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:30, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'45mm',
    maxAperture:1.4, minAperture:16, weight:285, length:75.3, diameter:70,
    filterThread:52, minFocusDist:30, maxMagnification:0.14,
    elements:9, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c016_30_14_product_img01.png',
    asin:null,
    prices:{USD:339,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c016_30_14/',
  },

  'sigma-56mm-f14': {
    name:'Sigma 56mm f/1.4 DC DN', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:56, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'84mm',
    maxAperture:1.4, minAperture:16, weight:295, length:61.5, diameter:70,
    filterThread:55, minFocusDist:50, maxMagnification:0.14,
    elements:10, groups:6, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c018_56_14_product_img01.png',
    asin:null,
    prices:{USD:479,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c018_56_14/',
  },

  /* ── Viltrox (Z mount AF) — largest third-party line on Z ── */
  /* Optical specs shared with the E-mount versions (verified); Z APS-C = 1.5×. */
  'viltrox-13mm-f14': {
    name:'Viltrox AF 13mm f/1.4', manufacturer:'Viltrox', line:'AF', type:'Prime',
    focalLength:13, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:1.4, minAperture:16, weight:420, length:90, diameter:74,
    filterThread:67, minFocusDist:22, maxMagnification:0.1,
    elements:14, groups:11, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:429,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:null,
  },

  'viltrox-16mm-f18': {
    name:'Viltrox AF 16mm f/1.8', manufacturer:'Viltrox', line:'Pro', type:'Prime',
    focalLength:16, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'16mm',
    maxAperture:1.8, minAperture:22, weight:550, length:101, diameter:85.2,
    filterThread:77, minFocusDist:27, maxMagnification:0.1,
    elements:15, groups:12, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:549,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:null,
  },

  'viltrox-27mm-f12': {
    name:'Viltrox AF 27mm f/1.2 Pro', manufacturer:'Viltrox', line:'Pro', type:'Prime',
    focalLength:27, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'41mm',
    maxAperture:1.2, minAperture:16, weight:560, length:92, diameter:82,
    filterThread:67, minFocusDist:28, maxMagnification:0.15,
    elements:15, groups:11, blades:11, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:549,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:null,
  },

  'viltrox-33mm-f14': {
    name:'Viltrox AF 33mm f/1.4', manufacturer:'Viltrox', line:'AF', type:'Prime',
    focalLength:33, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:270, length:72, diameter:65,
    filterThread:52, minFocusDist:40, maxMagnification:0.1,
    elements:10, groups:9, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:279,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:null,
  },

  'viltrox-56mm-f14': {
    name:'Viltrox AF 56mm f/1.4', manufacturer:'Viltrox', line:'AF', type:'Prime',
    focalLength:56, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'84mm',
    maxAperture:1.4, minAperture:16, weight:320, length:72, diameter:65,
    filterThread:52, minFocusDist:60, maxMagnification:0.1,
    elements:10, groups:9, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:329,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:null,
  },

  'viltrox-85mm-f18-ii': {
    name:'Viltrox AF 85mm f/1.8 II', manufacturer:'Viltrox', line:'AF', type:'Prime',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.8, minAperture:16, weight:371, length:92, diameter:80,
    filterThread:72, minFocusDist:80, maxMagnification:0.12,
    elements:10, groups:7, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:null,
  },

  /* ── Tamron (Z mount Di III) — excludes 17-28/28-75/70-180 (sold as Nikkor Z) ── */
  /* APS-C = 1.5× crop. Weights: 18-300 & 150-500 are Nikon-Z values; the others
     reuse the verified cross-mount weight (mount delta ~10-15g). */
  'tamron-11-20mm-f28': {
    name:'Tamron 11-20mm f/2.8 Di III-A RXD', manufacturer:'Tamron', line:'Di III-A', type:'Zoom',
    focalLength:null, focalLengthMin:11, focalLengthMax:20, focalLengthEquiv:'17-30mm',
    maxAperture:2.8, minAperture:16, weight:335, length:86.2, diameter:73,
    filterThread:67, minFocusDist:15, maxMagnification:0.25,
    elements:12, groups:10, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:659,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://tamron-americas.com/product/11-20mm-f-2-8-di-iii-a-rxd/',
  },

  'tamron-17-70mm-f28': {
    name:'Tamron 17-70mm f/2.8 Di III-A VC RXD', manufacturer:'Tamron', line:'Di III-A', type:'Zoom',
    focalLength:null, focalLengthMin:17, focalLengthMax:70, focalLengthEquiv:'26-105mm',
    maxAperture:2.8, minAperture:22, weight:525, length:119.3, diameter:74.6,
    filterThread:67, minFocusDist:19, maxMagnification:0.21,
    elements:16, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://tamron-americas.com/product/17-70mm-f-2-8-di-iii-a-vc-rxd/',
  },

  'tamron-18-300mm-f35-63': {
    name:'Tamron 18-300mm f/3.5-6.3 Di III-A VC VXD', manufacturer:'Tamron', line:'Di III-A', type:'Zoom',
    focalLength:null, focalLengthMin:18, focalLengthMax:300, focalLengthEquiv:'27-450mm',
    maxAperture:3.5, minAperture:22, weight:635, length:127.6, diameter:75.5,
    filterThread:67, minFocusDist:15, maxMagnification:0.5,
    elements:19, groups:15, blades:7, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://tamron-americas.com/product/18-300mm-f-3-5-6-3-di-iii-a-vc-vxd/',
  },

  'tamron-35-150mm-f2-28': {
    name:'Tamron 35-150mm f/2-2.8 Di III VXD', manufacturer:'Tamron', line:'Di III', type:'Zoom',
    focalLength:null, focalLengthMin:35, focalLengthMax:150, focalLengthEquiv:'35-150mm',
    maxAperture:2.0, minAperture:22, weight:1165, length:158, diameter:89.2,
    filterThread:82, minFocusDist:33, maxMagnification:0.18,
    elements:21, groups:15, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:1799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://tamron-americas.com/product/35-150mm-f-2-2-8-di-iii-vxd/',
  },

  'tamron-50-400mm-f45-63': {
    name:'Tamron 50-400mm f/4.5-6.3 Di III VC VXD', manufacturer:'Tamron', line:'Di III', type:'Zoom',
    focalLength:null, focalLengthMin:50, focalLengthMax:400, focalLengthEquiv:'50-400mm',
    maxAperture:4.5, minAperture:22, weight:1155, length:183.4, diameter:88.5,
    filterThread:67, minFocusDist:25, maxMagnification:0.5,
    elements:24, groups:18, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:1399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://tamron-americas.com/product/50-400mm-f-4-5-6-3-di-iii-vc-vxd/',
  },

  'tamron-70-300mm-f45-63': {
    name:'Tamron 70-300mm f/4.5-6.3 Di III RXD', manufacturer:'Tamron', line:'Di III', type:'Zoom',
    focalLength:null, focalLengthMin:70, focalLengthMax:300, focalLengthEquiv:'70-300mm',
    maxAperture:4.5, minAperture:22, weight:545, length:148, diameter:77,
    filterThread:67, minFocusDist:80, maxMagnification:0.11,
    elements:15, groups:10, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tamron_70-300mm_F_4.5-6.3_Di_III_RXD_%28Model_A047Z%29_Nikon_Z_%2852393501355%29.jpg/1280px-Tamron_70-300mm_F_4.5-6.3_Di_III_RXD_%28Model_A047Z%29_Nikon_Z_%2852393501355%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Tamron_70-300mm_F_4.5-6.3_Di_III_RXD_(Model_A047Z)_Nikon_Z_(52393501355).jpg"}, asin:null,
    prices:{USD:549,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://tamron-americas.com/product/70-300mm-f-4-5-6-3-di-iii-rxd/',
  },

  'tamron-150-500mm-f5-67': {
    name:'Tamron 150-500mm f/5-6.7 Di III VC VXD', manufacturer:'Tamron', line:'Di III', type:'Zoom',
    focalLength:null, focalLengthMin:150, focalLengthMax:500, focalLengthEquiv:'150-500mm',
    maxAperture:5.0, minAperture:22, weight:1720, length:212.3, diameter:93,
    filterThread:82, minFocusDist:60, maxMagnification:0.32,
    elements:25, groups:16, blades:7, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Tamron_150-500mm_F5-6.7_Di_III_VC_VXD_%28Model_A057Z%29_%2853272622666%29.jpg/1280px-Tamron_150-500mm_F5-6.7_Di_III_VC_VXD_%28Model_A057Z%29_%2853272622666%29.jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Tamron_150-500mm_F5-6.7_Di_III_VC_VXD_(Model_A057Z)_(53272622666).jpg"}, asin:null,
    prices:{USD:1399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://tamron-americas.com/product/150-500mm-f-5-6-7-di-iii-vc-vxd/',
  },

  /* ── Laowa (Z mount manual-focus specialty) ── */
  'laowa-90mm-f28-macro': {
    name:'Laowa 90mm f/2.8 2x Ultra Macro APO', manufacturer:'Laowa', line:'Ultra Macro APO', type:'Prime',
    focalLength:90, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:2.8, minAperture:22, weight:619, length:120, diameter:74,
    filterThread:67, minFocusDist:20.5, maxMagnification:2.0,
    elements:13, groups:10, blades:13, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.venuslens.net/product/laowa-90mm-f-2-8-2x-macro-apo/',
  },

  'laowa-15mm-f2': {
    name:'Laowa 15mm f/2 Zero-D', manufacturer:'Laowa', line:'Zero-D', type:'Prime',
    focalLength:15, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'15mm',
    maxAperture:2.0, minAperture:22, weight:500, length:82, diameter:66,
    filterThread:72, minFocusDist:15, maxMagnification:0.1,
    elements:12, groups:9, blades:5, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:849,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.venuslens.net/product/laowa-15mm-f2/',
  },

  'laowa-10mm-f4-cookie': {
    name:'Laowa 10mm f/4 Cookie', manufacturer:'Laowa', line:'Cookie', type:'Prime',
    focalLength:10, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'15mm',
    maxAperture:4.0, minAperture:22, weight:130, length:25, diameter:54,
    filterThread:37, minFocusDist:10, maxMagnification:0.1,
    elements:12, groups:8, blades:5, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:299,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.venuslens.net/product/laowa-10mm-f-4-cookie/',
  },

  /* ── Viltrox full-frame Z primes ── */
  'viltrox-24mm-f18': {
    name:'Viltrox AF 24mm f/1.8', manufacturer:'Viltrox', line:'AF', type:'Prime',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.8, minAperture:16, weight:370, length:92, diameter:65,
    filterThread:55, minFocusDist:30, maxMagnification:0.1,
    elements:11, groups:9, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:'B09CPDBWJY',
    prices:{USD:380,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://viltrox.com/products/viltrox-af-24mm-f18-z-mount-full-frame-prime-lens',
  },

  'viltrox-35mm-f18-evo': {
    name:'Viltrox AF 35mm f/1.8 EVO', manufacturer:'Viltrox', line:'EVO', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.8, minAperture:16, weight:375, length:78, diameter:69,
    filterThread:58, minFocusDist:34, maxMagnification:0.1,
    elements:13, groups:10, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:395,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://viltrox.com/products/af-35mm-f1-8-z',
  },

  'viltrox-40mm-f25-air': {
    name:'Viltrox AF 40mm f/2.5 Air', manufacturer:'Viltrox', line:'Air', type:'Prime',
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.5, minAperture:16, weight:180, length:55.9, diameter:68,
    filterThread:52, minFocusDist:34, maxMagnification:0.1,
    elements:10, groups:6, blades:7, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:158,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://viltrox.com/products/viltrox-af-40mm-f2-5-z',
  },

  /* ── Voigtländer (native Z manual-focus) ── */
  'voigtlander-apo-lanthar-50mm-f2': {
    name:'Voigtländer APO-Lanthar 50mm f/2 Z', manufacturer:'Voigtländer', line:'APO-Lanthar', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.0, minAperture:16, weight:370, length:64.3, diameter:63,
    filterThread:58, minFocusDist:45, maxMagnification:0.15,
    elements:10, groups:8, blades:12, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:'B09Z2NNDY4',
    prices:{USD:1049,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.voigtlaender.de/z-mount/50-mm-12-0-apo-lanthar/?lang=en',
  },

  'voigtlander-nokton-40mm-f12': {
    name:'Voigtländer Nokton 40mm f/1.2 Z', manufacturer:'Voigtländer', line:'Nokton', type:'Prime',
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:1.2, minAperture:22, weight:315, length:53.9, diameter:67.6,
    filterThread:58, minFocusDist:35, maxMagnification:0.1,
    elements:8, groups:6, blades:10, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:'B0BMWKQ1WP',
    prices:{USD:899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.voigtlaender.de/z-mount/40-mm-11-2-nokton/?lang=en',
  },

  /* ── Other (Yongnuo AF + budget makers) ── */
  'yongnuo-35mm-f2': {
    name:'Yongnuo YN35mm f/2Z DF DSM', manufacturer:'Yongnuo', line:'DF DSM', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:2.0, minAperture:16, weight:290, length:73, diameter:68,
    filterThread:52, minFocusDist:35, maxMagnification:0.13,
    elements:9, groups:8, blades:7, afType:'Stepping Motor (DSM)',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:250,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://yongnuo.eu/lenses/nikon-z-f/yn35mm-f2z-df-dsm/',
  },

  'yongnuo-50mm-f18': {
    name:'Yongnuo YN50mm f/1.8Z DF DSM', manufacturer:'Yongnuo', line:'DF DSM', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.8, minAperture:16, weight:417, length:87, diameter:68,
    filterThread:58, minFocusDist:45, maxMagnification:0.14,
    elements:11, groups:8, blades:9, afType:'Stepping Motor (DSM)',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:130,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://th.hkyongnuo.com/products/yn50mm-f18z-df-dsm',
  },

  'ttartisan-27mm-f28': {
    name:'TTArtisan AF 27mm f/2.8', manufacturer:'TTArtisan', line:'AF', type:'Prime',
    focalLength:27, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'41mm',
    maxAperture:2.8, minAperture:16, weight:93, length:41, diameter:64,
    filterThread:39, minFocusDist:35, maxMagnification:0.1,
    elements:6, groups:5, blades:7, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:149,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://ttartisan.store/products/af27',
  },

  '7artisans-27mm-f28': {
    name:'7Artisans AF 27mm f/2.8', manufacturer:'7Artisans', line:'AF', type:'Prime',
    focalLength:27, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'41mm',
    maxAperture:2.8, minAperture:16, weight:172, length:48, diameter:64,
    filterThread:52, minFocusDist:30, maxMagnification:0.1,
    elements:6, groups:5, blades:6, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:129,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://7artisans.store/products/27mm-f2-8-af-aps-c-lens-for-e',
  },

  'meike-85mm-f18': {
    name:'Meike 85mm f/1.8 Full Frame AF', manufacturer:'Meike', line:'AF', type:'Prime',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.8, minAperture:22, weight:386, length:92, diameter:80,
    filterThread:67, minFocusDist:85, maxMagnification:0.12,
    elements:null, groups:null, blades:9, afType:'STM',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:219,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://meikeglobal.com/products/85mm-f1-8z',
  },

};

const LENS_DROPDOWN_GROUPS = [
  { label: '── S-Line Primes ──', ids: ['z-20mm-f1-8-s', 'z-24mm-f1-8-s', 'z-35mm-f1-8-s', 'z-50mm-f1-8-s', 'z-85mm-f1-8-s', 'z-35mm-f1-2-s', 'z-50mm-f1-2-s', 'z-85mm-f1-2-s', 'z-135mm-f1-8-s-plena', 'z-mc-105mm-f2-8-vr-s', 'z-58mm-f0-95-s-noct'] },
  { label: '── Standard Primes ──', ids: ['z-26mm-f2-8', 'z-28mm-f2-8', 'z-28mm-f2-8-se', 'z-35mm-f1-4', 'z-40mm-f2', 'z-40mm-f2-se', 'z-50mm-f1-4', 'z-50mm-f2-8-mc'] },
  { label: '── S-Line Zooms ──',  ids: ['z-14-24mm-f2-8-s', 'z-24-70mm-f2-8-s', 'z-24-70mm-f4-s', 'z-14-30mm-f4-s', 'z-24-120mm-f4-s', 'z-70-200mm-f2-8-vr-s', 'z-100-400mm-f4-5-5-6-vr-s'] },
  { label: '── Standard / Travel Zooms ──', ids: ['z-17-28mm-f2-8', 'z-24-50mm-f4-6-3', 'z-28-75mm-f2-8', 'z-24-200mm-f4-6-3-vr', 'z-28-400mm-f4-8-vr'] },
  { label: '── Telephoto / Super-Telephoto ──', ids: ['z-70-180mm-f2-8', 'z-180-600mm-f5-6-6-3-vr', 'z-400mm-f4-5-vr-s', 'z-400mm-f2-8-tc-vr-s', 'z-600mm-f6-3-vr-s-pf', 'z-600mm-f4-tc-vr-s', 'z-800mm-f6-3-vr-s-pf'] },
  { label: '── DX Lenses ──',     ids: ['z-dx-24mm-f1-7', 'z-dx-12-28mm-pz-vr', 'z-dx-16-50mm-vr', 'z-dx-18-140mm-vr', 'z-dx-50-250mm-vr'] },
  { label: '── Sigma ──', ids: ['sigma-16mm-f14', 'sigma-30mm-f14', 'sigma-56mm-f14'] },
  { label: '── Viltrox ──', ids: ['viltrox-13mm-f14', 'viltrox-16mm-f18', 'viltrox-27mm-f12', 'viltrox-33mm-f14', 'viltrox-56mm-f14', 'viltrox-85mm-f18-ii', 'viltrox-24mm-f18', 'viltrox-35mm-f18-evo', 'viltrox-40mm-f25-air'] },
  { label: '── Tamron ──', ids: ['tamron-11-20mm-f28', 'tamron-17-70mm-f28', 'tamron-18-300mm-f35-63', 'tamron-35-150mm-f2-28', 'tamron-50-400mm-f45-63', 'tamron-70-300mm-f45-63', 'tamron-150-500mm-f5-67'] },
  { label: '── Voigtländer ──', ids: ['voigtlander-apo-lanthar-50mm-f2', 'voigtlander-nokton-40mm-f12'] },
  { label: '── Laowa ──', ids: ['laowa-10mm-f4-cookie', 'laowa-15mm-f2', 'laowa-90mm-f28-macro'] },
  { label: '── Other ──', ids: ['yongnuo-35mm-f2', 'yongnuo-50mm-f18', 'ttartisan-27mm-f28', '7artisans-27mm-f28', 'meike-85mm-f18'] },
];

return { BRAND_CONFIG, SERIES_COLORS, CAMERAS, CAMERA_ORDER,
         DROPDOWN_GROUPS, LENSES, LENS_DROPDOWN_GROUPS, REGISTERED_BRANDS };
})();
