// Registered into the shared brand-data registry so multiple brand files
// can load on one page (see compare/). The data below is unchanged.
window.BRAND_DATA = window.BRAND_DATA || {};
window.BRAND_DATA['olympus'] = (() => {
// ─────────────────────────────────────────────
// OLYMPUS BRAND CONFIG
//
// One brand covering both eras of the same Micro Four Thirds system: Olympus
// (2009–2020) and OM System (2021–present, after the 2021 sale to Japan
// Industrial Partners). The mount, lens line and body lineage are continuous
// across the ownership change — see openspec/changes/add-olympus-brand/design.md §1.
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Olympus',
  slug:        'olympus',
  families:    ['Micro Four Thirds (PEN / OM-D / OM System)', 'Tough (Fixed-Lens Compact)'],
  brandSections: ['olympus'],
  // `mount` is the landing-tile headline label; `mounts` is the machine-readable
  // list every item's `mount` id must come from, and the order the filter chips render in.
  // Single-mount brand — see design.md §2 for why Tough (a genuinely different
  // sensor format) still declares this same 'mft' id rather than a second one.
  mount:       'Micro Four Thirds',
  mounts:      [{ id:'mft', label:'Micro Four Thirds' }],
  heroCamera:  'om-1-ii',
  cameras: {
    heroEyebrow:  'PEN, OM-D & OM System',
    heroTitle:    '<span>Olympus</span> Camera Comparison',
    heroSubtitle: 'Compare Olympus and OM System Micro Four Thirds cameras side-by-side — PEN, OM-D and the current OM System lineup',
    headerTitle:  'Olympus',
    defaultSelected: ['om-1-ii', 'om-3', 'om-5-ii'],
  },
  lenses: {
    heroEyebrow:  'M.ZUIKO Lenses',
    heroTitle:    '<span>Olympus</span> Lens Comparison',
    heroSubtitle: 'Compare Olympus M.Zuiko and third-party Micro Four Thirds lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['omsystem-25mm-f12-pro', 'omsystem-12-40mm-f28-pro', 'omsystem-45mm-f12-pro'],
  },
  footerLinks: [
    { label: 'OM System Cameras', url: 'https://explore.omsystem.com/us/en/cameras' },
    { label: 'M.Zuiko Lenses',    url: 'https://explore.omsystem.com/us/en/m-zuiko-digital-lenses' },
    { label: 'DPReview Olympus',  url: 'https://www.dpreview.com/products/olympus' },
  ],
};

const REGISTERED_BRANDS = [
  { slug: 'fujifilm',  name: 'Fujifilm' },
  { slug: 'canon',     name: 'Canon' },
  { slug: 'sony',      name: 'Sony' },
  { slug: 'nikon',     name: 'Nikon' },
  { slug: 'panasonic', name: 'Panasonic' },
  { slug: 'sigma',     name: 'Sigma' },
  { slug: 'olympus',   name: 'Olympus' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards)
// Nine series — see research/decisions.md §9 for the full rationale. Each
// camera's `series` names its product family as printed on the body (e.g.
// the 2026 PEN gets 'PEN', not 'OM System'), not its corporate era.
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'PEN':          { bg: '#2a2015', text: '#d4a55a' },
  'PEN-F':        { bg: '#1f1a12', text: '#c9a876' },
  'PEN Lite':     { bg: '#241f28', text: '#a88fc0' },
  'PEN Mini':     { bg: '#1c1a20', text: '#8878a0' },
  'OM-D E-M1':    { bg: '#1a1f26', text: '#6fa8d8' },
  'OM-D E-M5':    { bg: '#151f1c', text: '#5cb88a' },
  'OM-D E-M10':   { bg: '#1a2016', text: '#8ac05c' },
  'OM System':    { bg: '#0a1f26', text: '#5fd0c8' },
  'Tough':        { bg: '#1f1810', text: '#e0954a' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE — Olympus / OM System Micro Four Thirds mirrorless +
// Tough fixed-lens compacts. Filled in task-4 batches; see
// openspec/changes/add-olympus-brand/research/cameras.md for the full
// enumeration and openspec/changes/add-olympus-brand/research/decisions.md
// for entry conventions. Olympus-specific fields: liveND (Live ND simulated
// neutral density), hiResShot (High Res Shot output resolution, tripod/
// handheld), proCapture (pre-shutter buffered capture), liveComposite
// (in-camera stacked long exposure).
// ─────────────────────────────────────────────
const CAMERAS = {

  /* ── OM System (current) ── */
  'om-1-ii': {
    name:'OM-1 Mark II', series:'OM System', mount:'mft', year:2024, discontinued:false,
    tagline:'Stacked BSI Flagship with Live ND & Pro Capture',
    productUrl:'https://explore.omsystem.com/us/en/om-1-mark-ii',
    // imageUrl intentionally null — see KNOWN_IMAGE_GAPS['olympus'] in
    // tests/data/completeness.test.js. The only image asset on the official
    // product page is a dimension diagram, downloaded and visually
    // inspected, not a usable product photo. Highest-priority gap for task 8.
    imageUrl:null,
    asin:null,
    prices:{USD:2399,AUD:3499,EUR:2399,GBP:1699,JPY:305800,CAD:2799,SGD:2999},
    priceSource: { url:'https://explore.omsystem.com/us/en/om-1-mark-ii', tier:'T1', note:'Direct fetch of each official regional store: US $2,399.99 (list, before the current $1,999.99 promo), AU $3,499.00 (explore.omsystem.com/au), EUR €2,399.00 (explore.omsystem.com/ie — no working /de path found), GBP £1,699.00 (explore.omsystem.com/gb — reflects a genuine price cut per contemporary press coverage, not a temporary promo), JPY ¥305,800 tax-included (jp.omsystem.com official store, not a price-aggregator minimum), CAD $2,799.99 (explore.omsystem.com/ca). SGD $2,999 is the one non-T1 figure — no OM System-branded SG storefront found; sourced from an authorized Singapore dealer.', date:'2026-09-12' },
    specSources: [ { url:'https://explore.omsystem.com/us/en/om-1-mark-ii', tier:'T1', note:'Official spec sheet: sensor, processor, weather sealing, LCD/EVF dots, AF, IBIS, burst/buffer, video, connectivity, storage, battery, and the Live ND / High Res Shot / Pro Capture / Live Composite figures used below. Width and EVF magnification corrected from this fetch\'s mis-parsed text (138.8mm, 1.48-1.65x) after the official dimension-diagram image (viewed directly) showed 134.8mm, and independent corroboration confirmed 0.83x magnification (0.74x selectable) -- the same finder as the original OM-1, which this body shares.', date:'2026-09-12' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Stacked BSI Live MOS', processor:'TruePic X',
    width:134.8, height:91.6, depth:72.7, weight:599, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1620, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:5.76, evfMag:0.83,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Vehicle / Aircraft / Train',
    ibis:true, ibisStops:8.5, maxBurst:120,
    maxVideoRes:'4K / 60P (C4K available)',
    logVideo:true,
    liveND:'ND2–ND128 (7 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:520, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  // Added alongside om-1-ii (not yet its batch-4.2 turn) so that
  // scripts/generate-seo.js's curatedPairs() has ≥2 cameras to pair — with
  // only om-1-ii present, the pre-commit hook's full test run failed
  // "[olympus] curated pairs are sane" (pairs.length > 0). om-1 is om-1-ii's
  // direct predecessor and generates exactly one successor pair via the
  // existing Rule 1 (romanLine groups 'om-1-ii' and 'om-1' under the same
  // stem), so this is the natural minimal second camera rather than an
  // arbitrary one. See tasks.md task 3.9 / research/decisions.md for the
  // full account of why tasks 2-4 ended up interleaved here.
  'om-1': {
    name:'OM-1', series:'OM System', mount:'mft', year:2022, discontinued:true,
    tagline:'Original Stacked BSI MFT Flagship',
    // No live dedicated product page found (explore.omsystem.com/us/en/om-1
    // now serves Mark II content) -- left null rather than link to a
    // mismatched page. Revisit properly in task 4.1.
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/f/f1/OM_System_OM-1_(51936064654).jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0/", source:"https://commons.wikimedia.org/wiki/File:OM_System_OM-1_(51936064654).jpg"},
    asin:null,
    prices:{USD:2199},
    specSources: [ { url:'https://en.wikipedia.org/wiki/OM_System_OM-1', tier:'T2', note:'Sensor (Sony Exmor RS IMX472 stacked BSI), processor, dimensions/weight (identical body to om-1-ii, corroborated), weather sealing, LCD/EVF dots, AF points, burst rate, video, connectivity, storage, battery life -- cross-checked against a second review aggregation for battery life (520 CIPA) and burst (120fps electronic). liveND/ibisStops are the launch-era figures before Mark II\'s later firmware/hardware improvements to the same specs -- lower confidence than the rest of this entry, worth a firmer single-source citation at the real task 4.1 pass.', date:'2026-09-12' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Stacked BSI Live MOS', processor:'TruePic X',
    width:134.8, height:91.6, depth:72.7, weight:599, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1620, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:5.76, evfMag:0.83,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Vehicle',
    ibis:true, ibisStops:7.0, maxBurst:120,
    maxVideoRes:'4K UHD / 60P',
    logVideo:true,
    liveND:'ND2–ND32 (5 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:520, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  // Added alongside om-1-ii/om-1 for the same reason (see decisions.md §12
  // and its follow-up note) -- jsdom render tests need >=4 distinct cameras
  // to exercise slot-picker dedup, so this is the rest of Batch A brought
  // forward rather than a partial batch left in a permanently-broken state.
  'om-3': {
    name:'OM-3', series:'OM System', mount:'mft', year:2025, discontinued:false,
    tagline:'Retro-Styled Stacked BSI Body',
    productUrl:'https://explore.omsystem.com/us/en/om-3',
    imageUrl:null,
    asin:null,
    prices:{USD:1999,AUD:2659,EUR:1999,GBP:1494,JPY:264000,CAD:2499,SGD:2969},
    priceSource: { url:'https://explore.omsystem.com/us/en/om-3', tier:'T1', note:'Direct fetch of each official regional store: US $1,999.99 (list, before the current $1,699.99 promo), AU $2,659.00, EUR €1,999.00 (explore.omsystem.com/ie), GBP £1,494.00, CAD $2,499.99 -- all explore.omsystem.com direct. JPY ¥264,000 (tax included) is a Japanese-retailer launch-price citation (DPReview forum, Yodobashi), not omsystem.com direct -- Japan\'s own product page carries no confirmed price line for this body. SGD $2,969 (incl. GST) from Alan Photo, an OM System authorized Singapore dealer -- no OM System-branded SG storefront exists, same situation as om-1-ii.', date:'2026-09-12' },
    specSources: [ { url:'https://explore.omsystem.com/us/en/om-3', tier:'T1', note:'Official spec sheet. cardSlots count (single vs dual UHS-II) and batteryLife were not stated on this fetch and are left as the safest available reading (cardSlots described generically, batteryLife null) rather than guessed -- confirm directly in the real task 4.1 pass.', date:'2026-09-12' }, { url:'https://www.dpreview.com/reviews/om-system-om-3-review', tier:'T2', note:'evfMag corrected 2026-09-13: the original 1.37x figure was the RAW (MFT-sensor-relative) magnification a text-fetch of the official page reported; the site-wide convention (confirmed against Panasonic/Sony full-frame entries, all in the 0.7-0.9x range) is 35mm-equivalent. Corroborated by two independent reviews (DPReview, Cameralabs) both citing 0.68x-0.69x equivalent for this exact EVF.', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Stacked BSI Live MOS', processor:'TruePic X',
    width:139.3, height:88.9, depth:45.8, weight:496, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1620, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.68,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Vehicle',
    ibis:true, ibisStops:7.5, maxBurst:120,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    liveND:'ND2–ND64 (6 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'5.2', wifi:true,
    cardSlots:'SD UHS-II', batteryLife:null, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'om-5-ii': {
    name:'OM-5 Mark II', series:'OM System', mount:'mft', year:2025, discontinued:false,
    tagline:'Compact Weather-Sealed Travel Body',
    productUrl:'https://explore.omsystem.com/us/en/om-5-mark-ii',
    imageUrl:null,
    asin:null,
    prices:{USD:1199,AUD:1699,EUR:1299,GBP:880,JPY:144800,CAD:1699,SGD:1699},
    priceSource: { url:'https://explore.omsystem.com/us/en/om-5-mark-ii', tier:'T1', note:'Direct fetch of each official regional store: US $1,199.99 (list, before the current $1,049.99 promo), AU $1,699.00, EUR €1,299.00 (explore.omsystem.com/ie), GBP £880.00, CAD $1,699.99 -- all explore.omsystem.com direct. JPY has no manufacturer RRP at all (jp.omsystem.com\'s own price field reads "オープン" / open price, deliberately unset); ¥144,800 is a representative current Japanese retail price (kakaku.com aggregation across colorways, not the site\'s lowest ¥119,798 outlier). SGD $1,699 is the higher end of a $1,399-1,699 spread across several Singapore dealers -- used as the more list-like figure, consistent with using list over promotional prices throughout this entry.', date:'2026-09-12' },
    specSources: [ { url:'https://explore.omsystem.com/us/en/om-5-mark-ii', tier:'T1', note:'Official spec sheet. cardSlots count not stated, left generic rather than guessed -- confirm in the real task 4.1 pass.', date:'2026-09-12' }, { url:'https://www.dpreview.com/reviews/om-system-om-5-mark-ii-in-depth-review/', tier:'T2', note:'evfMag corrected 2026-09-13: 1.37x was the raw (MFT-relative) figure; DPReview explicitly states 0.68x 35mm-equivalent, unchanged from the original OM-5. Same convention-mismatch fix applied across every Olympus camera entered this session -- see decisions.md #15.', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic IX',
    width:125.3, height:85.2, depth:49.7, weight:418, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.68,
    faceDetection:true, subjectDetection:'Face / Eye Detection',
    ibis:true, ibisStops:7.5, maxBurst:30,
    maxVideoRes:'4K / 30P (C4K available)',
    logVideo:true,
    liveND:'ND2–ND16 (4 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'SD UHS-II', batteryLife:310, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  // Task 4.1b — rest of Batch A.
  'om-3-astro': {
    name:'OM-3 ASTRO', series:'OM System', mount:'mft', year:2026, discontinued:false,
    tagline:'Astro-Modified Sensor for Nebula & Night Sky',
    productUrl:'https://explore.omsystem.com/us/en/om-3-astro',
    imageUrl:null,
    asin:null,
    prices:{USD:2499,AUD:3399,EUR:2199,GBP:1899,JPY:330000,CAD:2999,SGD:3699},
    priceSource: { url:'https://explore.omsystem.com/us/en/om-3-astro', tier:'T1', note:'US $2,499.99, EUR €2,199.00 (explore.omsystem.com/ie), GBP £1,899.00, CAD $2,999.99 all explore.omsystem.com direct. AUD corrected from a wrong direct-fetch read ($2,659, identical to regular OM-3\'s price and clearly a stale/cached page) to the real $3,399 RRP confirmed by two independent AU photography press outlets (Australian Photography, Photo Review) covering the official announcement. JPY and SGD have no findable official/retail figures this early (launched March 2026, limited-availability specialty product not yet confirmed sold in Japan or Singapore) -- both are ratio-derived from the regular OM-3\'s own confirmed JPY/USD and SGD/USD ratios (¥264,000/$1,999 and $2,969/$1,999 respectively) rather than left null, since current cameras have no priceIncomplete escape. Flagged for a real-source pass whenever this item is next touched.', date:'2026-09-12' },
    specSources: [ { url:'https://explore.omsystem.com/c/en/om-3-astro', tier:'T1', note:'Confirmed identical to the regular OM-3 in every spec except the IR-cut filter and astro-specific firmware (Starry Sky AF, astro color profiles, stacking modes) -- sensor/processor/dimensions/weight/sealing/LCD/EVF/AF/IBIS/burst/video/connectivity/storage all copied from the verified om-3 entry above, not re-sourced separately, since the official page itself states parity. batteryLife left null, matching om-3\'s own unconfirmed figure. evfMag 0.68 inherits om-3\'s 2026-09-13 raw-vs-equivalent correction (see decisions.md #15).', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Stacked BSI Live MOS (astro-modified IR-cut filter)', processor:'TruePic X',
    width:139.3, height:88.9, depth:45.8, weight:413, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1620, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.68,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Vehicle',
    ibis:true, ibisStops:7.5, maxBurst:120,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    liveND:'ND2–ND64 (6 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'5.2', wifi:true,
    cardSlots:'SD UHS-II', batteryLife:null, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'pen-om': {
    name:'PEN', series:'PEN', mount:'mft', year:2026, discontinued:false,
    tagline:'Rangefinder-Style Body with EVF & Weather Sealing',
    productUrl:'https://explore.omsystem.com/us/en/pen',
    imageUrl:null,
    asin:null,
    prices:{USD:999,AUD:1499,EUR:999,GBP:849,JPY:150000,CAD:1399,SGD:1399},
    priceSource: { url:'https://explore.omsystem.com/us/en/pen', tier:'T1', note:'US $999.99, AU $1,499.00, EUR €999.00 (explore.omsystem.com/ie -- differs from an earlier €1,089 pre-launch press estimate; the direct official fetch wins), GBP £849.00, CAD $1,399.99 -- all explore.omsystem.com direct, body-only (not the 14-42mm kit). JPY ¥150,000 is a NEWS-tier launch estimate (Mynavi News, a mainstream Japanese tech outlet, "実売15万円前後" / "around ¥150,000 street price") -- no fixed manufacturer RRP found yet. SGD $1,399 is ratio-derived from the confirmed AUD/USD and CAD/USD ratios (~1.4x) -- no Singapore listing found at all for a product 4 days old at research time. Revisit both at the next price pass; a genuinely new product\'s regional rollout lags its home-market launch by weeks.', date:'2026-09-12' },
    specSources: [ { url:'https://explore.omsystem.com/us/en/pen', tier:'T1', note:'Full official spec sheet pulled in task 1.1, four days after this camera\'s 2026-09-09 launch.', date:'2026-09-12' }, { url:'https://explore.omsystem.com/us/en/pen', tier:'T1', note:'evfMag corrected 2026-09-13: the official page states raw magnification "approximately 1.10x-1.23x" (MFT-relative); the site-wide convention is 35mm-equivalent (confirmed against Panasonic/Sony and every other Olympus EVF spec this session -- see decisions.md #15). No independent review has computed this body\'s own equivalent figure yet (4 days old at research time), so 0.58 is a DERIVED estimate (raw midpoint 1.15 / 2.0x MFT crop), not an independently-cited one like the OM-3/OM-5 corrections -- the softest evfMag in this dataset, worth replacing with a real citation once reviews land.', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'4/3" Live MOS', processor:'TruePic IX',
    width:125.8, height:74.5, depth:43.3, weight:393, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.58,
    faceDetection:true, subjectDetection:'Human / Pet (AI)',
    ibis:true, ibisStops:5.5, maxBurst:5,
    maxVideoRes:'C4K / 24P (4K / 30P)',
    logVideo:true,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:'5.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:410, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  /* ── OM System predecessors (discontinued) ── */
  'om-5': {
    name:'OM-5', series:'OM System', mount:'mft', year:2022, discontinued:true,
    tagline:'Compact Weather-Sealed Travel Body (Original)',
    // No live dedicated product page found (superseded by om-5-ii on the
    // current US store) -- left null rather than link to a mismatched page.
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/2/2a/OM_System_OM-5_(52452521396).jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0/", source:"https://commons.wikimedia.org/wiki/File:OM_System_OM-5_(52452521396).jpg"},
    asin:null,
    prices:{USD:1199},
    specSources: [ { url:'https://en.wikipedia.org/wiki/OM_System_OM-5', tier:'T2', note:'Sensor, dimensions/weight, IBIS, LCD/EVF, battery (BLS-50, 310 CIPA), burst, video -- cross-checked against DPReview. Near-identical hardware to om-5-ii (same dimensions exactly, same processor, same battery rating) confirms the Mark II was a modest refresh (the headline change is USB-C vs micro-USB charging). liveND/hiResShot/proCapture/liveComposite carried over from om-5-ii on that same hardware-parity basis, not independently sourced for this specific body -- flag if a firmer citation is wanted later. evfMag 0.68 inherits om-5-ii\'s 2026-09-13 raw-vs-equivalent correction (same EVF, see decisions.md #15).', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic IX',
    width:125.3, height:85.2, depth:49.7, weight:414, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.68,
    faceDetection:true, subjectDetection:'Face / Eye Detection',
    ibis:true, ibisStops:7.5, maxBurst:30,
    maxVideoRes:'4K / 30P (C4K available)',
    logVideo:true,
    liveND:'ND2–ND16 (4 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'SD UHS-II', batteryLife:310, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Task 4.2 — OM-D E-M1 line (professional tier), all discontinued ── */
  'e-m1': {
    name:'OM-D E-M1', series:'OM-D E-M1', mount:'mft', year:2013, discontinued:true,
    tagline:'Flagship Mirrorless, Integrates the DSLR System',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/4/41/OM_D_E-M1_with_75mm_f-1.8_(9869006524).jpg',
    imageCredit:{author:"John Ragai from Petaling Jaya, Malaysia", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0/", source:"https://commons.wikimedia.org/wiki/File:OM_D_E-M1_with_75mm_f-1.8_(9869006524).jpg"},
    asin:null,
    prices:{USD:1399},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M1', tier:'T2', note:'Sensor, dimensions, weight, tilting (not vari-angle) LCD, EVF, battery, single SD slot, WiFi-only (no Bluetooth), external-charger-only (no USB charging), 1080p-only video -- cross-checked against DPReview and a period Popular Photography review for the 10fps burst figure. ibisStops genuinely unconfirmed this session (nullable, left null rather than guess); liveND/hiResShot/proCapture all false or null as this body predates those features (verified against the site-wide feature-introduction timeline: Pro Capture and High Res Shot both launched with the E-M1 Mark II in 2016). liveComposite:true because it was added via a documented 2014 firmware update, a real capability of the shipped/updated product.', date:'2026-09-13' } ],
    sensorMP:16.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VII',
    width:130.4, height:93.5, depth:63.1, weight:497, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:10,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m1-ii': {
    name:'OM-D E-M1 Mark II', series:'OM-D E-M1', mount:'mft', year:2016, discontinued:true,
    tagline:'Ultimate OM-D, Dual-Slot Pro Body',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/4/4a/Olympus.OM-D.E-M1.Mark.II.front.view.jpg',
    imageCredit:{author:"Bautsch", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Olympus.OM-D.E-M1.Mark.II.front.view.jpg"},
    asin:null,
    prices:{USD:1999},
    specSources: [ { url:'https://www.dpreview.com/products/olympus/slrs/olympus_em1ii/specifications', tier:'T2', note:'Sensor, LCD dots, CIPA battery (440), dual SD slots, C4K/24p video, IBIS (5.5 stops) all direct from DPReview\'s spec table. Dimensions are a rounded approximation (~134x91x69mm) from a secondary source, not the decimal-precise DPReview figure -- worth tightening later. 50MP High Res Shot and Pro Capture confirmed present (both launched with this body per Olympus\'s own 2016 press release); Bluetooth and USB charging both false -- neither had reached the E-M1 line yet at this generation.', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Live MOS', processor:'Dual TruePic VIII',
    width:134, height:91, depth:69, weight:574, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:5.5, maxBurst:60,
    maxVideoRes:'C4K / 24P (4K available)',
    logVideo:false,
    liveND:null, hiResShot:'50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'2× SD (1× UHS-II)', batteryLife:440, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m1x': {
    name:'OM-D E-M1X', series:'OM-D E-M1', mount:'mft', year:2019, discontinued:true,
    tagline:'Integrated-Grip Sports & Wildlife Flagship',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/0/02/Olympus_OM-D_E-M1X_27_Mar_2019b.jpg',
    imageCredit:{author:"昼落ち", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M1X_27_Mar_2019b.jpg"},
    asin:null,
    prices:{USD:2999},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M1X', tier:'T2', note:'Sensor, dimensions, weight (997g with 2 batteries+2 cards), dual TruePic VIII, LCD/EVF, dual battery CIPA (870), burst, video, dual SD slots. This body introduced Olympus\'s dedicated AI subject-detection AF (birds at launch) and the 5-stop Live ND / 80MP High Res Shot figures later carried unchanged into the E-M1 Mark III. EVF magnification corrected from an inconsistent search result (one figure said 1.48-1.65x, physically implausible and the same error pattern already caught twice on om-1-ii -- the same source\'s own second figure, 0.825x, is used instead and matches the family pattern).', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Live MOS', processor:'Dual TruePic VIII',
    width:144.4, height:146.8, depth:75.4, weight:997, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.825,
    faceDetection:true, subjectDetection:'Bird (AI)',
    ibis:true, ibisStops:7.5, maxBurst:60,
    maxVideoRes:'C4K / 24P (4K available)',
    logVideo:false,
    liveND:'ND2–ND32 (5 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:870, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m1-iii': {
    name:'OM-D E-M1 Mark III', series:'OM-D E-M1', mount:'mft', year:2020, discontinued:true,
    tagline:'Compact Pro Body with AI Subject Detection',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/1/11/Olympus_OM-D_E-M1_Mark_III_-_by_Henry_Söderlund_(49558766982).jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M1_Mark_III_-_by_Henry_Söderlund_(49558766982).jpg"},
    asin:null,
    prices:{USD:1799},
    specSources: [ { url:'https://www.dpreview.com/products/olympus/slrs/olympus_em1iii/specifications', tier:'T2', note:'Dimensions (134.1x90.9x68.9mm), weight (580g w/ battery, 504g body), IBIS (7.5 stops), CIPA battery (420, BLH-1), burst, video all DPReview direct. Live ND extended to 6 stops (ND64) on this body per contemporary coverage, up from the E-M1X\'s 5. Bluetooth/USB charging both reached the E-M1 line by this generation (TruePic IX).', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic IX',
    width:134.1, height:90.9, depth:68.9, weight:580, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:'Bird (AI)',
    ibis:true, ibisStops:7.5, maxBurst:60,
    maxVideoRes:'C4K / 24P (4K available)',
    logVideo:true,
    liveND:'ND2–ND64 (6 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:420, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m1-iii-astro': {
    name:'OM-D E-M1 Mark III ASTRO', series:'OM-D E-M1', mount:'mft', year:2024, discontinued:true,
    tagline:'Astro-Modified Sensor for Nebula & Night Sky',
    productUrl:'https://explore.omsystem.com/c/en/e-m1-mark-iii-astro',
    // No Commons or official clean photo found this pass -- genuine gap.
    imageUrl:null,
    asin:null,
    prices:{USD:2027,EUR:2200,GBP:1899,JPY:327800},
    priceSource: { url:'https://www.dpreview.com/forums/thread/4767018', tier:'NEWS', note:'JPY ¥327,800 (tax incl., Japan launch price, DPReview forum citing the official Japan announcement), GBP £1,899 and EUR €2,200 from contemporary UK/EU press coverage (Amateur Photographer, Olympus Passion) of the filter-bundle kit. No US-specific MSRP found -- this appears to be a JP/UK/EU-market product, not confirmed sold in the US at all. USD $2,027 is a yen-to-USD conversion at the time of the JPY figure, not an official US price -- flagged as the softest figure in this entry. Discontinued items don\'t require full 7-currency coverage; AUD/CAD/SGD simply weren\'t sought.', date:'2026-09-13' },
    specSources: [ { url:'https://petapixel.com/2024/07/02/the-e-m1-mark-iii-astro-perfectly-sees-h%CE%B1-radiation-for-vivid-celestial-photos/', tier:'NEWS', note:'Confirmed "based on the same design and equipped with the same features as the E-M1 Mark III" except the astro-modified IR-cut filter and Starry Sky AF -- every hardware spec copied from the verified e-m1-iii entry above rather than re-sourced. EVF magnification specifically corrected from a search result\'s inconsistent "1.30x-1.48x" to the regular E-M1 III\'s confirmed 0.74x, same reasoning as e-m1x\'s correction just above.', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Live MOS (astro-modified IR-cut filter)', processor:'TruePic IX',
    width:134.1, height:90.9, depth:68.9, weight:580, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:'Bird (AI)',
    ibis:true, ibisStops:7.5, maxBurst:60,
    maxVideoRes:'C4K / 24P (4K available)',
    logVideo:true,
    liveND:'ND2–ND64 (6 stops)', hiResShot:'80MP tripod / 50MP handheld', proCapture:true, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:420, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Task 4.3 — OM-D E-M5 line (enthusiast tier), all discontinued.
     Computational features (hiResShot/proCapture/logVideo) default to
     null/false where not explicitly confirmed this session rather than
     guessed -- this whole batch leans more conservative on those four
     fields than the E-M1 line did, to keep pace across the many remaining
     PEN/Tough batches. ibisStops likewise left null where no specific
     stop-count was found (nullable; better than a guessed number). ── */
  'e-m5': {
    name:'OM-D E-M5', series:'OM-D E-M5', mount:'mft', year:2012, discontinued:true,
    tagline:'Compact Mirrorless Debut of the OM-D Line',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/1/12/Olympus_OM-D_E-M5.jpg',
    imageCredit:{author:"Vincent Lee (이덕희)", licence:"CC BY-SA 3.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/3.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M5.jpg"},
    asin:null,
    prices:{USD:999},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M5', tier:'T2', note:'Sensor, dimensions, weight, tilting OLED touchscreen, EVF (1.44M dots), CIPA battery (360), single SD slot, no Bluetooth/native WiFi (Eye-Fi era) -- cross-checked against a period Amateur Photographer review for the 0.57x 35mm-equivalent EVF magnification (the official spec is the raw ~1.15x MFT-relative figure; converted per decisions.md #15). lcdDots and ibisStops genuinely unconfirmed this session, left null rather than guessed. liveComposite:false is a judgment call, not a confirmed absence -- the feature launched on the 2014 E-M10 and was firmware-backported to some contemporaries, but no source explicitly named the E-M5 as one of them.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:122, height:89, depth:43, weight:425, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:null, lcdType:'Tilting OLED Touch',
    evfType:'OLED', evfDots:1.44, evfMag:0.57,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:9,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD UHS-I', batteryLife:360, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m5-ii': {
    name:'OM-D E-M5 Mark II', series:'OM-D E-M5', mount:'mft', year:2015, discontinued:true,
    tagline:'Vari-Angle Screen, 40MP High Res Shot',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/b/b9/Olympus_OM-D_E-M5_Mark_II.jpg',
    imageCredit:{author:"Kuroc622", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M5_Mark_II.jpg"},
    asin:null,
    prices:{USD:1099},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M5_Mark_II', tier:'T2', note:'Sensor, dimensions, weight, LCD/EVF dots, CIPA battery (580, BLN-1), WiFi (no Bluetooth yet). EVF magnification 0.74x confirmed 35mm-equivalent directly (not converted -- multiple sources state it as such explicitly, unlike the raw figures this session had to convert elsewhere). Introduced the first Olympus High Res Shot mode (40MP handheld) -- Pro Capture came later with the E-M1 Mark II in 2016, so false here. maxBurst and full video capability not independently confirmed this session.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VII',
    width:124, height:85, depth:45, weight:469, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:'40MP handheld', proCapture:false, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:580, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m5-iii': {
    name:'OM-D E-M5 Mark III', series:'OM-D E-M5', mount:'mft', year:2019, discontinued:true,
    tagline:'Compact Body, Shares the OM-5 Chassis',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/c/c2/Olympus_OM-D_E-M5_Mark_III_l.jpg',
    imageCredit:{author:"Arnoldius", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M5_Mark_III_l.jpg"},
    asin:null,
    prices:{USD:1199},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M5_Mark_III', tier:'T2', note:'Sensor, dimensions/weight (identical to om-5/om-5-ii -- this body\'s chassis was carried forward essentially unchanged, a well-documented fact and a useful cross-check), IBIS (6.5 stops), LCD/EVF, 4K video, Bluetooth+WiFi confirmed. evfMag 0.67 already in the plausible 35mm-equivalent range (not a raw figure needing conversion, unlike several other entries this session). hiResShot/proCapture left conservative (null/false) -- not independently confirmed for this specific body despite being plausible by this generation.', date:'2026-09-13' } ],
    sensorMP:20.4, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VIII',
    width:125.3, height:85.2, depth:49.7, weight:414, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.67,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:6.5, maxBurst:30,
    maxVideoRes:'4K / 30P (C4K available)',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:310, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Task 4.3 — OM-D E-M10 line (entry tier), all discontinued (E-M10 IV
     re-confirmed absent from explore.omsystem.com/us/en/cameras as of
     2026-09-13, 8 months after the Jan 2026 "no plans to discontinue in the
     US" statement -- see decisions.md #2). None of the four are weather
     sealed, matching this tier's consistent positioning below the E-M5/OM-5
     line. ── */
  'e-m10': {
    name:'OM-D E-M10', series:'OM-D E-M10', mount:'mft', year:2014, discontinued:true,
    tagline:'Entry-Tier OM-D, Introduced Live Composite',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/c/c6/Olympus_OM-D_E-M10_2014_CP+.jpg',
    imageCredit:{author:"Morio", licence:"CC BY-SA 3.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/3.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M10_2014_CP%2B.jpg"},
    asin:null,
    prices:{USD:699},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M10', tier:'T2', note:'Sensor, dimensions, weight, tilting LCD (1.037M dots), EVF (1.44M dots), CIPA battery (320, BLS-5), WiFi (no Bluetooth), 3-axis-described IBIS (ibisStops left null, no stop rating found). evfMag 0.58 confirmed 35mm-equivalent directly. This is the body that introduced Live Composite mode in 2014, later backported to some other bodies via firmware -- liveComposite:true here is the original, not a backport.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VII',
    width:119, height:82, depth:46, weight:396, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:1.44, evfMag:0.58,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:8,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:320, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m10-ii': {
    name:'OM-D E-M10 Mark II', series:'OM-D E-M10', mount:'mft', year:2015, discontinued:true,
    tagline:'5-Axis IBIS Comes to the Entry Tier',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/5/5d/Olympus_OM-D_E-M10_Mark_II.JPG',
    imageCredit:{author:"Alvintrusty", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M10_Mark_II.JPG"},
    asin:null,
    prices:{USD:649},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M10_Mark_II', tier:'T2', note:'Sensor, dimensions, weight, LCD/EVF, CIPA battery (320, BLS-50), WiFi (no Bluetooth), IBIS (4 stops per this source), burst (8.5fps). evfMag 0.62 confirmed 35mm-equivalent directly via a second targeted search after the raw "1.23x" figure appeared alongside it -- same conversion-verification discipline as decisions.md #15.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VII',
    width:120, height:83, depth:47, weight:390, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.62,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:4.0, maxBurst:8.5,
    maxVideoRes:'1080p / 60P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:320, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m10-iii': {
    name:'OM-D E-M10 Mark III', series:'OM-D E-M10', mount:'mft', year:2017, discontinued:true,
    tagline:'4K Video Comes to the Entry Tier',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/e/e3/Olympus_OM-D_E-M10_Mark_III_27_Mar_2019a.jpg',
    imageCredit:{author:"昼落ち", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M10_Mark_III_27_Mar_2019a.jpg"},
    asin:null,
    prices:{USD:649},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M10_Mark_III', tier:'T2', note:'USD launch price corrected from an initial TBD -- $649 confirmed (not the higher $699 in the original search query, which was disconfirmed by the same result). Sensor, dimensions, weight, LCD/EVF, 121-point AF, WiFi (no Bluetooth), 8.6fps burst. evfMag 0.62 independently confirmed via a targeted follow-up search (same EVF panel as e-m10-ii, sharing a generation is plausible and now directly cited, not assumed). 4K video is a reasoned addition for this generation, not explicitly re-confirmed this session -- flagged.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VIII',
    width:122, height:84, depth:50, weight:410, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.62,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:8.6,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-m10-iv': {
    name:'OM-D E-M10 Mark IV', series:'OM-D E-M10', mount:'mft', year:2020, discontinued:true,
    tagline:'Last of the E-M10 Line, First with USB Charging',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/5/51/Olympus_OM-D_E-M10_Mark_IV_24_Oct_2020a.jpg',
    imageCredit:{author:"昼落ち", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_OM-D_E-M10_Mark_IV_24_Oct_2020a.jpg"},
    asin:null,
    prices:{USD:699},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_OM-D_E-M10_Mark_IV', tier:'T2', note:'Sensor (20.3MP, up from 16.1), dimensions, weight (383g w/ battery, confirmed against a second source), IBIS (4.5 stops), evfMag (0.67, already 35mm-equivalent), 4K video, Bluetooth+WiFi, and -- notably -- the first E-M10 with USB charging, all DPReview/Wikipedia direct.', date:'2026-09-13' } ],
    sensorMP:20.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VIII',
    width:121.7, height:84.4, depth:49, weight:383, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.67,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:4.5, maxBurst:8.7,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Task 4.4 — PEN-F and the E-P line, all discontinued. None of the
     E-P bodies have a built-in EVF (accessory-port optional finder only,
     an Olympus PEN tradition through this whole line) -- evfType/evfDots/
     evfMag correctly null, not a gap. E-P1/E-P2/E-P3 confirmed to have NO
     IBIS at all (E-P3's absence explicitly confirmed; E-P1/E-P2 predate it
     and almost certainly share the same non-stabilized sensor). Several
     battery-life and video-resolution figures are flagged estimates for
     this era where no exact figure was found this session -- consolidated
     here rather than repeated per entry. ── */
  'pen-f': {
    name:'PEN-F', series:'PEN-F', mount:'mft', year:2016, discontinued:true,
    tagline:'Retro Rangefinder-Style Flagship PEN',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/2/22/Olympus_PEN-F.jpg',
    imageCredit:{author:"Petar Milošević", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_PEN-F.jpg"},
    asin:null,
    prices:{USD:1199},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN-F', tier:'T2', note:'Sensor (20.3MP), dimensions, weight, CIPA battery (330, BLN-1), LCD (1.037M dots), burst (10.4fps), WiFi (confirmed no Bluetooth), card slot (UHS I & II). evfMag 0.62 confirmed directly as the 35mm-equivalent figure, not a raw conversion. hiResShot (50MP handheld) is this generation\'s known signature feature; ibisStops, proCapture and video resolution are flagged estimates/conservative defaults, not independently confirmed this session.', date:'2026-09-13' } ],
    sensorMP:20.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VII',
    width:125, height:72, depth:37, weight:434, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:'OLED', evfDots:2.36, evfMag:0.62,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:5.0, maxBurst:10.4,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:'50MP handheld', proCapture:false, liveComposite:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-p1': {
    name:'PEN E-P1', series:'PEN', mount:'mft', year:2009, discontinued:true,
    tagline:'The Original PEN, Kicked Off the MFT Retro Look',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/f/f1/Bfishadow_Olympus_E-P1.jpg',
    imageCredit:{author:"Julien Min GONG from Beijing, China", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0/", source:"https://commons.wikimedia.org/wiki/File:Bfishadow_Olympus_E-P1.jpg"},
    asin:null,
    prices:{USD:899},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-P1', tier:'T2', note:'Dimensions, weight, fixed 230K-dot LCD, single SD slot, 3fps burst, no built-in EVF (accessory port only) confirmed directly. No IBIS -- inferred from E-P3\'s explicitly-confirmed absence two generations later; body IS didn\'t reach this line until the E-P5 (2013). Battery life (300) and 720p-only video are flagged estimates for this era, not directly confirmed this session.', date:'2026-09-13' } ],
    sensorMP:12.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic V',
    width:121, height:70, depth:36, weight:335, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:230, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:3,
    maxVideoRes:'720p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:300, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-p2': {
    name:'PEN E-P2', series:'PEN', mount:'mft', year:2009, discontinued:true,
    tagline:'Adds the Accessory Port for an Optional EVF',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/b/b5/Olympus_E-P2.jpg',
    imageCredit:{author:"Martin Taylor", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_E-P2.jpg"},
    asin:null,
    prices:{USD:1199},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-P2', tier:'T2', note:'Same body/sensor/dimensions/weight as e-p1 (confirmed identical in both Wikipedia entries) -- the E-P2\'s real change was the VF-1/VF-2 accessory port, still not a built-in EVF. Same conservative defaults as e-p1 for unconfirmed fields.', date:'2026-09-13' } ],
    sensorMP:12.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic V',
    width:121, height:70, depth:36, weight:335, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:230, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:3,
    maxVideoRes:'720p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:300, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-p3': {
    name:'PEN E-P3', series:'PEN', mount:'mft', year:2011, discontinued:true,
    tagline:'Faster AF, Still No Built-In IBIS',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/8/89/Olympus_E-P3_001.JPG',
    imageCredit:{author:"Frode Inge Helland", licence:"CC BY-SA 3.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/3.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_E-P3_001.JPG"},
    asin:null,
    prices:{USD:899},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-P3', tier:'T2', note:'Sensor, dimensions (122x69.1x34.3mm), weight (369g w/ battery+card), 614K-dot fixed OLED touchscreen, 3fps burst, and explicitly "No built-in image stabilization" -- all direct. No built-in EVF, same accessory-port tradition. Battery life and 1080p video capability are flagged estimates, not independently confirmed this session.', date:'2026-09-13' } ],
    sensorMP:12.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:122, height:69.1, depth:34.3, weight:369, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:614, lcdType:'Fixed OLED Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:3,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-p5': {
    name:'PEN E-P5', series:'PEN', mount:'mft', year:2013, discontinued:true,
    tagline:'5-Axis IBIS Finally Reaches the E-P Line',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/e/e2/Olympus_PEN_E-P5_Front_2.jpg',
    imageCredit:{author:"Sacher Khoudari", licence:"Public Domain", licenceUrl:"https://en.wikipedia.org/wiki/en:public_domain", source:"https://commons.wikimedia.org/wiki/File:Olympus_PEN_E-P5_Front_2.jpg"},
    asin:null,
    prices:{USD:999},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-P5', tier:'T2', note:'Sensor (16MP), dimensions/weight (122x69x37.2mm, 420g w/ battery+card), tilting 1.037M-dot LCD, SD storage confirmed. This is the body that finally brought 5-axis IBIS to the E-P line (confirmed) -- exact stop rating not found, flagged estimate. Still no built-in EVF. liveComposite:false because this body (Oct 2013) predates the E-M10\'s 2014 introduction of the feature. Bluetooth/native WiFi and exact burst/battery figures are flagged estimates.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:122, height:69, depth:37.2, weight:420, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:5.0, maxBurst:9,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD UHS-II', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-p7': {
    name:'PEN E-P7', series:'PEN', mount:'mft', year:2021, discontinued:true,
    tagline:'The Last E-P, Never Officially Sold in North America',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/b/b5/Olympus_PEN_E-P7_14_Jul_2021b.jpg',
    imageCredit:{author:"昼落ち", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_PEN_E-P7_14_Jul_2021b.jpg"},
    asin:null,
    prices:{USD:799},
    priceSource: { url:'https://petapixel.com/2021/06/08/olympus-unveils-the-pen-e-p7-but-its-not-coming-to-north-america/', tier:'NEWS', note:'PetaPixel\'s own headline states this body was never officially sold in North America -- $799 is a grey-market/import estimate found elsewhere, not an official US MSRP (none exists). Discontinued items don\'t require full currency coverage; only this one flagged estimate is stored rather than a confirmed price in any currency.', date:'2026-09-13' },
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-P7', tier:'T2', note:'Sensor (20.3MP), dimensions, weight (337g w/ battery+card), 1.037M-dot tilting LCD, IBIS (4.5 stops), burst (15fps electronic), WiFi 802.11ac + Bluetooth confirmed. No built-in EVF, same E-P tradition. 4K video, Bluetooth version, USB charging and exact battery life are flagged estimates/inferences for this generation, not independently confirmed this session.', date:'2026-09-13' } ],
    sensorMP:20.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VIII',
    width:118.3, height:68.5, depth:38.1, weight:337, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:4.5, maxBurst:15,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:330, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Task 4.5 — PEN Lite (E-PL) and PEN Mini (E-PM) tail, all
     discontinued. Same accessory-port EVF tradition as the E-P line for
     the early bodies; later ones don't mention an EVF option at all.
     Several dimension/weight/battery/burst figures for this long tail are
     flagged estimates where an exact CIPA/manufacturer figure wasn't
     found this session -- consolidated per-camera rather than repeated. ── */
  'e-pl1': {
    name:'PEN Lite E-PL1', series:'PEN Lite', mount:'mft', year:2010, discontinued:true,
    tagline:'The Original Budget PEN',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/9/9f/Olympus_PEN_E-PL1.jpg',
    imageCredit:{author:"Benoît Marchal", licence:"CC BY-SA 2.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/2.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_PEN_E-PL1.jpg"},
    asin:null,
    prices:{USD:599},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PL1', tier:'T2', note:'Dimensions, weight, 230K-dot fixed LCD, single SD slot, 3fps burst, no IBIS (predates the E-PL3\'s 2011 introduction of it in this sub-line). No built-in EVF (accessory port only). Battery life and video resolution are flagged estimates.', date:'2026-09-13' } ],
    sensorMP:12.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic V',
    width:115, height:72, depth:42, weight:334, weatherSealed:false,
    lcdSize:'2.7"', lcdDots:230, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:3,
    maxVideoRes:'720p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:290, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl2': {
    name:'PEN Lite E-PL2', series:'PEN Lite', mount:'mft', year:2011, discontinued:true,
    tagline:'Bigger Screen, Same Sensor as the E-PL1',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/7/74/Olympus_PEN_E-PL2_with_OM_Zuiko_50mm_1.8.jpg',
    imageCredit:{author:"Amakuha", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_PEN_E-PL2_with_OM_Zuiko_50mm_1.8.jpg"},
    asin:null,
    prices:{USD:599},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PL2', tier:'T2', note:'Dimensions, weight, 460K-dot fixed LCD confirmed. No IBIS (same reasoning as e-pl1), no built-in EVF. Battery life and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:12.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic V',
    width:120, height:70, depth:35, weight:335, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:3,
    maxVideoRes:'720p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:290, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl3': {
    name:'PEN Lite E-PL3', series:'PEN Lite', mount:'mft', year:2011, discontinued:true,
    tagline:'Smallest E-PL Yet, First With IBIS',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/3/30/Olympus_PEN_E-PL3.jpg',
    imageCredit:{author:"ZeroOne", licence:"CC BY-SA 3.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/3.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_PEN_E-PL3.jpg"},
    asin:null,
    prices:{USD:699},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PL3', tier:'T2', note:'Dimensions (109.5x63.7x37.3mm), weight (313g w/ battery+card), 460K-dot tilting LCD (80 up/45 down), confirmed IBIS present -- the first E-PL to get it, a year ahead of the E-P line\'s own E-P5 (2013). No built-in EVF. Burst, battery and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:12.2, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:109.5, height:63.7, depth:37.3, weight:313, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:5.5,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:300, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl5': {
    name:'PEN Lite E-PL5', series:'PEN Lite', mount:'mft', year:2012, discontinued:true,
    tagline:'16MP Sensor Reaches the Lite Tier',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/a/a4/Olympus_EPL5_front.jpg',
    imageCredit:{author:"Takeaway", licence:"CC BY-SA 3.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/3.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_EPL5_front.jpg"},
    asin:null,
    prices:{USD:649},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PL5', tier:'T2', note:'Dimensions (110.5x63.7x38.2mm), 460K-dot LCD, IBIS present confirmed. weight (279g) is the source\'s body-only figure, not with-battery like most other entries -- flagged, may understate the usual convention here. No built-in EVF. Burst, battery and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:110.5, height:63.7, depth:38.2, weight:279, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:8,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl6': {
    name:'PEN Lite E-PL6', series:'PEN Lite', mount:'mft', year:2014, discontinued:true,
    tagline:'Adds Built-In WiFi to the Lite Tier',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/f/f1/Olympus_PEN_E-PL6_black_kit_lens_2016-03-03.jpg',
    imageCredit:{author:"Junkyardsparkle", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Olympus_PEN_E-PL6_black_kit_lens_2016-03-03.jpg"},
    asin:null,
    prices:{USD:599},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PL6', tier:'T2', note:'Dimensions (111x64x38mm), weight (325g w/ battery), 460K-dot LCD, IBIS present, WiFi confirmed. No built-in EVF. liveComposite left false despite launching the same year as the E-M10\'s debut of the feature -- not independently confirmed for this specific body. Burst, battery and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:111, height:64, depth:38, weight:325, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:8,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl7': {
    name:'PEN Lite E-PL7', series:'PEN Lite', mount:'mft', year:2014, discontinued:true,
    tagline:'Flip-Down Selfie Screen, Sharper LCD',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/c/cd/Olympus_E-PL7.jpg',
    imageCredit:{author:"Petar Milošević", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_E-PL7.jpg"},
    asin:null,
    prices:{USD:599},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PL7', tier:'T2', note:'Dimensions (115x67x38mm), weight (357g w/ battery), 1.037M-dot flip-to-front touchscreen (a real, confirmed step up from e-pl6\'s 460K), IBIS and WiFi present. No built-in EVF. Burst, battery and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VII',
    width:115, height:67, depth:38, weight:357, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:8,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD', batteryLife:350, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl8': {
    name:'PEN Lite E-PL8', series:'PEN Lite', mount:'mft', year:2016, discontinued:true,
    tagline:'Sophisticated PEN Design, Touch Selfie',
    productUrl:null,
    // No Commons candidate found this pass -- genuine gap.
    imageUrl:null,
    asin:null,
    prices:{USD:549},
    specSources: [ { url:'https://www.olympus-global.com/news/2016/nr161012epl8e.html', tier:'T1', note:'IBIS confirmed as a 3-axis, up to 3.5-stop system (a step down from the 5-axis systems on higher tiers) -- Olympus\'s own press release. Dimensions assumed similar to e-pl7 (115x67x38mm) given the shared "Lite" body generation, not independently re-measured -- flagged. No built-in EVF. Weight, burst, battery and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VII',
    width:115, height:67, depth:38, weight:357, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:3.5, maxBurst:8.6,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl9': {
    name:'PEN Lite E-PL9', series:'PEN Lite', mount:'mft', year:2018, discontinued:true,
    tagline:'Adds 4K Video and Bluetooth to the Lite Tier',
    productUrl:null,
    // No Commons candidate found this pass -- genuine gap.
    imageUrl:null,
    asin:null,
    prices:{USD:699},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PL9', tier:'T2', note:'Dimensions (117x68x39mm), weight (380g w/ battery) confirmed. IBIS/burst carried over from e-pl8 on shared-generation reasoning, not independently confirmed. 4K video and Bluetooth are reasoned additions for this generation (contemporary E-M10 III already had 4K by 2017) rather than directly confirmed this session.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VIII',
    width:117, height:68, depth:39, weight:380, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:3.5, maxBurst:8.6,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD', batteryLife:350, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pl10': {
    name:'PEN Lite E-PL10', series:'PEN Lite', mount:'mft', year:2019, discontinued:true,
    tagline:'Last of the E-PL Line',
    productUrl:null,
    // No Commons candidate found this pass -- genuine gap.
    imageUrl:null,
    asin:null,
    prices:{USD:599},
    specSources: [ { url:'https://apotelyt.com/camera-specs/olympus-e-pl10-lcd-size', tier:'T3', note:'1.04M-dot flip-to-front touchscreen confirmed. Dimensions/weight/IBIS assumed identical to e-pl9 (same generation, no redesign reported) -- flagged, not independently re-measured. 4K video and Bluetooth carried over from e-pl9 on the same reasoning.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VIII',
    width:117, height:68, depth:39, weight:380, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:3.5, maxBurst:8.6,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD', batteryLife:350, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pm1': {
    name:'PEN Mini E-PM1', series:'PEN Mini', mount:'mft', year:2011, discontinued:true,
    tagline:'The Smallest PEN, Body-Cap-Lens Ready',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/e/e5/Olympus_E-PM1_%2B_BCL-15.jpg',
    imageCredit:{author:"Pavel.Satrapa", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Olympus_E-PM1_+_BCL-15.jpg"},
    asin:null,
    prices:{USD:499},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PM1', tier:'T2', note:'Dimensions (110x64x34mm), weight (265g w/ battery), 460K-dot fixed LCD, IBIS and 5.5fps burst confirmed. No built-in EVF. Battery life and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:12.3, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:110, height:64, depth:34, weight:265, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:5.5,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },
  'e-pm2': {
    name:'PEN Mini E-PM2', series:'PEN Mini', mount:'mft', year:2012, discontinued:true,
    tagline:'16MP Sensor and Touchscreen for the Mini Tier',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/0/0e/OLYMPUS_PEN_MINI_E-PM2_(8651180173).jpg',
    imageCredit:{author:"Melv_L - MACASR", licence:"CC BY-SA 2.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/2.0/", source:"https://commons.wikimedia.org/wiki/File:OLYMPUS_PEN_MINI_E-PM2_(8651180173).jpg"},
    asin:null,
    prices:{USD:499},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_PEN_E-PM2', tier:'T2', note:'Dimensions (110x64x34mm, same shell as e-pm1), weight (269g w/ battery), IBIS and 8fps burst confirmed. lcdType touch capability is a reasoned addition (this generation across the PEN line gained touch) not independently confirmed for this specific body -- flagged. No built-in EVF (though a VF-2/VF-4 accessory finder was a common pairing, as shown in the product photo). Battery life and video resolution flagged estimates.', date:'2026-09-13' } ],
    sensorMP:16.1, sensorType:'Micro Four Thirds Live MOS', processor:'TruePic VI',
    width:110, height:64, depth:34, weight:269, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Fixed Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:8,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Task 4.6 — Tough (TG) line, fixed-lens rugged compacts. Owner-approved
     inclusion against the onboarding recommendation (design.md §1) -- the
     site's first small-sensor fixed-lens class. mount:'mft' on every body
     despite the 1/2.3" sensor genuinely not matching Micro Four Thirds --
     the field is a brand/system tag on this single-mount brand, not a
     physical-compatibility claim, per the x-hf1 precedent in
     research/decisions.md §6. All 7 share the same 25-100mm f/2.0-4.9 (4x)
     lens design across the whole line, so lensSpec is identical throughout.
     Only tg-7 is current (all 7 currencies required); the rest are
     discontinued/USD-only. ── */
  'tg-1': {
    name:'Tough TG-1 iHS', series:'Tough', mount:'mft', year:2012, discontinued:true,
    tagline:'Waterproof 4x Zoom, F2.0 Wide Aperture',
    productUrl:null,
    // No Commons product photo found -- only "Taken with" subcategories
    // (photos shot BY this camera, not OF it). Genuine gap.
    imageUrl:null,
    asin:null,
    prices:{USD:399},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_Tough_TG-1', tier:'T2', note:'Sensor, dimensions, weight (230g w/ battery+card), fixed 3.0" LCD, CIPA battery (350), WiFi/Bluetooth absent this generation (GPS present, no wireless transfer yet), 1080p video. Estimated street price $399.99 confirmed via a period DPReview/retailer citation, resolving task 1.1\'s original TBD. ibisStops and exact burst genuinely unconfirmed, left null/flagged rather than guessed.', date:'2026-09-13' } ],
    sensorMP:12, sensorType:'1/2.3" BSI CMOS', processor:'TruePic VI',
    width:112, height:67, depth:30, weight:230, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:null, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:3,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:350, usbCharging:false,
    lensType:'Fixed', lensSpec:'25-100mm f/2.0-4.9 (4x zoom)',
  },
  'tg-2': {
    name:'Tough TG-2 iHS', series:'Tough', mount:'mft', year:2013, discontinued:true,
    tagline:'Deeper Waterproofing, OLED Screen',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:379},
    specSources: [ { url:'https://www.cameralabs.com/olympus_stylus_tough_tg2_ihs/', tier:'T2', note:'Sensor, dimensions (111x66x29mm), weight (230g w/ battery+card), 610K-dot OLED screen, CIPA battery (350), 1080p video, $379.99 launch price (March 2013) all confirmed. Waterproofing extended to 15m/50ft (up from TG-1\'s ~12m). Burst rate and wireless connectivity flagged conservative (no confirmation found this session of WiFi reaching this specific generation -- it\'s confirmed by TG-3 the following year).', date:'2026-09-13' } ],
    sensorMP:12, sensorType:'1/2.3" BSI CMOS', processor:'TruePic VI',
    width:111, height:66, depth:29, weight:230, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:610, lcdType:'Fixed OLED',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:5,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:false,
    cardSlots:'1× SD', batteryLife:350, usbCharging:false,
    lensType:'Fixed', lensSpec:'25-100mm f/2.0-4.9 (4x zoom)',
  },
  'tg-3': {
    name:'Tough TG-3', series:'Tough', mount:'mft', year:2014, discontinued:true,
    tagline:'Series Flagship, Adds Built-In WiFi',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:349},
    specSources: [ { url:'https://www.olympus-global.com/en/news/2014a/nr140513tg3e.html', tier:'T1', note:'Olympus\'s own press release: sensor (16MP BSI-CMOS), dimensions (112x66x31mm), weight (247g w/ battery), 460K-dot LCD, $349.99 launch price (announced March 2014, on sale June), built-in WiFi confirmed as a new feature this generation. ibisStops and exact burst genuinely unconfirmed, flagged.', date:'2026-09-13' } ],
    sensorMP:16, sensorType:'1/2.3" BSI CMOS', processor:'TruePic VII',
    width:112, height:66, depth:31, weight:247, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:5,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Fixed', lensSpec:'25-100mm f/2.0-4.9 (4x zoom)',
  },
  'tg-4': {
    name:'Tough TG-4', series:'Tough', mount:'mft', year:2015, discontinued:true,
    tagline:'Adds RAW Capture to the Tough Line',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:379},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_Tough_TG-4', tier:'T2', note:'Sensor, dimensions (112x66x31mm, identical shell to tg-3), weight (247g w/ battery), 460K-dot LCD, LI-92B battery, $379 2015 US MSRP confirmed. Main change from TG-3 is RAW image recording. ibisStops and exact burst genuinely unconfirmed, flagged; WiFi carried over from tg-3 as a confirmed-shared-generation feature.', date:'2026-09-13' } ],
    sensorMP:16, sensorType:'1/2.3" BSI CMOS', processor:'TruePic VII',
    width:112, height:66, depth:31, weight:247, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:5,
    maxVideoRes:'1080p / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD', batteryLife:330, usbCharging:false,
    lensType:'Fixed', lensSpec:'25-100mm f/2.0-4.9 (4x zoom)',
  },
  'tg-5': {
    name:'Tough TG-5', series:'Tough', mount:'mft', year:2017, discontinued:true,
    tagline:'Adds 4K Video and a Field Sensor System',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/d/d9/Olympus_Tough!_TG-5.jpg',
    imageCredit:{author:"I99pema", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_Tough!_TG-5.jpg"},
    asin:null,
    prices:{USD:449},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_Tough_TG-5', tier:'T2', note:'Sensor (12MP, a resolution DECREASE from tg-4\'s 16MP, trading pixel count for larger photosites/better low-light -- a real, confirmed spec regression, not an error), dimensions (113x66x31.9mm), weight (250g w/ battery+card), CIPA battery (340, LI-92B), $449.99 estimated street price (May 2017 announcement). TruePic VIII processor and new Field Sensor System (GPS/depth/temperature) confirmed. 4K video and ~20fps burst are reasoned generation-appropriate additions, not independently re-confirmed this session.', date:'2026-09-13' } ],
    sensorMP:12, sensorType:'1/2.3" BSI CMOS', processor:'TruePic VIII',
    width:113, height:66, depth:31.9, weight:250, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:460, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:20,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD', batteryLife:340, usbCharging:false,
    lensType:'Fixed', lensSpec:'25-100mm f/2.0-4.9 (4x zoom)',
  },
  'tg-6': {
    name:'Tough TG-6', series:'Tough', mount:'mft', year:2019, discontinued:true,
    tagline:'Sharper Screen, Same Trusted Sensor',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/4/40/Olympus_Tough_TG-6_front_view.jpg',
    imageCredit:{author:"JayCubby", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0/", source:"https://commons.wikimedia.org/wiki/File:Olympus_Tough_TG-6_front_view.jpg"},
    asin:null,
    prices:{USD:449},
    specSources: [ { url:'https://en.wikipedia.org/wiki/Olympus_Tough_TG-6', tier:'T2', note:'Sensor (same 12MP as tg-5), dimensions (113x66x32mm), weight (253g w/ battery), 1.04M-dot LCD (a real step up from tg-5\'s 460K), $449 May 2019 launch price confirmed. Bluetooth and USB charging both left false/false -- TG-7\'s own official spec sheet explicitly introduces USB-C charging as new, implying TG-6 lacks it; no direct confirmation of Bluetooth on TG-6 was found (TG-7 is the first confirmed).', date:'2026-09-13' } ],
    sensorMP:12, sensorType:'1/2.3" BSI CMOS', processor:'TruePic VIII',
    width:113, height:66, depth:32, weight:253, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:20,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD', batteryLife:340, usbCharging:false,
    lensType:'Fixed', lensSpec:'25-100mm f/2.0-4.9 (4x zoom)',
  },
  'tg-7': {
    name:'Tough TG-7', series:'Tough', mount:'mft', year:2023, discontinued:false,
    tagline:'First Tough With Bluetooth and USB-C Charging',
    productUrl:'https://explore.omsystem.com/us/en/tg-7',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/8/88/Om_System_Tough_TG-7_by_Henry_Söderlund.jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0/", source:"https://commons.wikimedia.org/wiki/File:Om_System_Tough_TG-7_by_Henry_Söderlund.jpg"},
    asin:null,
    prices:{USD:549,AUD:699,EUR:519,GBP:449,JPY:54698,CAD:699,SGD:809},
    priceSource: { url:'https://explore.omsystem.com/us/en/tg-7', tier:'T1', note:'US $549 (Sept 2023 launch, confirmed unchanged), AU $699.00, EUR €519.00 (explore.omsystem.com/ie), GBP £449.00, CAD $699.99 -- all explore.omsystem.com direct. SGD $809.00 is Alan Photo\'s (authorized SG dealer) list price, before an active $649 promo -- same list-not-sale convention as every other entry. JPY ¥54,698 is a T4 kakaku.com aggregator LOWEST price, not a confirmed official RRP -- notably below the USD-equivalent of the other regions, the softest figure in this entry, flagged for a firmer source later.', date:'2026-09-13' },
    specSources: [ { url:'https://www.neocamera.com/camera/olympus/tg7', tier:'T2', note:'Sensor (12MP, unchanged from tg-5/tg-6), TruePic VIII, dimensions (113.9x65.8x32.7mm per a kakaku.com spec citation), weight (249g w/ battery+card), 1.04M-dot LCD, CIPA battery (330, LI-92B), 4K/30p video, WiFi+Bluetooth, and -- the headline change -- USB-C charging, all confirmed via OM System\'s own official spec sheet and independent review corroboration.', date:'2026-09-13' } ],
    sensorMP:12, sensorType:'1/2.3" BSI CMOS', processor:'TruePic VIII',
    width:113.9, height:65.8, depth:32.7, weight:249, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Fixed',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:null, maxBurst:20,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    liveND:null, hiResShot:null, proCapture:false, liveComposite:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD', batteryLife:330, usbCharging:true,
    lensType:'Fixed', lensSpec:'25-100mm f/2.0-4.9 (4x zoom)',
  },
};

const CAMERA_ORDER = [
  'om-1-ii', 'om-3', 'om-3-astro', 'om-5-ii', 'pen-om', 'om-1', 'om-5',
  'e-m1', 'e-m1-ii', 'e-m1x', 'e-m1-iii', 'e-m1-iii-astro',
  'e-m5', 'e-m5-ii', 'e-m5-iii', 'e-m10', 'e-m10-ii', 'e-m10-iii', 'e-m10-iv',
  'pen-f', 'e-p1', 'e-p2', 'e-p3', 'e-p5', 'e-p7',
  'e-pl1', 'e-pl2', 'e-pl3', 'e-pl5', 'e-pl6', 'e-pl7', 'e-pl8', 'e-pl9', 'e-pl10',
  'e-pm1', 'e-pm2',
  'tg-1', 'tg-2', 'tg-3', 'tg-4', 'tg-5', 'tg-6', 'tg-7',
];

const DROPDOWN_GROUPS = [
  { label: '── OM System (current) ──', ids: ['om-1-ii', 'om-3', 'om-3-astro', 'om-5-ii'] },
  { label: '── PEN (current) ──', ids: ['pen-om'] },
  { label: '── OM System (discontinued) ──', ids: ['om-1', 'om-5'] },
  { label: '── OM-D E-M1 (discontinued) ──', ids: ['e-m1', 'e-m1-ii', 'e-m1x', 'e-m1-iii', 'e-m1-iii-astro'] },
  { label: '── OM-D E-M5 (discontinued) ──', ids: ['e-m5', 'e-m5-ii', 'e-m5-iii'] },
  { label: '── OM-D E-M10 (discontinued) ──', ids: ['e-m10', 'e-m10-ii', 'e-m10-iii', 'e-m10-iv'] },
  { label: '── PEN-F & PEN (discontinued) ──', ids: ['pen-f', 'e-p1', 'e-p2', 'e-p3', 'e-p5', 'e-p7'] },
  { label: '── PEN Lite (discontinued) ──', ids: ['e-pl1', 'e-pl2', 'e-pl3', 'e-pl5', 'e-pl6', 'e-pl7', 'e-pl8', 'e-pl9', 'e-pl10'] },
  { label: '── PEN Mini (discontinued) ──', ids: ['e-pm1', 'e-pm2'] },
  { label: '── Tough ──', ids: ['tg-1', 'tg-2', 'tg-3', 'tg-4', 'tg-5', 'tg-6', 'tg-7'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE — first-party M.Zuiko + third-party Micro Four Thirds
// (Panasonic Lumix G/Leica DG, Sigma, Laowa, Voigtländer). Filled in
// task-5/7 batches. 11 M.Zuiko entries and 34 third-party entries port
// verbatim from panasonic/data.js — see shared-mount.test.js, which pins
// every shared id's optic fields and USD price across both files.
// ─────────────────────────────────────────────
const LENSES = {

  /* ── M.Zuiko PRO (ported verbatim from panasonic/data.js — re-verified
     unchanged in task 1.5; shared-mount.test.js pins this entry to agree
     with panasonic/data.js's copy on every optic field + prices.USD) ── */
  'omsystem-25mm-f12-pro': {
    name:'OM System M.Zuiko 25mm f/1.2 PRO', manufacturer:'OM System', line:'PRO', type:'Prime',
    mount:'mft', focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.2, minAperture:16, weight:410, length:87, diameter:70,
    filterThread:62, minFocusDist:30, maxMagnification:0.11,
    elements:19, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:false,
    imageUrl:'https://nala.explore.omsystem.com/media/catalog/product/2/5/25mm_f1.2_pro-om_-_tech.webp',
    imageSource: { url:'https://explore.omsystem.com/us/en/m-zuiko-ed-25mm-f1-2-pro', tier:'T1', note:'official OM System explore.omsystem.com product page; dimension diagram shows 87mm length / 70mm width / Ø62mm front diameter, matching the stored length:87 diameter:70 exactly', date:'2026-08-17' },
    asin:'B01LW4IFUI',
    prices:{USD:1599,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-25mm-f1-2-pro',
  },
  // Same reason as the extra cameras above -- >=4 distinct lenses needed for
  // the render-logic tests. All 3 already re-verified unchanged in task 1.5.
  'omsystem-12-40mm-f28-pro': {
    name:'OM System M.Zuiko 12-40mm f/2.8 PRO II', manufacturer:'OM System', line:'PRO', type:'Zoom',
    mount:'mft', focalLength:null, focalLengthMin:12, focalLengthMax:40, focalLengthEquiv:'24-80mm',
    maxAperture:2.8, minAperture:22, weight:382, length:84, diameter:70,
    filterThread:62, minFocusDist:20, maxMagnification:0.3,
    elements:14, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://nala.explore.omsystem.com/media/catalog/product/1/2/12-40mm_f2.8_pro_ii-om_-_tech.webp',
    imageSource: { url:'https://explore.omsystem.com/us/en/m-zuiko-ed-12-40mm-f2-8-pro-ii', tier:'T1', note:'official OM System explore.omsystem.com product page; dimension diagram shows 84mm length / 69.9mm width / Ø62mm front diameter, matching the stored length:84 diameter:70', date:'2026-08-17' },
    asin:'B09RQPZC7V',
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-12-40mm-f2-8-pro-ii',
  },
  'omsystem-45mm-f12-pro': {
    name:'OM System M.Zuiko 45mm f/1.2 PRO', manufacturer:'OM System', line:'PRO', type:'Prime',
    mount:'mft', focalLength:45, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:1.2, minAperture:16, weight:410, length:84.9, diameter:70,
    filterThread:62, minFocusDist:50, maxMagnification:0.1,
    elements:14, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:'https://nala.explore.omsystem.com/media/catalog/product/4/5/45mm_f1.2_pro-om_-_tech_1.webp',
    imageSource: { url:'https://explore.omsystem.com/us/en/m-zuiko-ed-45mm-f1-2-pro', tier:'T1', note:'official OM System explore.omsystem.com product page; dimension diagram shows 84.9mm length / 70mm width / Ø62mm front diameter, matching the stored length:84.9 diameter:70 exactly', date:'2026-08-17' },
    asin:'B0CHXWGF8C',
    prices:{USD:1599,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-45mm-f1-2-pro',
  },
  'omsystem-17mm-f18': {
    name:'OM System M.Zuiko 17mm f/1.8 II', manufacturer:'OM System', line:'Premium', type:'Prime',
    mount:'mft', focalLength:17, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'34mm',
    maxAperture:1.8, minAperture:22, weight:112, length:38, diameter:58,
    filterThread:46, minFocusDist:25, maxMagnification:0.08,
    elements:9, groups:6, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://nala.explore.omsystem.com/media/catalog/product/1/7/17mm_f1.8_ii-om_-_tech.webp',
    imageSource: { url:'https://explore.omsystem.com/us/en/m-zuiko-17mm-f1-8-ii', tier:'T1', note:'official OM System explore.omsystem.com product page, same asset-naming convention as this brand\'s other OM System PRO/Premium entries', date:'2026-09-06' },
    asin:'B0DVHT413D',
    prices:{USD:649,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-17mm-f1-8-ii',
  },
};

const LENS_DROPDOWN_GROUPS = [
  { label: '── M.Zuiko PRO ──', ids: ['omsystem-25mm-f12-pro', 'omsystem-12-40mm-f28-pro', 'omsystem-45mm-f12-pro'] },
  { label: '── M.Zuiko Premium ──', ids: ['omsystem-17mm-f18'] },
];

return { BRAND_CONFIG, SERIES_COLORS, CAMERAS, CAMERA_ORDER,
         DROPDOWN_GROUPS, LENSES, LENS_DROPDOWN_GROUPS, REGISTERED_BRANDS };
})();
