#!/usr/bin/env node
// ─────────────────────────────────────────────
// SEO GENERATOR
//
// Regenerates every artifact that embeds the site's base URL or
// crawlable content, from brand data + site-config.js:
//
//   1. <!-- seo:begin/end --> head blocks in each <brand>/index.html
//      and the root index.html (description, canonical, OG/Twitter)
//   2. Curated static "X vs Y" pages at <brand>/vs/<a>-vs-<b>.html
//   3. sitemap.xml and robots.txt at the root
//
// Output is committed; tests/data/seo.test.js regenerates in memory
// and fails if the committed files are stale. Run after any change to
// site-config.js or a brand's cameras:
//
//   node scripts/generate-seo.js
//
// Pairing rules (deliberately curated — all-pairs would be thin
// content): consecutive same-series generations where the newer body
// is still current, plus each current body's two nearest USD-price
// neighbours.
// ─────────────────────────────────────────────
const fs = require('fs');
const path = require('path');
const { loadBrand, brandDirs, ROOT } = require('../tests/helpers/load-brand');

const SEO_BEGIN = '<!-- seo:begin (generated by scripts/generate-seo.js — do not edit by hand) -->';
const SEO_END = '<!-- seo:end -->';
const SEO_BODY_BEGIN = '<!-- seo:body:begin (generated by scripts/generate-seo.js — do not edit by hand) -->';
const SEO_BODY_END = '<!-- seo:body:end -->';

function siteConfig() {
  const src = fs.readFileSync(path.join(ROOT, 'site-config.js'), 'utf8');
  return new Function(`${src}; return SITE_CONFIG;`)();
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ─── Pairing rules ───────────────────────────
// The data's `series` field is a broad family (e.g. Sony "Alpha
// (Full-frame)" spans a7/a7R/a9/a1), so successor detection derives the
// *model line* from the slug structure instead.
const ROMAN = { i: 1, ii: 2, iii: 3, iv: 4, v: 5, vi: 6, vii: 7, viii: 8, ix: 9, x: 10 };

// Scheme A — roman-numeral generations of one line:
// a7r-v → a7r gen 5; x100vi → x100 gen 6; eos-r5-ii → eos-r5 gen 2.
function romanLine(slug) {
  let m = slug.match(/^(.+)-([ivx]+)$/);
  if (m && ROMAN[m[2]]) return { line: m[1], gen: ROMAN[m[2]] };
  m = slug.match(/^(.+\d)([ivx]+)$/);
  if (m && ROMAN[m[2]]) return { line: m[1], gen: ROMAN[m[2]] };
  return { line: slug, gen: 1 };
}

// Scheme B — numbered generations: x-t5 → line "x-t"/1-digit, gen 5.
// The digit count separates product tiers that share a stem
// (x-t5 flagship vs x-t50 mid-range vs x-t200 entry).
function numberLine(slug) {
  const m = slug.match(/^(.+?)(\d+)$/);
  return m ? { line: `${m[1]}#${m[2].length}`, gen: parseInt(m[2], 10) } : null;
}

function curatedPairs(cams) {
  const seen = new Set();
  const pairs = [];
  const usd = id => (cams[id].prices && cams[id].prices.USD) || 0;
  // Canonical order within a pair: newer first, then pricier, then slug.
  const add = (a, b) => {
    if (a === b) return;
    const [ca, cb] = [cams[a], cams[b]];
    if (cb.year > ca.year || (cb.year === ca.year && usd(b) > usd(a)) ||
        (cb.year === ca.year && usd(b) === usd(a) && b < a)) [a, b] = [b, a];
    const key = `${a}|${b}`;
    if (!seen.has(key)) { seen.add(key); pairs.push([a, b]); }
  };
  // Successors launch near their predecessor's RRP; a big gap means the
  // "line" grouping actually caught two different tiers (Z9 vs Z5).
  const priceClose = (a, b) =>
    usd(a) > 0 && usd(b) > 0 && Math.abs(usd(a) - usd(b)) / Math.max(usd(a), usd(b)) <= 0.4;

  // Rule 1: consecutive generations within a model line, newer body
  // still current. Scheme A is structurally unambiguous; scheme B adds
  // the price gate because a shared stem can still span tiers.
  const addSuccessors = (grouper, gated) => {
    const lines = {};
    for (const id of Object.keys(cams)) {
      const r = grouper(id);
      if (r) (lines[r.line] ??= []).push([id, r.gen]);
    }
    for (const list of Object.values(lines)) {
      list.sort((p, q) => q[1] - p[1] || cams[q[0]].year - cams[p[0]].year);
      for (let i = 0; i + 1 < list.length; i++) {
        const [newer, older] = [list[i][0], list[i + 1][0]];
        if (cams[newer].discontinued) continue;
        if (gated && !priceClose(newer, older)) continue;
        add(newer, older);
      }
    }
  };
  addSuccessors(romanLine, false);
  addSuccessors(numberLine, true);

  // Rule 2: current bodies vs their two nearest USD-price neighbours.
  const current = Object.keys(cams)
    .filter(id => !cams[id].discontinued && usd(id) > 0)
    .sort((a, b) => usd(b) - usd(a) || (a < b ? -1 : 1));
  for (let i = 0; i < current.length; i++) {
    for (let k = 1; k <= 2 && i + k < current.length; k++) add(current[i], current[i + k]);
  }
  return pairs;
}

// ─── vs-page ─────────────────────────────────
const VS_ROWS = [
  ['Price (USD RRP)', c => c.prices.USD == null ? null : `$${c.prices.USD.toLocaleString('en-US')}`],
  ['Announced', c => c.year],
  ['Sensor', c => `${c.sensorMP} MP ${c.sensorType}`],
  ['Processor', c => c.processor],
  ['In-body stabilization', c => c.ibis ? `Yes${c.ibisStops ? ` (${c.ibisStops} stops)` : ''}` : 'No'],
  ['Max burst', c => c.maxBurst == null ? null : `${c.maxBurst} fps`],
  ['Max video', c => c.maxVideoRes],
  ['Weather sealed', c => c.weatherSealed ? 'Yes' : 'No'],
  ['Weight', c => c.weight == null ? null : `${c.weight} g`],
  ['Battery (CIPA)', c => c.batteryLife == null ? null : `${c.batteryLife} shots`],
  ['Card slots', c => c.cardSlots],
  ['Lens mount', c => c.lensType],
];

// Complements engine.css (loaded alongside): header/hero/footer/tokens come
// from there, this styles the vs-specific CTA, spec-table card and related list.
const VS_CSS = `
  .header-back { font-size: 13px; color: rgba(255,255,255,.65); text-decoration: none; white-space: nowrap;
                 overflow: hidden; text-overflow: ellipsis; }
  .header-back:hover { color: #fff; }

  .vs-main { max-width: 840px; margin: 0 auto; padding: 8px 20px 40px; }

  .vs-products { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 24px 0 8px; }
  .vs-product { background: var(--white); border: 1px solid var(--border); border-radius: var(--radius);
                box-shadow: var(--shadow); padding: 18px; display: flex; flex-direction: column;
                align-items: center; gap: 10px; text-align: center; }
  .vs-photo { width: 100%; height: 160px; display: flex; align-items: center; justify-content: center; }
  .vs-img { max-width: 100%; max-height: 160px; object-fit: contain; }
  .vs-ph { width: 100%; height: 100%; border-radius: 8px; align-items: center; justify-content: center;
           font-weight: 700; font-size: 14px; padding: 10px; text-align: center; }
  .vs-pname { font-weight: 700; font-size: 16px; color: var(--gray-4); }
  .vs-pprice { font-weight: 700; font-size: 18px; color: var(--gray-4); }
  .vs-plinks { display: flex; gap: 8px; flex-wrap: wrap; justify-content: center; margin-top: 2px; }
  .vs-view { font-size: 12px; color: var(--accent-color); text-decoration: none; border: 1px solid var(--accent-color);
             padding: 5px 14px; border-radius: 999px; transition: all .15s; }
  .vs-view:hover { background: var(--accent-color); color: #fff; }
  .vs-view.na { color: var(--gray-3); border-color: var(--gray-3); }
  .vs-buy { font-size: 12px; color: #e07b00; text-decoration: none; border: 1px solid #e07b00;
            padding: 5px 14px; border-radius: 999px; transition: all .15s; }
  .vs-buy:hover { background: #e07b00; color: #fff; }
  .vs-cta { display: inline-flex; align-items: center; gap: 9px; background: var(--gray-4); color: #fff;
            text-decoration: none; padding: 12px 22px; border-radius: 999px; font-weight: 600; font-size: 14px;
            margin: 24px 0 20px; box-shadow: var(--shadow); transition: transform .12s ease, box-shadow .12s ease; }
  .vs-cta:hover { transform: translateY(-1px); box-shadow: 0 6px 18px rgba(0,0,0,.18); }
  .vs-cta .play { color: var(--accent-color); font-size: 11px; }

  .vs-card { background: var(--white); border: 1px solid var(--border); border-radius: var(--radius);
             box-shadow: var(--shadow); overflow: hidden; }
  .vs-card table { border-collapse: collapse; width: 100%; }
  .vs-card thead th { background: var(--gray-4); color: #fff; font-weight: 600; font-size: 14px;
                      padding: 14px 12px; text-align: center; }
  .vs-card thead th:first-child { text-align: left; font-weight: 500; color: rgba(255,255,255,.55); font-size: 12px; }
  .vs-card th[scope="row"] { text-align: left; font-weight: 500; color: var(--gray-3); font-size: 12px;
                             padding: 11px 16px; width: 34%; }
  .vs-card td { text-align: center; font-size: 13px; color: var(--gray-4); padding: 11px 12px; font-weight: 500; }
  .vs-card tbody tr { border-top: 1px solid var(--border); }
  .vs-card tbody tr:nth-child(odd) { background: #fafafa; }

  .vs-note { color: var(--gray-3); font-size: 12px; margin: 16px 2px 0; }

  .vs-related { margin-top: 36px; }
  .vs-related h2 { font-size: 15px; text-transform: uppercase; letter-spacing: .06em; color: var(--gray-3);
                   margin-bottom: 14px; font-weight: 700; }
  .vs-related ul { list-style: none; display: grid; gap: 8px 24px;
                   grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); }
  .vs-related a { color: var(--gray-4); text-decoration: none; font-size: 14px; display: inline-block;
                  padding: 3px 0; border-bottom: 1px solid transparent; }
  .vs-related a:hover { color: var(--accent-color); border-bottom-color: var(--accent-color); }
`.trim();

function productLd(brandName, cam) {
  const p = { '@type': 'Product', name: `${brandName} ${cam.name}`, brand: { '@type': 'Brand', name: brandName } };
  if (cam.imageUrl) p.image = cam.imageUrl;
  if (cam.prices && cam.prices.USD != null) {
    p.offers = { '@type': 'Offer', priceCurrency: 'USD', price: cam.prices.USD };
  }
  return p;
}

// Other curated pairs that share a camera with (aId, bId), so vs-pages form a
// connected cluster rather than isolated leaves. Deterministic: newest pair
// first, then priciest, then slug — capped so link equity stays focused.
function relatedPairs(allPairs, cams, aId, bId) {
  const self = `${aId}|${bId}`;
  const usd = id => (cams[id] && cams[id].prices && cams[id].prices.USD) || 0;
  const yr = id => (cams[id] && cams[id].year) || 0;
  return allPairs
    .filter(([x, y]) => `${x}|${y}` !== self && (x === aId || x === bId || y === aId || y === bId))
    .sort((p, q) => {
      const pn = Math.max(yr(p[0]), yr(p[1])), qn = Math.max(yr(q[0]), yr(q[1]));
      if (pn !== qn) return qn - pn;
      const pu = Math.max(usd(p[0]), usd(p[1])), qu = Math.max(usd(q[0]), usd(q[1]));
      if (pu !== qu) return qu - pu;
      return `${p[0]}|${p[1]}` < `${q[0]}|${q[1]}` ? -1 : 1;
    })
    .slice(0, 6);
}

// Static vs-pages default to the USD marketplace (amazon.com); the interactive
// tool offers all seven currencies. ASIN → the product page, else a search that
// always resolves. Mirrors engine.js amazonBuyUrl (no affiliate tag yet).
function amazonBuyUrlUSD(brandName, cam) {
  if (cam.asin) return `https://www.amazon.com/dp/${cam.asin}`;
  return `https://www.amazon.com/s?k=${encodeURIComponent(`${brandName} ${cam.name}`)}`;
}

// Product card: photo (with placeholder fallback), USD price, View + Buy.
// `displayName` optionally overrides the shown name (cross-brand pages
// prefix the brand so two same-named models can't be confused).
function productCardHTML(data, brandName, c, displayName) {
  const usdPrice = (c.prices && c.prices.USD != null) ? `$${c.prices.USD.toLocaleString('en-US')}` : '—';
  const shown = displayName || c.name;
  const sc = (data.SERIES_COLORS && data.SERIES_COLORS[c.series]) || { bg: '#222', text: '#ccc' };
  const phStyle = `background:${esc(sc.bg)};color:${esc(sc.text)}`;
  const photo = c.imageUrl
    ? `<img src="${esc(c.imageUrl)}" alt="${esc(brandName)} ${esc(c.name)}" class="vs-img" onerror="this.style.display='none';this.parentNode.querySelector('.vs-ph').style.display='flex'">
          <div class="vs-ph" style="display:none;${phStyle}">${esc(c.name)}</div>`
    : `<div class="vs-ph" style="${phStyle}">${esc(c.name)}</div>`;
  const viewURL = (c.productUrl && !c.productUrl.endsWith('/cameras/')) ? c.productUrl : null;
  const viewBtn = viewURL
    ? `<a class="vs-view" href="${esc(viewURL)}" target="_blank" rel="noopener">View &#8599;</a>`
    : `<span class="vs-view na">Discontinued</span>`;
  const buyBtn = `<a class="vs-buy" href="${esc(amazonBuyUrlUSD(brandName, c))}" target="_blank" rel="noopener">Buy &#8599;</a>`;
  return `        <div class="vs-product">
          <div class="vs-photo">${photo}</div>
          <div class="vs-pname">${esc(shown)}</div>
          <div class="vs-pprice">${usdPrice}</div>
          <div class="vs-plinks">${viewBtn}${buyBtn}</div>
        </div>`;
}

function vsPageHTML(brand, data, site, aId, bId, allPairs) {
  const cams = data.CAMERAS;
  const brandName = data.BRAND_CONFIG.name;
  const accent = data.BRAND_CONFIG.accentColor;
  const heroDark = data.BRAND_CONFIG.heroDark || '#2d0000';
  const [a, b] = [cams[aId], cams[bId]];
  const title = `${brandName} ${a.name} vs ${b.name}: Spec Comparison`;
  const desc = `Compare the ${brandName} ${a.name} (${a.year}) and ${b.name} (${b.year}) side by side — price, sensor, stabilization, video, weight and more.`;
  const url = `${site.baseUrl}/${brand}/vs/${aId}-vs-${bId}.html`;
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: title,
    itemListElement: [a, b].map((c, i) => ({ '@type': 'ListItem', position: i + 1, item: productLd(brandName, c) })),
  };
  const rows = VS_ROWS.map(([label, fn]) => {
    const [va, vb] = [fn(a), fn(b)];
    return `      <tr><th scope="row">${esc(label)}</th><td>${va == null ? '—' : esc(va)}</td><td>${vb == null ? '—' : esc(vb)}</td></tr>`;
  }).join('\n');

  const productsHTML = `      <div class="vs-products">
${productCardHTML(data, brandName, a)}
${productCardHTML(data, brandName, b)}
      </div>`;

  const related = relatedPairs(allPairs || [], cams, aId, bId);
  const relatedHTML = related.length ? `
    <section class="vs-related">
      <h2>Related comparisons</h2>
      <ul>
${related.map(([x, y]) =>
    `        <li><a href="${x}-vs-${y}.html">${esc(brandName)} ${esc(cams[x].name)} vs ${esc(cams[y].name)}</a></li>`).join('\n')}
      </ul>
    </section>` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="${esc(site.siteName)}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:url" content="${url}">
  <meta name="twitter:card" content="summary">
  <script type="application/ld+json">${JSON.stringify(ld)}</script>
  <!-- Umami analytics — temporarily disabled, kept for re-enabling.
  <script defer src="https://cloud.umami.is/script.js" data-website-id="365e9ee6-1fb5-4a0d-9c74-f6255522a196"></script> -->
  <script data-goatcounter="https://esusatyo.goatcounter.com/count" defer src="https://gc.zgo.at/count.js"></script>
  <link rel="stylesheet" href="../../engine.css">
  <style>
    :root { --accent-color: ${esc(accent)}; --hero-dark: ${esc(heroDark)}; }
    ${VS_CSS}
  </style>
</head>
<body>
  <header id="site-header">
    <div class="header-brand">
      <span class="brand-logo">Compare<span class="accent">CameraSpecs</span></span>
      <span class="header-sep">|</span>
      <a class="header-back" href="../index.html">All ${esc(brandName)} cameras</a>
    </div>
  </header>
  <div class="page-hero">
    <div class="hero-eyebrow">${esc(brandName)} &middot; Head-to-head</div>
    <h1 class="hero-title">${esc(a.name)} vs ${esc(b.name)}</h1>
    <p class="hero-subtitle">${esc(brandName)} ${esc(a.name)} (${a.year}) and ${esc(b.name)} (${b.year}) compared side by side.</p>
  </div>
  <main class="vs-main">
${productsHTML}
    <a class="vs-cta" href="../index.html#cameras=${aId},${bId}"><span class="play">&#9654;</span> Compare these interactively</a>
    <div class="vs-card">
      <table>
        <thead>
          <tr><th scope="col">Spec</th><th scope="col">${esc(a.name)}</th><th scope="col">${esc(b.name)}</th></tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>
    </div>
    <p class="vs-note">Prices shown are approximate manufacturer list prices (RRP) in USD and may differ from live retail prices.</p>${relatedHTML}
  </main>
  <footer>
    <p>${esc(site.siteName)} &mdash; For informational purposes only.</p>
    <p>Prices shown are approximate manufacturer list prices (RRP) and may differ from live retail prices. Use the Buy link for current pricing.</p>
    <p>Specs sourced from manufacturer documentation.</p>
    <p>Specs &amp; prices last verified: ${esc(site.dataVerified)}</p>
    <div id="affiliate-disclosure"></div>
    <p>
      <a href="../index.html">All ${esc(brandName)} cameras &amp; lenses</a>
      &middot;
      <a href="../../about.html">About</a>
      &middot;
      <a href="../../privacy.html">Privacy</a>
      &middot;
      Created by <a href="https://esusatyo.net" target="_blank" rel="noopener">Enrico Susatyo</a>
      &middot;
      Assisted by <a href="https://claude.ai" target="_blank" rel="noopener">Claude</a>
    </p>
  </footer>
</body>
</html>
`;
}

// ─── Cross-brand vs-pages ────────────────────
// Hand-curated matchups spanning brands (never auto-cartesian — that
// would be ~4,000 thin pages). Selection rationale: real head-to-head
// buying decisions, grouped by segment — flagship speed, high-res,
// mid-range full-frame hybrids (the volume segment), compact/entry
// full-frame, video-first bodies, enthusiast APS-C, retro/street, and
// vlogging/entry. Pairs are price- or segment-peers; the generator
// canonicalizes order (newer first, then pricier) and fails hard on
// any entry that doesn't resolve to a real brand/slug.
const CROSS_BRAND_MATCHUPS = [
  // Flagship speed & pro sports
  [['sony', 'a9-iii'], ['canon', 'eos-r1']],
  [['canon', 'eos-r1'], ['nikon', 'z9']],
  [['sony', 'a1-ii'], ['nikon', 'z9']],
  [['sony', 'a1-ii'], ['canon', 'eos-r1']],
  [['sony', 'a1-ii'], ['canon', 'eos-r5-ii']],
  // High-resolution full-frame
  [['sony', 'a7r-v'], ['canon', 'eos-r5-ii']],
  [['sony', 'a7r-v'], ['nikon', 'z8']],
  [['sony', 'a7r-vi'], ['canon', 'eos-r5-ii']],
  [['sony', 'a7r-vi'], ['nikon', 'z8']],
  [['nikon', 'z8'], ['canon', 'eos-r5-ii']],
  [['panasonic', 's1r-ii'], ['sony', 'a7r-v']],
  [['panasonic', 's1r-ii'], ['nikon', 'z8']],
  [['panasonic', 's1r-ii'], ['canon', 'eos-r5-ii']],
  [['sony', 'a7cr'], ['panasonic', 's1r-ii']],
  // Mid-range full-frame hybrids
  [['sony', 'a7-iv'], ['canon', 'eos-r6-ii']],
  [['sony', 'a7-v'], ['canon', 'eos-r6-iii']],
  [['sony', 'a7-v'], ['nikon', 'z6-iii']],
  [['canon', 'eos-r6-iii'], ['nikon', 'z6-iii']],
  [['sony', 'a7-iv'], ['nikon', 'z6-iii']],
  [['sony', 'a7-iv'], ['panasonic', 's5-ii']],
  [['canon', 'eos-r6-ii'], ['panasonic', 's5-ii']],
  [['nikon', 'z6-iii'], ['panasonic', 's5-ii']],
  [['sony', 'a7-v'], ['panasonic', 's1-ii']],
  [['canon', 'eos-r6-v'], ['sony', 'a7-v']],
  [['canon', 'eos-r6-v'], ['nikon', 'z6-iii']],
  // Compact & entry full-frame
  [['canon', 'eos-r8'], ['nikon', 'z5-ii']],
  [['sony', 'a7c-ii'], ['nikon', 'z5-ii']],
  [['sony', 'a7c-ii'], ['canon', 'eos-r8']],
  [['sony', 'a7c-ii'], ['panasonic', 's5-ii']],
  [['panasonic', 's9'], ['sony', 'a7c-ii']],
  [['panasonic', 's9'], ['canon', 'eos-r8']],
  [['nikon', 'z5-ii'], ['panasonic', 's5-ii']],
  // Video-first bodies
  [['sony', 'a7s-iii'], ['panasonic', 's1h']],
  [['sony', 'fx3'], ['panasonic', 's1h']],
  [['sony', 'fx3'], ['canon', 'eos-r5c']],
  [['sony', 'zv-e1'], ['panasonic', 's9']],
  [['nikon', 'zr'], ['sony', 'zv-e1']],
  [['nikon', 'zr'], ['panasonic', 's5-iix']],
  [['panasonic', 'gh7'], ['sony', 'fx30']],
  [['fujifilm', 'x-h2s'], ['sony', 'fx30']],
  [['fujifilm', 'x-h2s'], ['panasonic', 'gh7']],
  // Enthusiast APS-C (and APS-C vs full-frame crossovers)
  [['fujifilm', 'x-t5'], ['sony', 'a7-iv']],
  [['fujifilm', 'x-t5'], ['sony', 'a6700']],
  [['fujifilm', 'x-t5'], ['canon', 'eos-r7']],
  [['fujifilm', 'x-h2'], ['canon', 'eos-r7']],
  [['fujifilm', 'x-h2'], ['sony', 'a7-iv']],
  [['fujifilm', 'x-h2s'], ['canon', 'eos-r7']],
  [['sony', 'a6700'], ['canon', 'eos-r7']],
  [['sony', 'a6700'], ['nikon', 'z50-ii']],
  [['canon', 'eos-r7'], ['nikon', 'z50-ii']],
  [['canon', 'eos-r7'], ['panasonic', 'g9-ii']],
  [['fujifilm', 'x-t50'], ['sony', 'a6700']],
  [['fujifilm', 'x-s20'], ['sony', 'a6700']],
  [['fujifilm', 'x-s20'], ['canon', 'eos-r10']],
  [['sony', 'a6400'], ['canon', 'eos-r10']],
  [['nikon', 'z50-ii'], ['canon', 'eos-r10']],
  [['fujifilm', 'x-t30ii'], ['sony', 'a6400']],
  // Retro & street
  [['fujifilm', 'x-t5'], ['nikon', 'zf']],
  [['fujifilm', 'x100vi'], ['nikon', 'zf']],
  [['fujifilm', 'x100vi'], ['sony', 'a6700']],
  [['fujifilm', 'x-e5'], ['nikon', 'zf']],
  [['fujifilm', 'x-t50'], ['nikon', 'zfc']],
  [['panasonic', 'l10'], ['fujifilm', 'x100vi']],
  // Vlogging & entry
  [['fujifilm', 'x-m5'], ['sony', 'zv-e10-ii']],
  [['sony', 'zv-e10-ii'], ['canon', 'eos-r50v']],
  [['sony', 'zv-e10-ii'], ['nikon', 'z30']],
  [['canon', 'eos-r50v'], ['nikon', 'z30']],
  [['fujifilm', 'x-m5'], ['canon', 'eos-r50']],
  [['panasonic', 'g100d'], ['sony', 'zv-e10-ii']],
  [['panasonic', 'g100d'], ['nikon', 'z30']],
];

// Resolve, validate and canonicalize the curated matchups against the
// loaded brand data. Fails hard (throw, no partial output) on a typo,
// a same-brand pair, or a duplicate.
function resolveMatchups(brandData, matchups = CROSS_BRAND_MATCHUPS) {
  const seen = new Set();
  return matchups.map(entry => {
    const sides = entry.map(([brand, slug]) => {
      const data = brandData[brand];
      if (!data) throw new Error(`CROSS_BRAND_MATCHUPS: unknown brand '${brand}' in ${JSON.stringify(entry)}`);
      const cam = data.CAMERAS[slug];
      if (!cam) throw new Error(`CROSS_BRAND_MATCHUPS: unknown camera '${brand}:${slug}' in ${JSON.stringify(entry)}`);
      return { brand, slug, data, cam, brandName: data.BRAND_CONFIG.name };
    });
    if (sides[0].brand === sides[1].brand) {
      throw new Error(`CROSS_BRAND_MATCHUPS: same-brand pair ${JSON.stringify(entry)} — belongs in the per-brand curated set`);
    }
    // Canonical order: newer first, then pricier, then name — matches
    // the per-brand pairing convention.
    const usd = s => (s.cam.prices && s.cam.prices.USD) || 0;
    let [a, b] = sides;
    if (b.cam.year > a.cam.year || (b.cam.year === a.cam.year && usd(b) > usd(a))) [a, b] = [b, a];
    const key = [`${a.brand}:${a.slug}`, `${b.brand}:${b.slug}`].sort().join('|');
    if (seen.has(key)) throw new Error(`CROSS_BRAND_MATCHUPS: duplicate pair ${JSON.stringify(entry)}`);
    seen.add(key);
    return { a, b, file: `vs/${a.brand}-${a.slug}-vs-${b.brand}-${b.slug}.html` };
  });
}

const crossTitle = m => `${m.a.brandName} ${m.a.cam.name} vs ${m.b.brandName} ${m.b.cam.name}`;

// Sibling cross-brand pages sharing a camera with this one (capped),
// so the root vs/ cluster interlinks instead of leafing out.
function crossRelated(all, m) {
  const shares = (x, s) => (x.a.brand === s.brand && x.a.slug === s.slug) || (x.b.brand === s.brand && x.b.slug === s.slug);
  return all
    .filter(x => x.file !== m.file && (shares(x, m.a) || shares(x, m.b)))
    .sort((p, q) => {
      const yr = x => Math.max(x.a.cam.year, x.b.cam.year);
      if (yr(p) !== yr(q)) return yr(q) - yr(p);
      return p.file < q.file ? -1 : 1;
    })
    .slice(0, 6);
}

function crossVsPageHTML(site, m, all) {
  const { a, b } = m;
  const title = `${crossTitle(m)}: Spec Comparison`;
  const desc = `Compare the ${a.brandName} ${a.cam.name} (${a.cam.year}) and ${b.brandName} ${b.cam.name} (${b.cam.year}) side by side — price, sensor, stabilization, video, weight and more.`;
  const url = `${site.baseUrl}/${m.file}`;
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: title,
    itemListElement: [a, b].map((s, i) => ({ '@type': 'ListItem', position: i + 1, item: productLd(s.brandName, s.cam) })),
  };
  const rows = VS_ROWS.map(([label, fn]) => {
    const [va, vb] = [fn(a.cam), fn(b.cam)];
    return `      <tr><th scope="row">${esc(label)}</th><td>${va == null ? '—' : esc(va)}</td><td>${vb == null ? '—' : esc(vb)}</td></tr>`;
  }).join('\n');
  const fullName = s => `${s.brandName} ${s.cam.name}`;
  const compareHash = `#cameras=${a.brand}:${a.slug},${b.brand}:${b.slug}`;
  const related = crossRelated(all, m);
  const relatedHTML = related.length ? `
    <section class="vs-related">
      <h2>Related comparisons</h2>
      <ul>
${related.map(x => `        <li><a href="${path.basename(x.file)}">${esc(crossTitle(x))}</a></li>`).join('\n')}
      </ul>
    </section>` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="${esc(site.siteName)}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:url" content="${url}">
  <meta name="twitter:card" content="summary">
  <script type="application/ld+json">${JSON.stringify(ld)}</script>
  <!-- Umami analytics — temporarily disabled, kept for re-enabling.
  <script defer src="https://cloud.umami.is/script.js" data-website-id="365e9ee6-1fb5-4a0d-9c74-f6255522a196"></script> -->
  <script data-goatcounter="https://esusatyo.goatcounter.com/count" defer src="https://gc.zgo.at/count.js"></script>
  <link rel="stylesheet" href="../engine.css">
  <style>
    :root { --accent-color: #0071e3; --hero-dark: #26262b; }
    ${VS_CSS}
  </style>
</head>
<body>
  <header id="site-header">
    <div class="header-brand">
      <span class="brand-logo">Compare<span class="accent">CameraSpecs</span></span>
      <span class="header-sep">|</span>
      <a class="header-back" href="../compare/">Cross-brand compare</a>
    </div>
  </header>
  <div class="page-hero">
    <div class="hero-eyebrow">${esc(a.brandName)} vs ${esc(b.brandName)} &middot; Head-to-head</div>
    <h1 class="hero-title">${esc(fullName(a))} vs ${esc(fullName(b))}</h1>
    <p class="hero-subtitle">${esc(fullName(a))} (${a.cam.year}) and ${esc(fullName(b))} (${b.cam.year}) compared side by side.</p>
  </div>
  <main class="vs-main">
      <div class="vs-products">
${productCardHTML(a.data, a.brandName, a.cam, fullName(a))}
${productCardHTML(b.data, b.brandName, b.cam, fullName(b))}
      </div>
    <a class="vs-cta" href="../compare/${compareHash}"><span class="play">&#9654;</span> Compare these interactively</a>
    <div class="vs-card">
      <table>
        <thead>
          <tr><th scope="col">Spec</th><th scope="col">${esc(fullName(a))}</th><th scope="col">${esc(fullName(b))}</th></tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>
    </div>
    <p class="vs-note">Prices shown are approximate manufacturer list prices (RRP) in USD and may differ from live retail prices.</p>${relatedHTML}
  </main>
  <footer>
    <p>${esc(site.siteName)} &mdash; For informational purposes only.</p>
    <p>Prices shown are approximate manufacturer list prices (RRP) and may differ from live retail prices. Use the Buy link for current pricing.</p>
    <p>Specs sourced from manufacturer documentation.</p>
    <p>Specs &amp; prices last verified: ${esc(site.dataVerified)}</p>
    <div id="affiliate-disclosure"></div>
    <p>
      <a href="../compare/">Cross-brand compare</a>
      &middot;
      <a href="../${a.brand}/index.html">All ${esc(a.brandName)} cameras</a>
      &middot;
      <a href="../${b.brand}/index.html">All ${esc(b.brandName)} cameras</a>
      &middot;
      <a href="../about.html">About</a>
      &middot;
      <a href="../privacy.html">Privacy</a>
      &middot;
      Created by <a href="https://esusatyo.net" target="_blank" rel="noopener">Enrico Susatyo</a>
      &middot;
      Assisted by <a href="https://claude.ai" target="_blank" rel="noopener">Claude</a>
    </p>
  </footer>
</body>
</html>
`;
}

// ─── Compare-page blocks ─────────────────────
function compareHeadBlock(site, brandNames, nCams) {
  return metaBlock(
    site,
    `${site.baseUrl}/compare/`,
    'Compare Cameras Across Brands',
    `Compare 2–4 of ${nCams} cameras from ${brandNames.join(', ')} side by side — specs, prices and buy links in 7 currencies.`
  );
}

// Crawlable block for compare/index.html linking every cross-brand
// vs-page, so none of them is an orphan (mirrors the brand pages).
function compareBodyBlock(matchups) {
  const items = matchups.map(m =>
    `      <li><a href="../${m.file}">${esc(crossTitle(m))}</a></li>`).join('\n');
  return `${SEO_BODY_BEGIN}
  <section class="seo-links" aria-label="Popular cross-brand comparisons">
    <h2>Popular cross-brand camera comparisons</h2>
    <p>Pick any 2–4 cameras from Canon, Fujifilm, Nikon, Panasonic and Sony and compare them side by side. Popular head-to-head matchups across brands:</p>
    <ul>
${items}
    </ul>
  </section>
  ${SEO_BODY_END}`;
}

// ─── Head blocks ─────────────────────────────
function metaBlock(site, url, title, desc) {
  return `${SEO_BEGIN}
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="${esc(site.siteName)}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:url" content="${url}">
  <meta name="twitter:card" content="summary">
  ${SEO_END}`;
}

function brandHeadBlock(brand, data, site) {
  const name = data.BRAND_CONFIG.name;
  const nCams = Object.keys(data.CAMERAS).length;
  const nLenses = Object.keys(data.LENSES).length;
  return metaBlock(
    site,
    `${site.baseUrl}/${brand}/`,
    `${name} Camera & Lens Comparison`,
    `Compare ${nCams} ${name} cameras and ${nLenses} lenses side by side — price, sensor, autofocus, stabilization and video, in 7 currencies.`
  );
}

// about.html became a generated artifact once it started carrying the image
// credits, so it needs its canonical from site-config like every other page
// rather than a hardcoded URL.
function aboutHeadBlock(site) {
  return metaBlock(
    site,
    `${site.baseUrl}/about.html`,
    `About — ${site.siteName}`,
    `What ${site.siteName} is, how the spec and price data is sourced and verified, image credits, and who built it.`
  );
}

function rootHeadBlock(site, brandNames) {
  return metaBlock(
    site,
    `${site.baseUrl}/`,
    `${site.siteName} — Camera & Lens Comparison`,
    `Side-by-side camera and lens comparison for ${brandNames.join(', ')} — specs, prices and buy links in 7 currencies.`
  );
}

// Replace the content between a begin/end marker pair, preserving everything
// outside it. Refuses to write when either marker is missing, so a page that
// lost its markers fails loudly instead of silently dropping generated content.
// Crawlable block appended to each brand page, below the interactive tool.
// Links every curated vs-page for the brand, so no vs-page is orphaned: each
// is reachable from its brand page even before cross-linking.
function brandBodyBlock(brand, data, site, pairs) {
  const name = data.BRAND_CONFIG.name;
  const cams = data.CAMERAS;
  const nCams = Object.keys(cams).length;
  const nLenses = Object.keys(data.LENSES).length;
  const items = pairs.map(([a, b]) =>
    `      <li><a href="vs/${a}-vs-${b}.html">${esc(name)} ${esc(cams[a].name)} vs ${esc(cams[b].name)}</a></li>`
  ).join('\n');
  return `${SEO_BODY_BEGIN}
  <section class="seo-links" aria-label="Popular ${esc(name)} comparisons">
    <h2>Popular ${esc(name)} camera comparisons</h2>
    <p>Compare all ${nCams} ${esc(name)} cameras and ${nLenses} lenses side by side — price, sensor, autofocus, stabilization and video, in seven currencies. Popular head-to-head comparisons:</p>
    <ul>
${items}
    </ul>
  </section>
  ${SEO_BODY_END}`;
}

// Crawlable landing content for the root page: brand cards with live counts
// plus a sample of vs-pages, so the root passes authority into the cluster.
function rootBodyBlock(site, brands, crossSample = []) {
  const eyebrow = brands.map(b => esc(b.name).toUpperCase()).join(' · ');
  const compareCard = `        <li class="brand-card" style="--card-accent: #0071e3">
          <a href="./compare/">
            <div class="brand-name">All Brands</div>
            <div class="brand-count">Mix &amp; match 2&ndash;4 cameras from any brand</div>
            <div class="brand-go">Compare &rarr;</div>
          </a>
        </li>`;
  const cards = [compareCard, ...brands.map(br =>
    `        <li class="brand-card" style="--card-accent: ${esc(br.accent)}">
          <a href="./${br.slug}/">
            <div class="brand-name">${esc(br.name)}</div>
            <div class="brand-count">${br.nCams} cameras · ${br.nLenses} lenses</div>
            <div class="brand-go">Compare &rarr;</div>
          </a>
        </li>`
  )].join('\n');
  const cluster = [
    ...crossSample.map(m =>
      `        <li><a href="./${m.file}">${esc(crossTitle(m))}</a></li>`),
    ...brands.flatMap(br =>
      br.samplePairs.map(p =>
        `        <li><a href="./${br.slug}/vs/${p.a}-vs-${p.b}.html">${esc(br.name)} ${esc(p.aName)} vs ${esc(p.bName)}</a></li>`)),
  ].join('\n');
  return `${SEO_BODY_BEGIN}
  <header id="site-header">
    <div class="header-brand">
      <span class="brand-logo">Compare<span class="accent">CameraSpecs</span></span>
    </div>
  </header>
  <div class="page-hero">
    <div class="hero-eyebrow">${eyebrow}</div>
    <h1 class="hero-title">${esc(site.siteName)}</h1>
    <p class="hero-subtitle">Side-by-side camera &amp; lens comparisons — specs, prices and buy links in seven currencies.</p>
  </div>
  <main class="landing">
    <section>
      <h2>Choose a brand</h2>
      <ul class="brand-grid">
${cards}
      </ul>
    </section>
    <section>
      <h2>Popular comparisons</h2>
      <ul class="cluster">
${cluster}
      </ul>
    </section>
  </main>
  <footer>
    <p>${esc(site.siteName)} &mdash; For informational purposes only.</p>
    <p>Prices shown are approximate manufacturer list prices (RRP) and may differ from live retail prices. Use the Buy link for current pricing.</p>
    <p>Specs sourced from manufacturer documentation.</p>
    <p>Specs &amp; prices last verified: ${esc(site.dataVerified)}</p>
    <div id="affiliate-disclosure"></div>
    <p>
      <a href="./about.html">About</a>
      &middot;
      <a href="./privacy.html">Privacy</a>
      &middot;
      Created by <a href="https://esusatyo.net" target="_blank" rel="noopener">Enrico Susatyo</a>
      &middot;
      Assisted by <a href="https://claude.ai" target="_blank" rel="noopener">Claude</a>
    </p>
  </footer>
  ${SEO_BODY_END}`;
}

function withBlock(html, block, file, begin, end) {
  const start = html.indexOf(begin);
  const stop = html.indexOf(end);
  if (start === -1 || stop === -1) {
    throw new Error(`${file}: ${begin} / ${end} markers not found — refusing to write`);
  }
  return html.slice(0, start) + block + html.slice(stop + end.length);
}

function withHeadBlock(html, block, file) {
  return withBlock(html, block, file, SEO_BEGIN, SEO_END);
}

function withBodyBlock(html, block, file) {
  return withBlock(html, block, file, SEO_BODY_BEGIN, SEO_BODY_END);
}

// ─── Image credits (about.html) ──────────────
// Most Commons product photos here are CC BY / CC BY-SA, which permit reuse
// only *with attribution*, so this block is a licence obligation rather than a
// courtesy. It is generated from each item's `imageCredit` (populated by
// scripts/fetch-image-credits.js, enforced by schema.js) so it can never drift
// out of sync with the images actually shipped.
//
// Manufacturer/retailer product shots are deliberately absent: they are not
// freely licensed and no credit line would change that — they are publicity
// images used to depict the product they advertise.
function imageCreditsBlock(brandData) {
  const rows = [];
  for (const [brand, data] of Object.entries(brandData)) {
    // Display name, not the directory slug ("Canon", not "canon").
    const brandName = data.BRAND_CONFIG.name || brand;
    for (const [, item] of Object.entries({ ...data.CAMERAS, ...data.LENSES })) {
      if (!item.imageCredit) continue;
      rows.push({ brand: brandName, name: item.name, c: item.imageCredit });
    }
  }
  rows.sort((a, b) => a.brand.localeCompare(b.brand) || a.name.localeCompare(b.name));
  if (!rows.length) {
    return `${SEO_BODY_BEGIN}\n  <h2>Image credits</h2>\n  <p>No freely-licensed third-party images are currently in use.</p>\n  ${SEO_BODY_END}`;
  }

  // One <li> per photo: the work, its author, and its licence — each linked to
  // the Commons file page and the licence deed respectively.
  const items = rows.map(r => {
    const who = r.c.author ? esc(r.c.author) : 'Unknown author';
    const lic = r.c.licenceUrl
      ? `<a href="${esc(r.c.licenceUrl)}" rel="noopener nofollow">${esc(r.c.licence)}</a>`
      : esc(r.c.licence);
    return `    <li><a href="${esc(r.c.source)}" rel="noopener nofollow">${esc(r.brand)} ${esc(r.name)}</a>` +
           ` — ${who}, ${lic}</li>`;
  }).join('\n');

  const licences = [...new Set(rows.map(r => r.c.licence))].sort();
  return `${SEO_BODY_BEGIN}
  <h2>Image credits</h2>
  <p>Product photographs are used under free licences from
     <a href="https://commons.wikimedia.org" rel="noopener">Wikimedia Commons</a>. Each photo below is
     credited to its author and licence as those licences require; follow a product link for the
     original file and its full terms. Licences in use: ${esc(licences.join(', '))}.</p>
  <p>Remaining product images are manufacturer press/product photographs, used to depict the
     product they show; those remain the copyright of their respective manufacturers.</p>
  <details>
    <summary>${rows.length} credited photographs</summary>
    <ul class="credits">
${items}
    </ul>
  </details>
  ${SEO_BODY_END}`;
}

// ─── Sitemap & robots ────────────────────────
function sitemapXML(site, paths) {
  const urls = paths.map(p => `  <url><loc>${site.baseUrl}/${p}</loc></url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${site.baseUrl}/</loc></url>
${urls}
</urlset>
`;
}

function robotsTxt(site) {
  return `User-agent: *
Allow: /

Sitemap: ${site.baseUrl}/sitemap.xml
`;
}

// ─── Build everything (pure — returns path → content) ───
function buildAll() {
  const site = siteConfig();
  const files = new Map();
  const sitemapPaths = [];
  const brandNames = [];
  const brandInfo = [];
  const brandData = {};

  for (const brand of brandDirs()) {
    const { data } = loadBrand(brand);
    brandData[brand] = data;
    const name = data.BRAND_CONFIG.name;
    brandNames.push(name);

    const pairs = curatedPairs(data.CAMERAS);

    const idx = path.join(brand, 'index.html');
    let idxHtml = fs.readFileSync(path.join(ROOT, idx), 'utf8');
    idxHtml = withHeadBlock(idxHtml, brandHeadBlock(brand, data, site), idx);
    idxHtml = withBodyBlock(idxHtml, brandBodyBlock(brand, data, site, pairs), idx);
    files.set(idx, idxHtml);
    sitemapPaths.push(`${brand}/`);

    for (const [a, b] of pairs) {
      const rel = `${brand}/vs/${a}-vs-${b}.html`;
      files.set(rel, vsPageHTML(brand, data, site, a, b, pairs));
      sitemapPaths.push(rel);
    }

    const cams = data.CAMERAS;
    brandInfo.push({
      slug: brand,
      name,
      accent: data.BRAND_CONFIG.accentColor,
      nCams: Object.keys(cams).length,
      nLenses: Object.keys(data.LENSES).length,
      samplePairs: pairs.slice(0, 3).map(([a, b]) => ({ a, b, aName: cams[a].name, bName: cams[b].name })),
    });
  }

  // Cross-brand: the /compare/ page plus the curated root vs/ cluster.
  const matchups = resolveMatchups(brandData);
  sitemapPaths.push('compare/');
  for (const m of matchups) {
    files.set(m.file, crossVsPageHTML(site, m, matchups));
    sitemapPaths.push(m.file);
  }
  const cmp = path.join('compare', 'index.html');
  const totalCams = Object.values(brandData).reduce((n, d) => n + Object.keys(d.CAMERAS).length, 0);
  let cmpHtml = fs.readFileSync(path.join(ROOT, cmp), 'utf8');
  cmpHtml = withHeadBlock(cmpHtml, compareHeadBlock(site, brandNames, totalCams), cmp);
  cmpHtml = withBodyBlock(cmpHtml, compareBodyBlock(matchups), cmp);
  files.set(cmp, cmpHtml);

  sitemapPaths.push('about.html', 'privacy.html');
  const about = 'about.html';
  let aboutHtml = fs.readFileSync(path.join(ROOT, about), 'utf8');
  aboutHtml = withHeadBlock(aboutHtml, aboutHeadBlock(site), about);
  aboutHtml = withBodyBlock(aboutHtml, imageCreditsBlock(brandData), about);
  files.set(about, aboutHtml);

  let rootHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  rootHtml = withHeadBlock(rootHtml, rootHeadBlock(site, brandNames), 'index.html');
  rootHtml = withBodyBlock(rootHtml, rootBodyBlock(site, brandInfo, matchups.slice(0, 6)), 'index.html');
  files.set('index.html', rootHtml);
  files.set('sitemap.xml', sitemapXML(site, sitemapPaths));
  files.set('robots.txt', robotsTxt(site));
  return files;
}

// ─── CLI ─────────────────────────────────────
if (require.main === module) {
  const files = buildAll();
  let written = 0;
  for (const [rel, content] of files) {
    const abs = path.join(ROOT, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    if (!fs.existsSync(abs) || fs.readFileSync(abs, 'utf8') !== content) {
      fs.writeFileSync(abs, content);
      written++;
    }
  }
  // Remove stale vs-pages no longer in the curated set (per-brand vs/
  // directories plus the root cross-brand vs/).
  let removed = 0;
  for (const dir of [...brandDirs().map(b => `${b}/vs`), 'vs']) {
    const abs = path.join(ROOT, dir);
    if (!fs.existsSync(abs)) continue;
    for (const f of fs.readdirSync(abs)) {
      if (!files.has(`${dir}/${f}`)) { fs.unlinkSync(path.join(abs, f)); removed++; }
    }
  }
  console.log(`generate-seo: ${files.size} artifacts (${written} written, ${removed} stale removed)`);
}

module.exports = { siteConfig, curatedPairs, relatedPairs, vsPageHTML, resolveMatchups, crossVsPageHTML, crossTitle, CROSS_BRAND_MATCHUPS, compareHeadBlock, compareBodyBlock, brandHeadBlock, rootHeadBlock, brandBodyBlock, rootBodyBlock, withHeadBlock, withBodyBlock, sitemapXML, robotsTxt, buildAll, SEO_BEGIN, SEO_END, SEO_BODY_BEGIN, SEO_BODY_END };
