#!/usr/bin/env node
// ─────────────────────────────────────────────
// SEO GENERATOR
//
// Regenerates every artifact that embeds the site's base URL or
// crawlable content, from brand data + site-config.js:
//
//   1. <!-- seo:begin/end --> head blocks in each <brand>/index.html
//      and the root index.html (description, canonical, OG/Twitter)
//   2. Curated static "X vs Y" pages at <brand>/vs/<a>-vs-<b>.html
//   3. sitemap.xml and robots.txt at the root
//
// Output is committed; tests/data/seo.test.js regenerates in memory
// and fails if the committed files are stale. Run after any change to
// site-config.js or a brand's cameras:
//
//   node scripts/generate-seo.js
//
// Pairing rules (deliberately curated — all-pairs would be thin
// content): consecutive same-series generations where the newer body
// is still current, plus each current body's two nearest USD-price
// neighbours.
// ─────────────────────────────────────────────
const fs = require('fs');
const path = require('path');
const { loadBrand, brandDirs, ROOT } = require('../tests/helpers/load-brand');

const SEO_BEGIN = '<!-- seo:begin (generated by scripts/generate-seo.js — do not edit by hand) -->';
const SEO_END = '<!-- seo:end -->';

function siteConfig() {
  const src = fs.readFileSync(path.join(ROOT, 'site-config.js'), 'utf8');
  return new Function(`${src}; return SITE_CONFIG;`)();
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ─── Pairing rules ───────────────────────────
// The data's `series` field is a broad family (e.g. Sony "Alpha
// (Full-frame)" spans a7/a7R/a9/a1), so successor detection derives the
// *model line* from the slug structure instead.
const ROMAN = { i: 1, ii: 2, iii: 3, iv: 4, v: 5, vi: 6, vii: 7, viii: 8, ix: 9, x: 10 };

// Scheme A — roman-numeral generations of one line:
// a7r-v → a7r gen 5; x100vi → x100 gen 6; eos-r5-ii → eos-r5 gen 2.
function romanLine(slug) {
  let m = slug.match(/^(.+)-([ivx]+)$/);
  if (m && ROMAN[m[2]]) return { line: m[1], gen: ROMAN[m[2]] };
  m = slug.match(/^(.+\d)([ivx]+)$/);
  if (m && ROMAN[m[2]]) return { line: m[1], gen: ROMAN[m[2]] };
  return { line: slug, gen: 1 };
}

// Scheme B — numbered generations: x-t5 → line "x-t"/1-digit, gen 5.
// The digit count separates product tiers that share a stem
// (x-t5 flagship vs x-t50 mid-range vs x-t200 entry).
function numberLine(slug) {
  const m = slug.match(/^(.+?)(\d+)$/);
  return m ? { line: `${m[1]}#${m[2].length}`, gen: parseInt(m[2], 10) } : null;
}

function curatedPairs(cams) {
  const seen = new Set();
  const pairs = [];
  const usd = id => (cams[id].prices && cams[id].prices.USD) || 0;
  // Canonical order within a pair: newer first, then pricier, then slug.
  const add = (a, b) => {
    if (a === b) return;
    const [ca, cb] = [cams[a], cams[b]];
    if (cb.year > ca.year || (cb.year === ca.year && usd(b) > usd(a)) ||
        (cb.year === ca.year && usd(b) === usd(a) && b < a)) [a, b] = [b, a];
    const key = `${a}|${b}`;
    if (!seen.has(key)) { seen.add(key); pairs.push([a, b]); }
  };
  // Successors launch near their predecessor's RRP; a big gap means the
  // "line" grouping actually caught two different tiers (Z9 vs Z5).
  const priceClose = (a, b) =>
    usd(a) > 0 && usd(b) > 0 && Math.abs(usd(a) - usd(b)) / Math.max(usd(a), usd(b)) <= 0.4;

  // Rule 1: consecutive generations within a model line, newer body
  // still current. Scheme A is structurally unambiguous; scheme B adds
  // the price gate because a shared stem can still span tiers.
  const addSuccessors = (grouper, gated) => {
    const lines = {};
    for (const id of Object.keys(cams)) {
      const r = grouper(id);
      if (r) (lines[r.line] ??= []).push([id, r.gen]);
    }
    for (const list of Object.values(lines)) {
      list.sort((p, q) => q[1] - p[1] || cams[q[0]].year - cams[p[0]].year);
      for (let i = 0; i + 1 < list.length; i++) {
        const [newer, older] = [list[i][0], list[i + 1][0]];
        if (cams[newer].discontinued) continue;
        if (gated && !priceClose(newer, older)) continue;
        add(newer, older);
      }
    }
  };
  addSuccessors(romanLine, false);
  addSuccessors(numberLine, true);

  // Rule 2: current bodies vs their two nearest USD-price neighbours.
  const current = Object.keys(cams)
    .filter(id => !cams[id].discontinued && usd(id) > 0)
    .sort((a, b) => usd(b) - usd(a) || (a < b ? -1 : 1));
  for (let i = 0; i < current.length; i++) {
    for (let k = 1; k <= 2 && i + k < current.length; k++) add(current[i], current[i + k]);
  }
  return pairs;
}

// ─── vs-page ─────────────────────────────────
const VS_ROWS = [
  ['Price (USD RRP)', c => c.prices.USD == null ? null : `$${c.prices.USD.toLocaleString('en-US')}`],
  ['Announced', c => c.year],
  ['Sensor', c => `${c.sensorMP} MP ${c.sensorType}`],
  ['Processor', c => c.processor],
  ['In-body stabilization', c => c.ibis ? `Yes${c.ibisStops ? ` (${c.ibisStops} stops)` : ''}` : 'No'],
  ['Max burst', c => c.maxBurst == null ? null : `${c.maxBurst} fps`],
  ['Max video', c => c.maxVideoRes],
  ['Weather sealed', c => c.weatherSealed ? 'Yes' : 'No'],
  ['Weight', c => c.weight == null ? null : `${c.weight} g`],
  ['Battery (CIPA)', c => c.batteryLife == null ? null : `${c.batteryLife} shots`],
  ['Card slots', c => c.cardSlots],
  ['Lens mount', c => c.lensType],
];

const VS_CSS = `
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 720px; margin: 0 auto; padding: 24px 16px; line-height: 1.55; }
  h1 { font-size: 1.5rem; }
  table { border-collapse: collapse; width: 100%; margin: 20px 0; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid rgba(128,128,128,.35); }
  th { font-weight: 600; }
  .cta { display: inline-block; margin: 8px 0 16px; font-weight: 600; }
  footer { margin-top: 32px; font-size: .85rem; opacity: .75; }
`.trim();

function productLd(brandName, cam) {
  const p = { '@type': 'Product', name: `${brandName} ${cam.name}`, brand: { '@type': 'Brand', name: brandName } };
  if (cam.imageUrl) p.image = cam.imageUrl;
  if (cam.prices && cam.prices.USD != null) {
    p.offers = { '@type': 'Offer', priceCurrency: 'USD', price: cam.prices.USD };
  }
  return p;
}

function vsPageHTML(brand, data, site, aId, bId) {
  const cams = data.CAMERAS;
  const brandName = data.BRAND_CONFIG.name;
  const [a, b] = [cams[aId], cams[bId]];
  const title = `${brandName} ${a.name} vs ${b.name}: Spec Comparison`;
  const desc = `Compare the ${brandName} ${a.name} (${a.year}) and ${b.name} (${b.year}) side by side — price, sensor, stabilization, video, weight and more.`;
  const url = `${site.baseUrl}/${brand}/vs/${aId}-vs-${bId}.html`;
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: title,
    itemListElement: [a, b].map((c, i) => ({ '@type': 'ListItem', position: i + 1, item: productLd(brandName, c) })),
  };
  const rows = VS_ROWS.map(([label, fn]) => {
    const [va, vb] = [fn(a), fn(b)];
    return `      <tr><th scope="row">${esc(label)}</th><td>${va == null ? '—' : esc(va)}</td><td>${vb == null ? '—' : esc(vb)}</td></tr>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="${esc(site.siteName)}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:url" content="${url}">
  <meta name="twitter:card" content="summary">
  <script type="application/ld+json">${JSON.stringify(ld)}</script>
  <!-- Umami analytics — temporarily disabled, kept for re-enabling.
  <script defer src="https://cloud.umami.is/script.js" data-website-id="365e9ee6-1fb5-4a0d-9c74-f6255522a196"></script> -->
  <script data-goatcounter="https://esusatyo.goatcounter.com/count" defer src="https://gc.zgo.at/count.js"></script>
  <style>${VS_CSS}</style>
</head>
<body>
  <h1>${esc(brandName)} ${esc(a.name)} vs ${esc(b.name)}</h1>
  <p>The ${esc(brandName)} <strong>${esc(a.name)}</strong> (${a.year}) and <strong>${esc(b.name)}</strong> (${b.year}) compared side by side.
     Key specifications are below; the interactive tool adds the full spec sheet, winner highlighting,
     seven currencies and a third comparison slot.</p>
  <a class="cta" href="../index.html#cameras=${aId},${bId}">Open this comparison in the interactive tool &rarr;</a>
  <table>
    <thead>
      <tr><th scope="col">Spec</th><th scope="col">${esc(a.name)}</th><th scope="col">${esc(b.name)}</th></tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>
  <p>Prices shown are approximate manufacturer list prices (RRP) in USD and may differ from live retail prices.</p>
  <footer>
    <a href="../index.html">All ${esc(brandName)} cameras &amp; lenses</a> &middot;
    <a href="../../about.html">About</a> &middot;
    <a href="../../privacy.html">Privacy</a><br>
    Specs &amp; prices last verified: ${esc(site.dataVerified)}
  </footer>
</body>
</html>
`;
}

// ─── Head blocks ─────────────────────────────
function metaBlock(site, url, title, desc) {
  return `${SEO_BEGIN}
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="${esc(site.siteName)}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:url" content="${url}">
  <meta name="twitter:card" content="summary">
  ${SEO_END}`;
}

function brandHeadBlock(brand, data, site) {
  const name = data.BRAND_CONFIG.name;
  const nCams = Object.keys(data.CAMERAS).length;
  const nLenses = Object.keys(data.LENSES).length;
  return metaBlock(
    site,
    `${site.baseUrl}/${brand}/`,
    `${name} Camera & Lens Comparison`,
    `Compare ${nCams} ${name} cameras and ${nLenses} lenses side by side — price, sensor, autofocus, stabilization and video, in 7 currencies.`
  );
}

function rootHeadBlock(site, brandNames) {
  return metaBlock(
    site,
    `${site.baseUrl}/`,
    `${site.siteName} — Camera & Lens Comparison`,
    `Side-by-side camera and lens comparison for ${brandNames.join(', ')} — specs, prices and buy links in 7 currencies.`
  );
}

function withHeadBlock(html, block, file) {
  const start = html.indexOf(SEO_BEGIN);
  const end = html.indexOf(SEO_END);
  if (start === -1 || end === -1) {
    throw new Error(`${file}: seo:begin/seo:end markers not found — refusing to write`);
  }
  return html.slice(0, start) + block + html.slice(end + SEO_END.length);
}

// ─── Sitemap & robots ────────────────────────
function sitemapXML(site, paths) {
  const urls = paths.map(p => `  <url><loc>${site.baseUrl}/${p}</loc></url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${site.baseUrl}/</loc></url>
${urls}
</urlset>
`;
}

function robotsTxt(site) {
  return `User-agent: *
Allow: /

Sitemap: ${site.baseUrl}/sitemap.xml
`;
}

// ─── Build everything (pure — returns path → content) ───
function buildAll() {
  const site = siteConfig();
  const files = new Map();
  const sitemapPaths = [];
  const brandNames = [];

  for (const brand of brandDirs()) {
    const { data } = loadBrand(brand);
    brandNames.push(data.BRAND_CONFIG.name);

    const idx = path.join(brand, 'index.html');
    files.set(idx, withHeadBlock(fs.readFileSync(path.join(ROOT, idx), 'utf8'), brandHeadBlock(brand, data, site), idx));
    sitemapPaths.push(`${brand}/`);

    for (const [a, b] of curatedPairs(data.CAMERAS)) {
      const rel = `${brand}/vs/${a}-vs-${b}.html`;
      files.set(rel, vsPageHTML(brand, data, site, a, b));
      sitemapPaths.push(rel);
    }
  }

  sitemapPaths.push('about.html', 'privacy.html');
  files.set('index.html', withHeadBlock(fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8'), rootHeadBlock(site, brandNames), 'index.html'));
  files.set('sitemap.xml', sitemapXML(site, sitemapPaths));
  files.set('robots.txt', robotsTxt(site));
  return files;
}

// ─── CLI ─────────────────────────────────────
if (require.main === module) {
  const files = buildAll();
  let written = 0;
  for (const [rel, content] of files) {
    const abs = path.join(ROOT, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    if (!fs.existsSync(abs) || fs.readFileSync(abs, 'utf8') !== content) {
      fs.writeFileSync(abs, content);
      written++;
    }
  }
  // Remove stale vs-pages no longer in the curated set.
  let removed = 0;
  for (const brand of brandDirs()) {
    const vsDir = path.join(ROOT, brand, 'vs');
    if (!fs.existsSync(vsDir)) continue;
    for (const f of fs.readdirSync(vsDir)) {
      if (!files.has(`${brand}/vs/${f}`)) { fs.unlinkSync(path.join(vsDir, f)); removed++; }
    }
  }
  console.log(`generate-seo: ${files.size} artifacts (${written} written, ${removed} stale removed)`);
}

module.exports = { siteConfig, curatedPairs, vsPageHTML, brandHeadBlock, rootHeadBlock, withHeadBlock, sitemapXML, robotsTxt, buildAll, SEO_BEGIN, SEO_END };
