// ─────────────────────────────────────────────
// PANASONIC BRAND CONFIG
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Panasonic',
  slug:        'panasonic',
  accentColor: '#0046ad',
  heroDark:    '#0a1530',
  logoText:    'LUMIX',
  logoAccent:  '',
  families:    ['Lumix S (L-Mount)', 'Lumix G (Micro Four Thirds)'],
  brandSections: ['panasonic'],
  cameras: {
    heroEyebrow:  'Lumix S & G',
    heroTitle:    '<span>Panasonic</span> Camera Comparison',
    heroSubtitle: 'Compare up to 3 Panasonic Lumix cameras side-by-side — full-frame L-Mount and Micro Four Thirds',
    headerTitle:  'Camera Compare',
    defaultSelected: ['s5-ii', 's1r-ii', 'gh7'],
  },
  lenses: {
    heroEyebrow:  'LUMIX S & G Lenses',
    heroTitle:    '<span>Panasonic</span> Lens Comparison',
    heroSubtitle: 'Compare Panasonic LUMIX S (L-Mount) and LUMIX G (MFT) lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['lumix-s-50mm-f1-8', 'lumix-s-24-70mm-f2-8-pro', 'lumix-g-12-35mm-f2-8-ii'],
  },
  footerLinks: [
    { label: 'LUMIX S Series',   url: 'https://www.panasonic.com/global/consumer/lumix/s.html' },
    { label: 'LUMIX G Series',   url: 'https://www.panasonic.com/global/consumer/lumix/g.html' },
    { label: 'DPReview Panasonic', url: 'https://www.dpreview.com/products/panasonic' },
  ],
};

const REGISTERED_BRANDS = [
  { slug: 'fujifilm',  name: 'Fujifilm' },
  { slug: 'canon',     name: 'Canon' },
  { slug: 'sony',      name: 'Sony' },
  { slug: 'nikon',     name: 'Nikon' },
  { slug: 'panasonic', name: 'Panasonic' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards) — Lumix/Panasonic blue
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'Lumix S (Full-frame)': { bg: '#0a1530', text: '#6fa8ff' },
  'Lumix GH (MFT)':       { bg: '#0a1228', text: '#7fb0ff' },
  'Lumix G (MFT)':        { bg: '#0c1426', text: '#8ab4ff' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE — Panasonic Lumix mirrorless (L-Mount + Micro Four Thirds).
// Panasonic-specific fields: vLog (V-Log / V-Log L gamma), dualNativeIso
// (Dual Native ISO sensor tech), openGate (Open Gate full-sensor max capture),
// proResInternal (internal Apple ProRes / ProRes RAW recording).
// Pricing: USD is the list/RRP; non-USD figures are APPROXIMATE RRPs derived
// from USD via regional ratios (refined as real RRP surfaces). Specs verified
// against Panasonic official pages + DPReview/Wikipedia (see
// openspec/changes/add-panasonic-brand/research/).
// ─────────────────────────────────────────────
const CAMERAS = {

  /* ── Lumix S (Full-frame L-Mount) ── */
  's1r-ii': {
    name:'Lumix S1R II', series:'Lumix S (Full-frame)', year:2025, discontinued:false,
    tagline:'44MP High-Res 8K Hybrid',
    productUrl:'https://shop.panasonic.com/products/lumix-s1rii-full-frame-mirrorless-digital-camera-dc-s1rm2',
    imageUrl:null,
    asin:'B0DY21GMBD',
    prices:{USD:3299,AUD:5299,EUR:3829,GBP:3149,JPY:545000,CAD:4549,SGD:4699},
    sensorMP:44.3, sensorType:'Full-frame BSI CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:91.8, weight:795, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle / Train / Airplane',
    ibis:true, ibisStops:8.0, maxBurst:40,
    maxVideoRes:'8.1K / 30P',
    logVideo:true,
    vLog:'V-Log', dualNativeIso:true, openGate:'6.4K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's5-ii': {
    name:'Lumix S5 II', series:'Lumix S (Full-frame)', year:2023, discontinued:false,
    tagline:'Phase-Detect Hybrid Full-Frame',
    productUrl:'https://shop.panasonic.com/products/full-frame-mirrorless-camera-s5m2',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Panasonic_LUMIX_S5_II_%2852682131682%29.jpg/1280px-Panasonic_LUMIX_S5_II_%2852682131682%29.jpg',
    asin:'B0BR8JMCYG',
    prices:{USD:1999,AUD:3199,EUR:2299,GBP:1899,JPY:330000,CAD:2749,SGD:2849},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:90.1, weight:740, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:30,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:'6K', proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:370, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's1-ii': {
    name:'Lumix S1 II', series:'Lumix S (Full-frame)', year:2025, discontinued:false,
    tagline:'Partially-Stacked Hybrid Flagship',
    productUrl:'https://shop.panasonic.com/products/lumix-s1ii-full-frame-camera-partially-stacked-sensor-dc-s1m2',
    imageUrl:null,
    asin:'B0F8MHCD7V',
    prices:{USD:3199,AUD:5099,EUR:3699,GBP:3049,JPY:528000,CAD:4399,SGD:4549},
    sensorMP:24.1, sensorType:'Full-frame Partially-Stacked BSI CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:91.8, weight:800, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle / Train / Airplane',
    ibis:true, ibisStops:8.0, maxBurst:70,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log', dualNativeIso:true, openGate:'6K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's5-iix': {
    name:'Lumix S5 IIX', series:'Lumix S (Full-frame)', year:2023, discontinued:false,
    tagline:'All-Black Pro Video S5 II',
    productUrl:'https://shop.panasonic.com/products/lumix-s5iix-mirrorless-camera-dc-s5m2x',
    imageUrl:null,
    asin:'B0BR8FY5HT',
    prices:{USD:2199,AUD:3499,EUR:2549,GBP:2099,JPY:363000,CAD:3049,SGD:3149},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:90.1, weight:740, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:30,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:'6K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:370, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's9': {
    name:'Lumix S9', series:'Lumix S (Full-frame)', year:2024, discontinued:false,
    tagline:'Compact Full-Frame Creator Body',
    productUrl:'https://shop.panasonic.com/products/lumix-s9-full-frame-mirrorless-camera',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Panasonic_LUMIX_S9_front_view.jpg/1280px-Panasonic_LUMIX_S9_front_view.jpg',
    asin:'B0D4FBF5NK',
    prices:{USD:1499,AUD:2399,EUR:1749,GBP:1499,JPY:247000,CAD:2049,SGD:2149},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:126.0, height:73.9, depth:46.7, weight:486, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:30,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:'6K', proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:470, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's1h': {
    name:'Lumix S1H', series:'Lumix S (Full-frame)', year:2019, discontinued:false,
    tagline:'Cinema-Grade Full-Frame',
    productUrl:'https://shop.panasonic.com/products/s1h-full-frame-mirrorless-camera-body',
    imageUrl:null,
    asin:'B07WSRHXPR',
    prices:{USD:3499,AUD:5599,EUR:4049,GBP:3299,JPY:577000,CAD:4799,SGD:4999},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:151.0, height:114.2, depth:110.4, weight:1052, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2330, lcdType:'Tri-axis Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:9,
    maxVideoRes:'6K / 24P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'6K', proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix S — discontinued (USD list only) ── */
  's1': {
    name:'Lumix S1', series:'Lumix S (Full-frame)', year:2019, discontinued:true,
    tagline:'Original Full-Frame Hybrid',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:2499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:148.9, height:110.0, depth:96.7, weight:1017, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tri-axis Tilt Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human (face / eye / body)',
    ibis:true, ibisStops:6.0, maxBurst:9,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log (paid upgrade)', dualNativeIso:true, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× XQD + 1× SD UHS-II', batteryLife:380, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's1r': {
    name:'Lumix S1R', series:'Lumix S (Full-frame)', year:2019, discontinued:true,
    tagline:'Original 47MP High-Res',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:3699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:47.3, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:148.9, height:110.0, depth:96.7, weight:1020, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tri-axis Tilt Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human (face / eye / body)',
    ibis:true, ibisStops:6.0, maxBurst:9,
    maxVideoRes:'4K / 60P',
    logVideo:false,
    vLog:null, dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× XQD + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's5': {
    name:'Lumix S5', series:'Lumix S (Full-frame)', year:2020, discontinued:true,
    tagline:'Compact Full-Frame Hybrid',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:132.6, height:97.1, depth:81.9, weight:714, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:7,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:440, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix GH (Micro Four Thirds) ── */
  'gh7': {
    name:'Lumix GH7', series:'Lumix GH (MFT)', year:2024, discontinued:false,
    tagline:'ProRes RAW Video Flagship',
    productUrl:'https://shop.panasonic.com/products/gh7-mirrorless-camera',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Panasonic_LUMIX_GH7_front_view.jpg/1280px-Panasonic_LUMIX_GH7_front_view.jpg',
    asin:'B0D613NW2M',
    prices:{USD:2199,AUD:3499,EUR:2549,GBP:2099,JPY:363000,CAD:3049,SGD:3149},
    sensorMP:25.2, sensorType:'Micro Four Thirds BSI CMOS', processor:'Venus Engine',
    width:138.4, height:100.3, depth:99.6, weight:805, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle',
    ibis:true, ibisStops:7.5, maxBurst:75,
    maxVideoRes:'5.7K / 30P (Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'5.8K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'gh6': {
    name:'Lumix GH6', series:'Lumix GH (MFT)', year:2022, discontinued:false,
    tagline:'High-Res MFT Video Workhorse',
    productUrl:'https://shop.panasonic.com/products/gh6-mirrorless-camera-body',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Panasonic_Lumix_GH6_with_25mm_leica_lens.jpg/1280px-Panasonic_Lumix_GH6_with_25mm_leica_lens.jpg',
    asin:'B09T2RJ27P',
    prices:{USD:2199,AUD:3499,EUR:2549,GBP:2099,JPY:363000,CAD:3049,SGD:3149},
    sensorMP:25.2, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:138.4, height:100.3, depth:99.6, weight:823, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:7.5, maxBurst:75,
    maxVideoRes:'5.7K / 60P (Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'5.8K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix GH — discontinued (USD list only) ── */
  'gh5-ii': {
    name:'Lumix GH5 II', series:'Lumix GH (MFT)', year:2021, discontinued:true,
    tagline:'Live-Streaming MFT Hybrid',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Panasonic_Lumix_GH5_II_with_len.jpg/1280px-Panasonic_Lumix_GH5_II_with_len.jpg',
    asin:null,
    prices:{USD:1699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:138.5, height:98.1, depth:87.4, weight:727, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:12,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log L', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'gh5': {
    name:'Lumix GH5', series:'Lumix GH (MFT)', year:2017, discontinued:true,
    tagline:'Landmark MFT Video Body',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:138.5, height:98.1, depth:87.4, weight:725, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:1620, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human (face / eye / body)',
    ibis:true, ibisStops:5.0, maxBurst:12,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log L (paid upgrade)', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:410, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix G (Micro Four Thirds) ── */
  'g9-ii': {
    name:'Lumix G9 II', series:'Lumix G (MFT)', year:2023, discontinued:false,
    tagline:'Phase-Detect MFT Photo Flagship',
    productUrl:'https://shop.panasonic.com/products/lumix-g9ii-micro-four-thirds-camera-dc-g9m2',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Panasonic_Lumix_G9_II.jpg/1280px-Panasonic_Lumix_G9_II.jpg',
    asin:'B0CHTHLVHS',
    prices:{USD:1899,AUD:2999,EUR:2199,GBP:1799,JPY:313000,CAD:2599,SGD:2699},
    sensorMP:25.2, sensorType:'Micro Four Thirds BSI CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:90.1, weight:658, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.80,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle',
    ibis:true, ibisStops:8.0, maxBurst:60,
    maxVideoRes:'5.8K / 30P (Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'5.8K', proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:390, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'g100d': {
    name:'Lumix G100D', series:'Lumix G (MFT)', year:2024, discontinued:false,
    tagline:'Compact Vlogging MFT',
    productUrl:'https://shop.panasonic.com/products/g100d-mirrorless-camera-12-32mm-f3-5-5-6-lens',
    imageUrl:null,
    asin:null,
    prices:{USD:597,AUD:999,EUR:699,GBP:599,JPY:99000,CAD:829,SGD:869},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:115.6, height:82.5, depth:54.2, weight:412, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.73,
    faceDetection:true, subjectDetection:'Human (face / eye)',
    ibis:false, ibisStops:null, maxBurst:10,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    vLog:'V-Log L', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:270, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix G — discontinued (USD list only) ── */
  'g9': {
    name:'Lumix G9', series:'Lumix G (MFT)', year:2017, discontinued:true,
    tagline:'Original MFT Photo Flagship',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:136.9, height:97.3, depth:91.6, weight:658, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.83,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:60,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log L (paid upgrade)', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'gx9': {
    name:'Lumix GX9', series:'Lumix G (MFT)', year:2018, discontinued:true,
    tagline:'Rangefinder-Style Street Compact',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:124.0, height:72.1, depth:46.8, weight:407, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1240, lcdType:'Tilting Touch',
    evfType:'Tilting EVF', evfDots:2.76, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human (face / eye)',
    ibis:true, ibisStops:4.0, maxBurst:9,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    vLog:null, dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:260, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'g95': {
    name:'Lumix G95', series:'Lumix G (MFT)', year:2019, discontinued:true,
    tagline:'All-Rounder MFT Hybrid',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:130.4, height:93.5, depth:77.4, weight:536, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1240, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:'Human (face / eye)',
    ibis:true, ibisStops:5.0, maxBurst:9,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    vLog:'V-Log L', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:290, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

};

const CAMERA_ORDER = [
  's1r-ii', 's1-ii', 's5-ii', 's5-iix', 's9', 's1h', 's1', 's1r', 's5',
  'gh7', 'gh6', 'gh5-ii', 'gh5',
  'g9-ii', 'g100d', 'g9', 'gx9', 'g95',
];

const DROPDOWN_GROUPS = [
  { label: '── Lumix S — Full-Frame (L-Mount) ──', ids: ['s1r-ii', 's1-ii', 's5-ii', 's5-iix', 's9', 's1h', 's1', 's1r', 's5'] },
  { label: '── Lumix GH — Micro Four Thirds ──',   ids: ['gh7', 'gh6', 'gh5-ii', 'gh5'] },
  { label: '── Lumix G — Micro Four Thirds ──',    ids: ['g9-ii', 'g100d', 'g9', 'gx9', 'g95'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE — Panasonic LUMIX (first-party only; Leica DG are
// Leica-designed / Panasonic-made → manufacturer 'Panasonic').
// line: 'LUMIX S' (L-Mount, full-frame) | 'LUMIX G' (MFT, 2.0× crop equiv).
// `priceIncomplete: true` ships an item with USD (+ any confirmed regional)
// while regional RRP backfill is pending (see check-prices-and-buy-links).
// ─────────────────────────────────────────────
const LENSES = {

  /* ── LUMIX S Primes (L-Mount, full-frame) ── */
  'lumix-s-50mm-f1-8': {
    name:'LUMIX S 50mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B093NKZCR4',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.8, minAperture:22, weight:300, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:45, maxMagnification:0.14,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:447,AUD:699,EUR:null,GBP:null,JPY:null,CAD:599,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-50mm-f1-8-l-mount-interchangeable-lens-s-s50',
  },

  'lumix-s-18mm-f1-8': {
    name:'LUMIX S 18mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B0BDGGZ7NS',
    focalLength:18, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'18mm',
    maxAperture:1.8, minAperture:22, weight:340, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:18, maxMagnification:0.08,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:747,AUD:1199,EUR:null,GBP:null,JPY:null,CAD:999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-18mm-f1-8-l-mount-lens-s-s18',
  },

  'lumix-s-24mm-f1-8': {
    name:'LUMIX S 24mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B09F6WGXHM',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.8, minAperture:22, weight:310, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:24, maxMagnification:0.15,
    elements:12, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-24mm-f1-8-l-mount-lens-s-s24',
  },

  'lumix-s-35mm-f1-8': {
    name:'LUMIX S 35mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B09LD9DQG5',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.8, minAperture:22, weight:295, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:24, maxMagnification:0.15,
    elements:11, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Panasonic_Lumix_S_35mm_F1.8_%2852972339626%29.jpg/1280px-Panasonic_Lumix_S_35mm_F1.8_%2852972339626%29.jpg',
    prices:{USD:697,AUD:1099,EUR:null,GBP:null,JPY:null,CAD:949,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-35mm-f1-8-l-mount-lens-s-s35',
  },

  'lumix-s-85mm-f1-8': {
    name:'LUMIX S 85mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B08M24BV12',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.8, minAperture:22, weight:355, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:80, maxMagnification:0.13,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-85mm-f1-8-l-mount-lens-s-s85',
  },

  'lumix-s-40mm-f2': {
    name:'LUMIX S 40mm F2', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B0GY21YLS2',
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.0, minAperture:22, weight:300, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:23, maxMagnification:0.15,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-40mm-f2-l-mount-lens-s-s40',
  },

  'lumix-s-pro-50mm-f1-4': {
    name:'LUMIX S PRO 50mm F1.4', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B07N84VZ4Z',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:955, length:130.0, diameter:90.0,
    filterThread:77, minFocusDist:44, maxMagnification:0.15,
    elements:13, groups:11, blades:11, afType:'Dual Phase Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:2297,AUD:3599,EUR:null,GBP:null,JPY:null,CAD:3099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-pro-50mm-f1-4-l-mount-lens-s-x50',
  },

  'lumix-s-100mm-f2-8-macro': {
    name:'LUMIX S 100mm F2.8 MACRO', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B0CRSNV73W',
    focalLength:100, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'100mm',
    maxAperture:2.8, minAperture:22, weight:298, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:20, maxMagnification:1.0,
    elements:13, groups:11, blades:9, afType:'Dual Phase Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1599,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-100mm-f2-8-macro-l-mount-lens-s-e100',
  },

  /* ── LUMIX S Zooms (L-Mount, full-frame) ── */
  'lumix-s-24-70mm-f2-8-pro': {
    name:'LUMIX S PRO 24-70mm F2.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07WRMBFF3',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:935, length:140.0, diameter:90.9,
    filterThread:82, minFocusDist:37, maxMagnification:0.25,
    elements:18, groups:16, blades:11, afType:'Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:2197,AUD:3399,EUR:null,GBP:null,JPY:null,CAD:2899,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-pro-24-70mm-f2-8-l-mount-lens-s-e2470',
  },

  'lumix-s-pro-16-35mm-f4': {
    name:'LUMIX S PRO 16-35mm F4', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B00JEZ0OFS',
    focalLength:null, focalLengthMin:16, focalLengthMax:35, focalLengthEquiv:'16-35mm',
    maxAperture:4.0, minAperture:22, weight:500, length:100.0, diameter:84.6,
    filterThread:77, minFocusDist:25, maxMagnification:0.23,
    elements:12, groups:9, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:1497,AUD:2299,EUR:null,GBP:null,JPY:null,CAD:1999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-pro-16-35mm-f4-l-mount-lens-s-r1635',
  },

  'lumix-s-14-28mm-f4-5-6-macro': {
    name:'LUMIX S 14-28mm F4-5.6 MACRO', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B0BR8GF76K',
    focalLength:null, focalLengthMin:14, focalLengthMax:28, focalLengthEquiv:'14-28mm',
    maxAperture:4.0, minAperture:22, weight:345, length:89.6, diameter:84.0,
    filterThread:77, minFocusDist:15, maxMagnification:0.50,
    elements:14, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-14-28mm-f4-5-6-macro-l-mount-lens-s-r1428',
  },

  'lumix-s-20-60mm-f3-5-5-6': {
    name:'LUMIX S 20-60mm F3.5-5.6', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B088VSF94W',
    focalLength:null, focalLengthMin:20, focalLengthMax:60, focalLengthEquiv:'20-60mm',
    maxAperture:3.5, minAperture:22, weight:350, length:87.2, diameter:77.4,
    filterThread:67, minFocusDist:15, maxMagnification:0.43,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:599,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-20-60mm-f3-5-5-6-l-mount-lens-s-r2060',
  },

  'lumix-s-24-60mm-f2-8': {
    name:'LUMIX S 24-60mm F2.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B0F8P9V67L',
    focalLength:null, focalLengthMin:24, focalLengthMax:60, focalLengthEquiv:'24-60mm',
    maxAperture:2.8, minAperture:22, weight:544, length:99.7, diameter:77.5,
    filterThread:67, minFocusDist:30, maxMagnification:0.20,
    elements:13, groups:12, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:1099,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-24-60mm-f2-8-l-mount-lens-s-e2460',
  },

  'lumix-s-24-105mm-f4-macro': {
    name:'LUMIX S 24-105mm F4 MACRO O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07N83WBTF',
    focalLength:null, focalLengthMin:24, focalLengthMax:105, focalLengthEquiv:'24-105mm',
    maxAperture:4.0, minAperture:22, weight:680, length:118.0, diameter:84.0,
    filterThread:77, minFocusDist:30, maxMagnification:0.50,
    elements:16, groups:13, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Panasonic_Lumix_S_24-105mm_F4_Macro_O.I.S._20260621150950.jpg/1280px-Panasonic_Lumix_S_24-105mm_F4_Macro_O.I.S._20260621150950.jpg',
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-24-105mm-f4-macro-ois-l-mount-lens-s-r24105',
  },

  'lumix-s-28-200mm-f4-7-1-macro': {
    name:'LUMIX S 28-200mm F4-7.1 MACRO O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B0CW8722BG',
    focalLength:null, focalLengthMin:28, focalLengthMax:200, focalLengthEquiv:'28-200mm',
    maxAperture:4.0, minAperture:22, weight:413, length:93.4, diameter:77.3,
    filterThread:67, minFocusDist:14, maxMagnification:0.50,
    elements:17, groups:13, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-28-200mm-f4-7-1-macro-ois-l-mount-lens-s-r28200',
  },

  'lumix-s-pro-70-200mm-f2-8': {
    name:'LUMIX S PRO 70-200mm F2.8 O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07ZZQ3DCC',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1570, length:208.6, diameter:94.4,
    filterThread:82, minFocusDist:95, maxMagnification:0.21,
    elements:22, groups:17, blades:11, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:2597,AUD:3999,EUR:null,GBP:null,JPY:null,CAD:3499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-pro-70-200mm-f2-8-ois-l-mount-lens-s-e70200',
  },

  'lumix-s-pro-70-200mm-f4': {
    name:'LUMIX S PRO 70-200mm F4 O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07N844X8Q',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:4.0, minAperture:22, weight:985, length:179.0, diameter:84.4,
    filterThread:77, minFocusDist:92, maxMagnification:0.25,
    elements:23, groups:17, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Panasonic_Lumix_S_PRO_70-200mm_F4_O.I.S._%2851248180327%29.jpg/1280px-Panasonic_Lumix_S_PRO_70-200mm_F4_O.I.S._%2851248180327%29.jpg',
    prices:{USD:1697,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-pro-70-200mm-f4-ois-l-mount-lens-s-r70200',
  },

  'lumix-s-70-300mm-f4-5-5-6-macro': {
    name:'LUMIX S 70-300mm F4.5-5.6 MACRO O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B08XX5GTQZ',
    focalLength:null, focalLengthMin:70, focalLengthMax:300, focalLengthEquiv:'70-300mm',
    maxAperture:4.5, minAperture:22, weight:790, length:148.0, diameter:84.0,
    filterThread:77, minFocusDist:54, maxMagnification:0.50,
    elements:17, groups:11, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Panasonic_Lumix_S_70-300mm_F4.5-5.6_Macro_O.I.S._20260621143312.jpg/1280px-Panasonic_Lumix_S_70-300mm_F4.5-5.6_Macro_O.I.S._20260621143312.jpg',
    prices:{USD:1147,AUD:1799,EUR:null,GBP:null,JPY:null,CAD:1549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-70-300mm-f4-5-5-6-macro-ois-l-mount-lens-s-r70300',
  },

  /* ── LUMIX G Primes (Micro Four Thirds, 2.0× crop equiv) ── */
  'leica-dg-9mm-f1-7': {
    name:'LEICA DG SUMMILUX 9mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B0B1K7ZCDF',
    focalLength:9, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'18mm',
    maxAperture:1.7, minAperture:16, weight:130, length:52.0, diameter:60.3,
    filterThread:55, minFocusDist:9.5, maxMagnification:0.25,
    elements:12, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:799,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-summilux-9mm-f1-7-lens-h-x09',
  },

  'leica-dg-12mm-f1-4': {
    name:'LEICA DG SUMMILUX 12mm F1.4', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B01H1MNW68',
    focalLength:12, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.4, minAperture:16, weight:335, length:70.0, diameter:70.0,
    filterThread:62, minFocusDist:20, maxMagnification:0.10,
    elements:15, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-summilux-12mm-f1-4-asph-lens-h-x012',
  },

  'leica-dg-15mm-f1-7': {
    name:'LEICA DG SUMMILUX 15mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00J8HV6DG',
    focalLength:15, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'30mm',
    maxAperture:1.7, minAperture:16, weight:115, length:36.0, diameter:57.5,
    filterThread:46, minFocusDist:20, maxMagnification:0.10,
    elements:9, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2014, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-summilux-15mm-f1-7-asph-lens-h-x015',
  },

  'lumix-g-20mm-f1-7-ii': {
    name:'LUMIX G 20mm F1.7 II ASPH.', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00DJS830Y',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:1.7, minAperture:16, weight:87, length:25.5, diameter:63.0,
    filterThread:46, minFocusDist:20, maxMagnification:0.13,
    elements:7, groups:5, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:397,AUD:649,EUR:null,GBP:null,JPY:null,CAD:549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-20mm-f1-7-ii-asph-lens-h-h020a',
  },

  'leica-dg-25mm-f1-4-ii': {
    name:'LEICA DG SUMMILUX 25mm F1.4 II', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B07X76CG5S',
    focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:200, length:54.5, diameter:63.0,
    filterThread:46, minFocusDist:30, maxMagnification:0.11,
    elements:9, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-summilux-25mm-f1-4-ii-asph-lens-h-xa025',
  },

  'lumix-g-25mm-f1-7': {
    name:'LUMIX G 25mm F1.7 ASPH.', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B014RD6RC0',
    focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.7, minAperture:22, weight:125, length:52.0, diameter:60.8,
    filterThread:46, minFocusDist:25, maxMagnification:0.14,
    elements:8, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2015, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Panasonic_Lumix_G_25mm_F1.7_ASPH_lens.jpg/1280px-Panasonic_Lumix_G_25mm_F1.7_ASPH_lens.jpg',
    prices:{USD:247,AUD:399,EUR:null,GBP:null,JPY:null,CAD:329,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-25mm-f1-7-asph-lens-h-h025',
  },

  'leica-dg-42-5mm-f1-2-nocticron': {
    name:'LEICA DG NOCTICRON 42.5mm F1.2', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00HXE4GZQ',
    focalLength:42.5, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.2, minAperture:16, weight:425, length:76.8, diameter:74.0,
    filterThread:67, minFocusDist:50, maxMagnification:0.20,
    elements:14, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2014, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Leica_DG_Nocticron_42.5mm_F1.2_01.jpg/1280px-Leica_DG_Nocticron_42.5mm_F1.2_01.jpg',
    prices:{USD:1597,AUD:2499,EUR:null,GBP:null,JPY:null,CAD:2149,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-nocticron-42-5mm-f1-2-asph-lens-h-ns043',
  },

  'lumix-g-42-5mm-f1-7': {
    name:'LUMIX G 42.5mm F1.7 ASPH.', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00H36U69Y',
    focalLength:42.5, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.7, minAperture:22, weight:130, length:50.0, diameter:55.0,
    filterThread:37, minFocusDist:31, maxMagnification:0.20,
    elements:10, groups:8, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2015, discontinued:false,
    imageUrl:null,
    prices:{USD:397,AUD:649,EUR:null,GBP:null,JPY:null,CAD:549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-42-5mm-f1-7-asph-power-ois-lens-h-hs043',
  },

  'leica-dg-200mm-f2-8': {
    name:'LEICA DG ELMARIT 200mm F2.8', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B0776C5KQH',
    focalLength:200, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm',
    maxAperture:2.8, minAperture:22, weight:1245, length:174.0, diameter:87.5,
    filterThread:77, minFocusDist:115, maxMagnification:0.20,
    elements:15, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:2997,AUD:4699,EUR:null,GBP:null,JPY:null,CAD:4049,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-elmarit-200mm-f2-8-power-ois-lens-h-es200',
  },

  /* ── LUMIX G Zooms (Micro Four Thirds) ── */
  'lumix-g-12-35mm-f2-8-ii': {
    name:'LUMIX G X Vario 12-35mm F2.8 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01MY1ICID',
    focalLength:null, focalLengthMin:12, focalLengthMax:35, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:305, length:73.8, diameter:67.6,
    filterThread:58, minFocusDist:25, maxMagnification:0.17,
    elements:14, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:799,AUD:1299,EUR:null,GBP:null,JPY:null,CAD:1099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-x-vario-12-35mm-f2-8-ii-lens-h-hsa12035',
  },

  'lumix-g-35-100mm-f2-8-ii': {
    name:'LUMIX G X Vario 35-100mm F2.8 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01MU3WOVP',
    focalLength:null, focalLengthMin:35, focalLengthMax:100, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:360, length:100.0, diameter:67.4,
    filterThread:58, minFocusDist:85, maxMagnification:0.10,
    elements:18, groups:13, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1097,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-x-vario-35-100mm-f2-8-ii-lens-h-hsa35100',
  },

  'leica-dg-8-18mm-f2-8-4': {
    name:'LEICA DG VARIO-ELMARIT 8-18mm F2.8-4', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B071QWM469',
    focalLength:null, focalLengthMin:8, focalLengthMax:18, focalLengthEquiv:'16-36mm',
    maxAperture:2.8, minAperture:22, weight:315, length:88.0, diameter:73.4,
    filterThread:67, minFocusDist:23, maxMagnification:0.12,
    elements:15, groups:10, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1097,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-vario-elmarit-8-18mm-f2-8-4-asph-lens-h-e08018',
  },

  'leica-dg-10-25mm-f1-7': {
    name:'LEICA DG VARIO-SUMMILUX 10-25mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B07RS4VRL7',
    focalLength:null, focalLengthMin:10, focalLengthMax:25, focalLengthEquiv:'20-50mm',
    maxAperture:1.7, minAperture:16, weight:690, length:128.0, diameter:87.6,
    filterThread:77, minFocusDist:28, maxMagnification:0.14,
    elements:17, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:1797,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-vario-summilux-10-25mm-f1-7-asph-lens-h-x1025',
  },

  'leica-dg-25-50mm-f1-7': {
    name:'LEICA DG VARIO-SUMMILUX 25-50mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B098R6QB2C',
    focalLength:null, focalLengthMin:25, focalLengthMax:50, focalLengthEquiv:'50-100mm',
    maxAperture:1.7, minAperture:16, weight:654, length:128.0, diameter:87.6,
    filterThread:77, minFocusDist:28, maxMagnification:0.18,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1797,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-vario-summilux-25-50mm-f1-7-asph-lens-h-x2550',
  },

  'leica-dg-12-60mm-f2-8-4': {
    name:'LEICA DG VARIO-ELMARIT 12-60mm F2.8-4', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01N7LGSZO',
    focalLength:null, focalLengthMin:12, focalLengthMax:60, focalLengthEquiv:'24-120mm',
    maxAperture:2.8, minAperture:22, weight:320, length:86.0, diameter:68.4,
    filterThread:62, minFocusDist:20, maxMagnification:0.30,
    elements:14, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1549,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-vario-elmarit-12-60mm-f2-8-4-asph-power-ois-lens-h-es12060',
  },

  'lumix-g-12-60mm-f3-5-5-6': {
    name:'LUMIX G Vario 12-60mm F3.5-5.6 O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01C56V72Q',
    focalLength:null, focalLengthMin:12, focalLengthMax:60, focalLengthEquiv:'24-120mm',
    maxAperture:3.5, minAperture:22, weight:210, length:71.0, diameter:66.0,
    filterThread:58, minFocusDist:20, maxMagnification:0.27,
    elements:11, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:799,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-vario-12-60mm-f3-5-5-6-asph-power-ois-lens-h-fs12060',
  },

  'lumix-g-12-32mm-f3-5-5-6': {
    name:'LUMIX G Vario 12-32mm F3.5-5.6 O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B00FYK2LE4',
    focalLength:null, focalLengthMin:12, focalLengthMax:32, focalLengthEquiv:'24-64mm',
    maxAperture:3.5, minAperture:22, weight:70, length:24.0, diameter:55.5,
    filterThread:37, minFocusDist:20, maxMagnification:0.13,
    elements:8, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:277,AUD:449,EUR:null,GBP:null,JPY:null,CAD:379,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-vario-12-32mm-f3-5-5-6-asph-mega-ois-lens-h-fs12032',
  },

  'leica-dg-50-200mm-f2-8-4': {
    name:'LEICA DG VARIO-ELMARIT 50-200mm F2.8-4', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B07B49V8QF',
    focalLength:null, focalLengthMin:50, focalLengthMax:200, focalLengthEquiv:'100-400mm',
    maxAperture:2.8, minAperture:22, weight:655, length:132.0, diameter:76.0,
    filterThread:67, minFocusDist:75, maxMagnification:0.21,
    elements:21, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:1697,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-vario-elmarit-50-200mm-f2-8-4-asph-power-ois-lens-h-es50200',
  },

  'lumix-g-14-140mm-f3-5-5-6-ii': {
    name:'LUMIX G Vario 14-140mm F3.5-5.6 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B07PZB3YKH',
    focalLength:null, focalLengthMin:14, focalLengthMax:140, focalLengthEquiv:'28-280mm',
    maxAperture:3.5, minAperture:22, weight:265, length:75.0, diameter:67.0,
    filterThread:58, minFocusDist:30, maxMagnification:0.25,
    elements:14, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-vario-14-140mm-f3-5-5-6-ii-asph-power-ois-lens-h-fsa14140',
  },

  'lumix-g-100-300mm-f4-5-6-ii': {
    name:'LUMIX G Vario 100-300mm F4-5.6 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01N0U4BY2',
    focalLength:null, focalLengthMin:100, focalLengthMax:300, focalLengthEquiv:'200-600mm',
    maxAperture:4.0, minAperture:22, weight:520, length:126.0, diameter:73.6,
    filterThread:67, minFocusDist:150, maxMagnification:0.21,
    elements:17, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-vario-100-300mm-f4-5-6-ii-power-ois-lens-h-fsa100300',
  },

  'leica-dg-100-400mm-f4-6-3-ii': {
    name:'LEICA DG VARIO-ELMAR 100-400mm F4-6.3 II', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B0CHT96YC2',
    focalLength:null, focalLengthMin:100, focalLengthMax:400, focalLengthEquiv:'200-800mm',
    maxAperture:4.0, minAperture:22, weight:985, length:172.0, diameter:83.0,
    filterThread:72, minFocusDist:130, maxMagnification:0.25,
    elements:20, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:1797,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/leica-dg-vario-elmar-100-400mm-f4-6-3-ii-asph-power-ois-lens-h-rsa100400',
  },

};

const LENS_DROPDOWN_GROUPS = [
  { label: '── LUMIX S Primes (L-Mount) ──', ids: ['lumix-s-18mm-f1-8', 'lumix-s-24mm-f1-8', 'lumix-s-35mm-f1-8', 'lumix-s-40mm-f2', 'lumix-s-50mm-f1-8', 'lumix-s-pro-50mm-f1-4', 'lumix-s-85mm-f1-8', 'lumix-s-100mm-f2-8-macro'] },
  { label: '── LUMIX S Zooms (L-Mount) ──',  ids: ['lumix-s-14-28mm-f4-5-6-macro', 'lumix-s-pro-16-35mm-f4', 'lumix-s-20-60mm-f3-5-5-6', 'lumix-s-24-60mm-f2-8', 'lumix-s-24-70mm-f2-8-pro', 'lumix-s-24-105mm-f4-macro', 'lumix-s-28-200mm-f4-7-1-macro', 'lumix-s-pro-70-200mm-f2-8', 'lumix-s-pro-70-200mm-f4', 'lumix-s-70-300mm-f4-5-5-6-macro'] },
  { label: '── LUMIX G Primes (MFT) ──',     ids: ['leica-dg-9mm-f1-7', 'leica-dg-12mm-f1-4', 'leica-dg-15mm-f1-7', 'lumix-g-20mm-f1-7-ii', 'leica-dg-25mm-f1-4-ii', 'lumix-g-25mm-f1-7', 'leica-dg-42-5mm-f1-2-nocticron', 'lumix-g-42-5mm-f1-7', 'leica-dg-200mm-f2-8'] },
  { label: '── LUMIX G Zooms (MFT) ──',      ids: ['leica-dg-8-18mm-f2-8-4', 'leica-dg-10-25mm-f1-7', 'lumix-g-12-32mm-f3-5-5-6', 'leica-dg-12-60mm-f2-8-4', 'lumix-g-12-60mm-f3-5-5-6', 'lumix-g-12-35mm-f2-8-ii', 'leica-dg-25-50mm-f1-7', 'lumix-g-35-100mm-f2-8-ii', 'leica-dg-50-200mm-f2-8-4', 'lumix-g-14-140mm-f3-5-5-6-ii', 'lumix-g-100-300mm-f4-5-6-ii', 'leica-dg-100-400mm-f4-6-3-ii'] },
];
