// Registered into the shared brand-data registry so multiple brand files
// can load on one page (see compare/). The data below is unchanged.
window.BRAND_DATA = window.BRAND_DATA || {};
window.BRAND_DATA['panasonic'] = (() => {
// ─────────────────────────────────────────────
// PANASONIC BRAND CONFIG
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Panasonic',
  slug:        'panasonic',
  families:    ['Lumix S (L-Mount)', 'Lumix G (Micro Four Thirds)'],
  brandSections: ['panasonic'],
  mount:       'L-Mount / MFT',
  heroCamera:  's1r-ii',
  cameras: {
    heroEyebrow:  'Lumix S & G',
    heroTitle:    '<span>Panasonic</span> Camera Comparison',
    heroSubtitle: 'Compare up to 3 Panasonic Lumix cameras side-by-side — full-frame L-Mount and Micro Four Thirds',
    headerTitle:  'Panasonic',
    defaultSelected: ['s5-ii', 's1r-ii', 'gh7'],
  },
  lenses: {
    heroEyebrow:  'LUMIX S & G Lenses',
    heroTitle:    '<span>Panasonic</span> Lens Comparison',
    heroSubtitle: 'Compare Panasonic LUMIX S (L-Mount) and LUMIX G (MFT) lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['lumix-s-50mm-f1-8', 'lumix-s-24-70mm-f2-8-pro', 'lumix-g-12-35mm-f2-8-ii'],
  },
  footerLinks: [
    { label: 'LUMIX S Series',   url: 'https://www.panasonic.com/global/consumer/lumix/s.html' },
    { label: 'LUMIX G Series',   url: 'https://www.panasonic.com/global/consumer/lumix/g.html' },
    { label: 'DPReview Panasonic', url: 'https://www.dpreview.com/products/panasonic' },
  ],
};

const REGISTERED_BRANDS = [
  { slug: 'fujifilm',  name: 'Fujifilm' },
  { slug: 'canon',     name: 'Canon' },
  { slug: 'sony',      name: 'Sony' },
  { slug: 'nikon',     name: 'Nikon' },
  { slug: 'panasonic', name: 'Panasonic' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards) — Lumix/Panasonic blue
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'Lumix S (Full-frame)': { bg: '#0a1530', text: '#6fa8ff' },
  'Lumix GH (MFT)':       { bg: '#0a1228', text: '#7fb0ff' },
  'Lumix G (MFT)':        { bg: '#0c1426', text: '#8ab4ff' },
  'Lumix Compact':        { bg: '#0e1832', text: '#9ec2ff' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE — Panasonic Lumix mirrorless (L-Mount + Micro Four Thirds).
// Panasonic-specific fields: vLog (V-Log / V-Log L gamma), dualNativeIso
// (Dual Native ISO sensor tech), openGate (Open Gate full-sensor max capture),
// proResInternal (internal Apple ProRes / ProRes RAW recording).
// Pricing: USD is the list/RRP; non-USD figures are APPROXIMATE RRPs derived
// from USD via regional ratios (refined as real RRP surfaces). Specs verified
// against Panasonic official pages + DPReview/Wikipedia (see
// openspec/changes/add-panasonic-brand/research/).
// ─────────────────────────────────────────────
const CAMERAS = {

  /* ── Lumix S (Full-frame L-Mount) ── */
  's1r-ii': {
    name:'Lumix S1R II', series:'Lumix S (Full-frame)', year:2025, discontinued:false,
    tagline:'44MP High-Res 8K Hybrid',
    productUrl:'https://shop.panasonic.com/products/lumix-s1rii-full-frame-mirrorless-digital-camera-dc-s1rm2',
    imageUrl:'https://shop.panasonic.com/cdn/shop/files/S1RII_S-E2460_front_K.jpg?v=1779313634&width=500',
    asin:'B0DY21GMBD',
    prices:{USD:3299,AUD:5299,EUR:3829,GBP:3149,JPY:545000,CAD:4549,SGD:4699},
    sensorMP:44.3, sensorType:'Full-frame BSI CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:91.8, weight:795, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle / Train / Airplane',
    ibis:true, ibisStops:8.0, maxBurst:40,
    maxVideoRes:'8.1K / 30P',
    logVideo:true,
    vLog:'V-Log', dualNativeIso:true, openGate:'6.4K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's5-ii': {
    name:'Lumix S5 II', series:'Lumix S (Full-frame)', year:2023, discontinued:false,
    tagline:'Phase-Detect Hybrid Full-Frame',
    productUrl:'https://shop.panasonic.com/products/s5m2-full-frame-mirrorless-camera-body',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Panasonic_LUMIX_S5_II_%2852682131682%29.jpg/500px-Panasonic_LUMIX_S5_II_%2852682131682%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_LUMIX_S5_II_(52682131682).jpg"},
    asin:'B0BR8JMCYG',
    prices:{USD:1999,AUD:3199,EUR:2299,GBP:1899,JPY:330000,CAD:2749,SGD:2849},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:90.1, weight:740, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:30,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:'6K', proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:370, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's1-ii': {
    name:'Lumix S1 II', series:'Lumix S (Full-frame)', year:2025, discontinued:false,
    tagline:'Partially-Stacked Hybrid Flagship',
    productUrl:'https://shop.panasonic.com/products/lumix-s1ii-full-frame-camera-partially-stacked-sensor-dc-s1m2',
    imageUrl:null,
    asin:'B0F8MHCD7V',
    prices:{USD:3199,AUD:5099,EUR:3699,GBP:3049,JPY:528000,CAD:4399,SGD:4549},
    sensorMP:24.1, sensorType:'Full-frame Partially-Stacked BSI CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:91.8, weight:800, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle / Train / Airplane',
    ibis:true, ibisStops:8.0, maxBurst:70,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log', dualNativeIso:true, openGate:'6K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's5-iix': {
    name:'Lumix S5 IIX', series:'Lumix S (Full-frame)', year:2023, discontinued:false,
    tagline:'All-Black Pro Video S5 II',
    productUrl:'https://shop.panasonic.com/products/s5m2x-full-frame-mirrorless-camera-body',
    imageUrl:null,
    asin:'B0BR8FY5HT',
    prices:{USD:2199,AUD:3499,EUR:2549,GBP:2099,JPY:363000,CAD:3049,SGD:3149},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:90.1, weight:740, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:30,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:'6K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:370, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's9': {
    name:'Lumix S9', series:'Lumix S (Full-frame)', year:2024, discontinued:false,
    tagline:'Compact Full-Frame Creator Body',
    productUrl:'https://shop.panasonic.com/products/lumix-s9-full-frame-mirrorless-camera',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Panasonic_LUMIX_S9_front_view.jpg/500px-Panasonic_LUMIX_S9_front_view.jpg',
    imageCredit:{author:"Mateusz Stopczynski", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_LUMIX_S9_front_view.jpg"},
    asin:'B0D4FBF5NK',
    prices:{USD:1499,AUD:2399,EUR:1749,GBP:1499,JPY:247000,CAD:2049,SGD:2149},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:126.0, height:73.9, depth:46.7, weight:486, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilting Touch',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:30,
    maxVideoRes:'6K / 30P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:'6K', proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:470, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's1h': {
    name:'Lumix S1H', series:'Lumix S (Full-frame)', year:2019, discontinued:false,
    tagline:'Cinema-Grade Full-Frame',
    productUrl:'https://shop.panasonic.com/products/s1h-full-frame-mirrorless-camera-body',
    imageUrl:null,
    asin:'B07WSRHXPR',
    prices:{USD:3499,AUD:5599,EUR:4049,GBP:3299,JPY:577000,CAD:4799,SGD:4999},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:151.0, height:114.2, depth:110.4, weight:1052, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2330, lcdType:'Tri-axis Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:9,
    maxVideoRes:'6K / 24P (3:2 Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'6K', proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix S — discontinued (USD list only) ── */
  's1': {
    name:'Lumix S1', series:'Lumix S (Full-frame)', year:2019, discontinued:true,
    tagline:'Original Full-Frame Hybrid',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:2499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:148.9, height:110.0, depth:96.7, weight:1017, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tri-axis Tilt Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human (face / eye / body)',
    ibis:true, ibisStops:6.0, maxBurst:9,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log (paid upgrade)', dualNativeIso:true, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× XQD + 1× SD UHS-II', batteryLife:380, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's1r': {
    name:'Lumix S1R', series:'Lumix S (Full-frame)', year:2019, discontinued:true,
    tagline:'Original 47MP High-Res',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Panasonic.Lumix.S1R.50f1.4.jpg/500px-Panasonic.Lumix.S1R.50f1.4.jpg',
    imageCredit:{author:"Bautsch", licence:"CC0", licenceUrl:"http://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Panasonic.Lumix.S1R.50f1.4.jpg"},
    asin:null,
    prices:{USD:3699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:47.3, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:148.9, height:110.0, depth:96.7, weight:1020, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2100, lcdType:'Tri-axis Tilt Touch',
    evfType:'EVF', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human (face / eye / body)',
    ibis:true, ibisStops:6.0, maxBurst:9,
    maxVideoRes:'4K / 60P',
    logVideo:false,
    vLog:null, dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× XQD + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  's5': {
    name:'Lumix S5', series:'Lumix S (Full-frame)', year:2020, discontinued:true,
    tagline:'Compact Full-Frame Hybrid',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame CMOS', processor:'Venus Engine',
    width:132.6, height:97.1, depth:81.9, weight:714, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:7,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log / V-Log L', dualNativeIso:true, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:440, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix GH (Micro Four Thirds) ── */
  'gh7': {
    name:'Lumix GH7', series:'Lumix GH (MFT)', year:2024, discontinued:false,
    tagline:'ProRes RAW Video Flagship',
    productUrl:'https://shop.panasonic.com/products/gh7-mirrorless-camera',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Panasonic_LUMIX_GH7_front_view.jpg/500px-Panasonic_LUMIX_GH7_front_view.jpg',
    imageCredit:{author:"Mateusz Stopczynski", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_LUMIX_GH7_front_view.jpg"},
    asin:'B0D613NW2M',
    prices:{USD:2199,AUD:3499,EUR:2549,GBP:2099,JPY:363000,CAD:3049,SGD:3149},
    sensorMP:25.2, sensorType:'Micro Four Thirds BSI CMOS', processor:'Venus Engine',
    width:138.4, height:100.3, depth:99.6, weight:805, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle',
    ibis:true, ibisStops:7.5, maxBurst:75,
    maxVideoRes:'5.7K / 30P (Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'5.8K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'gh6': {
    name:'Lumix GH6', series:'Lumix GH (MFT)', year:2022, discontinued:false,
    tagline:'High-Res MFT Video Workhorse',
    productUrl:'https://shop.panasonic.com/products/gh6-mirrorless-camera-body',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Panasonic_Lumix_GH6_with_25mm_leica_lens.jpg/500px-Panasonic_Lumix_GH6_with_25mm_leica_lens.jpg',
    imageCredit:{author:"Peachyeung316", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_GH6_with_25mm_leica_lens.jpg"},
    asin:'B09T2RJ27P',
    prices:{USD:2199,AUD:3499,EUR:2549,GBP:2099,JPY:363000,CAD:3049,SGD:3149},
    sensorMP:25.2, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:138.4, height:100.3, depth:99.6, weight:823, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Tilt & Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:7.5, maxBurst:75,
    maxVideoRes:'5.7K / 60P (Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'5.8K', proResInternal:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× CFexpress Type B + 1× SD UHS-II', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix GH — discontinued (USD list only) ── */
  'gh5-ii': {
    name:'Lumix GH5 II', series:'Lumix GH (MFT)', year:2021, discontinued:true,
    tagline:'Live-Streaming MFT Hybrid',
    productUrl:null,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Panasonic_Lumix_GH5_II_with_len.jpg/500px-Panasonic_Lumix_GH5_II_with_len.jpg',
    imageCredit:{author:"Peachyeung316", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_GH5_II_with_len.jpg"},
    asin:null,
    prices:{USD:1699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:138.5, height:98.1, depth:87.4, weight:727, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:12,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log L', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'gh5': {
    name:'Lumix GH5', series:'Lumix GH (MFT)', year:2017, discontinued:true,
    tagline:'Landmark MFT Video Body',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:138.5, height:98.1, depth:87.4, weight:725, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:1620, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.76,
    faceDetection:true, subjectDetection:'Human (face / eye / body)',
    ibis:true, ibisStops:5.0, maxBurst:12,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log L (paid upgrade)', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:410, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix G (Micro Four Thirds) ── */
  'g9-ii': {
    name:'Lumix G9 II', series:'Lumix G (MFT)', year:2023, discontinued:false,
    tagline:'Phase-Detect MFT Photo Flagship',
    productUrl:'https://shop.panasonic.com/products/g9m2-mirrorless-camera-body',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Panasonic_Lumix_G9_II.jpg/500px-Panasonic_Lumix_G9_II.jpg',
    imageCredit:{author:"Peachyeung316", licence:"CC BY-SA 4.0", licenceUrl:"https://creativecommons.org/licenses/by-sa/4.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_G9_II.jpg"},
    asin:'B0CHTHLVHS',
    prices:{USD:1899,AUD:2999,EUR:2199,GBP:1799,JPY:313000,CAD:2599,SGD:2699},
    sensorMP:25.2, sensorType:'Micro Four Thirds BSI CMOS', processor:'Venus Engine',
    width:134.3, height:102.3, depth:90.1, weight:658, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.80,
    faceDetection:true, subjectDetection:'Human / Animal / Car / Motorcycle',
    ibis:true, ibisStops:8.0, maxBurst:60,
    maxVideoRes:'5.8K / 30P (Open Gate)',
    logVideo:true,
    vLog:'V-Log / V-Gamut', dualNativeIso:true, openGate:'5.8K', proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:390, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'g100d': {
    name:'Lumix G100D', series:'Lumix G (MFT)', year:2024, discontinued:false,
    tagline:'Compact Vlogging MFT',
    productUrl:'https://shop.panasonic.com/products/g100d-mirrorless-camera-12-32mm-f3-5-5-6-lens',
    imageUrl:null,
    asin:'B0CQCDTT82',
    prices:{USD:597,AUD:999,EUR:699,GBP:599,JPY:99000,CAD:829,SGD:869},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:115.6, height:82.5, depth:54.2, weight:412, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.73,
    faceDetection:true, subjectDetection:'Human (face / eye)',
    ibis:false, ibisStops:null, maxBurst:10,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    vLog:'V-Log L', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:270, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix G — discontinued (USD list only) ── */
  'g9': {
    name:'Lumix G9', series:'Lumix G (MFT)', year:2017, discontinued:true,
    tagline:'Original MFT Photo Flagship',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:136.9, height:97.3, depth:91.6, weight:658, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1040, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:3.68, evfMag:0.83,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye / body)',
    ibis:true, ibisStops:6.5, maxBurst:60,
    maxVideoRes:'4K / 60P',
    logVideo:true,
    vLog:'V-Log L (paid upgrade)', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'gx9': {
    name:'Lumix GX9', series:'Lumix G (MFT)', year:2018, discontinued:true,
    tagline:'Rangefinder-Style Street Compact',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:124.0, height:72.1, depth:46.8, weight:407, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1240, lcdType:'Tilting Touch',
    evfType:'Tilting EVF', evfDots:2.76, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human (face / eye)',
    ibis:true, ibisStops:4.0, maxBurst:9,
    maxVideoRes:'4K / 30P',
    logVideo:false,
    vLog:null, dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:260, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  'g95': {
    name:'Lumix G95', series:'Lumix G (MFT)', year:2019, discontinued:true,
    tagline:'All-Rounder MFT Hybrid',
    productUrl:null,
    imageUrl:null,
    asin:null,
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:20.3, sensorType:'Micro Four Thirds CMOS', processor:'Venus Engine',
    width:130.4, height:93.5, depth:77.4, weight:536, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1240, lcdType:'Free-angle Touch',
    evfType:'EVF', evfDots:2.36, evfMag:0.74,
    faceDetection:true, subjectDetection:'Human (face / eye)',
    ibis:true, ibisStops:5.0, maxBurst:9,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    vLog:'V-Log L', dualNativeIso:false, openGate:null, proResInternal:false,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:290, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
  },

  /* ── Lumix Compact (fixed-lens) ── */
  'l10': {
    name:'Lumix L10', series:'Lumix Compact', year:2026, discontinued:false,
    tagline:'Premium Fixed-Lens Compact',
    productUrl:'https://shop.panasonic.com/products/lumix-l10-premium-point-shoot-digital-camera-24-75mm-zoom-lens',
    imageUrl:null,
    asin:null,
    prices:{USD:1499,AUD:2399,EUR:1749,GBP:1499,JPY:247000,CAD:2049,SGD:2149},
    sensorMP:20.4, sensorType:'Micro Four Thirds BSI CMOS', processor:'Venus Engine',
    width:127.1, height:73.9, depth:66.9, weight:508, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1840, lcdType:'Free-angle Touch',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal (face / eye)',
    ibis:false, ibisStops:null, maxBurst:30,
    maxVideoRes:'5.6K / 60P (Open Gate)',
    logVideo:true,
    vLog:'V-Log', dualNativeIso:true, openGate:'5.6K', proResInternal:false,
    bluetooth:'5.0', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:null, usbCharging:true,
    lensType:'Fixed', lensSpec:'24-75mm equiv. f/1.7-2.8',
  },

};

const CAMERA_ORDER = [
  's1r-ii', 's1-ii', 's5-ii', 's5-iix', 's9', 's1h', 's1', 's1r', 's5',
  'gh7', 'gh6', 'gh5-ii', 'gh5',
  'g9-ii', 'g100d', 'g9', 'gx9', 'g95',
  'l10',
];

const DROPDOWN_GROUPS = [
  { label: '── Lumix S — Full-Frame (L-Mount) ──', ids: ['s1r-ii', 's1-ii', 's5-ii', 's5-iix', 's9', 's1h', 's1', 's1r', 's5'] },
  { label: '── Lumix GH — Micro Four Thirds ──',   ids: ['gh7', 'gh6', 'gh5-ii', 'gh5'] },
  { label: '── Lumix G — Micro Four Thirds ──',    ids: ['g9-ii', 'g100d', 'g9', 'gx9', 'g95'] },
  { label: '── Lumix Compact (fixed-lens) ──',     ids: ['l10'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE — Panasonic LUMIX (first-party only; Leica DG are
// Leica-designed / Panasonic-made → manufacturer 'Panasonic').
// line: 'LUMIX S' (L-Mount, full-frame) | 'LUMIX G' (MFT, 2.0× crop equiv).
// `priceIncomplete: true` ships an item with USD (+ any confirmed regional)
// while regional RRP backfill is pending (see check-prices-and-buy-links).
// ─────────────────────────────────────────────
const LENSES = {

  /* ── LUMIX S Primes (L-Mount, full-frame) ── */
  'lumix-s-50mm-f1-8': {
    name:'LUMIX S 50mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B093NKZCR4',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.8, minAperture:22, weight:300, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:45, maxMagnification:0.14,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:447,AUD:699,EUR:null,GBP:null,JPY:null,CAD:599,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-50mm-f1-8-l-mount-lens',
  },

  'lumix-s-18mm-f1-8': {
    name:'LUMIX S 18mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B0BDGGZ7NS',
    focalLength:18, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'18mm',
    maxAperture:1.8, minAperture:22, weight:340, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:18, maxMagnification:0.08,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:747,AUD:1199,EUR:null,GBP:null,JPY:null,CAD:999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-18mm-f1-8-l-mount-lens',
  },

  'lumix-s-24mm-f1-8': {
    name:'LUMIX S 24mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B09F6WGXHM',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.8, minAperture:22, weight:310, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:24, maxMagnification:0.15,
    elements:12, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-24mm-f1-8-l-mount-lens',
  },

  'lumix-s-35mm-f1-8': {
    name:'LUMIX S 35mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B09LD9DQG5',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.8, minAperture:22, weight:295, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:24, maxMagnification:0.15,
    elements:11, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Panasonic_Lumix_S_35mm_F1.8_%2852972339626%29.jpg/500px-Panasonic_Lumix_S_35mm_F1.8_%2852972339626%29.jpg',
    imageCredit:{author:"Henry Söderlund from Helsinki, Finland", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_S_35mm_F1.8_(52972339626).jpg"},
    prices:{USD:697,AUD:1099,EUR:null,GBP:null,JPY:null,CAD:949,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-35mm-f1-8-l-mount',
  },

  'lumix-s-85mm-f1-8': {
    name:'LUMIX S 85mm F1.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B08M24BV12',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.8, minAperture:22, weight:355, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:80, maxMagnification:0.13,
    elements:9, groups:8, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-85mm-f1-8-l-mount-lens',
  },

  'lumix-s-40mm-f2': {
    name:'LUMIX S 40mm F2', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B0GY21YLS2',
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.0, minAperture:22, weight:300, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:23, maxMagnification:0.15,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-s-series-40mm-f2-l-mount-camera-lens',
  },

  'lumix-s-pro-50mm-f1-4': {
    name:'LUMIX S PRO 50mm F1.4', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B07N84VZ4Z',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:955, length:130.0, diameter:90.0,
    filterThread:77, minFocusDist:44, maxMagnification:0.15,
    elements:13, groups:11, blades:11, afType:'Dual Phase Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:2297,AUD:3599,EUR:null,GBP:null,JPY:null,CAD:3099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-50mm-f1-4-l-mount-lens',
  },

  'lumix-s-100mm-f2-8-macro': {
    name:'LUMIX S 100mm F2.8 MACRO', manufacturer:'Panasonic', line:'LUMIX S', type:'Prime', asin:'B0CRSNV73W',
    focalLength:100, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'100mm',
    maxAperture:2.8, minAperture:22, weight:298, length:82.0, diameter:73.6,
    filterThread:67, minFocusDist:20, maxMagnification:1.0,
    elements:13, groups:11, blades:9, afType:'Dual Phase Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1599,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-100mm-l-mount-lens',
  },

  /* ── LUMIX S Zooms (L-Mount, full-frame) ── */
  'lumix-s-24-70mm-f2-8-pro': {
    name:'LUMIX S PRO 24-70mm F2.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07WRMBFF3',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:935, length:140.0, diameter:90.9,
    filterThread:82, minFocusDist:37, maxMagnification:0.25,
    elements:18, groups:16, blades:11, afType:'Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:2197,AUD:3399,EUR:null,GBP:null,JPY:null,CAD:2899,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-pro-24-70mm-f2-8-l-mount-lens',
  },

  'lumix-s-pro-16-35mm-f4': {
    name:'LUMIX S PRO 16-35mm F4', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B00JEZ0OFS',
    focalLength:null, focalLengthMin:16, focalLengthMax:35, focalLengthEquiv:'16-35mm',
    maxAperture:4.0, minAperture:22, weight:500, length:100.0, diameter:84.6,
    filterThread:77, minFocusDist:25, maxMagnification:0.23,
    elements:12, groups:9, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:1497,AUD:2299,EUR:null,GBP:null,JPY:null,CAD:1999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-pro-16-35mm-f4-l-mount-lens',
  },

  'lumix-s-14-28mm-f4-5-6-macro': {
    name:'LUMIX S 14-28mm F4-5.6 MACRO', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B0BR8GF76K',
    focalLength:null, focalLengthMin:14, focalLengthMax:28, focalLengthEquiv:'14-28mm',
    maxAperture:4.0, minAperture:22, weight:345, length:89.6, diameter:84.0,
    filterThread:77, minFocusDist:15, maxMagnification:0.50,
    elements:14, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-14-28mm-f4-5-6-l-mount-lens',
  },

  'lumix-s-20-60mm-f3-5-5-6': {
    name:'LUMIX S 20-60mm F3.5-5.6', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B088VSF94W',
    focalLength:null, focalLengthMin:20, focalLengthMax:60, focalLengthEquiv:'20-60mm',
    maxAperture:3.5, minAperture:22, weight:350, length:87.2, diameter:77.4,
    filterThread:67, minFocusDist:15, maxMagnification:0.43,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:599,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-20-60mm-f3-5-5-6-asph-lens',
  },

  'lumix-s-24-60mm-f2-8': {
    name:'LUMIX S 24-60mm F2.8', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B0F8P9V67L',
    focalLength:null, focalLengthMin:24, focalLengthMax:60, focalLengthEquiv:'24-60mm',
    maxAperture:2.8, minAperture:22, weight:544, length:99.7, diameter:77.5,
    filterThread:67, minFocusDist:30, maxMagnification:0.20,
    elements:13, groups:12, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:1099,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-24-60mm-f2-8-l-mount-lens-s-e2460',
  },

  'lumix-s-24-105mm-f4-macro': {
    name:'LUMIX S 24-105mm F4 MACRO O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07N83WBTF',
    focalLength:null, focalLengthMin:24, focalLengthMax:105, focalLengthEquiv:'24-105mm',
    maxAperture:4.0, minAperture:22, weight:680, length:118.0, diameter:84.0,
    filterThread:77, minFocusDist:30, maxMagnification:0.50,
    elements:16, groups:13, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Panasonic_Lumix_S_24-105mm_F4_Macro_O.I.S._20260621150950.jpg/500px-Panasonic_Lumix_S_24-105mm_F4_Macro_O.I.S._20260621150950.jpg',
    imageCredit:{author:"TurnOnTheNight", licence:"CC0", licenceUrl:"http://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_S_24-105mm_F4_Macro_O.I.S._20260621150950.jpg"},
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-r24105-24-105mm-f4-l-mount-lens',
  },

  'lumix-s-28-200mm-f4-7-1-macro': {
    name:'LUMIX S 28-200mm F4-7.1 MACRO O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B0CW8722BG',
    focalLength:null, focalLengthMin:28, focalLengthMax:200, focalLengthEquiv:'28-200mm',
    maxAperture:4.0, minAperture:22, weight:413, length:93.4, diameter:77.3,
    filterThread:67, minFocusDist:14, maxMagnification:0.50,
    elements:17, groups:13, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:897,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-28-200mm-l-mount-lens',
  },

  'lumix-s-pro-70-200mm-f2-8': {
    name:'LUMIX S PRO 70-200mm F2.8 O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07ZZQ3DCC',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1570, length:208.6, diameter:94.4,
    filterThread:82, minFocusDist:95, maxMagnification:0.21,
    elements:22, groups:17, blades:11, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:2597,AUD:3999,EUR:null,GBP:null,JPY:null,CAD:3499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-pro-70-200mm-f2-8-l-mount-lens',
  },

  'lumix-s-pro-70-200mm-f4': {
    name:'LUMIX S PRO 70-200mm F4 O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B07N844X8Q',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:4.0, minAperture:22, weight:985, length:179.0, diameter:84.4,
    filterThread:77, minFocusDist:92, maxMagnification:0.25,
    elements:23, groups:17, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Panasonic_Lumix_S_PRO_70-200mm_F4_O.I.S._%2851248180327%29.jpg/500px-Panasonic_Lumix_S_PRO_70-200mm_F4_O.I.S._%2851248180327%29.jpg',
    imageCredit:{author:"Henry Söderlund", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_S_PRO_70-200mm_F4_O.I.S._(51248180327).jpg"},
    prices:{USD:1697,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-pro-70-200mm-f4-l-mount-lens',
  },

  'lumix-s-70-300mm-f4-5-5-6-macro': {
    name:'LUMIX S 70-300mm F4.5-5.6 MACRO O.I.S.', manufacturer:'Panasonic', line:'LUMIX S', type:'Zoom', asin:'B08XX5GTQZ',
    focalLength:null, focalLengthMin:70, focalLengthMax:300, focalLengthEquiv:'70-300mm',
    maxAperture:4.5, minAperture:22, weight:790, length:148.0, diameter:84.0,
    filterThread:77, minFocusDist:54, maxMagnification:0.50,
    elements:17, groups:11, blades:9, afType:'Linear Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Panasonic_Lumix_S_70-300mm_F4.5-5.6_Macro_O.I.S._20260621143312.jpg/500px-Panasonic_Lumix_S_70-300mm_F4.5-5.6_Macro_O.I.S._20260621143312.jpg',
    imageCredit:{author:"TurnOnTheNight", licence:"CC0", licenceUrl:"http://creativecommons.org/publicdomain/zero/1.0/deed.en", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_S_70-300mm_F4.5-5.6_Macro_O.I.S._20260621143312.jpg"},
    prices:{USD:1147,AUD:1799,EUR:null,GBP:null,JPY:null,CAD:1549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/s-series-70-300mm-f4-5-5-6-l-mount-lens',
  },

  /* ── LUMIX G Primes (Micro Four Thirds, 2.0× crop equiv) ── */
  'leica-dg-9mm-f1-7': {
    name:'LEICA DG SUMMILUX 9mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B0B1K7ZCDF',
    focalLength:9, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'18mm',
    maxAperture:1.7, minAperture:16, weight:130, length:52.0, diameter:60.3,
    filterThread:55, minFocusDist:9.5, maxMagnification:0.25,
    elements:12, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:799,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-9mm-f1-7-asph-leica-lens',
  },

  'leica-dg-12mm-f1-4': {
    name:'LEICA DG SUMMILUX 12mm F1.4', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B01H1MNW68',
    focalLength:12, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.4, minAperture:16, weight:335, length:70.0, diameter:70.0,
    filterThread:62, minFocusDist:20, maxMagnification:0.10,
    elements:15, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:1297,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-12mm-f1-4-asph-leica-lens',
  },

  'leica-dg-15mm-f1-7': {
    name:'LEICA DG SUMMILUX 15mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00J8HV6DG',
    focalLength:15, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'30mm',
    maxAperture:1.7, minAperture:16, weight:115, length:36.0, diameter:57.5,
    filterThread:46, minFocusDist:20, maxMagnification:0.10,
    elements:9, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2014, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-15mm-f1-7-asph-leica-lens',
  },

  'lumix-g-20mm-f1-7-ii': {
    name:'LUMIX G 20mm F1.7 II ASPH.', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00DJS830Y',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:1.7, minAperture:16, weight:87, length:25.5, diameter:63.0,
    filterThread:46, minFocusDist:20, maxMagnification:0.13,
    elements:7, groups:5, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:397,AUD:649,EUR:null,GBP:null,JPY:null,CAD:549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-20mm-f1-7-asph-lens',
  },

  'leica-dg-25mm-f1-4-ii': {
    name:'LEICA DG SUMMILUX 25mm F1.4 II', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B07X76CG5S',
    focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:200, length:54.5, diameter:63.0,
    filterThread:46, minFocusDist:30, maxMagnification:0.11,
    elements:9, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-25mm-f1-4-aph-leica-lens',
  },

  'lumix-g-25mm-f1-7': {
    name:'LUMIX G 25mm F1.7 ASPH.', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B014RD6RC0',
    focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.7, minAperture:22, weight:125, length:52.0, diameter:60.8,
    filterThread:46, minFocusDist:25, maxMagnification:0.14,
    elements:8, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2015, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Panasonic_Lumix_G_25mm_F1.7_ASPH_lens.jpg/500px-Panasonic_Lumix_G_25mm_F1.7_ASPH_lens.jpg',
    imageCredit:{author:"AlbertGy", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0", source:"https://commons.wikimedia.org/wiki/File:Panasonic_Lumix_G_25mm_F1.7_ASPH_lens.jpg"},
    prices:{USD:247,AUD:399,EUR:null,GBP:null,JPY:null,CAD:329,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-25mm-f1-7-asph-lens',
  },

  'leica-dg-42-5mm-f1-2-nocticron': {
    name:'LEICA DG NOCTICRON 42.5mm F1.2', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00HXE4GZQ',
    focalLength:42.5, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.2, minAperture:16, weight:425, length:76.8, diameter:74.0,
    filterThread:67, minFocusDist:50, maxMagnification:0.20,
    elements:14, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2014, discontinued:false,
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Leica_DG_Nocticron_42.5mm_F1.2_01.jpg/500px-Leica_DG_Nocticron_42.5mm_F1.2_01.jpg',
    imageCredit:{author:"456 Photo", licence:"CC BY 2.0", licenceUrl:"https://creativecommons.org/licenses/by/2.0", source:"https://commons.wikimedia.org/wiki/File:Leica_DG_Nocticron_42.5mm_F1.2_01.jpg"},
    prices:{USD:1597,AUD:2499,EUR:null,GBP:null,JPY:null,CAD:2149,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-42-5mm-f1-2-asph-leica-lens',
  },

  'lumix-g-42-5mm-f1-7': {
    name:'LUMIX G 42.5mm F1.7 ASPH.', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B00H36U69Y',
    focalLength:42.5, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.7, minAperture:22, weight:130, length:50.0, diameter:55.0,
    filterThread:37, minFocusDist:31, maxMagnification:0.20,
    elements:10, groups:8, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2015, discontinued:false,
    imageUrl:null,
    prices:{USD:397,AUD:649,EUR:null,GBP:null,JPY:null,CAD:549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-42-5mm-f1-7-asph-lens',
  },

  'leica-dg-200mm-f2-8': {
    name:'LEICA DG ELMARIT 200mm F2.8', manufacturer:'Panasonic', line:'LUMIX G', type:'Prime', asin:'B0776C5KQH',
    focalLength:200, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm',
    maxAperture:2.8, minAperture:22, weight:1245, length:174.0, diameter:87.5,
    filterThread:77, minFocusDist:115, maxMagnification:0.20,
    elements:15, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:2997,AUD:4699,EUR:null,GBP:null,JPY:null,CAD:4049,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-200mm-f2-8-asph-leica-1-4x-teleconverter',
  },

  /* ── LUMIX G Zooms (Micro Four Thirds) ── */
  'lumix-g-12-35mm-f2-8-ii': {
    name:'LUMIX G X Vario 12-35mm F2.8 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01MY1ICID',
    focalLength:null, focalLengthMin:12, focalLengthMax:35, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:305, length:73.8, diameter:67.6,
    filterThread:58, minFocusDist:25, maxMagnification:0.17,
    elements:14, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:799,AUD:1299,EUR:null,GBP:null,JPY:null,CAD:1099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-12-35mm-f2-8-asph-leica-lens',
  },

  'lumix-g-35-100mm-f2-8-ii': {
    name:'LUMIX G X Vario 35-100mm F2.8 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01MU3WOVP',
    focalLength:null, focalLengthMin:35, focalLengthMax:100, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:360, length:100.0, diameter:67.4,
    filterThread:58, minFocusDist:85, maxMagnification:0.10,
    elements:18, groups:13, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1097,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-35-100mm-f2-8-asph-lens-1',
  },

  'leica-dg-8-18mm-f2-8-4': {
    name:'LEICA DG VARIO-ELMARIT 8-18mm F2.8-4', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B071QWM469',
    focalLength:null, focalLengthMin:8, focalLengthMax:18, focalLengthEquiv:'16-36mm',
    maxAperture:2.8, minAperture:22, weight:315, length:88.0, diameter:73.4,
    filterThread:67, minFocusDist:23, maxMagnification:0.12,
    elements:15, groups:10, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1097,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1479,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-8-18mm-f2-8-4-0-leica-lens',
  },

  'leica-dg-10-25mm-f1-7': {
    name:'LEICA DG VARIO-SUMMILUX 10-25mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B07RS4VRL7',
    focalLength:null, focalLengthMin:10, focalLengthMax:25, focalLengthEquiv:'20-50mm',
    maxAperture:1.7, minAperture:16, weight:690, length:128.0, diameter:87.6,
    filterThread:77, minFocusDist:28, maxMagnification:0.14,
    elements:17, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:1797,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-10-25mm-f1-7-asph-leica-lens',
  },

  'leica-dg-25-50mm-f1-7': {
    name:'LEICA DG VARIO-SUMMILUX 25-50mm F1.7', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B098R6QB2C',
    focalLength:null, focalLengthMin:25, focalLengthMax:50, focalLengthEquiv:'50-100mm',
    maxAperture:1.7, minAperture:16, weight:654, length:128.0, diameter:87.6,
    filterThread:77, minFocusDist:28, maxMagnification:0.18,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1797,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-25-50mm-f1-7-asph-leica-lens',
  },

  'leica-dg-12-60mm-f2-8-4': {
    name:'LEICA DG VARIO-ELMARIT 12-60mm F2.8-4', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01N7LGSZO',
    focalLength:null, focalLengthMin:12, focalLengthMax:60, focalLengthEquiv:'24-120mm',
    maxAperture:2.8, minAperture:22, weight:320, length:86.0, diameter:68.4,
    filterThread:62, minFocusDist:20, maxMagnification:0.30,
    elements:14, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:997,AUD:1549,EUR:null,GBP:null,JPY:null,CAD:1349,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-12-60mm-f2-8-4-0-asph-leica-lens',
  },

  'lumix-g-12-60mm-f3-5-5-6': {
    name:'LUMIX G Vario 12-60mm F3.5-5.6 O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01C56V72Q',
    focalLength:null, focalLengthMin:12, focalLengthMax:60, focalLengthEquiv:'24-120mm',
    maxAperture:3.5, minAperture:22, weight:210, length:71.0, diameter:66.0,
    filterThread:58, minFocusDist:20, maxMagnification:0.27,
    elements:11, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:497,AUD:799,EUR:null,GBP:null,JPY:null,CAD:679,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-12-60mm-f3-5-5-6-asph-lens',
  },

  'lumix-g-12-32mm-f3-5-5-6': {
    name:'LUMIX G Vario 12-32mm F3.5-5.6 O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B00FYK2LE4',
    focalLength:null, focalLengthMin:12, focalLengthMax:32, focalLengthEquiv:'24-64mm',
    maxAperture:3.5, minAperture:22, weight:70, length:24.0, diameter:55.5,
    filterThread:37, minFocusDist:20, maxMagnification:0.13,
    elements:8, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:277,AUD:449,EUR:null,GBP:null,JPY:null,CAD:379,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/lumix-g-vario-12-32mm-f3-5-5-6-asph-mega-ois-lens-h-fs12032',
  },

  'leica-dg-50-200mm-f2-8-4': {
    name:'LEICA DG VARIO-ELMARIT 50-200mm F2.8-4', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B07B49V8QF',
    focalLength:null, focalLengthMin:50, focalLengthMax:200, focalLengthEquiv:'100-400mm',
    maxAperture:2.8, minAperture:22, weight:655, length:132.0, diameter:76.0,
    filterThread:67, minFocusDist:75, maxMagnification:0.21,
    elements:21, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:1697,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-50-200mm-f2-8-4-0-leica-lens',
  },

  'lumix-g-14-140mm-f3-5-5-6-ii': {
    name:'LUMIX G Vario 14-140mm F3.5-5.6 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B07PZB3YKH',
    focalLength:null, focalLengthMin:14, focalLengthMax:140, focalLengthEquiv:'28-280mm',
    maxAperture:3.5, minAperture:22, weight:265, length:75.0, diameter:67.0,
    filterThread:58, minFocusDist:30, maxMagnification:0.25,
    elements:14, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-14-140mm-f4-0-5-6-asph-lens',
  },

  'lumix-g-100-300mm-f4-5-6-ii': {
    name:'LUMIX G Vario 100-300mm F4-5.6 II O.I.S.', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B01N0U4BY2',
    focalLength:null, focalLengthMin:100, focalLengthMax:300, focalLengthEquiv:'200-600mm',
    maxAperture:4.0, minAperture:22, weight:520, length:126.0, diameter:73.6,
    filterThread:67, minFocusDist:150, maxMagnification:0.21,
    elements:17, groups:12, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:597,AUD:949,EUR:null,GBP:null,JPY:null,CAD:799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-100-300mm-f4-0-5-6-asph-lens',
  },

  'leica-dg-100-400mm-f4-6-3-ii': {
    name:'LEICA DG VARIO-ELMAR 100-400mm F4-6.3 II', manufacturer:'Panasonic', line:'LUMIX G', type:'Zoom', asin:'B0CHT96YC2',
    focalLength:null, focalLengthMin:100, focalLengthMax:400, focalLengthEquiv:'200-800mm',
    maxAperture:4.0, minAperture:22, weight:985, length:172.0, diameter:83.0,
    filterThread:72, minFocusDist:130, maxMagnification:0.25,
    elements:20, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:1797,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://shop.panasonic.com/products/g-series-100-400mm-f4-0-6-3-asph-leica-lens',
  },


  /* ── Sigma (L-Mount, native full-frame DG DN) ── */
  'sigma-20mm-f14-dg': {
    name:'Sigma 20mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:1.4, minAperture:16, weight:630, length:113.2, diameter:87.8,
    filterThread:82, minFocusDist:23, maxMagnification:0.16,
    elements:17, groups:15, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a022_20_14_product_img01.png',
    asin:null,
    prices:{USD:899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a022_20_14/',
  },
  'sigma-24mm-f14-dg': {
    name:'Sigma 24mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.4, minAperture:16, weight:510, length:97.5, diameter:75.7,
    filterThread:72, minFocusDist:25, maxMagnification:0.14,
    elements:17, groups:14, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a022_24_14_product_img01.png',
    asin:null,
    prices:{USD:799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a022_24_14/',
  },
  'sigma-35mm-f14-dg': {
    name:'Sigma 35mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:640, length:111.5, diameter:75.5,
    filterThread:67, minFocusDist:30, maxMagnification:0.19,
    elements:15, groups:11, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a021_35_14_product_img01.png',
    asin:null,
    prices:{USD:799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a021_35_14/',
  },
  'sigma-50mm-f14-dg': {
    name:'Sigma 50mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:660, length:111.5, diameter:78.2,
    filterThread:72, minFocusDist:45, maxMagnification:0.15,
    elements:14, groups:11, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a023_50_14_product_img01.png',
    asin:null,
    prices:{USD:849,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a023_50_14/',
  },
  'sigma-85mm-f14-dg': {
    name:'Sigma 85mm f/1.4 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Prime',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.4, minAperture:16, weight:625, length:96.1, diameter:82.8,
    filterThread:77, minFocusDist:85, maxMagnification:0.12,
    elements:15, groups:11, blades:11, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a020_85_14_product_img01.png',
    asin:null,
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a020_85_14/',
  },
  'sigma-20mm-f2-dg': {
    name:'Sigma 20mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:2.0, minAperture:22, weight:370, length:74.4, diameter:70,
    filterThread:62, minFocusDist:22, maxMagnification:0.15,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c022_20_2_product_img01.png',
    asin:null,
    prices:{USD:699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c022_20_2/',
  },
  'sigma-24mm-f2-dg': {
    name:'Sigma 24mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:2.0, minAperture:22, weight:360, length:74, diameter:70,
    filterThread:62, minFocusDist:24.5, maxMagnification:0.15,
    elements:13, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c021_24_2_product_img01.png',
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c021_24_2/',
  },
  'sigma-35mm-f2-dg': {
    name:'Sigma 35mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:2.0, minAperture:22, weight:325, length:67.4, diameter:70,
    filterThread:58, minFocusDist:27, maxMagnification:0.18,
    elements:10, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c020_35_2_product_img01.png',
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c020_35_2/',
  },
  'sigma-45mm-f28-dg': {
    name:'Sigma 45mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:45, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'45mm',
    maxAperture:2.8, minAperture:22, weight:230, length:48.2, diameter:64,
    filterThread:55, minFocusDist:24, maxMagnification:0.25,
    elements:8, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2019, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c019_45_28_product_img01.png',
    asin:null,
    prices:{USD:549,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c019_45_28/',
  },
  'sigma-50mm-f2-dg': {
    name:'Sigma 50mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.0, minAperture:22, weight:345, length:70, diameter:70,
    filterThread:58, minFocusDist:45, maxMagnification:0.14,
    elements:11, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c023_50_2_product_img01.png',
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c023_50_2/',
  },
  'sigma-65mm-f2-dg': {
    name:'Sigma 65mm f/2 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:65, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'65mm',
    maxAperture:2.0, minAperture:22, weight:405, length:76.7, diameter:72,
    filterThread:62, minFocusDist:55, maxMagnification:0.15,
    elements:12, groups:9, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c020_65_2_product_img01.png',
    asin:null,
    prices:{USD:699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c020_65_2/',
  },
  'sigma-90mm-f28-dg': {
    name:'Sigma 90mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:90, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:2.8, minAperture:22, weight:295, length:61.7, diameter:64,
    filterThread:55, minFocusDist:50, maxMagnification:0.2,
    elements:11, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:true,
    imageUrl:null,
    asin:null,
    prices:{USD:639,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c021_90_28/',
  },
  'sigma-17mm-f4-dg': {
    name:'Sigma 17mm f/4 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:17, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'17mm',
    maxAperture:4.0, minAperture:22, weight:220, length:50.8, diameter:64,
    filterThread:55, minFocusDist:12, maxMagnification:0.28,
    elements:9, groups:8, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2023, discontinued:true,
    imageUrl:'https://www.sigma-global.com/lenses/c023_17_4_product_img01.png',
    asin:null,
    prices:{USD:599,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://www.sigma-global.com/en/lenses/c023_17_4/',
  },
  'sigma-16-28mm-f28-dg': {
    name:'Sigma 16-28mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Zoom',
    focalLength:null, focalLengthMin:16, focalLengthMax:28, focalLengthEquiv:'16-28mm',
    maxAperture:2.8, minAperture:22, weight:450, length:102.6, diameter:77.2,
    filterThread:72, minFocusDist:25, maxMagnification:0.18,
    elements:16, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c022_16_28_28_product_img01.png',
    asin:null,
    prices:{USD:899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c022_16_28_28/',
  },
  'sigma-28-70mm-f28-dg': {
    name:'Sigma 28-70mm f/2.8 DG DN Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Zoom',
    focalLength:null, focalLengthMin:28, focalLengthMax:70, focalLengthEquiv:'28-70mm',
    maxAperture:2.8, minAperture:22, weight:470, length:103.5, diameter:72.2,
    filterThread:67, minFocusDist:19, maxMagnification:0.3,
    elements:16, groups:12, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:899,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c021_28_70_28/',
  },
  'sigma-24-70mm-f28-dg-ii': {
    name:'Sigma 24-70mm f/2.8 DG DN II Art', manufacturer:'Sigma', line:'Art', type:'Zoom',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:745, length:122.2, diameter:87.8,
    filterThread:82, minFocusDist:17, maxMagnification:0.34,
    elements:19, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a024_24_70_28_ii_product_img01.png',
    asin:null,
    prices:{USD:1199,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a024_24_70_28_ii/',
  },
  'sigma-28-45mm-f18-dg': {
    name:'Sigma 28-45mm f/1.8 DG DN Art', manufacturer:'Sigma', line:'Art', type:'Zoom',
    focalLength:null, focalLengthMin:28, focalLengthMax:45, focalLengthEquiv:'28-45mm',
    maxAperture:1.8, minAperture:16, weight:960, length:153.4, diameter:87.8,
    filterThread:82, minFocusDist:30, maxMagnification:0.25,
    elements:18, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/a024_28_45_18_product_img01.png',
    asin:null,
    prices:{USD:1349,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/a024_28_45_18/',
  },
  'sigma-70-200mm-f28-dg': {
    name:'Sigma 70-200mm f/2.8 DG DN OS Sports', manufacturer:'Sigma', line:'Sports', type:'Zoom',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1345, length:207, diameter:90.6,
    filterThread:77, minFocusDist:65, maxMagnification:0.19,
    elements:20, groups:15, blades:11, afType:'HLA Linear',
    weatherSealed:true, ois:true, oisStops:7.5, year:2023, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s023_70_200_28_product_img01.png',
    asin:null,
    prices:{USD:1499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s023_70_200_28/',
  },
  'sigma-100-400mm-f5-63-dg': {
    name:'Sigma 100-400mm f/5-6.3 DG DN OS Contemporary', manufacturer:'Sigma', line:'Contemporary', type:'Zoom',
    focalLength:null, focalLengthMin:100, focalLengthMax:400, focalLengthEquiv:'100-400mm',
    maxAperture:5.0, minAperture:22, weight:1140, length:199.2, diameter:86,
    filterThread:67, minFocusDist:112, maxMagnification:0.24,
    elements:22, groups:16, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:4, year:2020, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:949,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c020_100_400_5_63/',
  },
  'sigma-150-600mm-f5-63-dg': {
    name:'Sigma 150-600mm f/5-6.3 DG DN OS Sports', manufacturer:'Sigma', line:'Sports', type:'Zoom',
    focalLength:null, focalLengthMin:150, focalLengthMax:600, focalLengthEquiv:'150-600mm',
    maxAperture:5.0, minAperture:22, weight:2100, length:263.6, diameter:109.4,
    filterThread:95, minFocusDist:58, maxMagnification:0.34,
    elements:25, groups:15, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:6.5, year:2021, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/s021_150_600_5_63_product_img01.png',
    asin:null,
    prices:{USD:1499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/s021_150_600_5_63/',
  },

  /* ── Voigtländer (L-Mount, native full-frame manual-focus) ── */
  'voigtlander-apo-lanthar-35mm-f2-l': {
    name:'Voigtländer APO-Lanthar 35mm f/2 Aspherical', manufacturer:'Voigtländer', line:'APO-Lanthar', type:'Prime',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:2.0, minAperture:16, weight:352, length:67.3, diameter:62.6,
    filterThread:49, minFocusDist:35, maxMagnification:0.19,
    elements:11, groups:9, blades:12, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:1149,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.voigtlaender.de/l-mount/35-mm-12-0-apo-lanthar/?lang=en',
  },

  'voigtlander-apo-lanthar-50mm-f2-l': {
    name:'Voigtländer APO-Lanthar 50mm f/2 Aspherical', manufacturer:'Voigtländer', line:'APO-Lanthar', type:'Prime',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.0, minAperture:16, weight:364, length:61, diameter:63,
    filterThread:49, minFocusDist:45, maxMagnification:0.15,
    elements:10, groups:8, blades:12, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:1049,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.voigtlaender.de/l-mount/50-mm-12-0-apo-lanthar/?lang=en',
  },

  /* ── Laowa (L-Mount full-frame manual-focus specialty) ── */
  'laowa-90mm-f28-macro-l': {
    name:'Laowa 90mm f/2.8 2x Ultra Macro APO', manufacturer:'Laowa', line:'Ultra Macro APO', type:'Prime',
    focalLength:90, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:2.8, minAperture:22, weight:619, length:120, diameter:74,
    filterThread:67, minFocusDist:20.5, maxMagnification:2.0,
    elements:13, groups:10, blades:13, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.venuslens.net/product/laowa-90mm-f-2-8-2x-macro-apo/',
  },

  'laowa-15mm-f2-l': {
    name:'Laowa 15mm f/2 Zero-D', manufacturer:'Laowa', line:'Zero-D', type:'Prime',
    focalLength:15, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'15mm',
    maxAperture:2.0, minAperture:22, weight:500, length:82, diameter:66,
    filterThread:72, minFocusDist:15, maxMagnification:0.1,
    elements:12, groups:9, blades:5, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:849,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.venuslens.net/product/laowa-15mm-f2/',
  },

  /* ── OM System M.Zuiko (MFT, 2.0× crop) — major MFT third party ── */
  'omsystem-12-40mm-f28-pro': {
    name:'OM System M.Zuiko 12-40mm f/2.8 PRO II', manufacturer:'OM System', line:'PRO', type:'Zoom',
    focalLength:null, focalLengthMin:12, focalLengthMax:40, focalLengthEquiv:'24-80mm',
    maxAperture:2.8, minAperture:22, weight:382, length:84, diameter:70,
    filterThread:62, minFocusDist:20, maxMagnification:0.3,
    elements:14, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:1000,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-12-40mm-f2-8-pro-ii',
  },
  'omsystem-40-150mm-f4-pro': {
    name:'OM System M.Zuiko 40-150mm f/4 PRO', manufacturer:'OM System', line:'PRO', type:'Zoom',
    focalLength:null, focalLengthMin:40, focalLengthMax:150, focalLengthEquiv:'80-300mm',
    maxAperture:4.0, minAperture:22, weight:382, length:99, diameter:69,
    filterThread:62, minFocusDist:70, maxMagnification:0.2,
    elements:15, groups:9, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:900,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-40-150mm-f4-0-pro',
  },
  'omsystem-12-100mm-f4-pro': {
    name:'OM System M.Zuiko 12-100mm f/4 IS PRO', manufacturer:'OM System', line:'PRO', type:'Zoom',
    focalLength:null, focalLengthMin:12, focalLengthMax:100, focalLengthEquiv:'24-200mm',
    maxAperture:4.0, minAperture:22, weight:561, length:117, diameter:78,
    filterThread:72, minFocusDist:15, maxMagnification:0.3,
    elements:17, groups:11, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:true, oisStops:6.5, year:2016, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:1300,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-12-100mm-f4-0-is-pro',
  },
  'omsystem-17mm-f12-pro': {
    name:'OM System M.Zuiko 17mm f/1.2 PRO', manufacturer:'OM System', line:'PRO', type:'Prime',
    focalLength:17, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'34mm',
    maxAperture:1.2, minAperture:16, weight:390, length:87, diameter:68,
    filterThread:62, minFocusDist:20, maxMagnification:0.15,
    elements:15, groups:11, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:1200,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-17mm-f1-2-pro',
  },
  'omsystem-25mm-f12-pro': {
    name:'OM System M.Zuiko 25mm f/1.2 PRO', manufacturer:'OM System', line:'PRO', type:'Prime',
    focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.2, minAperture:16, weight:410, length:87, diameter:70,
    filterThread:62, minFocusDist:30, maxMagnification:0.11,
    elements:19, groups:14, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:1200,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-25mm-f1-2-pro',
  },
  'omsystem-45mm-f12-pro': {
    name:'OM System M.Zuiko 45mm f/1.2 PRO', manufacturer:'OM System', line:'PRO', type:'Prime',
    focalLength:45, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:1.2, minAperture:16, weight:410, length:84.9, diameter:70,
    filterThread:62, minFocusDist:50, maxMagnification:0.1,
    elements:14, groups:10, blades:9, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:1200,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-45mm-f1-2-pro',
  },
  'omsystem-60mm-f28-macro': {
    name:'OM System M.Zuiko 60mm f/2.8 Macro', manufacturer:'OM System', line:'Macro', type:'Prime',
    focalLength:60, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'120mm',
    maxAperture:2.8, minAperture:22, weight:185, length:82, diameter:56,
    filterThread:46, minFocusDist:19, maxMagnification:1.0,
    elements:13, groups:10, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:550,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-ed-60mm-f2-8-macro',
  },
  'omsystem-17mm-f18': {
    name:'OM System M.Zuiko 17mm f/1.8 II', manufacturer:'OM System', line:'Premium', type:'Prime',
    focalLength:17, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'34mm',
    maxAperture:1.8, minAperture:22, weight:112, length:38, diameter:58,
    filterThread:46, minFocusDist:25, maxMagnification:0.08,
    elements:9, groups:6, blades:7, afType:'Stepping Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:550,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-17mm-f1-8-ii',
  },
  'omsystem-25mm-f18': {
    name:'OM System M.Zuiko 25mm f/1.8', manufacturer:'OM System', line:'Premium', type:'Prime',
    focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.8, minAperture:22, weight:136, length:41, diameter:56,
    filterThread:46, minFocusDist:25, maxMagnification:0.12,
    elements:9, groups:7, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2014, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-25mm-f1-8-black',
  },
  'omsystem-45mm-f18': {
    name:'OM System M.Zuiko 45mm f/1.8', manufacturer:'OM System', line:'Premium', type:'Prime',
    focalLength:45, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:1.8, minAperture:22, weight:116, length:46, diameter:56,
    filterThread:37, minFocusDist:50, maxMagnification:0.11,
    elements:9, groups:8, blades:7, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2011, discontinued:false,
    imageUrl:null,
    asin:null,
    prices:{USD:399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://explore.omsystem.com/us/en/m-zuiko-45mm-f1-8',
  },

  /* ── Sigma (MFT, APS-C DC DN, 2.0× crop) ── */
  'sigma-16mm-f14-mft': {
    name:'Sigma 16mm f/1.4 DC DN', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:16, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'32mm',
    maxAperture:1.4, minAperture:16, weight:405, length:92.3, diameter:72.2,
    filterThread:67, minFocusDist:25, maxMagnification:0.1,
    elements:16, groups:13, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c017_16_14_product_img01.png',
    asin:null,
    prices:{USD:449,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c017_16_14/',
  },
  'sigma-30mm-f14-mft': {
    name:'Sigma 30mm f/1.4 DC DN', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:30, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'60mm',
    maxAperture:1.4, minAperture:16, weight:265, length:73.3, diameter:64.8,
    filterThread:52, minFocusDist:30, maxMagnification:0.14,
    elements:9, groups:7, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2016, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c016_30_14_product_img01.png',
    asin:null,
    prices:{USD:339,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c016_30_14/',
  },
  'sigma-56mm-f14-mft': {
    name:'Sigma 56mm f/1.4 DC DN', manufacturer:'Sigma', line:'Contemporary', type:'Prime',
    focalLength:56, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'112mm',
    maxAperture:1.4, minAperture:16, weight:280, length:59.5, diameter:66.5,
    filterThread:55, minFocusDist:50, maxMagnification:0.14,
    elements:10, groups:6, blades:9, afType:'Stepping Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:'https://www.sigma-global.com/lenses/c018_56_14_product_img01.png',
    asin:null,
    prices:{USD:479,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true,
    productUrl:'https://www.sigma-global.com/en/lenses/c018_56_14/',
  },

  /* ── Voigtländer & Laowa (MFT manual-focus specialty) ── */
  'voigtlander-nokton-25mm-f095': {
    name:'Voigtländer Nokton 25mm f/0.95', manufacturer:'Voigtländer', line:'Nokton', type:'Prime',
    focalLength:25, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:0.95, minAperture:16, weight:435, length:70, diameter:60.6,
    filterThread:52, minFocusDist:17, maxMagnification:0.11,
    elements:11, groups:8, blades:10, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.voigtlaender.de/mft/25-mm-10-95-nokton/?lang=en',
  },

  'laowa-7-5mm-f2-mft': {
    name:'Laowa 7.5mm f/2 MFT', manufacturer:'Laowa', line:'Zero-D', type:'Prime',
    focalLength:7.5, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'15mm',
    maxAperture:2.0, minAperture:22, weight:170, length:55, diameter:55,
    filterThread:46, minFocusDist:12, maxMagnification:0.11,
    elements:13, groups:9, blades:7, afType:'Manual',
    weatherSealed:false, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:null, asin:null,
    prices:{USD:499,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    priceIncomplete:true, productUrl:'https://www.venuslens.net/product/laowa-7-5mm-f2/',
  },
};

const LENS_DROPDOWN_GROUPS = [
  { label: '── LUMIX S Primes (L-Mount) ──', ids: ['lumix-s-18mm-f1-8', 'lumix-s-24mm-f1-8', 'lumix-s-35mm-f1-8', 'lumix-s-40mm-f2', 'lumix-s-50mm-f1-8', 'lumix-s-pro-50mm-f1-4', 'lumix-s-85mm-f1-8', 'lumix-s-100mm-f2-8-macro'] },
  { label: '── LUMIX S Zooms (L-Mount) ──',  ids: ['lumix-s-14-28mm-f4-5-6-macro', 'lumix-s-pro-16-35mm-f4', 'lumix-s-20-60mm-f3-5-5-6', 'lumix-s-24-60mm-f2-8', 'lumix-s-24-70mm-f2-8-pro', 'lumix-s-24-105mm-f4-macro', 'lumix-s-28-200mm-f4-7-1-macro', 'lumix-s-pro-70-200mm-f2-8', 'lumix-s-pro-70-200mm-f4', 'lumix-s-70-300mm-f4-5-5-6-macro'] },
  { label: '── LUMIX G Primes (MFT) ──',     ids: ['leica-dg-9mm-f1-7', 'leica-dg-12mm-f1-4', 'leica-dg-15mm-f1-7', 'lumix-g-20mm-f1-7-ii', 'leica-dg-25mm-f1-4-ii', 'lumix-g-25mm-f1-7', 'leica-dg-42-5mm-f1-2-nocticron', 'lumix-g-42-5mm-f1-7', 'leica-dg-200mm-f2-8'] },
  { label: '── LUMIX G Zooms (MFT) ──',      ids: ['leica-dg-8-18mm-f2-8-4', 'leica-dg-10-25mm-f1-7', 'lumix-g-12-32mm-f3-5-5-6', 'leica-dg-12-60mm-f2-8-4', 'lumix-g-12-60mm-f3-5-5-6', 'lumix-g-12-35mm-f2-8-ii', 'leica-dg-25-50mm-f1-7', 'lumix-g-35-100mm-f2-8-ii', 'leica-dg-50-200mm-f2-8-4', 'lumix-g-14-140mm-f3-5-5-6-ii', 'lumix-g-100-300mm-f4-5-6-ii', 'leica-dg-100-400mm-f4-6-3-ii'] },
  { label: '── Sigma Primes (L-Mount) ──', ids: ['sigma-20mm-f14-dg', 'sigma-24mm-f14-dg', 'sigma-35mm-f14-dg', 'sigma-50mm-f14-dg', 'sigma-85mm-f14-dg', 'sigma-20mm-f2-dg', 'sigma-24mm-f2-dg', 'sigma-35mm-f2-dg', 'sigma-45mm-f28-dg', 'sigma-50mm-f2-dg', 'sigma-65mm-f2-dg', 'sigma-90mm-f28-dg', 'sigma-17mm-f4-dg'] },
  { label: '── Sigma Zooms (L-Mount) ──', ids: ['sigma-16-28mm-f28-dg', 'sigma-28-70mm-f28-dg', 'sigma-24-70mm-f28-dg-ii', 'sigma-28-45mm-f18-dg', 'sigma-70-200mm-f28-dg', 'sigma-100-400mm-f5-63-dg', 'sigma-150-600mm-f5-63-dg'] },
  { label: '── Voigtländer (L-Mount) ──', ids: ['voigtlander-apo-lanthar-35mm-f2-l', 'voigtlander-apo-lanthar-50mm-f2-l'] },
  { label: '── Laowa (L-Mount) ──', ids: ['laowa-90mm-f28-macro-l', 'laowa-15mm-f2-l'] },
  { label: '── OM System Primes (MFT) ──', ids: ['omsystem-17mm-f12-pro', 'omsystem-25mm-f12-pro', 'omsystem-45mm-f12-pro', 'omsystem-60mm-f28-macro', 'omsystem-17mm-f18', 'omsystem-25mm-f18', 'omsystem-45mm-f18'] },
  { label: '── OM System Zooms (MFT) ──', ids: ['omsystem-12-40mm-f28-pro', 'omsystem-40-150mm-f4-pro', 'omsystem-12-100mm-f4-pro'] },
  { label: '── Sigma (MFT) ──', ids: ['sigma-16mm-f14-mft', 'sigma-30mm-f14-mft', 'sigma-56mm-f14-mft'] },
  { label: '── Voigtländer & Laowa (MFT) ──', ids: ['voigtlander-nokton-25mm-f095', 'laowa-7-5mm-f2-mft'] },
];

return { BRAND_CONFIG, SERIES_COLORS, CAMERAS, CAMERA_ORDER,
         DROPDOWN_GROUPS, LENSES, LENS_DROPDOWN_GROUPS, REGISTERED_BRANDS };
})();
