// ─────────────────────────────────────────────
// SONY BRAND CONFIG
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Sony',
  slug:        'sony',
  accentColor: '#ff6a00',
  heroDark:    '#1a0d00',
  logoText:    'Sony',
  logoAccent:  '',
  families:    ['E-mount System'],
  brandSections: ['sony'],
  cameras: {
    heroEyebrow:  'Alpha E-mount System',
    heroTitle:    '<span>Sony</span> Camera Comparison',
    heroSubtitle: 'Compare up to 3 Sony Alpha cameras side-by-side across the full lineup',
    headerTitle:  'Camera Compare',
    defaultSelected: ['a7-iv', 'a6700', 'a7c-ii'],
  },
  lenses: {
    heroEyebrow:  'E-mount Lenses',
    heroTitle:    '<span>Sony</span> Lens Comparison',
    heroSubtitle: 'Compare Sony FE & E mount lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['fe-50mm-f14-gm', 'fe-24-70mm-f28-gm-ii', 'fe-70-200mm-f28-gm-oss-ii'],
  },
  footerLinks: [
    { label: 'Sony Alpha Universe', url: 'https://alphauniverse.com' },
    { label: 'DPReview Sony',       url: 'https://www.dpreview.com/products/sony' },
    { label: 'Sony Alpha Rumors',   url: 'https://www.sonyalpharumors.com' },
  ],
};

// All brands must register the same list (config.test.js enforces parity).
const REGISTERED_BRANDS = [
  { slug: 'fujifilm', name: 'Fujifilm' },
  { slug: 'canon',    name: 'Canon' },
  { slug: 'sony',     name: 'Sony' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards)
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'Alpha (Full-frame)': { bg: '#2a1500', text: '#ffae66' },
  'Alpha (APS-C)':      { bg: '#1f1000', text: '#e09a5a' },
  'Cinema Line':        { bg: '#1a1a1a', text: '#d0d0d0' },
  'ZV (Vlog)':          { bg: '#241200', text: '#ffc080' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE
// Sony E-mount bodies (full-frame Alpha, APS-C Alpha, Cinema Line, ZV).
// Pricing: USD is the launch RRP. Non-USD figures derived via
// scripts/compute-prices.js unless a confirmed regional RRP is available;
// discontinued bodies may carry null for non-USD currencies.
// Sony-specific fields: logProfile (Log/colour profiles), aiAf (dedicated AI
// Processing Unit), realtimeTracking (Real-time Tracking AF).
// ─────────────────────────────────────────────
const CAMERAS = {
  // Populated in batches — see openspec/changes/add-sony-brand/research/cameras.md

  /* ── Alpha Full-frame ── */
  'a7-iv': {
    name:'A7 IV', series:'Alpha (Full-frame)', year:2021, discontinued:false,
    tagline:'All-round Hybrid Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m4-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sony_A7_IV_%28ILCE-7M4%29_-_by_Henry_S%C3%B6derlund_%2851739988735%29.jpg/1280px-Sony_A7_IV_%28ILCE-7M4%29_-_by_Henry_S%C3%B6derlund_%2851739988735%29.jpg',
    asin:'B09JZT6YK5',
    prices:{USD:2499,AUD:4299,EUR:2800,GBP:2400,JPY:330000,CAD:3299,SGD:3399},
    sensorMP:33.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:131.3, height:96.4, depth:79.8, weight:658, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Bird',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 60P (Super35)',
    logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× CFexpress Type A / SD UHS-II + 1× SD UHS-II', batteryLife:580, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:false, realtimeTracking:true,
  },

  'a7c-ii': {
    name:'A7C II', series:'Alpha (Full-frame)', year:2023, discontinued:false,
    tagline:'Compact 33MP Full-frame with AI AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7cm2-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Sony_ILCE-7CM2_8_nov_2023a.jpg/1280px-Sony_ILCE-7CM2_8_nov_2023a.jpg',
    asin:'B0CGTTVYGM',
    prices:{USD:2199,AUD:3699,EUR:2500,GBP:2100,JPY:309000,CAD:2900,SGD:3000},
    sensorMP:33.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:124.0, height:71.1, depth:63.4, weight:514, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:7.0, maxBurst:10,
    maxVideoRes:'4K / 60P (Super35)',
    logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7r-v': {
    name:'A7R V', series:'Alpha (Full-frame)', year:2022, discontinued:false,
    tagline:'61MP Resolution + AI AF + 8K',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm5-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Sony_a7R_V_20230616_162554.jpg/1280px-Sony_a7R_V_20230616_162554.jpg',
    asin:'B0BKLQFFSF',
    prices:{USD:3898,AUD:5999,EUR:4500,GBP:4000,JPY:560000,CAD:5200,SGD:5400},
    sensorMP:61.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:131.3, height:96.9, depth:82.4, weight:723, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'4-axis Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:8.0, maxBurst:10,
    maxVideoRes:'8K / 24P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a1-ii': {
    name:'A1 II', series:'Alpha (Full-frame)', year:2024, discontinued:false,
    tagline:'50MP Flagship: Speed + Resolution + 8K',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce1m2-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Sony_a1_II.jpg/1280px-Sony_a1_II.jpg',
    asin:'B0DNLVHJ74',
    prices:{USD:6499,AUD:9999,EUR:7300,GBP:6300,JPY:990000,CAD:8500,SGD:8800},
    sensorMP:50.1, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ XR',
    width:136.1, height:96.9, depth:82.9, weight:743, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'4-axis Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:8.5, maxBurst:30,
    maxVideoRes:'8K / 30P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:520, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a9-iii': {
    name:'A9 III', series:'Alpha (Full-frame)', year:2024, discontinued:false,
    tagline:"World's First Global Shutter Full-frame",
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce9m3-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Sony_ILCE-9M3_9_mar_2024a.jpg/1280px-Sony_ILCE-9M3_9_mar_2024a.jpg',
    asin:'B0CMV98DP2',
    prices:{USD:5998,AUD:9499,EUR:6999,GBP:6100,JPY:880000,CAD:7900,SGD:8200},
    sensorMP:24.6, sensorType:'Full-frame Global Shutter Exmor RS CMOS', processor:'BIONZ XR',
    width:136.1, height:96.9, depth:82.9, weight:703, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'4-axis Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:8.0, maxBurst:120,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7-v': {
    name:'A7 V', series:'Alpha (Full-frame)', year:2025, discontinued:false,
    tagline:'Partially-stacked 33MP Hybrid + BIONZ XR2',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m5-b',
    imageUrl:null,
    asin:null,
    prices:{USD:2899,AUD:4999,EUR:3299,GBP:2899,JPY:430000,CAD:3699,SGD:3899},
    sensorMP:33.0, sensorType:'Full-frame Partially-stacked Exmor RS BSI CMOS', processor:'BIONZ XR2',
    width:130.3, height:96.4, depth:82.4, weight:695, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:7.5, maxBurst:30,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'5.3', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:null, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7cr': {
    name:'A7C R', series:'Alpha (Full-frame)', year:2023, discontinued:false,
    tagline:'Compact 61MP with AI AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7cr-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Sony_ILCE-7CR_8_nov_2023a.jpg/1280px-Sony_ILCE-7CR_8_nov_2023a.jpg',
    asin:'B0CGTVF6HS',
    prices:{USD:2999,AUD:5099,EUR:3400,GBP:3000,JPY:450000,CAD:3900,SGD:4100},
    sensorMP:61.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:124.0, height:71.1, depth:63.4, weight:515, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:7.0, maxBurst:8,
    maxVideoRes:'4K / 60P (Super35)',
    logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7s-iii': {
    name:'A7S III', series:'Alpha (Full-frame)', year:2021, discontinued:false,
    tagline:'12MP Low-light Video Specialist',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7sm3-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Sony_%CE%B17S_III_21_Oct_2020a.jpg/1280px-Sony_%CE%B17S_III_21_Oct_2020a.jpg',
    asin:'B08DP4NKGN',
    prices:{USD:3498,AUD:5999,EUR:4200,GBP:3800,JPY:440000,CAD:4500,SGD:4800},
    sensorMP:12.1, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:128.9, height:96.9, depth:80.8, weight:699, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:600, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a1': {
    name:'A1', series:'Alpha (Full-frame)', year:2021, discontinued:true,
    tagline:'Original 50MP Flagship (8K)',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce1-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Sony_A1_-_front_view_-_by_Henry_S%C3%B6derlund_%2850993589248%29.jpg/1280px-Sony_A1_-_front_view_-_by_Henry_S%C3%B6derlund_%2850993589248%29.jpg',
    asin:null,
    prices:{USD:6498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:50.1, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ XR',
    width:128.9, height:96.9, depth:80.8, weight:737, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird',
    ibis:true, ibisStops:5.5, maxBurst:30,
    maxVideoRes:'8K / 30P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:false, realtimeTracking:true,
  },

  'a7c': {
    name:'A7C', series:'Alpha (Full-frame)', year:2020, discontinued:true,
    tagline:'First Compact Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7c-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Sony_%CE%B17C_24_Oct_2020a.jpg/1280px-Sony_%CE%B17C_24_Oct_2020a.jpg',
    asin:null,
    prices:{USD:1799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:124.0, height:71.1, depth:59.7, weight:509, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:922, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.59,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:740, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  /* ── Alpha Full-frame (discontinued) ── */
  'a9-ii': {
    name:'A9 II', series:'Alpha (Full-frame)', year:2019, discontinued:true,
    tagline:'Pro Sports Stacked 24MP',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce9m2-b',
    imageUrl:null, asin:null,
    prices:{USD:4498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ X',
    width:128.9, height:96.4, depth:77.5, weight:678, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:20,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:690, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7r-iv': {
    name:'A7R IV', series:'Alpha (Full-frame)', year:2019, discontinued:true,
    tagline:'First 61MP Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm4a-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Sony_Alpha_7R_IV_body_with_Sony_Zeiss_55mm_lens.jpg/1280px-Sony_Alpha_7R_IV_body_with_Sony_Zeiss_55mm_lens.jpg', asin:null,
    prices:{USD:3498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:61.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:128.9, height:96.4, depth:77.5, weight:665, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:670, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7-iii': {
    name:'A7 III', series:'Alpha (Full-frame)', year:2018, discontinued:true,
    tagline:'The Full-frame Workhorse',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m3-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/2/2c/Sony_Alpha7_III_20_apr_2018f.jpg', asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.6, depth:73.7, weight:650, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:922, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'2× SD (1× UHS-II)', batteryLife:710, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a9': {
    name:'A9', series:'Alpha (Full-frame)', year:2017, discontinued:true,
    tagline:'First Stacked Pro Sports Body',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce9-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Sony_Alpha_A9_DSCF0221_%2834482667712%29.jpg/1280px-Sony_Alpha_A9_DSCF0221_%2834482667712%29.jpg', asin:null,
    prices:{USD:4498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ X',
    width:126.9, height:95.6, depth:63.0, weight:673, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:20,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'2× SD (1× UHS-II)', batteryLife:650, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7r-iii': {
    name:'A7R III', series:'Alpha (Full-frame)', year:2017, discontinued:true,
    tagline:'42MP High-resolution Hybrid',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm3a-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Sony_Alpha_ILCE-7RM3_full_frame_camera_with_lens.jpeg/1280px-Sony_Alpha_ILCE-7RM3_full_frame_camera_with_lens.jpeg', asin:null,
    prices:{USD:3198,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:42.4, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.6, depth:73.7, weight:657, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'2× SD (1× UHS-II)', batteryLife:650, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7r-ii': {
    name:'A7R II', series:'Alpha (Full-frame)', year:2015, discontinued:true,
    tagline:'First BSI 42MP Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm2',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Sony_A7RMII.jpg/1280px-Sony_A7RMII.jpg', asin:null,
    prices:{USD:3198,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:42.4, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.7, depth:60.3, weight:625, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1228, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human',
    ibis:true, ibisStops:4.5, maxBurst:5,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:290, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a7s-ii': {
    name:'A7S II', series:'Alpha (Full-frame)', year:2015, discontinued:true,
    tagline:'12MP Low-light Video',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7sm2',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Sony_A7S_II_with_FE_24-70_F4_ZA_lens.jpg/1280px-Sony_A7S_II_with_FE_24-70_F4_ZA_lens.jpg', asin:null,
    prices:{USD:2998,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:12.2, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.7, depth:60.3, weight:627, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1228, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human',
    ibis:true, ibisStops:4.5, maxBurst:5,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:370, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a7-ii': {
    name:'A7 II', series:'Alpha (Full-frame)', year:2014, discontinued:true,
    tagline:'First IBIS Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m2',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/8/8e/Sony_a7_II_with_FE_28mm_F2_and_fisheye_converter_-_Crop.jpg', asin:null,
    prices:{USD:1698,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'Full-frame Exmor CMOS', processor:'BIONZ X',
    width:126.9, height:95.7, depth:59.7, weight:599, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1228, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:4.5, maxBurst:5,
    maxVideoRes:'1080 / 60P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a7r': {
    name:'A7R', series:'Alpha (Full-frame)', year:2013, discontinued:true,
    tagline:'Original 36MP No-AA Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7r',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Sony_Alpha_ILCE-7R_front_2014_CP%2B.jpg/1280px-Sony_Alpha_ILCE-7R_front_2014_CP%2B.jpg', asin:null,
    prices:{USD:2298,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:36.4, sensorType:'Full-frame Exmor CMOS (no AA filter)', processor:'BIONZ X',
    width:126.9, height:94.4, depth:48.2, weight:465, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1230, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:4,
    maxVideoRes:'1080 / 60P', logVideo:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:340, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:false,
  },

  'a7': {
    name:'A7', series:'Alpha (Full-frame)', year:2013, discontinued:true,
    tagline:'The Original Full-frame Mirrorless',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Sony_Alpha_ILCE-7_%28A7%29_full-frame_camera_no_body_cap.jpg/1280px-Sony_Alpha_ILCE-7_%28A7%29_full-frame_camera_no_body_cap.jpg', asin:null,
    prices:{USD:1698,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'Full-frame Exmor CMOS', processor:'BIONZ X',
    width:126.9, height:94.4, depth:48.2, weight:474, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1230, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:5,
    maxVideoRes:'1080 / 60P', logVideo:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:340, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:false,
  },

  'a7s': {
    name:'A7S', series:'Alpha (Full-frame)', year:2014, discontinued:true,
    tagline:'First 12MP Low-light Specialist',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7s',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/c/cf/ILCE-7S.jpg', asin:null,
    prices:{USD:2498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:12.2, sensorType:'Full-frame Exmor CMOS', processor:'BIONZ X',
    width:126.9, height:94.4, depth:48.2, weight:489, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1230, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:5,
    maxVideoRes:'4K / 30P (external)', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log2', aiAf:false, realtimeTracking:false,
  },

  /* ── Alpha APS-C ── */
  'a6700': {
    name:'A6700', series:'Alpha (APS-C)', year:2023, discontinued:false,
    tagline:'Flagship APS-C with AI AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6700-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Sony_A6700_by_Henry_S%C3%B6derlund.jpg/1280px-Sony_A6700_by_Henry_S%C3%B6derlund.jpg',
    asin:'B0CBN8Y77Z',
    prices:{USD:1399,AUD:2399,EUR:1700,GBP:1450,JPY:230000,CAD:1900,SGD:2100},
    sensorMP:26.0, sensorType:'APS-C BSI CMOS', processor:'BIONZ XR',
    width:122.0, height:69.0, depth:75.1, weight:493, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:5.0, maxBurst:11,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:570, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a6600': {
    name:'A6600', series:'Alpha (APS-C)', year:2019, discontinued:true,
    tagline:'APS-C Flagship with IBIS',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6600-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/2020-05_-_Sony_ILCE-6600_-_01.jpg/1280px-2020-05_-_Sony_ILCE-6600_-_01.jpg', asin:null,
    prices:{USD:1399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:69.3, weight:503, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:810, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a6500': {
    name:'A6500', series:'Alpha (APS-C)', year:2016, discontinued:true,
    tagline:'First APS-C with IBIS',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6500',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Sony_Alpha_ILCE-6500_front-left_2017_CP%2B.jpg/1280px-Sony_Alpha_ILCE-6500_front-left_2017_CP%2B.jpg', asin:null,
    prices:{USD:1398,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:53.3, weight:453, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human',
    ibis:true, ibisStops:5.0, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a6400': {
    name:'A6400', series:'Alpha (APS-C)', year:2019, discontinued:false,
    tagline:'Real-time Tracking APS-C',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6400-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/2022-02-17_Sony_alpha_6400_IMG20220217210008.jpg/1280px-2022-02-17_Sony_alpha_6400_IMG20220217210008.jpg', asin:'B07MTWVN3M',
    prices:{USD:899,AUD:1499,EUR:1050,GBP:950,JPY:140000,CAD:1300,SGD:1400},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:49.9, weight:403, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'180° Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:410, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a6300': {
    name:'A6300', series:'Alpha (APS-C)', year:2016, discontinued:true,
    tagline:'4K APS-C with Fast Hybrid AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6300',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Sony_Alpha_ILCE-6300_APS-C-frame_camera_no_body_cap.jpeg/1280px-Sony_Alpha_ILCE-6300_APS-C-frame_camera_no_body_cap.jpeg', asin:null,
    prices:{USD:998,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:48.8, weight:404, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a6100': {
    name:'A6100', series:'Alpha (APS-C)', year:2019, discontinued:true,
    tagline:'Entry APS-C with Fast AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6100-b',
    imageUrl:null, asin:null,
    prices:{USD:748,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:49.9, weight:396, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:921, lcdType:'180° Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:1.44, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:false,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:420, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:true,
  },

  'a6000': {
    name:'A6000', series:'Alpha (APS-C)', year:2014, discontinued:true,
    tagline:'The Best-selling APS-C',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6000',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Sony_Alpha_ILCE-6000_APS-C-frame_camera_no_body_cap-Crop.jpeg/1280px-Sony_Alpha_ILCE-6000_APS-C-frame_camera_no_body_cap-Crop.jpeg', asin:null,
    prices:{USD:648,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:45.1, weight:344, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:1.44, evfMag:0.70,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'1080 / 60P', logVideo:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:false,
  },

  /* ── Cinema Line ── */
  'fx3': {
    name:'FX3', series:'Cinema Line', year:2021, discontinued:false,
    tagline:'Full-frame Cinema in a Compact Body',
    productUrl:'https://electronics.sony.com/imaging/cinema-line-cameras/p/ilmefx3-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Sony_FX3_with_Sony_FE_24mm_F1.4_GM_-_by_Henry_S%C3%B6derlund_%2851061907312%2C_cropped%29.jpg/1280px-Sony_FX3_with_Sony_FE_24mm_F1.4_GM_-_by_Henry_S%C3%B6derlund_%2851061907312%2C_cropped%29.jpg', asin:'B08WJKKD47',
    prices:{USD:3899,AUD:6499,EUR:4700,GBP:4200,JPY:528000,CAD:5000,SGD:5300},
    sensorMP:12.1, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:129.7, height:77.8, depth:84.5, weight:715, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 120P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:600, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'fx30': {
    name:'FX30', series:'Cinema Line', year:2022, discontinued:false,
    tagline:'APS-C Cinema Line Gateway',
    productUrl:'https://electronics.sony.com/imaging/cinema-line-cameras/p/ilmefx30b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Sony_FX30_with_Sony_E_10-20mm_F4_PZ_G_-_by_Henry_S%C3%B6derlund_%2852445895581%29.jpg/1280px-Sony_FX30_with_Sony_E_10-20mm_F4_PZ_G_-_by_Henry_S%C3%B6derlund_%2852445895581%29.jpg', asin:'B0BR8BKFPK',
    prices:{USD:1799,AUD:2899,EUR:2100,GBP:1800,JPY:290000,CAD:2400,SGD:2500},
    sensorMP:26.0, sensorType:'APS-C BSI CMOS', processor:'BIONZ XR',
    width:129.7, height:77.8, depth:84.5, weight:646, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:2360, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 120P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:570, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  /* ── ZV (Vlog) ── */
  'zv-e1': {
    name:'ZV-E1', series:'ZV (Vlog)', year:2023, discontinued:false,
    tagline:'Full-frame Vlog with AI Framing',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilczv-e1-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sony_ZV-E1_with_Sony_FE_28-60mm_F4-5.6_-_by_Henry_S%C3%B6derlund_%2852854053098%29.jpg/1280px-Sony_ZV-E1_with_Sony_FE_28-60mm_F4-5.6_-_by_Henry_S%C3%B6derlund_%2852854053098%29.jpg', asin:'B0BZWNWCZ9',
    prices:{USD:2198,AUD:3499,EUR:2700,GBP:2300,JPY:298000,CAD:2900,SGD:3000},
    sensorMP:12.1, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:121.0, height:71.9, depth:54.3, weight:483, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 120P', logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:570, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'zv-e10-ii': {
    name:'ZV-E10 II', series:'ZV (Vlog)', year:2024, discontinued:false,
    tagline:'26MP APS-C Content Creator',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilczv-e10m2-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sony_ZV-E10_Mark_II.tiff/lossy-page1-960px-Sony_ZV-E10_Mark_II.tiff.jpg', asin:'B0D92W8GYV',
    prices:{USD:999,AUD:1699,EUR:1100,GBP:1000,JPY:150000,CAD:1400,SGD:1500},
    sensorMP:26.0, sensorType:'APS-C BSI CMOS', processor:'BIONZ XR',
    width:114.8, height:67.5, depth:57.3, weight:377, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 60P', logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:610, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:false, realtimeTracking:true,
  },

  'zv-e10': {
    name:'ZV-E10', series:'ZV (Vlog)', year:2021, discontinued:true,
    tagline:'First APS-C Vlog Camera',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilczv-e10-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Sony_ZV-E10_with_Sony_E_16-50mm_F3.5-5.6_OSS_PZ_-_by_Henry_S%C3%B6derlund_%2851375243603%29.jpg/1280px-Sony_ZV-E10_with_Sony_E_16-50mm_F3.5-5.6_OSS_PZ_-_by_Henry_S%C3%B6derlund_%2851375243603%29.jpg', asin:null,
    prices:{USD:699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:115.2, height:64.2, depth:44.8, weight:343, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:440, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },
};

const CAMERA_ORDER = [
  'a7-v', 'a9-iii', 'a1-ii',
  'a7r-v', 'a7cr', 'a7c-ii', 'a7s-iii', 'a7-iv',
  'a1', 'a7c', 'a9-ii', 'a7r-iv', 'a7-iii', 'a9', 'a7r-iii',
  'a7r-ii', 'a7s-ii', 'a7-ii', 'a7r', 'a7', 'a7s',
  'a6700', 'a6400', 'a6600', 'a6500', 'a6300', 'a6100', 'a6000',
  'fx3', 'fx30',
  'zv-e1', 'zv-e10-ii', 'zv-e10',
];

const DROPDOWN_GROUPS = [
  { label: '── Alpha Full-frame (2024–2025) ──', ids: ['a7-v', 'a9-iii', 'a1-ii'] },
  { label: '── Alpha Full-frame (2021–2023) ──', ids: ['a7r-v', 'a7cr', 'a7c-ii', 'a7s-iii', 'a7-iv'] },
  { label: '── Alpha Full-frame (2017–2020) ──', ids: ['a1', 'a7c', 'a9-ii', 'a7r-iv', 'a7-iii', 'a9', 'a7r-iii'] },
  { label: '── Alpha Full-frame (2013–2015) ──', ids: ['a7r-ii', 'a7s-ii', 'a7-ii', 'a7r', 'a7', 'a7s'] },
  { label: '── Alpha APS-C ──',                  ids: ['a6700', 'a6400', 'a6600', 'a6500', 'a6300', 'a6100', 'a6000'] },
  { label: '── Cinema Line ──',                  ids: ['fx3', 'fx30'] },
  { label: '── ZV (Vlog) ──',                    ids: ['zv-e1', 'zv-e10-ii', 'zv-e10'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE
// Sony first-party FE (full-frame) + E (APS-C) lenses, incl. Sony-Zeiss (ZA).
// Specs verified against Sony official pages + DPReview.
// See openspec/changes/add-sony-brand/research/lenses.md
// ─────────────────────────────────────────────
const LENSES = {
  // Populated in batches by line (FE GM / FE G / FE / E).

  /* ── Sony FE Primes ── */
  'fe-50mm-f14-gm': {
    name:'FE 50mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B0BWFSJXQC',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:516, length:96.0, diameter:80.6,
    filterThread:67, minFocusDist:38, maxMagnification:0.16,
    elements:14, groups:11, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:1600,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:1999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50f14gm',
  },

  'fe-14mm-f18-gm': {
    name:'FE 14mm F1.8 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B09316YPCH',
    focalLength:14, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'14mm',
    maxAperture:1.8, minAperture:16, weight:460, length:99.8, diameter:83.0,
    filterThread:null, minFocusDist:25, maxMagnification:0.10,
    elements:14, groups:11, blades:9, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1598,AUD:2499,EUR:null,GBP:null,JPY:null,CAD:1999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel14f18gm',
  },

  'fe-24mm-f14-gm': {
    name:'FE 24mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B07HJXVHSS',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.4, minAperture:16, weight:445, length:92.4, diameter:75.4,
    filterThread:67, minFocusDist:24, maxMagnification:0.17,
    elements:13, groups:10, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:1398,AUD:2199,EUR:null,GBP:null,JPY:null,CAD:1799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel24f14gm',
  },

  'fe-35mm-f14-gm': {
    name:'FE 35mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B08SWMH186',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:524, length:96.0, diameter:76.0,
    filterThread:67, minFocusDist:25, maxMagnification:0.26,
    elements:14, groups:10, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1398,AUD:2199,EUR:null,GBP:null,JPY:null,CAD:1799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel35f14gm',
  },

  'fe-50mm-f12-gm': {
    name:'FE 50mm F1.2 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B08Z4HVBXC',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.2, minAperture:16, weight:778, length:108.0, diameter:87.0,
    filterThread:72, minFocusDist:40, maxMagnification:0.17,
    elements:14, groups:10, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1998,AUD:3099,EUR:null,GBP:null,JPY:null,CAD:2599,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50f12gm',
  },

  'fe-85mm-f14-gm-ii': {
    name:'FE 85mm F1.4 GM II', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B0DFHSFL7L',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.4, minAperture:16, weight:642, length:107.3, diameter:84.7,
    filterThread:77, minFocusDist:80, maxMagnification:0.12,
    elements:14, groups:11, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:1798,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel85f14gm2',
  },

  'fe-85mm-f14-gm': {
    name:'FE 85mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B01BESR5KO',
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.4, minAperture:16, weight:820, length:107.5, diameter:89.5,
    filterThread:77, minFocusDist:80, maxMagnification:0.12,
    elements:11, groups:8, blades:11, afType:'SSM',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:true,
    imageUrl:null,
    prices:{USD:1798,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel85f14gm',
  },

  'fe-100mm-f28-stf-gm': {
    name:'FE 100mm F2.8 STF GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B06WRMXVKK',
    focalLength:100, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'100mm',
    maxAperture:2.8, minAperture:20, weight:700, length:118.1, diameter:85.2,
    filterThread:72, minFocusDist:57, maxMagnification:0.25,
    elements:13, groups:10, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1498,AUD:2299,EUR:null,GBP:null,JPY:null,CAD:1899,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel100f28gm',
  },

  'fe-135mm-f18-gm': {
    name:'FE 135mm F1.8 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B07P6MNC3R',
    focalLength:135, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'135mm',
    maxAperture:1.8, minAperture:22, weight:950, length:127.0, diameter:89.5,
    filterThread:82, minFocusDist:70, maxMagnification:0.25,
    elements:13, groups:10, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:2098,AUD:3299,EUR:null,GBP:null,JPY:null,CAD:2699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel135f18gm',
  },

  'fe-300mm-f28-gm': {
    name:'FE 300mm F2.8 GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B0CMV75475',
    focalLength:300, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'300mm',
    maxAperture:2.8, minAperture:22, weight:1470, length:265.0, diameter:124.0,
    filterThread:40.5, minFocusDist:200, maxMagnification:0.16,
    elements:21, groups:17, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:5999,AUD:9499,EUR:null,GBP:null,JPY:null,CAD:7799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel300f28gm',
  },

  'fe-400mm-f28-gm': {
    name:'FE 400mm F2.8 GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B07FHDZ3Z6',
    focalLength:400, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm',
    maxAperture:2.8, minAperture:22, weight:2895, length:359.0, diameter:158.1,
    filterThread:40.5, minFocusDist:270, maxMagnification:0.16,
    elements:23, groups:17, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:11998,AUD:18999,EUR:null,GBP:null,JPY:null,CAD:15499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel400f28gm',
  },

  'fe-600mm-f4-gm': {
    name:'FE 600mm F4 GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B07SZVGKMD',
    focalLength:600, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'600mm',
    maxAperture:4.0, minAperture:22, weight:3040, length:449.0, diameter:163.6,
    filterThread:40.5, minFocusDist:450, maxMagnification:0.14,
    elements:24, groups:18, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:12998,AUD:19999,EUR:null,GBP:null,JPY:null,CAD:16999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel600f40gm',
  },

  /* ── Sony FE G + standard primes ── */
  'fe-16mm-f18-g': {
    name:'FE 16mm F1.8 G', manufacturer:'Sony', line:'FE G', type:'Prime', asin:'B0DYK97L9M',
    focalLength:16, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'16mm',
    maxAperture:1.8, minAperture:22, weight:304, length:73.8, diameter:73.8,
    filterThread:67, minFocusDist:15, maxMagnification:0.25,
    elements:15, groups:12, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2025, discontinued:false,
    imageUrl:null,
    prices:{USD:799,AUD:1299,EUR:null,GBP:null,JPY:null,CAD:999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel16f18g',
  },

  'fe-20mm-f18-g': {
    name:'FE 20mm F1.8 G', manufacturer:'Sony', line:'FE G', type:'Prime', asin:'B08556WW56',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'20mm',
    maxAperture:1.8, minAperture:22, weight:373, length:84.7, diameter:73.5,
    filterThread:67, minFocusDist:18, maxMagnification:0.20,
    elements:14, groups:12, blades:9, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:898,AUD:1399,EUR:null,GBP:null,JPY:null,CAD:1149,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel20f18g',
  },

  'fe-24mm-f28-g': {
    name:'FE 24mm F2.8 G', manufacturer:'Sony', line:'FE G', type:'Prime', asin:'B08ZSWL58M',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:2.8, minAperture:22, weight:162, length:45.0, diameter:68.0,
    filterThread:49, minFocusDist:24, maxMagnification:0.13,
    elements:8, groups:7, blades:7, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:598,AUD:949,EUR:null,GBP:null,JPY:null,CAD:749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel24f28g',
  },

  'fe-40mm-f25-g': {
    name:'FE 40mm F2.5 G', manufacturer:'Sony', line:'FE G', type:'Prime', asin:'B08ZSW1PHB',
    focalLength:40, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'40mm',
    maxAperture:2.5, minAperture:22, weight:173, length:45.0, diameter:68.0,
    filterThread:49, minFocusDist:28, maxMagnification:0.20,
    elements:9, groups:9, blades:7, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:598,AUD:949,EUR:null,GBP:null,JPY:null,CAD:749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel40f25g',
  },

  'fe-50mm-f25-g': {
    name:'FE 50mm F2.5 G', manufacturer:'Sony', line:'FE G', type:'Prime', asin:'B08ZSYM3K1',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.5, minAperture:22, weight:174, length:45.0, diameter:68.0,
    filterThread:49, minFocusDist:31, maxMagnification:0.18,
    elements:9, groups:9, blades:7, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:598,AUD:949,EUR:null,GBP:null,JPY:null,CAD:749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50f25g',
  },

  'fe-90mm-f28-macro-g': {
    name:'FE 90mm F2.8 Macro G OSS', manufacturer:'Sony', line:'FE G', type:'Prime', asin:'B00U29GNEG',
    focalLength:90, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'90mm',
    maxAperture:2.8, minAperture:22, weight:602, length:130.5, diameter:79.0,
    filterThread:62, minFocusDist:28, maxMagnification:1.0,
    elements:15, groups:11, blades:9, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2015, discontinued:false,
    imageUrl:null,
    prices:{USD:1098,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel90m28g',
  },

  'fe-28mm-f2': {
    name:'FE 28mm F2', manufacturer:'Sony', line:'FE', type:'Prime', asin:'B00U29GN6O',
    focalLength:28, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'28mm',
    maxAperture:2.0, minAperture:22, weight:200, length:60.0, diameter:64.0,
    filterThread:49, minFocusDist:29, maxMagnification:0.13,
    elements:9, groups:8, blades:9, afType:'Linear',
    weatherSealed:false, ois:false, oisStops:null, year:2015, discontinued:false,
    imageUrl:null,
    prices:{USD:448,AUD:699,EUR:null,GBP:null,JPY:null,CAD:579,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel28f20',
  },

  'fe-35mm-f18': {
    name:'FE 35mm F1.8', manufacturer:'Sony', line:'FE', type:'Prime', asin:'B07V8X4KGG',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.8, minAperture:22, weight:280, length:73.0, diameter:65.6,
    filterThread:55, minFocusDist:22, maxMagnification:0.24,
    elements:11, groups:8, blades:9, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:748,AUD:1199,EUR:null,GBP:null,JPY:null,CAD:949,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel35f18f',
  },

  'fe-50mm-f18': {
    name:'FE 50mm F1.8', manufacturer:'Sony', line:'FE', type:'Prime', asin:'B01DLMD5O6',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.8, minAperture:22, weight:186, length:59.5, diameter:68.6,
    filterThread:49, minFocusDist:45, maxMagnification:0.14,
    elements:6, groups:5, blades:7, afType:'DC Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:248,AUD:399,EUR:null,GBP:null,JPY:null,CAD:329,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50f18f',
  },

  'fe-50mm-f28-macro': {
    name:'FE 50mm F2.8 Macro', manufacturer:'Sony', line:'FE', type:'Prime', asin:'B01LC8GMV4',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:2.8, minAperture:16, weight:236, length:71.0, diameter:70.8,
    filterThread:55, minFocusDist:16, maxMagnification:1.0,
    elements:8, groups:7, blades:7, afType:'DC Motor',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:498,AUD:799,EUR:null,GBP:null,JPY:null,CAD:649,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50m28',
  },

  /* ── Sony-Zeiss (ZA) FE primes ── */
  'fe-35mm-f14-za': {
    name:'FE 35mm F1.4 ZA Distagon', manufacturer:'Sony', line:'FE ZA', type:'Prime', asin:'B00U29GNBO',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:630, length:112.0, diameter:78.5,
    filterThread:72, minFocusDist:30, maxMagnification:0.18,
    elements:12, groups:8, blades:9, afType:'DDSSM',
    weatherSealed:true, ois:false, oisStops:null, year:2015, discontinued:true,
    imageUrl:null,
    prices:{USD:1598,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel35f14z',
  },

  'fe-35mm-f28-za': {
    name:'FE 35mm F2.8 ZA Sonnar', manufacturer:'Sony', line:'FE ZA', type:'Prime', asin:'B00FSB79KU',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:2.8, minAperture:22, weight:120, length:36.5, diameter:61.5,
    filterThread:49, minFocusDist:35, maxMagnification:0.12,
    elements:7, groups:5, blades:7, afType:'Linear',
    weatherSealed:false, ois:false, oisStops:null, year:2013, discontinued:true,
    imageUrl:null,
    prices:{USD:798,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel35f28z',
  },

  'fe-50mm-f14-za': {
    name:'FE 50mm F1.4 ZA Planar', manufacturer:'Sony', line:'FE ZA', type:'Prime', asin:'B01IALYGU0',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:778, length:108.0, diameter:83.5,
    filterThread:72, minFocusDist:45, maxMagnification:0.15,
    elements:12, groups:9, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:true,
    imageUrl:null,
    prices:{USD:1498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50f14z',
  },

  'fe-55mm-f18-za': {
    name:'FE 55mm F1.8 ZA Sonnar', manufacturer:'Sony', line:'FE ZA', type:'Prime', asin:'B00FSB799Q',
    focalLength:55, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'55mm',
    maxAperture:1.8, minAperture:22, weight:281, length:70.5, diameter:64.4,
    filterThread:49, minFocusDist:50, maxMagnification:0.14,
    elements:7, groups:5, blades:9, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:998,AUD:1599,EUR:null,GBP:null,JPY:null,CAD:1299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel55f18z',
  },

  /* ── Sony FE Zooms ── */
  'fe-24-70mm-f28-gm-ii': {
    name:'FE 24-70mm F2.8 GM II', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B09YYY6P98',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:695, length:119.9, diameter:87.8,
    filterThread:82, minFocusDist:21, maxMagnification:0.32,
    elements:20, groups:15, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:2298,AUD:3399,EUR:null,GBP:null,JPY:null,CAD:2900,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2470gm2',
  },

  'fe-70-200mm-f28-gm-oss-ii': {
    name:'FE 70-200mm F2.8 GM OSS II', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B09JCMLP46',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1045, length:200.0, diameter:88.0,
    filterThread:77, minFocusDist:40, maxMagnification:0.30,
    elements:17, groups:14, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:2798,AUD:4299,EUR:null,GBP:null,JPY:null,CAD:3600,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel70200gm2',
  },

  'fe-12-24mm-f28-gm': {
    name:'FE 12-24mm F2.8 GM', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B08CHN22SJ',
    focalLength:null, focalLengthMin:12, focalLengthMax:24, focalLengthEquiv:'12-24mm',
    maxAperture:2.8, minAperture:22, weight:847, length:137.0, diameter:97.6,
    filterThread:null, minFocusDist:28, maxMagnification:0.14,
    elements:17, groups:14, blades:9, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:2998,AUD:4699,EUR:null,GBP:null,JPY:null,CAD:3899,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel1224gm',
  },

  'fe-16-35mm-f28-gm-ii': {
    name:'FE 16-35mm F2.8 GM II', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B0CGTW24VF',
    focalLength:null, focalLengthMin:16, focalLengthMax:35, focalLengthEquiv:'16-35mm',
    maxAperture:2.8, minAperture:22, weight:547, length:121.6, diameter:87.8,
    filterThread:82, minFocusDist:22, maxMagnification:0.32,
    elements:15, groups:12, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:2298,AUD:3599,EUR:null,GBP:null,JPY:null,CAD:2999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel1635gm2',
  },

  'fe-16-35mm-f28-gm': {
    name:'FE 16-35mm F2.8 GM', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B071LHLS11',
    focalLength:null, focalLengthMin:16, focalLengthMax:35, focalLengthEquiv:'16-35mm',
    maxAperture:2.8, minAperture:22, weight:680, length:121.6, diameter:88.5,
    filterThread:82, minFocusDist:28, maxMagnification:0.19,
    elements:16, groups:13, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:false, oisStops:null, year:2017, discontinued:true,
    imageUrl:null,
    prices:{USD:2198,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel1635gm',
  },

  'fe-28-70mm-f2-gm': {
    name:'FE 28-70mm F2 GM', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B0DNKVBCYL',
    focalLength:null, focalLengthMin:28, focalLengthMax:70, focalLengthEquiv:'28-70mm',
    maxAperture:2.0, minAperture:22, weight:918, length:139.8, diameter:92.9,
    filterThread:86, minFocusDist:38, maxMagnification:0.23,
    elements:20, groups:14, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:2899,AUD:4499,EUR:null,GBP:null,JPY:null,CAD:3799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2870gm',
  },

  'fe-50-150mm-f2-gm': {
    name:'FE 50-150mm F2 GM', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B0F5X657S5',
    focalLength:null, focalLengthMin:50, focalLengthMax:150, focalLengthEquiv:'50-150mm',
    maxAperture:2.0, minAperture:22, weight:1340, length:200.0, diameter:102.8,
    filterThread:95, minFocusDist:40, maxMagnification:0.20,
    elements:19, groups:17, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2025, discontinued:false,
    imageUrl:null,
    prices:{USD:3899,AUD:5999,EUR:null,GBP:null,JPY:null,CAD:5099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50150gm',
  },

  'fe-100-400mm-f45-63-gm-oss': {
    name:'FE 100-400mm F4.5-5.6 GM OSS', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B071RFR318',
    focalLength:null, focalLengthMin:100, focalLengthMax:400, focalLengthEquiv:'100-400mm',
    maxAperture:4.5, minAperture:32, weight:1395, length:205.0, diameter:93.9,
    filterThread:77, minFocusDist:98, maxMagnification:0.35,
    elements:22, groups:16, blades:9, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:2498,AUD:3899,EUR:null,GBP:null,JPY:null,CAD:3299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel100400gm',
  },

  'fe-12-24mm-f4-g': {
    name:'FE 12-24mm F4 G', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B072J4B6WS',
    focalLength:null, focalLengthMin:12, focalLengthMax:24, focalLengthEquiv:'12-24mm',
    maxAperture:4.0, minAperture:22, weight:565, length:117.4, diameter:87.0,
    filterThread:null, minFocusDist:28, maxMagnification:0.14,
    elements:17, groups:13, blades:7, afType:'DDSSM',
    weatherSealed:true, ois:false, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1698,AUD:2699,EUR:null,GBP:null,JPY:null,CAD:2199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel1224g',
  },

  'fe-16-25mm-f28-g': {
    name:'FE 16-25mm F2.8 G', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B0D1VWRW46',
    focalLength:null, focalLengthMin:16, focalLengthMax:25, focalLengthEquiv:'16-25mm',
    maxAperture:2.8, minAperture:22, weight:409, length:91.4, diameter:74.8,
    filterThread:67, minFocusDist:18, maxMagnification:0.20,
    elements:16, groups:13, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:1098,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel1625g',
  },

  'fe-16-35mm-f4-pz-g': {
    name:'FE 16-35mm F4 PZ G', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B09W6CG368',
    focalLength:null, focalLengthMin:16, focalLengthMax:35, focalLengthEquiv:'16-35mm',
    maxAperture:4.0, minAperture:22, weight:353, length:88.1, diameter:80.5,
    filterThread:72, minFocusDist:24, maxMagnification:0.23,
    elements:13, groups:12, blades:7, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:1198,AUD:1899,EUR:null,GBP:null,JPY:null,CAD:1549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel1635g',
  },

  'fe-20-70mm-f4-g': {
    name:'FE 20-70mm F4 G', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B0BSHFF5WX',
    focalLength:null, focalLengthMin:20, focalLengthMax:70, focalLengthEquiv:'20-70mm',
    maxAperture:4.0, minAperture:22, weight:488, length:99.0, diameter:78.7,
    filterThread:72, minFocusDist:25, maxMagnification:0.39,
    elements:16, groups:13, blades:9, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:1098,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2070g',
  },

  'fe-24-50mm-f28-g': {
    name:'FE 24-50mm F2.8 G', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B0CVSLTYLK',
    focalLength:null, focalLengthMin:24, focalLengthMax:50, focalLengthEquiv:'24-50mm',
    maxAperture:2.8, minAperture:22, weight:440, length:92.3, diameter:74.8,
    filterThread:67, minFocusDist:19, maxMagnification:0.33,
    elements:16, groups:13, blades:11, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:1098,AUD:1699,EUR:null,GBP:null,JPY:null,CAD:1399,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2450g',
  },

  'fe-24-105mm-f4-g-oss': {
    name:'FE 24-105mm F4 G OSS', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B076V9P58R',
    focalLength:null, focalLengthMin:24, focalLengthMax:105, focalLengthEquiv:'24-105mm',
    maxAperture:4.0, minAperture:22, weight:663, length:113.3, diameter:83.4,
    filterThread:77, minFocusDist:38, maxMagnification:0.31,
    elements:17, groups:14, blades:9, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1298,AUD:1999,EUR:null,GBP:null,JPY:null,CAD:1699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel24105g',
  },

  'fe-70-200mm-f4-g-oss': {
    name:'FE 70-200mm F4 G OSS', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B00I8BICEO',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:4.0, minAperture:22, weight:840, length:175.0, diameter:80.0,
    filterThread:72, minFocusDist:100, maxMagnification:0.13,
    elements:21, groups:15, blades:9, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2014, discontinued:true,
    imageUrl:null,
    prices:{USD:1498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel70200g',
  },

  'fe-70-200mm-f4-macro-g-oss-ii': {
    name:'FE 70-200mm F4 Macro G OSS II', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B0CBNBDVMZ',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:4.0, minAperture:22, weight:794, length:149.0, diameter:82.2,
    filterThread:72, minFocusDist:26, maxMagnification:0.50,
    elements:19, groups:13, blades:9, afType:'XD Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:1698,AUD:2699,EUR:null,GBP:null,JPY:null,CAD:2199,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel70200g2',
  },

  'fe-70-300mm-f45-56-g-oss': {
    name:'FE 70-300mm F4.5-5.6 G OSS', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B01DLMD7DK',
    focalLength:null, focalLengthMin:70, focalLengthMax:300, focalLengthEquiv:'70-300mm',
    maxAperture:4.5, minAperture:32, weight:854, length:143.5, diameter:84.0,
    filterThread:72, minFocusDist:90, maxMagnification:0.31,
    elements:16, groups:13, blades:9, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2016, discontinued:false,
    imageUrl:null,
    prices:{USD:1198,AUD:1899,EUR:null,GBP:null,JPY:null,CAD:1549,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel70300g',
  },

  'fe-200-600mm-f56-63-g-oss': {
    name:'FE 200-600mm F5.6-6.3 G OSS', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B07SZXDN9X',
    focalLength:null, focalLengthMin:200, focalLengthMax:600, focalLengthEquiv:'200-600mm',
    maxAperture:5.6, minAperture:36, weight:2115, length:318.0, diameter:111.5,
    filterThread:95, minFocusDist:240, maxMagnification:0.20,
    elements:24, groups:17, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:1998,AUD:3099,EUR:null,GBP:null,JPY:null,CAD:2599,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel200600g',
  },

  'fe-400-800mm-f63-8-g-oss': {
    name:'FE 400-800mm F6.3-8 G OSS', manufacturer:'Sony', line:'FE G', type:'Zoom', asin:'B0DYKB9RY9',
    focalLength:null, focalLengthMin:400, focalLengthMax:800, focalLengthEquiv:'400-800mm',
    maxAperture:6.3, minAperture:51, weight:2475, length:348.0, diameter:119.8,
    filterThread:105, minFocusDist:170, maxMagnification:0.23,
    elements:27, groups:19, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2025, discontinued:false,
    imageUrl:null,
    prices:{USD:2899,AUD:4499,EUR:null,GBP:null,JPY:null,CAD:3799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel400800g',
  },

  'fe-16-35mm-f4-za-oss': {
    name:'FE 16-35mm F4 ZA OSS Vario-Tessar', manufacturer:'Sony', line:'FE ZA', type:'Zoom', asin:'B00NN6J3AG',
    focalLength:null, focalLengthMin:16, focalLengthMax:35, focalLengthEquiv:'16-35mm',
    maxAperture:4.0, minAperture:22, weight:518, length:98.5, diameter:78.5,
    filterThread:72, minFocusDist:28, maxMagnification:0.19,
    elements:12, groups:10, blades:7, afType:'Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2014, discontinued:true,
    imageUrl:null,
    prices:{USD:1348,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel1635z',
  },

  'fe-24-70mm-f4-za-oss': {
    name:'FE 24-70mm F4 ZA OSS Vario-Tessar', manufacturer:'Sony', line:'FE ZA', type:'Zoom', asin:'B00FSB79FU',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:4.0, minAperture:22, weight:426, length:94.5, diameter:73.0,
    filterThread:67, minFocusDist:40, maxMagnification:0.20,
    elements:12, groups:10, blades:7, afType:'Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2014, discontinued:true,
    imageUrl:null,
    prices:{USD:1198,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2470z',
  },

  'fe-24-240mm-f35-63-oss': {
    name:'FE 24-240mm F3.5-6.3 OSS', manufacturer:'Sony', line:'FE', type:'Zoom', asin:'B00U29GNC8',
    focalLength:null, focalLengthMin:24, focalLengthMax:240, focalLengthEquiv:'24-240mm',
    maxAperture:3.5, minAperture:40, weight:780, length:118.5, diameter:80.5,
    filterThread:72, minFocusDist:50, maxMagnification:0.27,
    elements:17, groups:12, blades:7, afType:'Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2015, discontinued:false,
    imageUrl:null,
    prices:{USD:998,AUD:1599,EUR:null,GBP:null,JPY:null,CAD:1299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel24240',
  },

  'fe-28-60mm-f4-56': {
    name:'FE 28-60mm F4-5.6', manufacturer:'Sony', line:'FE', type:'Zoom', asin:'B08J3HTGQX',
    focalLength:null, focalLengthMin:28, focalLengthMax:60, focalLengthEquiv:'28-60mm',
    maxAperture:4.0, minAperture:22, weight:167, length:45.0, diameter:66.6,
    filterThread:40.5, minFocusDist:30, maxMagnification:0.16,
    elements:8, groups:7, blades:7, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2020, discontinued:false,
    imageUrl:null,
    prices:{USD:498,AUD:799,EUR:null,GBP:null,JPY:null,CAD:649,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2860',
  },

  'fe-28-70mm-f35-56-oss': {
    name:'FE 28-70mm F3.5-5.6 OSS', manufacturer:'Sony', line:'FE', type:'Zoom', asin:'B00GTXHQ8Q',
    focalLength:null, focalLengthMin:28, focalLengthMax:70, focalLengthEquiv:'28-70mm',
    maxAperture:3.5, minAperture:22, weight:295, length:83.0, diameter:72.5,
    filterThread:55, minFocusDist:30, maxMagnification:0.19,
    elements:11, groups:9, blades:7, afType:'DC Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2013, discontinued:true,
    imageUrl:null,
    prices:{USD:498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2870',
  },

  'fe-28-70mm-f35-56-oss-ii': {
    name:'FE 28-70mm F3.5-5.6 OSS II', manufacturer:'Sony', line:'FE', type:'Zoom', asin:'B0G4SC388G',
    focalLength:null, focalLengthMin:28, focalLengthMax:70, focalLengthEquiv:'28-70mm',
    maxAperture:3.5, minAperture:22, weight:290, length:83.0, diameter:72.5,
    filterThread:55, minFocusDist:30, maxMagnification:0.19,
    elements:11, groups:9, blades:7, afType:'Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2025, discontinued:false,
    imageUrl:null,
    prices:{USD:548,AUD:849,EUR:null,GBP:null,JPY:null,CAD:699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2870-2',
  },

  /* ── Sony E (APS-C) Primes ── */
  'e-11mm-f18': {
    name:'E 11mm F1.8', manufacturer:'Sony', line:'E', type:'Prime', asin:'B0B2RZZBPN',
    focalLength:11, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'16.5mm',
    maxAperture:1.8, minAperture:16, weight:181, length:57.5, diameter:66.0,
    filterThread:55, minFocusDist:12, maxMagnification:0.20,
    elements:12, groups:11, blades:7, afType:'Linear',
    weatherSealed:false, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:548,AUD:899,EUR:null,GBP:null,JPY:null,CAD:699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel11f18',
  },

  'e-15mm-f14-g': {
    name:'E 15mm F1.4 G', manufacturer:'Sony', line:'E G', type:'Prime', asin:'B0B2X335XB',
    focalLength:15, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'22.5mm',
    maxAperture:1.4, minAperture:16, weight:219, length:69.5, diameter:66.0,
    filterThread:55, minFocusDist:17, maxMagnification:0.17,
    elements:14, groups:11, blades:7, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:748,AUD:1199,EUR:null,GBP:null,JPY:null,CAD:949,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel15f14g',
  },

  'e-16mm-f28': {
    name:'E 16mm F2.8', manufacturer:'Sony', line:'E', type:'Prime', asin:'B003OUX6MW',
    focalLength:16, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:2.8, minAperture:22, weight:67, length:22.5, diameter:62.0,
    filterThread:49, minFocusDist:24, maxMagnification:0.078,
    elements:5, groups:5, blades:7, afType:'DC Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2010, discontinued:true,
    imageUrl:null,
    prices:{USD:248,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel16f28',
  },

  'e-20mm-f28': {
    name:'E 20mm F2.8', manufacturer:'Sony', line:'E', type:'Prime', asin:'B00B20OYUO',
    focalLength:20, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'30mm',
    maxAperture:2.8, minAperture:22, weight:69, length:20.4, diameter:62.6,
    filterThread:49, minFocusDist:20, maxMagnification:0.12,
    elements:6, groups:6, blades:7, afType:'Linear',
    weatherSealed:false, ois:false, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:348,AUD:549,EUR:null,GBP:null,JPY:null,CAD:449,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel20f28',
  },

  'e-24mm-f18-za': {
    name:'E 24mm F1.8 ZA Sonnar', manufacturer:'Sony', line:'E ZA', type:'Prime', asin:'B005LLIEO2',
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'36mm',
    maxAperture:1.8, minAperture:22, weight:225, length:65.5, diameter:63.0,
    filterThread:49, minFocusDist:16, maxMagnification:0.25,
    elements:10, groups:8, blades:7, afType:'Linear',
    weatherSealed:false, ois:false, oisStops:null, year:2011, discontinued:true,
    imageUrl:null,
    prices:{USD:1098,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel24f18z',
  },

  'e-30mm-f35-macro': {
    name:'E 30mm F3.5 Macro', manufacturer:'Sony', line:'E', type:'Prime', asin:'B0054I54JU',
    focalLength:30, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'45mm',
    maxAperture:3.5, minAperture:22, weight:138, length:55.5, diameter:62.0,
    filterThread:49, minFocusDist:9.5, maxMagnification:1.0,
    elements:7, groups:6, blades:7, afType:'DC Motor',
    weatherSealed:false, ois:false, oisStops:null, year:2011, discontinued:true,
    imageUrl:null,
    prices:{USD:278,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel30m35',
  },

  'e-35mm-f18-oss': {
    name:'E 35mm F1.8 OSS', manufacturer:'Sony', line:'E', type:'Prime', asin:'B0096W1P5W',
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'52.5mm',
    maxAperture:1.8, minAperture:22, weight:154, length:45.0, diameter:63.0,
    filterThread:49, minFocusDist:30, maxMagnification:0.15,
    elements:8, groups:6, blades:7, afType:'DC Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2012, discontinued:false,
    imageUrl:null,
    prices:{USD:448,AUD:699,EUR:null,GBP:null,JPY:null,CAD:579,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel35f18',
  },

  'e-50mm-f18-oss': {
    name:'E 50mm F1.8 OSS', manufacturer:'Sony', line:'E', type:'Prime', asin:'B00EPWC30O',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'75mm',
    maxAperture:1.8, minAperture:22, weight:202, length:62.0, diameter:62.0,
    filterThread:49, minFocusDist:39, maxMagnification:0.16,
    elements:9, groups:8, blades:7, afType:'DC Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2011, discontinued:false,
    imageUrl:null,
    prices:{USD:348,AUD:549,EUR:null,GBP:null,JPY:null,CAD:449,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel50f18',
  },

  /* ── Sony E (APS-C) Zooms ── */
  'e-10-18mm-f4-oss': {
    name:'E 10-18mm F4 OSS', manufacturer:'Sony', line:'E', type:'Zoom', asin:'B0096W1ONK',
    focalLength:null, focalLengthMin:10, focalLengthMax:18, focalLengthEquiv:'15-27mm',
    maxAperture:4.0, minAperture:22, weight:225, length:63.5, diameter:70.0,
    filterThread:62, minFocusDist:25, maxMagnification:0.10,
    elements:10, groups:8, blades:7, afType:'Linear',
    weatherSealed:false, ois:true, oisStops:null, year:2012, discontinued:false,
    imageUrl:null,
    prices:{USD:848,AUD:1349,EUR:null,GBP:null,JPY:null,CAD:1099,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel1018',
  },

  'e-10-20mm-f4-pz-g': {
    name:'E 10-20mm F4 PZ G', manufacturer:'Sony', line:'E G', type:'Zoom', asin:'B0B2RYSS32',
    focalLength:null, focalLengthMin:10, focalLengthMax:20, focalLengthEquiv:'15-30mm',
    maxAperture:4.0, minAperture:22, weight:178, length:55.0, diameter:69.8,
    filterThread:62, minFocusDist:18, maxMagnification:0.18,
    elements:11, groups:10, blades:7, afType:'Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:748,AUD:1199,EUR:null,GBP:null,JPY:null,CAD:949,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel1020g',
  },

  'e-16-50mm-f35-56-pz-oss': {
    name:'E 16-50mm F3.5-5.6 PZ OSS', manufacturer:'Sony', line:'E', type:'Zoom', asin:'B0096W1PG6',
    focalLength:null, focalLengthMin:16, focalLengthMax:50, focalLengthEquiv:'24-75mm',
    maxAperture:3.5, minAperture:22, weight:116, length:29.9, diameter:64.7,
    filterThread:40.5, minFocusDist:25, maxMagnification:0.215,
    elements:9, groups:8, blades:7, afType:'Linear',
    weatherSealed:false, ois:true, oisStops:null, year:2013, discontinued:true,
    imageUrl:null,
    prices:{USD:348,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/selp1650',
  },

  'e-16-50mm-f35-56-pz-oss-ii': {
    name:'E 16-50mm F3.5-5.6 PZ OSS II', manufacturer:'Sony', line:'E', type:'Zoom', asin:'B0771TQZP8',
    focalLength:null, focalLengthMin:16, focalLengthMax:50, focalLengthEquiv:'24-75mm',
    maxAperture:3.5, minAperture:22, weight:107, length:31.3, diameter:64.7,
    filterThread:40.5, minFocusDist:25, maxMagnification:0.22,
    elements:9, groups:8, blades:7, afType:'Linear',
    weatherSealed:false, ois:true, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:349,AUD:549,EUR:null,GBP:null,JPY:null,CAD:449,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/selp1650-2',
  },

  'e-16-55mm-f28-g': {
    name:'E 16-55mm F2.8 G', manufacturer:'Sony', line:'E G', type:'Zoom', asin:'B07WZVKZHK',
    focalLength:null, focalLengthMin:16, focalLengthMax:55, focalLengthEquiv:'24-82.5mm',
    maxAperture:2.8, minAperture:22, weight:494, length:100.0, diameter:73.0,
    filterThread:67, minFocusDist:33, maxMagnification:0.20,
    elements:17, groups:12, blades:9, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:1398,AUD:2199,EUR:null,GBP:null,JPY:null,CAD:1799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel1655g',
  },

  'e-16-70mm-f4-za-oss': {
    name:'E 16-70mm F4 ZA OSS Vario-Tessar', manufacturer:'Sony', line:'E ZA', type:'Zoom', asin:'B00ENZRPG0',
    focalLength:null, focalLengthMin:16, focalLengthMax:70, focalLengthEquiv:'24-105mm',
    maxAperture:4.0, minAperture:22, weight:308, length:75.0, diameter:66.6,
    filterThread:55, minFocusDist:35, maxMagnification:0.23,
    elements:12, groups:10, blades:7, afType:'Linear',
    weatherSealed:false, ois:true, oisStops:null, year:2013, discontinued:true,
    imageUrl:null,
    prices:{USD:998,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel1670z',
  },

  'e-18-105mm-f4-g-oss-pz': {
    name:'E 18-105mm F4 G OSS PZ', manufacturer:'Sony', line:'E G', type:'Zoom', asin:'B00ENZRQH8',
    focalLength:null, focalLengthMin:18, focalLengthMax:105, focalLengthEquiv:'27-157.5mm',
    maxAperture:4.0, minAperture:22, weight:427, length:110.0, diameter:78.0,
    filterThread:72, minFocusDist:45, maxMagnification:0.11,
    elements:16, groups:12, blades:7, afType:'Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2013, discontinued:false,
    imageUrl:null,
    prices:{USD:598,AUD:949,EUR:null,GBP:null,JPY:null,CAD:749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/selp18105g',
  },

  'e-18-135mm-f35-56-oss': {
    name:'E 18-135mm F3.5-5.6 OSS', manufacturer:'Sony', line:'E', type:'Zoom', asin:'B078VPM6WM',
    focalLength:null, focalLengthMin:18, focalLengthMax:135, focalLengthEquiv:'27-202.5mm',
    maxAperture:3.5, minAperture:22, weight:325, length:88.0, diameter:67.2,
    filterThread:55, minFocusDist:45, maxMagnification:0.29,
    elements:16, groups:12, blades:7, afType:'Linear',
    weatherSealed:false, ois:true, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:598,AUD:949,EUR:null,GBP:null,JPY:null,CAD:749,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel18135',
  },

  'e-55-210mm-f45-63-oss': {
    name:'E 55-210mm F4.5-6.3 OSS', manufacturer:'Sony', line:'E', type:'Zoom', asin:'B00HNJWSDS',
    focalLength:null, focalLengthMin:55, focalLengthMax:210, focalLengthEquiv:'82.5-315mm',
    maxAperture:4.5, minAperture:32, weight:345, length:108.0, diameter:63.8,
    filterThread:49, minFocusDist:100, maxMagnification:0.225,
    elements:13, groups:9, blades:7, afType:'DC Motor',
    weatherSealed:false, ois:true, oisStops:null, year:2011, discontinued:false,
    imageUrl:null,
    prices:{USD:348,AUD:549,EUR:null,GBP:null,JPY:null,CAD:449,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel55210',
  },

  'e-70-350mm-f45-63-g-oss': {
    name:'E 70-350mm F4.5-6.3 G OSS', manufacturer:'Sony', line:'E G', type:'Zoom', asin:'B07X72DMLC',
    focalLength:null, focalLengthMin:70, focalLengthMax:350, focalLengthEquiv:'105-525mm',
    maxAperture:4.5, minAperture:32, weight:625, length:142.0, diameter:77.0,
    filterThread:67, minFocusDist:110, maxMagnification:0.23,
    elements:19, groups:13, blades:7, afType:'XD Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:998,AUD:1599,EUR:null,GBP:null,JPY:null,CAD:1299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/aps-c-e-mount/p/sel70350g',
  },
};

const LENS_DROPDOWN_GROUPS = [
  { label: '── Sony FE Primes ──', ids: [
    'fe-14mm-f18-gm', 'fe-16mm-f18-g', 'fe-20mm-f18-g', 'fe-24mm-f14-gm',
    'fe-24mm-f28-g', 'fe-28mm-f2', 'fe-35mm-f14-gm', 'fe-35mm-f14-za',
    'fe-35mm-f18', 'fe-35mm-f28-za', 'fe-40mm-f25-g', 'fe-50mm-f12-gm',
    'fe-50mm-f14-gm', 'fe-50mm-f14-za', 'fe-50mm-f18', 'fe-50mm-f25-g',
    'fe-50mm-f28-macro', 'fe-55mm-f18-za', 'fe-85mm-f14-gm-ii', 'fe-85mm-f14-gm',
    'fe-90mm-f28-macro-g', 'fe-100mm-f28-stf-gm', 'fe-135mm-f18-gm',
    'fe-300mm-f28-gm', 'fe-400mm-f28-gm', 'fe-600mm-f4-gm',
  ] },
  { label: '── Sony FE Zooms ──',  ids: [
    'fe-12-24mm-f28-gm', 'fe-12-24mm-f4-g', 'fe-16-25mm-f28-g', 'fe-16-35mm-f28-gm-ii',
    'fe-16-35mm-f28-gm', 'fe-16-35mm-f4-pz-g', 'fe-16-35mm-f4-za-oss', 'fe-20-70mm-f4-g',
    'fe-24-50mm-f28-g', 'fe-24-70mm-f28-gm-ii', 'fe-24-70mm-f4-za-oss', 'fe-24-105mm-f4-g-oss',
    'fe-24-240mm-f35-63-oss', 'fe-28-60mm-f4-56', 'fe-28-70mm-f2-gm',
    'fe-28-70mm-f35-56-oss-ii', 'fe-28-70mm-f35-56-oss', 'fe-50-150mm-f2-gm',
    'fe-70-200mm-f28-gm-oss-ii', 'fe-70-200mm-f4-macro-g-oss-ii', 'fe-70-200mm-f4-g-oss',
    'fe-70-300mm-f45-56-g-oss', 'fe-100-400mm-f45-63-gm-oss', 'fe-200-600mm-f56-63-g-oss',
    'fe-400-800mm-f63-8-g-oss',
  ] },
  { label: '── Sony E (APS-C) Primes ──', ids: [
    'e-11mm-f18', 'e-15mm-f14-g', 'e-16mm-f28', 'e-20mm-f28', 'e-24mm-f18-za',
    'e-30mm-f35-macro', 'e-35mm-f18-oss', 'e-50mm-f18-oss',
  ] },
  { label: '── Sony E (APS-C) Zooms ──', ids: [
    'e-10-18mm-f4-oss', 'e-10-20mm-f4-pz-g', 'e-16-50mm-f35-56-pz-oss-ii',
    'e-16-50mm-f35-56-pz-oss', 'e-16-55mm-f28-g', 'e-16-70mm-f4-za-oss',
    'e-18-105mm-f4-g-oss-pz', 'e-18-135mm-f35-56-oss', 'e-55-210mm-f45-63-oss',
    'e-70-350mm-f45-63-g-oss',
  ] },
];
