// ─────────────────────────────────────────────
// SONY BRAND CONFIG
// ─────────────────────────────────────────────
const BRAND_CONFIG = {
  name:        'Sony',
  slug:        'sony',
  accentColor: '#ff6a00',
  heroDark:    '#1a0d00',
  logoText:    'Sony',
  logoAccent:  '',
  families:    ['E-mount System'],
  brandSections: ['sony'],
  cameras: {
    heroEyebrow:  'Alpha E-mount System',
    heroTitle:    '<span>Sony</span> Camera Comparison',
    heroSubtitle: 'Compare up to 3 Sony Alpha cameras side-by-side across the full lineup',
    headerTitle:  'Camera Compare',
    defaultSelected: ['a7-iv', 'a6700', 'a7c-ii'],
  },
  lenses: {
    heroEyebrow:  'E-mount Lenses',
    heroTitle:    '<span>Sony</span> Lens Comparison',
    heroSubtitle: 'Compare Sony FE & E mount lenses side-by-side',
    headerTitle:  'Lens Compare',
    defaultSelected: ['fe-50mm-f14-gm', 'fe-24-70mm-f28-gm-ii', 'fe-70-200mm-f28-gm-oss-ii'],
  },
  footerLinks: [
    { label: 'Sony Alpha Universe', url: 'https://alphauniverse.com' },
    { label: 'DPReview Sony',       url: 'https://www.dpreview.com/products/sony' },
    { label: 'Sony Alpha Rumors',   url: 'https://www.sonyalpharumors.com' },
  ],
};

// All brands must register the same list (config.test.js enforces parity).
const REGISTERED_BRANDS = [
  { slug: 'fujifilm', name: 'Fujifilm' },
  { slug: 'canon',    name: 'Canon' },
  { slug: 'sony',     name: 'Sony' },
];

// ─────────────────────────────────────────────
// SERIES COLORS (for camera placeholder cards)
// ─────────────────────────────────────────────
const SERIES_COLORS = {
  'Alpha (Full-frame)': { bg: '#2a1500', text: '#ffae66' },
  'Alpha (APS-C)':      { bg: '#1f1000', text: '#e09a5a' },
  'Cinema Line':        { bg: '#1a1a1a', text: '#d0d0d0' },
  'ZV (Vlog)':          { bg: '#241200', text: '#ffc080' },
};

// ─────────────────────────────────────────────
// CAMERA DATABASE
// Sony E-mount bodies (full-frame Alpha, APS-C Alpha, Cinema Line, ZV).
// Pricing: USD is the launch RRP. Non-USD figures derived via
// scripts/compute-prices.js unless a confirmed regional RRP is available;
// discontinued bodies may carry null for non-USD currencies.
// Sony-specific fields: logProfile (Log/colour profiles), aiAf (dedicated AI
// Processing Unit), realtimeTracking (Real-time Tracking AF).
// ─────────────────────────────────────────────
const CAMERAS = {
  // Populated in batches — see openspec/changes/add-sony-brand/research/cameras.md

  /* ── Alpha Full-frame ── */
  'a7-iv': {
    name:'A7 IV', series:'Alpha (Full-frame)', year:2021, discontinued:false,
    tagline:'All-round Hybrid Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m4-b',
    imageUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sony_A7_IV_%28ILCE-7M4%29_-_by_Henry_S%C3%B6derlund_%2851739988735%29.jpg/1280px-Sony_A7_IV_%28ILCE-7M4%29_-_by_Henry_S%C3%B6derlund_%2851739988735%29.jpg',
    asin:'B09JZT6YK5',
    prices:{USD:2499,AUD:4299,EUR:2800,GBP:2400,JPY:330000,CAD:3299,SGD:3399},
    sensorMP:33.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:131.3, height:96.4, depth:79.8, weight:658, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Bird',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 60P (Super35)',
    logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× CFexpress Type A / SD UHS-II + 1× SD UHS-II', batteryLife:580, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:false, realtimeTracking:true,
  },

  'a7c-ii': {
    name:'A7C II', series:'Alpha (Full-frame)', year:2023, discontinued:false,
    tagline:'Compact 33MP Full-frame with AI AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7cm2-b',
    imageUrl:null,
    asin:'B0CGTTVYGM',
    prices:{USD:2199,AUD:3699,EUR:2500,GBP:2100,JPY:309000,CAD:2900,SGD:3000},
    sensorMP:33.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:124.0, height:71.1, depth:63.4, weight:514, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:7.0, maxBurst:10,
    maxVideoRes:'4K / 60P (Super35)',
    logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7r-v': {
    name:'A7R V', series:'Alpha (Full-frame)', year:2022, discontinued:false,
    tagline:'61MP Resolution + AI AF + 8K',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm5-b',
    imageUrl:null,
    asin:'B0BKLQFFSF',
    prices:{USD:3898,AUD:5999,EUR:4500,GBP:4000,JPY:560000,CAD:5200,SGD:5400},
    sensorMP:61.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:131.3, height:96.9, depth:82.4, weight:723, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'4-axis Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:8.0, maxBurst:10,
    maxVideoRes:'8K / 24P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a1-ii': {
    name:'A1 II', series:'Alpha (Full-frame)', year:2024, discontinued:false,
    tagline:'50MP Flagship: Speed + Resolution + 8K',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce1m2-b',
    imageUrl:null,
    asin:'B0DNLVHJ74',
    prices:{USD:6499,AUD:9999,EUR:7300,GBP:6300,JPY:990000,CAD:8500,SGD:8800},
    sensorMP:50.1, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ XR',
    width:136.1, height:96.9, depth:82.9, weight:743, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'4-axis Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:8.5, maxBurst:30,
    maxVideoRes:'8K / 30P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:520, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a9-iii': {
    name:'A9 III', series:'Alpha (Full-frame)', year:2024, discontinued:false,
    tagline:"World's First Global Shutter Full-frame",
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce9m3-b',
    imageUrl:null,
    asin:'B0CMV98DP2',
    prices:{USD:5998,AUD:9499,EUR:6999,GBP:6100,JPY:880000,CAD:7900,SGD:8200},
    sensorMP:24.6, sensorType:'Full-frame Global Shutter Exmor RS CMOS', processor:'BIONZ XR',
    width:136.1, height:96.9, depth:82.9, weight:703, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'4-axis Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:8.0, maxBurst:120,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7-v': {
    name:'A7 V', series:'Alpha (Full-frame)', year:2025, discontinued:false,
    tagline:'Partially-stacked 33MP Hybrid + BIONZ XR2',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m5-b',
    imageUrl:null,
    asin:null,
    prices:{USD:2899,AUD:4999,EUR:3299,GBP:2899,JPY:430000,CAD:3699,SGD:3899},
    sensorMP:33.0, sensorType:'Full-frame Partially-stacked Exmor RS BSI CMOS', processor:'BIONZ XR2',
    width:130.3, height:96.4, depth:82.4, weight:695, weatherSealed:true,
    lcdSize:'3.2"', lcdDots:2095, lcdType:'Multi-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:7.5, maxBurst:30,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'5.3', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:null, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7cr': {
    name:'A7C R', series:'Alpha (Full-frame)', year:2023, discontinued:false,
    tagline:'Compact 61MP with AI AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7cr-b',
    imageUrl:null,
    asin:'B0CGTVF6HS',
    prices:{USD:2999,AUD:5099,EUR:3400,GBP:3000,JPY:450000,CAD:3900,SGD:4100},
    sensorMP:61.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:124.0, height:71.1, depth:63.4, weight:515, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:7.0, maxBurst:8,
    maxVideoRes:'4K / 60P (Super35)',
    logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a7s-iii': {
    name:'A7S III', series:'Alpha (Full-frame)', year:2021, discontinued:false,
    tagline:'12MP Low-light Video Specialist',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7sm3-b',
    imageUrl:null,
    asin:'B08DP4NKGN',
    prices:{USD:3498,AUD:5999,EUR:4200,GBP:3800,JPY:440000,CAD:4500,SGD:4800},
    sensorMP:12.1, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:128.9, height:96.9, depth:80.8, weight:699, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:600, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a1': {
    name:'A1', series:'Alpha (Full-frame)', year:2021, discontinued:true,
    tagline:'Original 50MP Flagship (8K)',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce1-b',
    imageUrl:null,
    asin:null,
    prices:{USD:6498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:50.1, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ XR',
    width:128.9, height:96.9, depth:80.8, weight:737, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:9.44, evfMag:0.90,
    faceDetection:true, subjectDetection:'Human / Animal / Bird',
    ibis:true, ibisStops:5.5, maxBurst:30,
    maxVideoRes:'8K / 30P',
    logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:530, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:false, realtimeTracking:true,
  },

  'a7c': {
    name:'A7C', series:'Alpha (Full-frame)', year:2020, discontinued:true,
    tagline:'First Compact Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7c-b',
    imageUrl:null,
    asin:null,
    prices:{USD:1799,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:124.0, height:71.1, depth:59.7, weight:509, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:922, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.59,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 30P',
    logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:740, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  /* ── Alpha Full-frame (discontinued) ── */
  'a9-ii': {
    name:'A9 II', series:'Alpha (Full-frame)', year:2019, discontinued:true,
    tagline:'Pro Sports Stacked 24MP',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce9m2-b',
    imageUrl:null, asin:null,
    prices:{USD:4498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ X',
    width:128.9, height:96.4, depth:77.5, weight:678, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:20,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:690, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7r-iv': {
    name:'A7R IV', series:'Alpha (Full-frame)', year:2019, discontinued:true,
    tagline:'First 61MP Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm4a-b',
    imageUrl:null, asin:null,
    prices:{USD:3498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:61.0, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:128.9, height:96.4, depth:77.5, weight:665, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:5.76, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× SD UHS-II', batteryLife:670, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7-iii': {
    name:'A7 III', series:'Alpha (Full-frame)', year:2018, discontinued:true,
    tagline:'The Full-frame Workhorse',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m3-b',
    imageUrl:null, asin:null,
    prices:{USD:1999,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.6, depth:73.7, weight:650, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:922, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'2× SD (1× UHS-II)', batteryLife:710, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a9': {
    name:'A9', series:'Alpha (Full-frame)', year:2017, discontinued:true,
    tagline:'First Stacked Pro Sports Body',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce9-b',
    imageUrl:null, asin:null,
    prices:{USD:4498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'Full-frame Stacked Exmor RS CMOS', processor:'BIONZ X',
    width:126.9, height:95.6, depth:63.0, weight:673, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:20,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'2× SD (1× UHS-II)', batteryLife:650, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7r-iii': {
    name:'A7R III', series:'Alpha (Full-frame)', year:2017, discontinued:true,
    tagline:'42MP High-resolution Hybrid',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm3a-b',
    imageUrl:null, asin:null,
    prices:{USD:3198,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:42.4, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.6, depth:73.7, weight:657, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:3.69, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'2× SD (1× UHS-II)', batteryLife:650, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a7r-ii': {
    name:'A7R II', series:'Alpha (Full-frame)', year:2015, discontinued:true,
    tagline:'First BSI 42MP Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7rm2',
    imageUrl:null, asin:null,
    prices:{USD:3198,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:42.4, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.7, depth:60.3, weight:625, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1228, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human',
    ibis:true, ibisStops:4.5, maxBurst:5,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:290, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a7s-ii': {
    name:'A7S II', series:'Alpha (Full-frame)', year:2015, discontinued:true,
    tagline:'12MP Low-light Video',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7sm2',
    imageUrl:null, asin:null,
    prices:{USD:2998,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:12.2, sensorType:'Full-frame BSI CMOS', processor:'BIONZ X',
    width:126.9, height:95.7, depth:60.3, weight:627, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1228, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.78,
    faceDetection:true, subjectDetection:'Human',
    ibis:true, ibisStops:4.5, maxBurst:5,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:370, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a7-ii': {
    name:'A7 II', series:'Alpha (Full-frame)', year:2014, discontinued:true,
    tagline:'First IBIS Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7m2',
    imageUrl:null, asin:null,
    prices:{USD:1698,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'Full-frame Exmor CMOS', processor:'BIONZ X',
    width:126.9, height:95.7, depth:59.7, weight:599, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1228, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:true, ibisStops:4.5, maxBurst:5,
    maxVideoRes:'1080 / 60P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a7r': {
    name:'A7R', series:'Alpha (Full-frame)', year:2013, discontinued:true,
    tagline:'Original 36MP No-AA Full-frame',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7r',
    imageUrl:null, asin:null,
    prices:{USD:2298,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:36.4, sensorType:'Full-frame Exmor CMOS (no AA filter)', processor:'BIONZ X',
    width:126.9, height:94.4, depth:48.2, weight:465, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1230, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:4,
    maxVideoRes:'1080 / 60P', logVideo:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:340, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:false,
  },

  'a7': {
    name:'A7', series:'Alpha (Full-frame)', year:2013, discontinued:true,
    tagline:'The Original Full-frame Mirrorless',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7',
    imageUrl:null, asin:null,
    prices:{USD:1698,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'Full-frame Exmor CMOS', processor:'BIONZ X',
    width:126.9, height:94.4, depth:48.2, weight:474, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1230, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:5,
    maxVideoRes:'1080 / 60P', logVideo:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:340, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:false,
  },

  'a7s': {
    name:'A7S', series:'Alpha (Full-frame)', year:2014, discontinued:true,
    tagline:'First 12MP Low-light Specialist',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilce7s',
    imageUrl:null, asin:null,
    prices:{USD:2498,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:12.2, sensorType:'Full-frame Exmor CMOS', processor:'BIONZ X',
    width:126.9, height:94.4, depth:48.2, weight:489, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1230, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:5,
    maxVideoRes:'4K / 30P (external)', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log2', aiAf:false, realtimeTracking:false,
  },

  /* ── Alpha APS-C ── */
  'a6700': {
    name:'A6700', series:'Alpha (APS-C)', year:2023, discontinued:false,
    tagline:'Flagship APS-C with AI AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6700-b',
    imageUrl:null,
    asin:'B0CBN8Y77Z',
    prices:{USD:1399,AUD:2399,EUR:1700,GBP:1450,JPY:230000,CAD:1900,SGD:2100},
    sensorMP:26.0, sensorType:'APS-C BSI CMOS', processor:'BIONZ XR',
    width:122.0, height:69.0, depth:75.1, weight:493, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.71,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:5.0, maxBurst:11,
    maxVideoRes:'4K / 120P',
    logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:570, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'a6600': {
    name:'A6600', series:'Alpha (APS-C)', year:2019, discontinued:true,
    tagline:'APS-C Flagship with IBIS',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6600-b',
    imageUrl:null, asin:null,
    prices:{USD:1399,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:69.3, weight:503, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:810, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a6500': {
    name:'A6500', series:'Alpha (APS-C)', year:2016, discontinued:true,
    tagline:'First APS-C with IBIS',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6500',
    imageUrl:null, asin:null,
    prices:{USD:1398,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:53.3, weight:453, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human',
    ibis:true, ibisStops:5.0, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:350, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a6400': {
    name:'A6400', series:'Alpha (APS-C)', year:2019, discontinued:false,
    tagline:'Real-time Tracking APS-C',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6400-b',
    imageUrl:null, asin:'B07MTWVN3M',
    prices:{USD:899,AUD:1499,EUR:1050,GBP:950,JPY:140000,CAD:1300,SGD:1400},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:49.9, weight:403, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'180° Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:410, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'a6300': {
    name:'A6300', series:'Alpha (APS-C)', year:2016, discontinued:true,
    tagline:'4K APS-C with Fast Hybrid AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6300',
    imageUrl:null, asin:null,
    prices:{USD:998,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:48.8, weight:404, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:2.36, evfMag:0.70,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:400, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:false,
  },

  'a6100': {
    name:'A6100', series:'Alpha (APS-C)', year:2019, discontinued:true,
    tagline:'Entry APS-C with Fast AF',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6100-b',
    imageUrl:null, asin:null,
    prices:{USD:748,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:49.9, weight:396, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:921, lcdType:'180° Tilting Touchscreen',
    evfType:'EVF (OLED)', evfDots:1.44, evfMag:0.70,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:false,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:420, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:true,
  },

  'a6000': {
    name:'A6000', series:'Alpha (APS-C)', year:2014, discontinued:true,
    tagline:'The Best-selling APS-C',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilce6000',
    imageUrl:null, asin:null,
    prices:{USD:648,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.3, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:120.0, height:66.9, depth:45.1, weight:344, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Tilting',
    evfType:'EVF (OLED)', evfDots:1.44, evfMag:0.70,
    faceDetection:true, subjectDetection:null,
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'1080 / 60P', logVideo:false,
    bluetooth:false, wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:360, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:null, aiAf:false, realtimeTracking:false,
  },

  /* ── Cinema Line ── */
  'fx3': {
    name:'FX3', series:'Cinema Line', year:2021, discontinued:false,
    tagline:'Full-frame Cinema in a Compact Body',
    productUrl:'https://electronics.sony.com/imaging/cinema-line-cameras/p/ilmefx3-b',
    imageUrl:null, asin:'B08WJKKD47',
    prices:{USD:3899,AUD:6499,EUR:4700,GBP:4200,JPY:528000,CAD:5000,SGD:5300},
    sensorMP:12.1, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:129.7, height:77.8, depth:84.5, weight:715, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1440, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.5, maxBurst:10,
    maxVideoRes:'4K / 120P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:600, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  'fx30': {
    name:'FX30', series:'Cinema Line', year:2022, discontinued:false,
    tagline:'APS-C Cinema Line Gateway',
    productUrl:'https://electronics.sony.com/imaging/cinema-line-cameras/p/ilmefx30b',
    imageUrl:null, asin:'B0BR8BKFPK',
    prices:{USD:1799,AUD:2899,EUR:2100,GBP:1800,JPY:290000,CAD:2400,SGD:2500},
    sensorMP:26.0, sensorType:'APS-C BSI CMOS', processor:'BIONZ XR',
    width:129.7, height:77.8, depth:84.5, weight:646, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:2360, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 120P', logVideo:true,
    bluetooth:'5.0', wifi:true,
    cardSlots:'2× CFexpress Type A / SD UHS-II', batteryLife:570, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone / S-Log2', aiAf:false, realtimeTracking:true,
  },

  /* ── ZV (Vlog) ── */
  'zv-e1': {
    name:'ZV-E1', series:'ZV (Vlog)', year:2023, discontinued:false,
    tagline:'Full-frame Vlog with AI Framing',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/full-frame/p/ilczv-e1-b',
    imageUrl:null, asin:'B0BZWNWCZ9',
    prices:{USD:2198,AUD:3499,EUR:2700,GBP:2300,JPY:298000,CAD:2900,SGD:3000},
    sensorMP:12.1, sensorType:'Full-frame BSI CMOS', processor:'BIONZ XR',
    width:121.0, height:71.9, depth:54.3, weight:483, weatherSealed:true,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal / Bird / Insect / Car / Train / Plane',
    ibis:true, ibisStops:5.0, maxBurst:10,
    maxVideoRes:'4K / 120P', logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:570, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:true, realtimeTracking:true,
  },

  'zv-e10-ii': {
    name:'ZV-E10 II', series:'ZV (Vlog)', year:2024, discontinued:false,
    tagline:'26MP APS-C Content Creator',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilczv-e10m2-b',
    imageUrl:null, asin:'B0D92W8GYV',
    prices:{USD:999,AUD:1699,EUR:1100,GBP:1000,JPY:150000,CAD:1400,SGD:1500},
    sensorMP:26.0, sensorType:'APS-C BSI CMOS', processor:'BIONZ XR',
    width:114.8, height:67.5, depth:57.3, weight:377, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:1037, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 60P', logVideo:true,
    bluetooth:'4.2', wifi:true,
    cardSlots:'1× SD UHS-II', batteryLife:610, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Cinetone', aiAf:false, realtimeTracking:true,
  },

  'zv-e10': {
    name:'ZV-E10', series:'ZV (Vlog)', year:2021, discontinued:true,
    tagline:'First APS-C Vlog Camera',
    productUrl:'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/ilczv-e10-b',
    imageUrl:null, asin:null,
    prices:{USD:699,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    sensorMP:24.2, sensorType:'APS-C Exmor CMOS', processor:'BIONZ X',
    width:115.2, height:64.2, depth:44.8, weight:343, weatherSealed:false,
    lcdSize:'3.0"', lcdDots:921, lcdType:'Vari-angle Touchscreen',
    evfType:null, evfDots:null, evfMag:null,
    faceDetection:true, subjectDetection:'Human / Animal',
    ibis:false, ibisStops:null, maxBurst:11,
    maxVideoRes:'4K / 30P', logVideo:true,
    bluetooth:'4.1', wifi:true,
    cardSlots:'1× SD UHS-I', batteryLife:440, usbCharging:true,
    lensType:'Interchangeable', lensSpec:null,
    logProfile:'S-Log3 / S-Log2', aiAf:false, realtimeTracking:true,
  },
};

const CAMERA_ORDER = [
  'a7-v', 'a9-iii', 'a1-ii',
  'a7r-v', 'a7cr', 'a7c-ii', 'a7s-iii', 'a7-iv',
  'a1', 'a7c', 'a9-ii', 'a7r-iv', 'a7-iii', 'a9', 'a7r-iii',
  'a7r-ii', 'a7s-ii', 'a7-ii', 'a7r', 'a7', 'a7s',
  'a6700', 'a6400', 'a6600', 'a6500', 'a6300', 'a6100', 'a6000',
  'fx3', 'fx30',
  'zv-e1', 'zv-e10-ii', 'zv-e10',
];

const DROPDOWN_GROUPS = [
  { label: '── Alpha Full-frame (2024–2025) ──', ids: ['a7-v', 'a9-iii', 'a1-ii'] },
  { label: '── Alpha Full-frame (2021–2023) ──', ids: ['a7r-v', 'a7cr', 'a7c-ii', 'a7s-iii', 'a7-iv'] },
  { label: '── Alpha Full-frame (2017–2020) ──', ids: ['a1', 'a7c', 'a9-ii', 'a7r-iv', 'a7-iii', 'a9', 'a7r-iii'] },
  { label: '── Alpha Full-frame (2013–2015) ──', ids: ['a7r-ii', 'a7s-ii', 'a7-ii', 'a7r', 'a7', 'a7s'] },
  { label: '── Alpha APS-C ──',                  ids: ['a6700', 'a6400', 'a6600', 'a6500', 'a6300', 'a6100', 'a6000'] },
  { label: '── Cinema Line ──',                  ids: ['fx3', 'fx30'] },
  { label: '── ZV (Vlog) ──',                    ids: ['zv-e1', 'zv-e10-ii', 'zv-e10'] },
];

// ─────────────────────────────────────────────
// LENS DATABASE
// Sony first-party FE (full-frame) + E (APS-C) lenses, incl. Sony-Zeiss (ZA).
// Specs verified against Sony official pages + DPReview.
// See openspec/changes/add-sony-brand/research/lenses.md
// ─────────────────────────────────────────────
const LENSES = {
  // Populated in batches by line (FE GM / FE G / FE / E).

  /* ── Sony FE Primes ── */
  'fe-50mm-f14-gm': {
    name:'FE 50mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B0BWFSJXQC',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.4, minAperture:16, weight:516, length:96.0, diameter:80.6,
    filterThread:67, minFocusDist:38, maxMagnification:0.16,
    elements:14, groups:11, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:1600,AUD:2599,EUR:null,GBP:null,JPY:null,CAD:1999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50f14gm',
  },

  'fe-14mm-f18-gm': {
    name:'FE 14mm F1.8 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:14, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'14mm',
    maxAperture:1.8, minAperture:16, weight:460, length:99.8, diameter:83.0,
    filterThread:null, minFocusDist:25, maxMagnification:0.10,
    elements:14, groups:11, blades:9, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1598,AUD:2499,EUR:null,GBP:null,JPY:null,CAD:1999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel14f18gm',
  },

  'fe-24mm-f14-gm': {
    name:'FE 24mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:24, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'24mm',
    maxAperture:1.4, minAperture:16, weight:445, length:92.4, diameter:75.4,
    filterThread:67, minFocusDist:24, maxMagnification:0.17,
    elements:13, groups:10, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:false, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:1398,AUD:2199,EUR:null,GBP:null,JPY:null,CAD:1799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel24f14gm',
  },

  'fe-35mm-f14-gm': {
    name:'FE 35mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:35, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'35mm',
    maxAperture:1.4, minAperture:16, weight:524, length:96.0, diameter:76.0,
    filterThread:67, minFocusDist:25, maxMagnification:0.26,
    elements:14, groups:10, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1398,AUD:2199,EUR:null,GBP:null,JPY:null,CAD:1799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel35f14gm',
  },

  'fe-50mm-f12-gm': {
    name:'FE 50mm F1.2 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:'B08Z4HVBXC',
    focalLength:50, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'50mm',
    maxAperture:1.2, minAperture:16, weight:778, length:108.0, diameter:87.0,
    filterThread:72, minFocusDist:40, maxMagnification:0.17,
    elements:14, groups:10, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:1998,AUD:3099,EUR:null,GBP:null,JPY:null,CAD:2599,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel50f12gm',
  },

  'fe-85mm-f14-gm-ii': {
    name:'FE 85mm F1.4 GM II', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.4, minAperture:16, weight:642, length:107.3, diameter:84.7,
    filterThread:77, minFocusDist:80, maxMagnification:0.12,
    elements:14, groups:11, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2024, discontinued:false,
    imageUrl:null,
    prices:{USD:1798,AUD:2799,EUR:null,GBP:null,JPY:null,CAD:2299,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel85f14gm2',
  },

  'fe-85mm-f14-gm': {
    name:'FE 85mm F1.4 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:85, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'85mm',
    maxAperture:1.4, minAperture:16, weight:820, length:107.5, diameter:89.5,
    filterThread:77, minFocusDist:80, maxMagnification:0.12,
    elements:11, groups:8, blades:11, afType:'SSM',
    weatherSealed:true, ois:false, oisStops:null, year:2016, discontinued:true,
    imageUrl:null,
    prices:{USD:1798,AUD:null,EUR:null,GBP:null,JPY:null,CAD:null,SGD:null},
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel85f14gm',
  },

  'fe-100mm-f28-stf-gm': {
    name:'FE 100mm F2.8 STF GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:100, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'100mm',
    maxAperture:2.8, minAperture:20, weight:700, length:118.1, diameter:85.2,
    filterThread:72, minFocusDist:57, maxMagnification:0.25,
    elements:13, groups:10, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2017, discontinued:false,
    imageUrl:null,
    prices:{USD:1498,AUD:2299,EUR:null,GBP:null,JPY:null,CAD:1899,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel100f28gm',
  },

  'fe-135mm-f18-gm': {
    name:'FE 135mm F1.8 GM', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:135, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'135mm',
    maxAperture:1.8, minAperture:22, weight:950, length:127.0, diameter:89.5,
    filterThread:82, minFocusDist:70, maxMagnification:0.25,
    elements:13, groups:10, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:2098,AUD:3299,EUR:null,GBP:null,JPY:null,CAD:2699,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel135f18gm',
  },

  'fe-300mm-f28-gm': {
    name:'FE 300mm F2.8 GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:300, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'300mm',
    maxAperture:2.8, minAperture:22, weight:1470, length:265.0, diameter:124.0,
    filterThread:40.5, minFocusDist:200, maxMagnification:0.16,
    elements:21, groups:17, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2023, discontinued:false,
    imageUrl:null,
    prices:{USD:5999,AUD:9499,EUR:null,GBP:null,JPY:null,CAD:7799,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel300f28gm',
  },

  'fe-400mm-f28-gm': {
    name:'FE 400mm F2.8 GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:400, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'400mm',
    maxAperture:2.8, minAperture:22, weight:2895, length:359.0, diameter:158.1,
    filterThread:40.5, minFocusDist:270, maxMagnification:0.16,
    elements:23, groups:17, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2018, discontinued:false,
    imageUrl:null,
    prices:{USD:11998,AUD:18999,EUR:null,GBP:null,JPY:null,CAD:15499,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel400f28gm',
  },

  'fe-600mm-f4-gm': {
    name:'FE 600mm F4 GM OSS', manufacturer:'Sony', line:'FE GM', type:'Prime', asin:null,
    focalLength:600, focalLengthMin:null, focalLengthMax:null, focalLengthEquiv:'600mm',
    maxAperture:4.0, minAperture:22, weight:3040, length:449.0, diameter:163.6,
    filterThread:40.5, minFocusDist:450, maxMagnification:0.14,
    elements:24, groups:18, blades:11, afType:'DDSSM',
    weatherSealed:true, ois:true, oisStops:null, year:2019, discontinued:false,
    imageUrl:null,
    prices:{USD:12998,AUD:19999,EUR:null,GBP:null,JPY:null,CAD:16999,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel600f40gm',
  },

  /* ── Sony FE Zooms ── */
  'fe-24-70mm-f28-gm-ii': {
    name:'FE 24-70mm F2.8 GM II', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B09YYY6P98',
    focalLength:null, focalLengthMin:24, focalLengthMax:70, focalLengthEquiv:'24-70mm',
    maxAperture:2.8, minAperture:22, weight:695, length:119.9, diameter:87.8,
    filterThread:82, minFocusDist:21, maxMagnification:0.32,
    elements:20, groups:15, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:false, oisStops:null, year:2022, discontinued:false,
    imageUrl:null,
    prices:{USD:2298,AUD:3399,EUR:null,GBP:null,JPY:null,CAD:2900,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel2470gm2',
  },

  'fe-70-200mm-f28-gm-oss-ii': {
    name:'FE 70-200mm F2.8 GM OSS II', manufacturer:'Sony', line:'FE GM', type:'Zoom', asin:'B09JCMLP46',
    focalLength:null, focalLengthMin:70, focalLengthMax:200, focalLengthEquiv:'70-200mm',
    maxAperture:2.8, minAperture:22, weight:1045, length:200.0, diameter:88.0,
    filterThread:77, minFocusDist:40, maxMagnification:0.30,
    elements:17, groups:14, blades:11, afType:'XD Linear',
    weatherSealed:true, ois:true, oisStops:null, year:2021, discontinued:false,
    imageUrl:null,
    prices:{USD:2798,AUD:4299,EUR:null,GBP:null,JPY:null,CAD:3600,SGD:null},
    priceIncomplete:true,
    productUrl:'https://electronics.sony.com/imaging/lenses/full-frame-e-mount/p/sel70200gm2',
  },
};

const LENS_DROPDOWN_GROUPS = [
  { label: '── Sony FE Primes ──', ids: [
    'fe-14mm-f18-gm', 'fe-24mm-f14-gm', 'fe-35mm-f14-gm', 'fe-50mm-f12-gm',
    'fe-50mm-f14-gm', 'fe-85mm-f14-gm-ii', 'fe-85mm-f14-gm', 'fe-100mm-f28-stf-gm',
    'fe-135mm-f18-gm', 'fe-300mm-f28-gm', 'fe-400mm-f28-gm', 'fe-600mm-f4-gm',
  ] },
  { label: '── Sony FE Zooms ──',  ids: ['fe-24-70mm-f28-gm-ii', 'fe-70-200mm-f28-gm-oss-ii'] },
];
